DROP FUNCTION IF EXISTS APDC.FN_GET_YMD;

CREATE FUNCTION APDC.FN_GET_YMD(VAR_YMD CHAR(8), VAR_YEAR_ADD INT, VAR_MONTH_ADD INT, VAR_DAY_ADD INT, IS_END_DAY CHAR(1)) RETURNS CHAR(8)

BEGIN
    DECLARE VAR_RETURN_YMD CHAR(8);
    DECLARE VAR_ADD_YMD CHAR(8);

    SET VAR_ADD_YMD = DATE_FORMAT(DATE_ADD(DATE_ADD(DATE_ADD(CAST(VAR_YMD AS DATE), INTERVAL VAR_YEAR_ADD YEAR),
                                                    INTERVAL VAR_MONTH_ADD MONTH),
                                            INTERVAL VAR_DAY_ADD DAY), '%Y%m%d');

    IF VAR_ADD_YMD IS NOT NULL AND IS_END_DAY = 'Y' THEN
        SET VAR_RETURN_YMD = DATE_FORMAT(DATE_SUB(DATE_ADD(CONCAT(SUBSTRING(VAR_ADD_YMD, 1, 6), '01'), INTERVAL 1 MONTH),
                                                    INTERVAL 1 DAY), '%Y%m%d');
    ELSEIF VAR_ADD_YMD IS NOT NULL AND IS_END_DAY = 'N' THEN
        SET VAR_RETURN_YMD = CONCAT(SUBSTRING(VAR_ADD_YMD, 1, 6), '01');
    ELSEIF VAR_ADD_YMD IS NOT NULL AND IS_END_DAY IS NULL THEN
        SET VAR_RETURN_YMD = VAR_ADD_YMD;
    ELSE
        SET VAR_RETURN_YMD = NULL;
    END IF;

    RETURN VAR_RETURN_YMD;
END