DROP FUNCTION IF EXISTS APDC.FN_GET_FY_Y;

CREATE FUNCTION APDC.FN_GET_FY_Y(VAR_YMD CHAR(8), VAR_YEAR_ADD INT) RETURNS CHAR(4)

BEGIN
    DECLARE VAR_FY_Y CHAR(4);
    DECLARE TMP_FY_M CHAR(2);

    SET TMP_FY_M = SUBSTRING(VAR_YMD, 5, 2);

    IF TMP_FY_M='01' OR TMP_FY_M='02' OR TMP_FY_M='03' THEN
        SET VAR_FY_Y = CAST(CAST(SUBSTRING(VAR_YMD, 1, 4) AS INT)-1+VAR_YEAR_ADD AS CHAR);
    ELSEIF TMP_FY_M IN ('04','05','06','07','08','09','10','11','12') THEN
        SET VAR_FY_Y = CAST(CAST(SUBSTRING(VAR_YMD, 1, 4) AS INT)+VAR_YEAR_ADD AS CHAR);
    ELSE
        SET VAR_FY_Y = NULL;
    END IF;

    RETURN VAR_FY_Y;
END