USE APDC;

INSERT INTO APDC.SYS_ROLE VALUES ('WANTDC','SYSADMIN','系统管理员','80005096',NOW());
INSERT INTO APDC.SYS_ROLE VALUES ('WANTDC','WSADMIN','批發管理員','80005096',NOW());
INSERT INTO APDC.SYS_ROLE VALUES ('WANTDC','KAADMIN','現渠管理員','80005096',NOW());