SET FOREIGN_KEY_CHECKS=0 ;

CREATE TABLE `CM_CODE`
(
	`CODE_KIND` VARCHAR(10) NOT NULL,
	`CODE_ID` VARCHAR(10) NOT NULL,
	`CODE_PARENT` VARCHAR(10) 	 NULL,
	`CODE_NM` VARCHAR(150) 	 NULL,
	`IS_DELETED` CHAR(1) NOT NULL,
	`SORT_ORDER` VARCHAR(10) 	 NULL,
	`UPD_USER_ID` VARCHAR(50) NOT NULL,
	`UPD_DT` DATETIME(0) NOT NULL,
	CONSTRAINT `PK_CM_CODE` PRIMARY KEY (`CODE_KIND`,`CODE_ID`)
)

;

SET FOREIGN_KEY_CHECKS=1 ;
