SET FOREIGN_KEY_CHECKS=0 ;

CREATE TABLE `DC0021_SALES_RPT01_HEAD`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`DATA_DATE` CHAR(8) NOT NULL,
	`DATA_DATE1` CHAR(8) NOT NULL,
	`DATA_DATE2` CHAR(8) NOT NULL,
	`WORKDAYS` INT NOT NULL,
	`WORKDAY_TOTAL` INT NOT NULL,
	`WORKDAY_PC` DECIMAL(21,8) NOT NULL,
	`REQ_DATE` CHAR(8) NOT NULL,
	`BU_AMT_SD` DECIMAL(21,4) NOT NULL,
	`BU_AMT_D` DECIMAL(21,4) NOT NULL,
	`BU_AMT_POSTING` DECIMAL(21,4) NOT NULL,
	`BU_AMT_LAST_ALL` DECIMAL(21,4) NOT NULL,
	`BU_AMT_PC` DECIMAL(21,8) NOT NULL,
	`BU_REQ` DECIMAL(21,4) NOT NULL,
	CONSTRAINT `PK_DC0021_SALES_RPT01_HEAD` PRIMARY KEY (`DATA_DATE`)
)

;

CREATE TABLE `DC0021_SALES_RPT01`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`DATA_DATE` CHAR(8) NOT NULL,
	`BU01_ID` VARCHAR(10) NOT NULL,
	`BU01_NM` VARCHAR(150) NOT NULL,
	`BU_AMT_SD2` DECIMAL(21,4) NOT NULL,
	`BU_AMT_SD1` DECIMAL(21,4) NOT NULL,
	`BU_AMT_SD` DECIMAL(21,4) NOT NULL,
	`BU_AMT_D` DECIMAL(21,4) NOT NULL,
	`BU_AMT_LAST_ALL` DECIMAL(21,4) NOT NULL,
	`BU_AMT_PC` DECIMAL(21,8) NOT NULL,
	`BU_AMT_DIF_ALL` DECIMAL(21,4) NOT NULL,
	`BU_AMT_LAST` DECIMAL(21,4) NOT NULL,
	`BU_AMT_GR` DECIMAL(21,8) NOT NULL,
	`BU_AMT_DIF` DECIMAL(21,4) NOT NULL,
	`BU_AMT_POSTING` DECIMAL(21,4) NOT NULL,
	`BU_AMT_STMT` DECIMAL(21,4) 	 NULL,
	`BU_AMT_STMT_DIF` DECIMAL(21,4) 	 NULL,
	`BU_REQ` DECIMAL(21,4) 	 NULL,
	`BU_REQ_PC` DECIMAL(21,8) 	 NULL,
	`BU_REQ_DIF` DECIMAL(21,4) 	 NULL,
	CONSTRAINT `PK_DC0021_SALES_RPT01` PRIMARY KEY (`DATA_DATE`,`BU01_ID`)
)

;

CREATE TABLE `DC0021_REQ`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`DATA_DATE` CHAR(8) NOT NULL,
	`REQ_YM` CHAR(6) NOT NULL,
	`WANT_CHAN_ID` VARCHAR(10) NOT NULL,
	`WANT_CHAN_NM` VARCHAR(60) 	 NULL,
	`WANT_COM_ID` VARCHAR(4) NOT NULL,
	`WANT_COM_NM` VARCHAR(60) 	 NULL,
	`PROD_H1_ID` VARCHAR(20) NOT NULL,
	`PROD_H1_NM` VARCHAR(60) 	 NULL,
	`PROD_H2_ID` VARCHAR(20) NOT NULL,
	`PROD_H2_NM` VARCHAR(60) 	 NULL,
	`PROD_H3_ID` VARCHAR(20) NOT NULL,
	`PROD_H3_NM` VARCHAR(60) 	 NULL,
	`REQ_QTY_PKG` DECIMAL(21,4) NOT NULL,
	`REQ_AMT` DECIMAL(21,4) NOT NULL,
	`BU01_ID` VARCHAR(10) 	 NULL,
	`BU01_NM` VARCHAR(150) 	 NULL,
	CONSTRAINT `PK_DC0021_REQ` PRIMARY KEY (`DATA_DATE`,`REQ_YM`,`WANT_CHAN_ID`,`WANT_COM_ID`,`PROD_H1_ID`,`PROD_H2_ID`,`PROD_H3_ID`)
)

;

CREATE TABLE `DC0021_CUST_STMT`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`DATA_DATE` CHAR(8) NOT NULL,
	`RPT_YM` CHAR(6) NOT NULL,
	`SALES_CREDIT_ID` VARCHAR(4) NOT NULL,
	`SALES_CREDIT_DESC` VARCHAR(300) 	 NULL,
	`WANT_COM_ID` VARCHAR(4) NOT NULL,
	`WANT_COM_NM` VARCHAR(60) 	 NULL,
	`SALES_OFF_ID` VARCHAR(4) NOT NULL,
	`SALES_OFF_NM` VARCHAR(60) 	 NULL,
	`TODAY_AMT` DECIMAL(21,4) NOT NULL,
	`BAL_BEGIN` DECIMAL(21,4) NOT NULL,
	`CUM_AMT` DECIMAL(21,4) NOT NULL,
	`SALES_AMT` DECIMAL(21,4) NOT NULL,
	`BAL_END` DECIMAL(21,4) NOT NULL,
	`BU01_ID` VARCHAR(10) 	 NULL,
	`BU01_NM` VARCHAR(150) 	 NULL,
	CONSTRAINT `PK_DC0021_CUST_STMT` PRIMARY KEY (`DATA_DATE`,`RPT_YM`,`SALES_CREDIT_ID`,`WANT_COM_ID`,`SALES_OFF_ID`)
)

;

CREATE TABLE `DC0021_CUST_SALES`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`DATA_DATE` CHAR(8) NOT NULL,
	`RPT_YM` CHAR(6) NOT NULL,
	`WANT_CHAN_ID` VARCHAR(10) NOT NULL,
	`WANT_CHAN_NM` VARCHAR(60) 	 NULL,
	`WANT_COM_ID` VARCHAR(4) NOT NULL,
	`WANT_COM_NM` VARCHAR(60) 	 NULL,
	`PROD_H1_ID` VARCHAR(20) NOT NULL,
	`PROD_H1_NM` VARCHAR(60) 	 NULL,
	`PROD_H2_ID` VARCHAR(20) NOT NULL,
	`PROD_H2_NM` VARCHAR(60) 	 NULL,
	`PROD_H3_ID` VARCHAR(20) NOT NULL,
	`PROD_H3_NM` VARCHAR(60) 	 NULL,
	`POSTED_AMT_LAST_ALL` DECIMAL(21,4) NOT NULL,
	`POSTED_AMT_LAST` DECIMAL(21,4) NOT NULL,
	`POSTED_AMT_THIS` DECIMAL(21,4) NOT NULL,
	`POSTING_AMT` DECIMAL(21,4) NOT NULL,
	`BU01_ID` VARCHAR(10) 	 NULL,
	`BU01_NM` VARCHAR(150) 	 NULL,
	CONSTRAINT `PK_DC0021_CUST_SALES` PRIMARY KEY (`DATA_DATE`,`RPT_YM`,`WANT_CHAN_ID`,`WANT_COM_ID`,`PROD_H1_ID`,`PROD_H2_ID`,`PROD_H3_ID`)
)

;

SET FOREIGN_KEY_CHECKS=1 ;
