SET FOREIGN_KEY_CHECKS=0 ;

CREATE TABLE `DC0022_EMP_SALES`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`DATA_DATE` CHAR(8) NOT NULL,
	`EMP_ID` VARCHAR(8) NOT NULL,
	`EMP_NM` VARCHAR(60) NOT NULL,
	`EMP_GENDER` CHAR(1) 	 NULL,
	`EMP_GENDER_NM` VARCHAR(150) 	 NULL,
	`ONBOARD_YMD` CHAR(8) NOT NULL,
	`SENIORITY` DECIMAL(21,4) NOT NULL,
	`HR_COM_ID` VARCHAR(8) NOT NULL,
	`HR_COM_NM` VARCHAR(60) 	 NULL,
	`HR_OFF_ID` VARCHAR(8) NOT NULL,
	`HR_OFF_NM` VARCHAR(60) 	 NULL,
	`EMP_POS_ID` VARCHAR(8) NOT NULL,
	`EMP_POS_NM` VARCHAR(60) 	 NULL,
	`EMP_POS_PROP_ID` VARCHAR(3) NOT NULL,
	`EMP_POS_PROP_NM` VARCHAR(60) 	 NULL,
	`EMP_POS_TYPE` VARCHAR(3) NOT NULL,
	`EMP_POS_TYPE_NM` VARCHAR(60) 	 NULL,
	`EMP_POS_TITLE_ID` VARCHAR(8) NOT NULL,
	`EMP_POS_TITLE_NM` VARCHAR(60) 	 NULL,
	`EMP_POS_LEVEL_ID` VARCHAR(2) NOT NULL,
	`EMP_POS_LEVEL_NM` VARCHAR(60) 	 NULL,
	`EMP_POS_FLAG` VARCHAR(2) 	 NULL,
	CONSTRAINT `PK_DC0022_EMP_SALES` PRIMARY KEY (`DATA_DATE`,`EMP_ID`)
)

;

SET FOREIGN_KEY_CHECKS=1 ;
