SET FOREIGN_KEY_CHECKS=0 ;

CREATE TABLE `BW_SAPBHP_BIC_TZWWCHAN`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`BIC_ZWWCHAN` VARCHAR(10) NOT NULL,
	`TXTSH` VARCHAR(20) NOT NULL
)

;

CREATE TABLE `BW_SAPBHP_BIC_TZWW_COMPY`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`BIC_ZWW_COMPY` VARCHAR(4) NOT NULL,
	`TXTSH` VARCHAR(20) NOT NULL
)

;

CREATE TABLE `BW_SAPBHP_BIC_TZSD_PXXL`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`BIC_ZSD_PXXL` VARCHAR(5) NOT NULL,
	`LANGU` VARCHAR(1) NOT NULL,
	`TXTSH` VARCHAR(20) NOT NULL
)

;

CREATE TABLE `BW_SAPBHP_BIC_TZCOOIC064`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`BIC_ZCOOIC064` VARCHAR(6) NOT NULL,
	`LANGU` VARCHAR(1) NOT NULL,
	`TXTSH` VARCHAR(20) NOT NULL
)

;

CREATE TABLE `BW_SAPBHP_BIC_PZCUS_WWID`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`DISTR_CHAN` VARCHAR(2) NOT NULL,
	`MATERIAL` VARCHAR(18) NOT NULL,
	`DIVISION` VARCHAR(2) NOT NULL,
	`SALESORG` VARCHAR(4) NOT NULL,
	`ITEM_CATEG` VARCHAR(4) NOT NULL,
	`BIC_ZCUS_WWID` VARCHAR(15) NOT NULL,
	`OBJVERS` VARCHAR(1) NOT NULL,
	`BIC_ZWWCHAN` VARCHAR(10) NOT NULL
)

;

CREATE TABLE `BW_SAPBHP_BIC_AZWGZ_O0100`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`DOC_NUMBER` VARCHAR(15) NOT NULL,
	`S_ORD_ITEM` VARCHAR(6) NOT NULL,
	`DELIV_NUMB` VARCHAR(15) NOT NULL,
	`BIC_ZDN_ITEM` VARCHAR(6) NOT NULL,
	`DOC_DATE` VARCHAR(8) NOT NULL,
	`MATERIAL` VARCHAR(18) NOT NULL,
	`CUST_SALES` VARCHAR(15) NOT NULL,
	`CUSTOMER` VARCHAR(15) NOT NULL,
	`COMP_CODE` VARCHAR(4) NOT NULL,
	`SALESORG` VARCHAR(4) NOT NULL,
	`DISTR_CHAN` VARCHAR(2) NOT NULL,
	`DIVISION` VARCHAR(2) NOT NULL,
	`ITEM_CATEG` VARCHAR(4) NOT NULL,
	`BIC_ZCUS_WWID` VARCHAR(15) NOT NULL,
	`BIC_ZWGZ_KDM` DECIMAL(21,2) NOT NULL,
	`BIC_ZWGZ_QRM` DECIMAL(21,2) NOT NULL
)

;

CREATE TABLE `BW_SAPBHP_BIC_AZSD_O21900`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`CALMONTH` VARCHAR(6) NOT NULL,
	`CALDAY` VARCHAR(8) NOT NULL,
	`BIC_ZWD_FLAG` VARCHAR(1) NOT NULL,
	`BIC_ZWD_M2D` INT NOT NULL,
	`BIC_ZWD_M_SUM` INT NOT NULL
)

;

CREATE TABLE `BW_SAPBHP_BIC_AZSD_O2100`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`FISCYEAR` VARCHAR(4) NOT NULL,
	`FISCVARNT` VARCHAR(2) NOT NULL,
	`BILL_NUM` VARCHAR(10) NOT NULL,
	`BILL_ITEM` VARCHAR(6) NOT NULL,
	`CALMONTH` VARCHAR(6) NOT NULL,
	`CALDAY` VARCHAR(8) NOT NULL,
	`SUBTOTAL_1` DECIMAL(21,2) NOT NULL,
	`ITEM_CATEG` VARCHAR(4) NOT NULL,
	`CUST_SALES` VARCHAR(15) NOT NULL,
	`DIVISION` VARCHAR(2) NOT NULL,
	`MATERIAL` VARCHAR(18) NOT NULL,
	`DISTR_CHAN` VARCHAR(2) NOT NULL,
	`SALESORG` VARCHAR(4) NOT NULL,
	`COMP_CODE` VARCHAR(4) NOT NULL,
	`BIC_ZCUS_WWID` VARCHAR(15) NOT NULL,
	`CUSTOMER` VARCHAR(15) NOT NULL
)

;

CREATE TABLE `BW_SAPBHP_BIC_AZKZY_O0100`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`BIC_ZKNUM` VARCHAR(10) NOT NULL,
	`COMP_CODE` VARCHAR(4) NOT NULL,
	`SALESORG` VARCHAR(4) NOT NULL,
	`DISTR_CHAN` VARCHAR(2) NOT NULL,
	`DIVISION` VARCHAR(2) NOT NULL,
	`CUSTOMER` VARCHAR(15) NOT NULL,
	`MATERIAL` VARCHAR(18) NOT NULL,
	`MATL_GRP_1` VARCHAR(3) NOT NULL,
	`BIC_ZZKZYS` VARCHAR(1) NOT NULL,
	`BIC_ZKAMOUNT` DECIMAL(21,2) NOT NULL
)

;

CREATE TABLE `BW_SAPBHP_BIC_AZHR_O7300`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`EMPLOYEE` VARCHAR(8) NOT NULL,
	`CALMONTH` VARCHAR(6) NOT NULL,
	`RECORDMODE` VARCHAR(1) NOT NULL,
	`EE_SNAME` VARCHAR(30) NOT NULL,
	`BIC_ZAMT_06` DECIMAL(21,2) NOT NULL,
	`BIC_ZAMT_30` DECIMAL(21,2) NOT NULL,
	`BIC_ZAMT_255` DECIMAL(21,2) NOT NULL,
	`BIC_ZAMT_31` DECIMAL(21,2) NOT NULL,
	`BIC_ZAMT_56` DECIMAL(21,2) NOT NULL,
	`BIC_ZAMT_109` DECIMAL(21,2) NOT NULL,
	`CURRENCY` VARCHAR(5) NOT NULL
)

;

CREATE TABLE `BW_SAPBHP_BIC_AZHR_O7200`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`EMPLOYEE` VARCHAR(8) NOT NULL,
	`CALDAY` VARCHAR(8) NOT NULL,
	`ACTIONTYPE` VARCHAR(2) NOT NULL,
	`RECORDMODE` VARCHAR(1) NOT NULL,
	`EE_SNAME` VARCHAR(30) NOT NULL,
	`BIC_ZACTION_N` VARCHAR(40) NOT NULL
)

;

CREATE TABLE `BW_SAPBHP_BIC_AZHR_O7100`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`EMPLOYEE` VARCHAR(8) NOT NULL,
	`DATETO` VARCHAR(8) NOT NULL,
	`RECORDMODE` VARCHAR(1) NOT NULL,
	`BIC_ZORG_03` VARCHAR(8) NOT NULL,
	`BIC_ZORG_04` VARCHAR(8) NOT NULL,
	`BIC_ZORG_05` VARCHAR(8) NOT NULL,
	`BIC_ZORG_06` VARCHAR(8) NOT NULL,
	`BIC_ZORG_07` VARCHAR(8) NOT NULL,
	`BIC_ZORG_08` VARCHAR(8) NOT NULL,
	`BIC_ZORG_09` VARCHAR(8) NOT NULL,
	`BIC_ZORG_03_T` VARCHAR(20) NOT NULL,
	`BIC_ZORG_04_T` VARCHAR(20) NOT NULL,
	`BIC_ZORG_05_T` VARCHAR(20) NOT NULL,
	`BIC_ZORG_06_T` VARCHAR(20) NOT NULL,
	`BIC_ZORG_07_T` VARCHAR(20) NOT NULL,
	`BIC_ZORG_08_T` VARCHAR(20) NOT NULL,
	`BIC_ZORG_09_T` VARCHAR(20) NOT NULL,
	`EE_SNAME` VARCHAR(30) NOT NULL,
	`PERS_AREA` VARCHAR(4) NOT NULL,
	`BIC_ZPERS_A_N` VARCHAR(40) NOT NULL,
	`PERS_SAREA` VARCHAR(4) NOT NULL,
	`BIC_ZPERSSA_N` VARCHAR(20) NOT NULL,
	`ENTRYDATE` VARCHAR(8) NOT NULL,
	`BIC_ZORGUNIT` VARCHAR(8) NOT NULL,
	`BIC_ZORG_T` VARCHAR(20) NOT NULL,
	`HRPOSITION` VARCHAR(8) NOT NULL,
	`BIC_ZHRPOS_N` VARCHAR(50) NOT NULL,
	`BIC_ZPOS_ATTR` VARCHAR(10) NOT NULL,
	`BIC_ZPOS_A_N` VARCHAR(20) NOT NULL,
	`BIC_ZHRIC189` VARCHAR(3) NOT NULL,
	`BIC_ZHRIC205` VARCHAR(20) NOT NULL,
	`BIC_ZHRIC206` VARCHAR(3) NOT NULL,
	`BIC_ZHRIC208` VARCHAR(40) NOT NULL,
	`BIC_ZHRIC207` VARCHAR(32) NOT NULL,
	`JOB` VARCHAR(8) NOT NULL,
	`BIC_ZJOB_N` VARCHAR(20) NOT NULL,
	`BIC_ZSGRADE` VARCHAR(2) NOT NULL,
	`BIC_ZGRADE_N` VARCHAR(20) NOT NULL,
	`GENDER` VARCHAR(4) NOT NULL,
	`BIC_ZHRIC209` VARCHAR(20) NOT NULL,
	`BIC_ZHRIK029` DECIMAL(21,3) NOT NULL
)

;

SET FOREIGN_KEY_CHECKS=1 ;
