/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 12-十一月-2018 上午 12:25:01 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 ;

/* Create Tables */

CREATE TABLE `IWANT_SALES_DISTRICT`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`ID` VARCHAR(10) NOT NULL,
	`NAME` VARCHAR(50) NOT NULL,
	`STATUS` CHAR(1) NOT NULL
)

;

SET FOREIGN_KEY_CHECKS=1 ;
