SET FOREIGN_KEY_CHECKS=0 ;

CREATE TABLE `KA_WANTWANT_KA_SAP_SHIPPING_RETURN`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`ID` BIGINT NOT NULL,
	`SAP_ORDER_NO` VARCHAR(64) NOT NULL,
	`SAP_POSNR` INT NOT NULL,
	`DIFFERENCE_BOX_NUM` INT NOT NULL,
	`ACTUAL_DELIVER_BOX_NUM` INT NOT NULL,
	`SAP_HARVEST_DATE` CHAR(8) NOT NULL,
	`SAP_RETURN_RECEIPT_DATE` CHAR(8) NOT NULL,
	`SAP_SHIPMENT_NUM` VARCHAR(64) NOT NULL,
	`SAP_SHIPMENT_NAME` VARCHAR(32) NOT NULL,
	`RETURN_DATE` CHAR(8) NOT NULL,
	`RETURN_TIME` CHAR(14) NOT NULL,
	`CUSTOMER_RECEIVED_BOX_NUM` INT NOT NULL,
	`TEXT_DESC` VARCHAR(32) NOT NULL,
	`CREATED` CHAR(14) NOT NULL
)

;

CREATE TABLE `KA_WANTWANT_KA_SAP_PIN_CHECK_DETAIL`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`ID` BIGINT NOT NULL,
	`SAP_PIN_CHECK_ID` BIGINT NOT NULL,
	`SAP_ORDER_NO` VARCHAR(64) NOT NULL,
	`STATUS` INT NOT NULL,
	`SAP_POSNR` INT NOT NULL,
	`SAP_PER_PRICE` DECIMAL(10,2) NOT NULL,
	`SAP_ORDER_CREATE_NUM` DECIMAL(15,3) NOT NULL,
	`SAP_APP_NEW_PRICE` DECIMAL(10,2) NOT NULL,
	`SAP_PROMOTION_SEASON_DATE` CHAR(8) NOT NULL,
	`SAP_IS_CHECK` VARCHAR(10) NOT NULL,
	`SAP_REASON_REJECTION` VARCHAR(64) NOT NULL,
	`IS_SHIPPING` INT NOT NULL,
	`AUDIT_STATUS` INT NOT NULL
)

;

CREATE TABLE `KA_WANTWANT_KA_SAP_PIN_CHECK`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`ID` BIGINT NOT NULL,
	`SAP_ORDER_NO` VARCHAR(64) NOT NULL,
	`ORDER_MAIN_ID` VARCHAR(40) NOT NULL,
	`AUDIT_STATUS` INT NOT NULL,
	`SAP_OPEN_ORDER_DATE` CHAR(8) NOT NULL,
	`SAP_DELIVERY_BRANCH` VARCHAR(64) NOT NULL,
	`SAP_IS_CHECK` VARCHAR(10) NOT NULL,
	`SAP_CHECK_NUM` VARCHAR(64) NOT NULL,
	`STATUS` INT NOT NULL,
	`SAP_AUDIT_NAME` VARCHAR(64) NOT NULL,
	`RETURN_DATE` CHAR(14) NOT NULL,
	`RETURN_TIME` CHAR(14) NOT NULL,
	`CREATED` CHAR(14) NOT NULL
)

;

CREATE TABLE `KA_WANTWANT_KA_SAP_ORDER_DETAIL`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`ID` BIGINT NOT NULL,
	`KA_SAP_ORDER_ID` BIGINT NOT NULL,
	`OPEN_NO` VARCHAR(64) NOT NULL,
	`VALID_NO` VARCHAR(64) NOT NULL,
	`KA_MATERIEL_CODE` VARCHAR(64) NOT NULL,
	`KA_MATERIEL_NAME` VARCHAR(255) NOT NULL,
	`IS_BUY_TERM` VARCHAR(8) NOT NULL,
	`PER_PRODUCTION_DATE` CHAR(8) NOT NULL,
	`STORE_PLACE` VARCHAR(32) NOT NULL,
	`SAP_BOX_OLD_PRICE` DECIMAL(10,4) NOT NULL,
	`SAP_BOX_NEW_PRICE` DECIMAL(10,4) NOT NULL,
	`SAP_ORDER_NUM` INT NOT NULL,
	`KA_TOTAL_BOX_NUM` INT NOT NULL,
	`KA_MATERIEL_CODE_REPLACE` VARCHAR(64) NOT NULL,
	`KA_MATERIEL_NAME_REPLACE` VARCHAR(64) NOT NULL,
	`IS_REPLACE` INT NOT NULL,
	`SAP_POSNR` INT NOT NULL,
	`SAP_PER_PRICE` DECIMAL(10,2) NOT NULL,
	`SAP_ORDER_CREATE_NUM` INT NOT NULL,
	`SAP_RETURN_DESC` VARCHAR(200) NOT NULL,
	`SAP_AUDIT_BOX_NUM` INT NOT NULL,
	`SAP_AUDIT_PER_PRICE` DECIMAL(10,2) NOT NULL,
	`SAP_REASON_REJECTION` VARCHAR(64) NOT NULL,
	`SAP_DELIVE_BOX_NUM` INT NOT NULL,
	`DIFFERENCE_BOX_NUM` INT NOT NULL
)

;

CREATE TABLE `KA_WANTWANT_KA_SAP_ORDER`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`ID` BIGINT NOT NULL,
	`ORDER_CREATE_NUMBER` INT NOT NULL,
	`OPEN_NO` VARCHAR(64) NOT NULL,
	`CHECK_NO` VARCHAR(64) NOT NULL,
	`ORDER_MAIN_ID` VARCHAR(40) NOT NULL,
	`ORDER_NO` VARCHAR(64) NOT NULL,
	`STORE_CODE` VARCHAR(64) NOT NULL,
	`STORE_NAME` VARCHAR(64) NOT NULL,
	`DELIVER_ADDRESS_CODE` VARCHAR(64) NOT NULL,
	`DELIVER_ADDRESS_DESC` VARCHAR(2000) NOT NULL,
	`JUDGE_FIELD` VARCHAR(32) NOT NULL,
	`SAP_CUST_CODE` VARCHAR(64) NOT NULL,
	`KA_DELIVER_COMP_CODE` VARCHAR(64) NOT NULL,
	`KA_DELIVER_COMP_NAME` VARCHAR(64) NOT NULL,
	`KA_BILL_COMP_CODE` VARCHAR(64) NOT NULL,
	`KA_BILL_COMP_NAME` VARCHAR(64) NOT NULL,
	`KA_BILL_DITCH_CODE` VARCHAR(64) NOT NULL,
	`KA_BILL_PROD_CODE` VARCHAR(64) NOT NULL,
	`DELIVER_DATE` CHAR(8) NOT NULL,
	`SAP_BILL_DELIVER_CODE` VARCHAR(64) NOT NULL,
	`SAP_BILL_DELIVER_NAME` VARCHAR(64) NOT NULL,
	`IS_FACT_DEV` VARCHAR(6) NOT NULL,
	`OPEN_ORDER_DATE` CHAR(8) NOT NULL,
	`SAP_ORDER_NO` VARCHAR(64) NOT NULL,
	`SAP_RETURN_DESC` VARCHAR(200) NOT NULL,
	`RETURN_TIME` CHAR(14) NOT NULL,
	`ORDER_STATUS` INT NOT NULL,
	`STATUS` INT NOT NULL,
	`REQUEST_DESC` VARCHAR(32) NOT NULL,
	`CREATED_TIME` CHAR(14) NOT NULL,
	`CREATED_BY` VARCHAR(32) NOT NULL,
	`CREATED_BY_NAME` VARCHAR(32) NOT NULL,
	`UPDATED_TIME` CHAR(14) NOT NULL,
	`UPDATED_BY` VARCHAR(32) NOT NULL,
	`UPDATE_BY_NAME` VARCHAR(32) NOT NULL
)

;

CREATE TABLE `KA_WANTWANT_KA_ORDER_CHECK_RESULT`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`ID` BIGINT NOT NULL,
	`SYS_CODE` CHAR(4) NOT NULL,
	`STORE_CODE` VARCHAR(64) NOT NULL,
	`STORE_NAME` VARCHAR(64) NOT NULL,
	`DELIVER_ADDRESS_CODE` VARCHAR(64) NOT NULL,
	`DELIVER_ADDRESS_DESC` VARCHAR(2000) NOT NULL,
	`JUDGE_FIELD` VARCHAR(32) NOT NULL,
	`CHECK_NO` VARCHAR(32) NOT NULL,
	`ORDER_NO` VARCHAR(32) NOT NULL,
	`ORDER_MAIN_ID` VARCHAR(40) NOT NULL,
	`CUST_CODE` VARCHAR(64) NOT NULL,
	`DELIVER_COMP_CODE` VARCHAR(64) NOT NULL,
	`BILL_COMP_CODE` VARCHAR(64) NOT NULL,
	`BILL_DITCH_CODE` VARCHAR(64) NOT NULL,
	`BILL_PROD_CODE` VARCHAR(64) NOT NULL,
	`BILL_DELIVER_CODE` VARCHAR(64) NOT NULL,
	`OPEN_ORDER_DATE` CHAR(8) NOT NULL,
	`IS_FACTDEV` VARCHAR(11) NOT NULL,
	`CHECK_USER` BIGINT NOT NULL,
	`CHECK_DATE` CHAR(8) NOT NULL,
	`CHECK_TIME` CHAR(6) NOT NULL,
	`TYPE` INT NOT NULL,
	`IS_OVER` VARCHAR(11) NOT NULL,
	`RESULT_DATE` CHAR(8) NOT NULL,
	`RESULT_TIME` CHAR(6) NOT NULL,
	`CHECK_STATUS` INT NOT NULL,
	`CHECK_RESULT` VARCHAR(200) NOT NULL,
	`STATUS` INT NOT NULL,
	`CREATE_TIME` CHAR(14) NOT NULL,
	`CREATE_BY` BIGINT NOT NULL,
	`CREATE_BY_NAME` VARCHAR(32) NOT NULL
)

;

CREATE TABLE `KA_WANTWANT_KA_ORDER_CHECK_DETAIL_RESULT`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`ID` BIGINT NOT NULL,
	`ORDER_MAIN_ID` VARCHAR(40) NOT NULL,
	`CHECK_NO` VARCHAR(32) NOT NULL,
	`ORDER_NUM` VARCHAR(32) NOT NULL,
	`MATERIEL_CODE` VARCHAR(64) NOT NULL,
	`MATERIEL_NAME` VARCHAR(64) NOT NULL,
	`ALLOW_DATE` CHAR(8) NOT NULL,
	`SAP_ORDER_NUM` INT NOT NULL,
	`SAP_BOX_PRICE` DECIMAL(16,2) NOT NULL,
	`SAP_BOX_PRICE_OLD` DECIMAL(16,4) NOT NULL,
	`MATERIEL_CODE_REPLACE` VARCHAR(64) NOT NULL,
	`MATERIEL_NAME_REPLACE` VARCHAR(64) NOT NULL,
	`IS_BUY_TERM` VARCHAR(20) NOT NULL,
	`RESULT` VARCHAR(200) NOT NULL,
	`DISTRO_RESULT` VARCHAR(200) NOT NULL,
	`STATUS` INT NOT NULL
)

;

SET FOREIGN_KEY_CHECKS=1 ;
