DROP PROCEDURE IF EXISTS RAWWANT.SP_DAT_BW_HR_00001_TRUNCATE_TABLE;

CREATE PROCEDURE RAWWANT.SP_DAT_BW_HR_00001_TRUNCATE_TABLE (
    VAR_EDI_NO CHAR(12), VAR_DATA_DATE CHAR(8), OUT VAR_SP_RESULT CHAR(1)
)
BEGIN

    TRUNCATE TABLE RAWWANT.BW_SAPBHP_BIC_AZHR_O7100;
    TRUNCATE TABLE RAWWANT.BW_SAPBHP_BIC_AZHR_O7200;
    TRUNCATE TABLE RAWWANT.BW_SAPBHP_BIC_AZHR_O7300;

    SET VAR_SP_RESULT='Y';
    COMMIT;
END
;