--檢查CUSTOMER_SALES以及CUSTOMER的客戶ID是否匹配 441 
SELECT *
FROM RAWWANT.IWANT_SALES_CUSTOMER_SALES
WHERE CUSTOMER_ID NOT IN (SELECT ID FROM RAWWANT.IWANT_SALES_CUSTOMER)
;

--排除STATUS=’0’(已失效)以及CUSTOMER_ID=‘999’ 0
SELECT *
FROM RAWWANT.IWANT_SALES_CUSTOMER_SALES
WHERE STATUS <> '0' AND CUSTOMER_ID <> '999' AND CUSTOMER_ID NOT IN (SELECT ID FROM RAWWANT.IWANT_SALES_CUSTOMER)
;

--檢查CUSTOMER以及MARKET_FULL_VIEW的THIRD_ID是否匹配 11472 
SELECT *
FROM RAWWANT.IWANT_SALES_CUSTOMER
WHERE THIRD_ID NOT IN (SELECT THIRD_ID FROM RAWWANT.IWANT_SALES_MARKET_FULL_VIEW)
;
--排除BRANCH=null 0
SELECT *
FROM RAWWANT.IWANT_SALES_CUSTOMER
WHERE BRANCH_ID <> '' AND THIRD_ID NOT IN (SELECT THIRD_ID FROM RAWWANT.IWANT_SALES_MARKET_FULL_VIEW)
;

--檢查CUSTOMER_SALES的CREDIT_ID以及CHANNEL的CHANNEL_ID是否匹配 27349
SELECT *
FROM RAWWANT.IWANT_SALES_CUSTOMER_SALES
WHERE CREDIT_ID NOT IN (SELECT CHANNEL_ID FROM RAWWANT.IWANT_SALES_CHANNEL)
;

--排除STATUS='0' AND CREDIT_ID = null  0
SELECT *
FROM RAWWANT.IWANT_SALES_CUSTOMER_SALES
WHERE STATUS<>'0' AND CREDIT_ID <> null AND CREDIT_ID NOT IN (SELECT CHANNEL_ID FROM RAWWANT.IWANT_SALES_CHANNEL)
;

--檢查CUSTOMER_SALES的USER_ID以及EMP_POSITION_ORG_VIEW的EMP_ID是否匹配 27349
SELECT *
FROM RAWWANT.IWANT_SALES_CUSTOMER_SALES
WHERE USER_ID NOT IN (SELECT EMP_ID FROM RAWWANT.IWANT_SALES_EMP_POSITION_ORG_VIEW)
;

--排除STATUS='0'  (00070835,00323794) 2 愛旺旺上面有這兩個人 
SELECT *
FROM RAWWANT.IWANT_SALES_CUSTOMER_SALES
WHERE STATUS<>'0' AND USER_ID NOT IN (SELECT EMP_ID FROM RAWWANT.IWANT_SALES_EMP_POSITION_ORG_VIEW)
;

SELECT *
FROM RAWWANT.IWANT_SALES_EMP_POSITION_ORG_VIEW
ORDER BY EMP_ID
;

--檢查已失效、未生效、已生效邏輯
SELECT STATUS
     , START_TIME
     , CASE WHEN STATUS='0' THEN '已失效'
            WHEN STATUS='1' AND DATE(SYSDATE()) <  DATE(START_TIME) THEN '未生效'
     			  ELSE '已生效' END AS STATUS_TXT
FROM RAWWANT.IWANT_SALES_CUSTOMER_SALES
ORDER BY STATUS DESC, START_TIME DESC
;


--確認POS_TYPE_ID = 001及004 (總監及所長) 是否可以排除
SELECT *
FROM RAWWANT.IWANT_SALES_EMP_POSITION_ORG_VIEW
WHERE POS_TYPE_ID IN ('001','004')
;

SELECT *
FROM RAWWANT.IWANT_SALES_EMP_POSITION_ORG_VIEW
WHERE POS_TYPE_ID IN ('001','004') AND EMP_ID NOT IN (SELECT EMP_ID FROM RAWWANT.IWANT_SALES_EMP_POSITION_ORG_VIEW WHERE POS_TYPE_ID NOT IN ('001','004') )
;

SELECT *
FROM RAWWANT.IWANT_SALES_CUSTOMER_SALES
WHERE USER_ID = '00022354'
; 

/*
SELECT *
FROM RAWWANT.IWANT_SALES_EMP_POSITION_ORG_VIEW
WHERE POS_TYPE_ID NOT IN ('001','004')
*/
--檢查經銷商自有業代
SELECT *
FROM RAWWANT.IWANT_SALES_EMP_POSITION_ORG_VIEW
WHERE LOCATE('C', EMP_ID)=0
;
SELECT *
FROM RAWWANT.IWANT_SALES_CUSTOMER_SALES
WHERE LOCATE('C', EMP_ID)=0
;

--不包含虛擬經銷商  29940  34323
SELECT COUNT(1)
FROM(
SELECT DISTINCT 
       A.CREDIT_ID AS CHANNEL_ID, G.CHANNEL_NAME
		 , C.COMPANY_ID, C.COMPANY_NAME
		 , C.BRANCH_ID, C.BRANCH_NAME
     , C.MARKET_ID AS CUS_MARKET_ID, C.MARKET_NAME AS CUS_MARKET_NAME
		 , C.THIRD_ID, C.THIRD_NAME
		 , A.CUSTOMER_ID, B.NAME CUSTOMER_NAME
		 , A.USER_ID EMP_ID, EMP1.EMP_NAME
		 , EMP1.CHANNEL_ID AS EMP_CHANNEL_ID
		 , EMP1.POS_NAME
     , CASE WHEN A.STATUS='0' THEN '已失效'
            WHEN A.STATUS='1' AND DATE(SYSDATE()) <  DATE(A.START_TIME) THEN '未生效'
     			  ELSE '已生效' END AS STATUS
		 , A.START_TIME, A.END_TIME
		 , CSMR.MARKET_RELATION_ID, CSMR.MARKET_TYPE
     , CSMR.MARKET_ID, CSMR.MARKET_NAME
		 , CSMR.SMALL_MARKET_ID, CSMR.SMALL_MARKET_NAME
FROM RAWWANT.IWANT_SALES_CUSTOMER_SALES A
JOIN RAWWANT.IWANT_SALES_CUSTOMER B 
  ON A.CUSTOMER_ID=B.ID
JOIN RAWWANT.IWANT_SALES_MARKET_FULL_VIEW C 
  ON B.THIRD_ID=C.THIRD_ID
JOIN RAWWANT.IWANT_SALES_CHANNEL G 
ON A.CREDIT_ID=G.CHANNEL_ID
LEFT JOIN RAWWANT.IWANT_SALES_EMP_POSITION_ORG_VIEW EMP1
       ON A.USER_ID=EMP1.EMP_ID
LEFT JOIN RAWWANT.IWANT_SALES_CUS_SALES_MARKET_REL CSMR 
       ON A.MARKET_RELATION_ID=CSMR.MARKET_RELATION_ID
WHERE A.CUSTOMER_ID<>'999'AND A.STATUS='1' AND DATE(SYSDATE()) >=  DATE(A.START_TIME) AND LOCATE('C', A.USER_ID)=0 
) A
;



--









--檢查CUSTOMER_SALES的EMP_BRANCH_ID以及MARKET_FULL_VIEW的BRANCH_ID是否匹配

SELECT EMP_BRANCH_ID, COUNT(1)
FROM RAWWANT.IWANT_SALES_CUSTOMER_SALES
GROUP BY EMP_BRANCH_ID
;

SELECT *
FROM RAWWANT.IWANT_SALES_CUSTOMER_SALES
WHERE CUSTOMER_ID='999' AND EMP_BRANCH_ID<>'' AND EMP_BRANCH_ID NOT IN (SELECT BRANCH_ID FROM RAWWANT.IWANT_SALES_MARKET_FULL_VIEW)
;

SELECT *
FROM RAWWANT.IWANT_SALES_CUSTOMER_SALES
WHERE CUSTOMER_ID='999' AND EMP_COMPANY_ID<>'' AND EMP_COMPANY_ID NOT IN (SELECT COMPANY_ID FROM RAWWANT.IWANT_SALES_MARKET_FULL_VIEW)
;

SELECT *
FROM RAWWANT.IWANT_SALES_CUSTOMER_SALES
WHERE STATUS<>'0' AND USER_ID NOT IN (SELECT EMP_ID FROM RAWWANT.IWANT_SALES_EMP_POSITION_ORG_VIEW)
;


--虚拟经销商虚拟经销商 
SELECT COUNT(1)
FROM (
SELECT DISTINCT 
       A.CREDIT_ID CHANNEL_ID, G.CHANNEL_NAME
		 , A.EMP_COMPANY_ID, NVL(C.NAME, ' ') COMPANY_NAME
		 , NVL(A.EMP_BRANCH_ID, ' ') BRANCH_ID, NVL(B.BRANCH_NAME, ' ') BRANCH_NAME
		 , ' ' CUSTOMER_MARKET_ID, ' ' CUSTOMER_MARKET_NAME
		 , ' ' THIRD_ID , ' ' THIRD_NAME
		 , A.CUSTOMER_ID, '虚拟经销商' CUSTOMER_NAME
		 , A.USER_ID EMP_ID, EMP1.EMP_NAME
		 , EMP1.CHANNEL_ID EMP_CHANNEL_ID
		 , EMP1.POS_NAME
     , CASE WHEN A.STATUS='0' THEN '已失效'
            WHEN A.STATUS='1' AND DATE(SYSDATE()) <  DATE(A.START_TIME) THEN '未生效'
     			  ELSE '已生效' END AS STATUS
		 , A.START_TIME, A.END_TIME
		 , CSMR.MARKET_RELATION_ID, CSMR.MARKET_TYPE
     , CSMR.MARKET_ID, CSMR.MARKET_NAME
		 , CSMR.SMALL_MARKET_ID, CSMR.SMALL_MARKET_NAME
FROM RAWWANT.IWANT_SALES_CUSTOMER_SALES A
JOIN RAWWANT.IWANT_SALES_CHANNEL G 
  ON A.CREDIT_ID=G.CHANNEL_ID
LEFT JOIN RAWWANT.IWANT_SALES_MARKET_FULL_VIEW B 
  ON A.EMP_BRANCH_ID = B.BRANCH_ID
LEFT JOIN RAWWANT.IWANT_SALES_COMPANY C 
       ON A.EMP_COMPANY_ID = C.ID 
LEFT JOIN RAWWANT.IWANT_SALES_EMP_POSITION_ORG_VIEW EMP1 
       ON A.USER_ID=EMP1.EMP_ID
LEFT JOIN RAWWANT.IWANT_SALES_CUS_SALES_MARKET_REL CSMR 
       ON A.MARKET_RELATION_ID=CSMR.MARKET_RELATION_ID
WHERE A.CUSTOMER_ID='999' AND  A.STATUS='1' AND DATE(SYSDATE()) >=  DATE(A.START_TIME) AND LOCATE('C', A.USER_ID)=0 
) A
;



--UNION ALL COUNT(1) 33248
SELECT DISTINCT 
       A.CREDIT_ID AS CHANNEL_ID, G.CHANNEL_NAME
		 , C.COMPANY_ID, C.COMPANY_NAME
		 , C.BRANCH_ID, C.BRANCH_NAME
     , C.MARKET_ID AS CUS_MARKET_ID, C.MARKET_NAME AS CUS_MARKET_NAME
		 , C.THIRD_ID, C.THIRD_NAME
		 , A.CUSTOMER_ID, B.NAME CUSTOMER_NAME
		 , A.USER_ID AS EMP_ID, EMP1.EMP_NAME
		 , EMP1.CHANNEL_ID AS EMP_CHANNEL_ID
		 , EMP1.POS_NAME
     , CASE WHEN A.STATUS='0' THEN '已失效'
            WHEN A.STATUS='1' AND DATE(SYSDATE()) <  DATE(A.START_TIME) THEN '未生效'
     			  ELSE '已生效' END AS STATUS
		 , A.START_TIME, A.END_TIME
		 , CSMR.MARKET_RELATION_ID, CSMR.MARKET_TYPE
     , CSMR.MARKET_ID, CSMR.MARKET_NAME
		 , CSMR.SMALL_MARKET_ID, CSMR.SMALL_MARKET_NAME
FROM RAWWANT.IWANT_SALES_CUSTOMER_SALES A
JOIN RAWWANT.IWANT_SALES_CUSTOMER B 
  ON A.CUSTOMER_ID=B.ID
JOIN RAWWANT.IWANT_SALES_MARKET_FULL_VIEW C 
  ON B.THIRD_ID=C.THIRD_ID
JOIN RAWWANT.IWANT_SALES_CHANNEL G 
ON A.CREDIT_ID=G.CHANNEL_ID
LEFT JOIN RAWWANT.IWANT_SALES_EMP_POSITION_ORG_VIEW EMP1
       ON A.USER_ID=EMP1.EMP_ID
LEFT JOIN RAWWANT.IWANT_SALES_CUS_SALES_MARKET_REL CSMR 
       ON A.MARKET_RELATION_ID=CSMR.MARKET_RELATION_ID
WHERE A.CUSTOMER_ID<>'999'AND A.STATUS='1' AND DATE(SYSDATE()) >=  DATE(A.START_TIME) AND LOCATE('C', A.USER_ID)=0 
UNION ALL
SELECT DISTINCT  
       A.CREDIT_ID AS CHANNEL_ID, G.CHANNEL_NAME
		 , A.EMP_COMPANY_ID, B.COMPANY_NAME
		 , B.BRANCH_ID, B.BRANCH_NAME
		 , '' AS CUS_MARKET_ID, '' AS CUS_MARKET_NAME
		 , '' AS THIRD_ID , '' AS THIRD_NAME
		 , A.CUSTOMER_ID, '虚拟经销商' AS CUSTOMER_NAME
		 , A.USER_ID AS EMP_ID, EMP1.EMP_NAME
		 , EMP1.CHANNEL_ID AS EMP_CHANNEL_ID
		 , EMP1.POS_NAME
     , CASE WHEN A.STATUS='0' THEN '已失效'
            WHEN A.STATUS='1' AND DATE(SYSDATE()) <  DATE(A.START_TIME) THEN '未生效'
     			  ELSE '已生效' END AS STATUS
		 , A.START_TIME, A.END_TIME
		 , CSMR.MARKET_RELATION_ID, CSMR.MARKET_TYPE
     , CSMR.MARKET_ID, CSMR.MARKET_NAME
		 , CSMR.SMALL_MARKET_ID, CSMR.SMALL_MARKET_NAME
FROM RAWWANT.IWANT_SALES_CUSTOMER_SALES A
JOIN RAWWANT.IWANT_SALES_CHANNEL G 
  ON A.CREDIT_ID=G.CHANNEL_ID
LEFT JOIN RAWWANT.IWANT_SALES_MARKET_FULL_VIEW B 
  ON A.EMP_BRANCH_ID = B.BRANCH_ID
LEFT JOIN RAWWANT.IWANT_SALES_EMP_POSITION_ORG_VIEW EMP1 
       ON A.USER_ID=EMP1.EMP_ID
LEFT JOIN RAWWANT.IWANT_SALES_CUS_SALES_MARKET_REL CSMR 
       ON A.MARKET_RELATION_ID=CSMR.MARKET_RELATION_ID
WHERE A.CUSTOMER_ID='999' AND  A.STATUS='1' AND DATE(SYSDATE()) >=  DATE(A.START_TIME) AND LOCATE('C', A.USER_ID)=0 

;


--subquery 1 24111
--PK CHANNEL_ID, CUSTOMER_ID, CUS_MARKET_ID, EMP_ID, START_TIME, END_TIME
SELECT DISTINCT
       A.CREDIT_ID AS CHANNEL_ID, G.CHANNEL_NAME
		 , A.CUSTOMER_ID, B.NAME CUSTOMER_NAME
		 , C.COMPANY_ID, C.COMPANY_NAME
		 , C.BRANCH_ID, C.BRANCH_NAME
     , C.MARKET_ID AS CUS_MARKET_ID, C.MARKET_NAME AS CUS_MARKET_NAME
		 , C.THIRD_ID, C.THIRD_NAME
		 , A.USER_ID AS EMP_ID
     , A.STATUS
		 , A.START_TIME, A.END_TIME
     , A.MARKET_RELATION_ID
FROM RAWWANT.IWANT_SALES_CUSTOMER_SALES A
JOIN RAWWANT.IWANT_SALES_CUSTOMER B
  ON A.CUSTOMER_ID=B.ID
JOIN RAWWANT.IWANT_SALES_MARKET_FULL_VIEW C 
  ON B.THIRD_ID=C.THIRD_ID
JOIN RAWWANT.IWANT_SALES_CHANNEL G 
  ON A.CREDIT_ID=G.CHANNEL_ID
WHERE CUSTOMER_ID<>'999' AND A.STATUS='1' AND DATE(SYSDATE()) >=  DATE(A.START_TIME) AND LOCATE('C', A.USER_ID)=0 
UNION ALL
SELECT DISTINCT
       A.CREDIT_ID AS CHANNEL_ID, G.CHANNEL_NAME
		 , A.CUSTOMER_ID, '虚拟经销商' AS CUSTOMER_NAME
		 , B.COMPANY_ID, B.COMPANY_NAME
		 , B.BRANCH_ID, B.BRANCH_NAME
     , '' AS CUS_MARKET_ID, '' AS CUS_MARKET_NAME
		 , '' AS THIRD_ID, '' AS THIRD_NAME
		 , A.USER_ID AS EMP_ID
     , A.STATUS
		 , A.START_TIME, A.END_TIME
     , A.MARKET_RELATION_ID
FROM RAWWANT.IWANT_SALES_CUSTOMER_SALES A
JOIN RAWWANT.IWANT_SALES_MARKET_FULL_VIEW B
  ON A.EMP_BRANCH_ID = B.BRANCH_ID
JOIN RAWWANT.IWANT_SALES_CHANNEL G 
  ON A.CREDIT_ID=G.CHANNEL_ID
WHERE CUSTOMER_ID='999' AND A.STATUS='1' AND DATE(SYSDATE()) >=  DATE(A.START_TIME) AND LOCATE('C', A.USER_ID)=0
;

--CHECK PK
SELECT Y.CHANNEL_ID, Y.CUSTOMER_ID, Y.CUS_MARKET_ID, Y.EMP_ID, Y.START_TIME, Y.END_TIME, Y.CN
FROM (
SELECT Z.CHANNEL_ID, Z.CUSTOMER_ID, Z.CUS_MARKET_ID, Z.EMP_ID, Z.START_TIME, Z.END_TIME, COUNT(1) AS CN
FROM (
SELECT DISTINCT
       A.CREDIT_ID AS CHANNEL_ID, G.CHANNEL_NAME
		 , A.CUSTOMER_ID, B.NAME CUSTOMER_NAME
		 , C.COMPANY_ID, C.COMPANY_NAME
		 , C.BRANCH_ID, C.BRANCH_NAME
     , C.MARKET_ID AS CUS_MARKET_ID, C.MARKET_NAME AS CUS_MARKET_NAME
		 , C.THIRD_ID, C.THIRD_NAME
		 , A.USER_ID AS EMP_ID
     , A.STATUS
		 , A.START_TIME, A.END_TIME
     , A.MARKET_RELATION_ID
FROM RAWWANT.IWANT_SALES_CUSTOMER_SALES A
JOIN RAWWANT.IWANT_SALES_CUSTOMER B
  ON A.CUSTOMER_ID=B.ID
JOIN RAWWANT.IWANT_SALES_MARKET_FULL_VIEW C 
  ON B.THIRD_ID=C.THIRD_ID
JOIN RAWWANT.IWANT_SALES_CHANNEL G 
  ON A.CREDIT_ID=G.CHANNEL_ID
WHERE CUSTOMER_ID<>'999' AND A.STATUS='1' AND DATE(SYSDATE()) >=  DATE(A.START_TIME) AND LOCATE('C', A.USER_ID)=0 
UNION ALL
SELECT DISTINCT
       A.CREDIT_ID AS CHANNEL_ID, G.CHANNEL_NAME
		 , A.CUSTOMER_ID, '虚拟经销商' AS CUSTOMER_NAME
		 , B.COMPANY_ID, B.COMPANY_NAME
		 , B.BRANCH_ID, B.BRANCH_NAME
     , '' AS CUS_MARKET_ID, '' AS CUS_MARKET_NAME
		 , '' AS THIRD_ID, '' AS THIRD_NAME
		 , A.USER_ID AS EMP_ID
     , A.STATUS
		 , A.START_TIME, A.END_TIME
     , A.MARKET_RELATION_ID
FROM RAWWANT.IWANT_SALES_CUSTOMER_SALES A
JOIN RAWWANT.IWANT_SALES_MARKET_FULL_VIEW B
  ON A.EMP_BRANCH_ID = B.BRANCH_ID
JOIN RAWWANT.IWANT_SALES_CHANNEL G 
  ON A.CREDIT_ID=G.CHANNEL_ID
WHERE CUSTOMER_ID='999' AND A.STATUS='1' AND DATE(SYSDATE()) >=  DATE(A.START_TIME) AND LOCATE('C', A.USER_ID)=0
)Z
GROUP BY Z.CHANNEL_ID, Z.CUSTOMER_ID, Z.CUS_MARKET_ID, Z.EMP_ID, Z.START_TIME, Z.END_TIME
)Y
WHERE Y.CN>1
;





--USE subquery 1 33248
SELECT DISTINCT 
       SUB1.CHANNEL_ID, SUB1.CHANNEL_NAME
		 , SUB1.COMPANY_ID, SUB1.COMPANY_NAME
		 , SUB1.BRANCH_ID, SUB1.BRANCH_NAME
     , SUB1.CUS_MARKET_ID, SUB1.CUS_MARKET_NAME
		 , SUB1.THIRD_ID, SUB1.THIRD_NAME
		 , SUB1.CUSTOMER_ID, SUB1.CUSTOMER_NAME
		 , SUB1.EMP_ID, EMP1.EMP_NAME
		 , EMP1.CHANNEL_ID AS EMP_CHANNEL_ID
		 , EMP1.POS_NAME
     , CASE WHEN SUB1.STATUS='0' THEN '已失效'
            WHEN SUB1.STATUS='1' AND DATE(SYSDATE()) <  DATE(SUB1.START_TIME) THEN '未生效'
     			  ELSE '已生效' END AS STATUS
		 , SUB1.START_TIME, SUB1.END_TIME
		 , CSMR.MARKET_RELATION_ID, CSMR.MARKET_TYPE
     , CSMR.MARKET_ID, CSMR.MARKET_NAME
		 , CSMR.SMALL_MARKET_ID, CSMR.SMALL_MARKET_NAME
FROM (
SELECT DISTINCT
       A.CREDIT_ID AS CHANNEL_ID, G.CHANNEL_NAME
		 , A.CUSTOMER_ID, B.NAME CUSTOMER_NAME
		 , C.COMPANY_ID, C.COMPANY_NAME
		 , C.BRANCH_ID, C.BRANCH_NAME
     , C.MARKET_ID AS CUS_MARKET_ID, C.MARKET_NAME AS CUS_MARKET_NAME
		 , C.THIRD_ID, C.THIRD_NAME
		 , A.USER_ID AS EMP_ID
     , A.STATUS
		 , A.START_TIME, A.END_TIME
     , A.MARKET_RELATION_ID
FROM RAWWANT.IWANT_SALES_CUSTOMER_SALES A
JOIN RAWWANT.IWANT_SALES_CUSTOMER B
  ON A.CUSTOMER_ID=B.ID
JOIN RAWWANT.IWANT_SALES_MARKET_FULL_VIEW C 
  ON B.THIRD_ID=C.THIRD_ID
JOIN RAWWANT.IWANT_SALES_CHANNEL G 
  ON A.CREDIT_ID=G.CHANNEL_ID
WHERE CUSTOMER_ID<>'999' AND A.STATUS='1' AND DATE(SYSDATE()) >=  DATE(A.START_TIME) AND LOCATE('C', A.USER_ID)=0 
UNION ALL
SELECT DISTINCT
       A.CREDIT_ID AS CHANNEL_ID, G.CHANNEL_NAME
		 , A.CUSTOMER_ID, '虚拟经销商' AS CUSTOMER_NAME
		 , B.COMPANY_ID, B.COMPANY_NAME
		 , B.BRANCH_ID, B.BRANCH_NAME
     , '' AS CUS_MARKET_ID, '' AS CUS_MARKET_NAME
		 , '' AS THIRD_ID, '' AS THIRD_NAME
		 , A.USER_ID AS EMP_ID
     , A.STATUS
		 , A.START_TIME, A.END_TIME
     , A.MARKET_RELATION_ID
FROM RAWWANT.IWANT_SALES_CUSTOMER_SALES A
JOIN RAWWANT.IWANT_SALES_MARKET_FULL_VIEW B
  ON A.EMP_BRANCH_ID = B.BRANCH_ID
JOIN RAWWANT.IWANT_SALES_CHANNEL G 
  ON A.CREDIT_ID=G.CHANNEL_ID
WHERE CUSTOMER_ID='999' AND A.STATUS='1' AND DATE(SYSDATE()) >=  DATE(A.START_TIME) AND LOCATE('C', A.USER_ID)=0
) SUB1
LEFT JOIN RAWWANT.IWANT_SALES_EMP_POSITION_ORG_VIEW EMP1 
       ON SUB1.EMP_ID=EMP1.EMP_ID
LEFT JOIN RAWWANT.IWANT_SALES_CUS_SALES_MARKET_REL CSMR 
       ON SUB1.MARKET_RELATION_ID=CSMR.MARKET_RELATION_ID
;


/*
主任 AE           POS_TYPE_ID=013,014,015,024              
城市經理 CT_MAN    POS_TYPE_ID=027
區域經理 RGN_MAN   POS_TYPE_ID=006
區域總監 DGN_DIR   POS_TYPE_ID=028
*/

