--分公司  29筆  2.45秒
SELECT B.BIC_ZWW_COMPY, SUM(SF_AMOUNT) AS SF_AMOUNT
FROM (
      SELECT CONCAT('0000000',(CASE WHEN ERP_ID<>'' THEN ERP_ID ELSE KEYACCOUNT_ID END)) AS KEYACCOUNT_ID
           , PROD_ID
           , SUM(SF_AMOUNT) AS SF_AMOUNT
      FROM RAWWANT.IRPT_SAPBW_ZBW_SF_ZY_VIEW
      WHERE YEARMONTH ='201811'
      GROUP BY (CASE WHEN ERP_ID<>'' THEN ERP_ID ELSE KEYACCOUNT_ID END), PROD_ID) A
JOIN (
      SELECT CUSTOMER
           , BIC_ZWW_COMPY
      FROM RAWWANT.BW_SAPBHP_BI0_PCUSTOMER
      WHERE BIC_ZWW_COMPY<>'' AND LENGTH(CUSTOMER)=15) B
ON A.KEYACCOUNT_ID=B.CUSTOMER
JOIN RAWWANT.BW_SAPBHP_BI0_PMATERIAL M
ON A.PROD_ID=M.MATERIAL
GROUP BY B.BIC_ZWW_COMPY
ORDER BY B.BIC_ZWW_COMPY
;
--產品線 106筆  2.562秒
SELECT M.PRODH3, SUM(SF_AMOUNT) AS SF_AMOUNT
FROM (
      SELECT CONCAT('0000000',(CASE WHEN ERP_ID<>'' THEN ERP_ID ELSE KEYACCOUNT_ID END)) AS KEYACCOUNT_ID
           , PROD_ID
           , SUM(SF_AMOUNT) AS SF_AMOUNT
      FROM RAWWANT.IRPT_SAPBW_ZBW_SF_ZY_VIEW
      WHERE YEARMONTH ='201811'
      GROUP BY (CASE WHEN ERP_ID<>'' THEN ERP_ID ELSE KEYACCOUNT_ID END), PROD_ID) A
JOIN (
      SELECT CUSTOMER
           , BIC_ZWW_COMPY
      FROM RAWWANT.BW_SAPBHP_BI0_PCUSTOMER
      WHERE BIC_ZWW_COMPY<>'' AND LENGTH(CUSTOMER)=15) B
ON A.KEYACCOUNT_ID=B.CUSTOMER
JOIN RAWWANT.BW_SAPBHP_BI0_PMATERIAL M
ON A.PROD_ID=M.MATERIAL
GROUP BY M.PRODH3
ORDER BY M.PRODH3
;

--分公司產品線  1810筆 2.625秒
SELECT B.BIC_ZWW_COMPY, M.PRODH3
     , SUM(SF_AMOUNT) AS SF_AMOUNT
FROM (
      SELECT CONCAT('0000000',(CASE WHEN ERP_ID<>'' THEN ERP_ID ELSE KEYACCOUNT_ID END)) AS KEYACCOUNT_ID
           , PROD_ID
           , SUM(SF_AMOUNT) AS SF_AMOUNT
      FROM RAWWANT.IRPT_SAPBW_ZBW_SF_ZY_VIEW
      WHERE YEARMONTH ='201811'
      GROUP BY (CASE WHEN ERP_ID<>'' THEN ERP_ID ELSE KEYACCOUNT_ID END), PROD_ID) A
JOIN (
      SELECT CUSTOMER
           , BIC_ZWW_COMPY
      FROM RAWWANT.BW_SAPBHP_BI0_PCUSTOMER
      WHERE BIC_ZWW_COMPY<>'' AND LENGTH(CUSTOMER)=15) B
ON A.KEYACCOUNT_ID=B.CUSTOMER
JOIN RAWWANT.BW_SAPBHP_BI0_PMATERIAL M
ON A.PROD_ID=M.MATERIAL
GROUP BY B.BIC_ZWW_COMPY, M.PRODH3
ORDER BY B.BIC_ZWW_COMPY, M.PRODH3
;






--0
SELECT *
FROM RAWWANT.IRPT_SAPBW_ZBW_SF_ZY_VIEW
WHERE YEARMONTH ='201811' AND CONCAT('0000000',(CASE WHEN ERP_ID<>'' THEN ERP_ID ELSE KEYACCOUNT_ID END)) NOT IN (SELECT CUSTOMER FROM RAWWANT.BW_SAPBHP_BI0_PCUSTOMER WHERE BIC_ZWW_COMPY<>'' AND LENGTH(CUSTOMER) = 15)
;

--10
SELECT ERP_ID, KEYACCOUNT_ID
FROM RAWWANT.IRPT_SAPBW_ZBW_SF_ZY_VIEW
WHERE YEARMONTH ='201811' AND ERP_ID <> '' AND KEYACCOUNT_ID <>''
GROUP BY ERP_ID, KEYACCOUNT_ID
;



--6
SELECT A.ERP_ID, A.KEYACCOUNT_ID
     , B.BIC_ZWW_COMPY
     , C.BIC_ZWW_COMPY
FROM (
      SELECT ERP_ID, KEYACCOUNT_ID
      FROM RAWWANT.IRPT_SAPBW_ZBW_SF_ZY_VIEW
      WHERE YEARMONTH ='201811' AND ERP_ID <> '' AND KEYACCOUNT_ID <>''
      GROUP BY ERP_ID, KEYACCOUNT_ID
     ) A
JOIN ( 
      SELECT CUSTOMER
           , BIC_ZWW_COMPY
      FROM RAWWANT.BW_SAPBHP_BI0_PCUSTOMER
      WHERE BIC_ZWW_COMPY<>'' AND LENGTH(CUSTOMER)=15
     ) B
ON CONCAT('0000000',A.ERP_ID)=B.CUSTOMER
JOIN (
      SELECT CUSTOMER
           , BIC_ZWW_COMPY
      FROM RAWWANT.BW_SAPBHP_BI0_PCUSTOMER
      WHERE BIC_ZWW_COMPY<>'' AND LENGTH(CUSTOMER)=15
     ) C
ON CONCAT('0000000',A.KEYACCOUNT_ID)=C.CUSTOMER
WHERE B.BIC_ZWW_COMPY <> C.BIC_ZWW_COMPY
;


--0
SELECT *
FROM RAWWANT.IRPT_SAPBW_ZBW_SF_ZY_VIEW
WHERE YEARMONTH ='201811' AND CONCAT('0000000',(CASE WHEN ERP_ID<>'' THEN ERP_ID ELSE KEYACCOUNT_ID END)) NOT IN (SELECT CUSTOMER FROM RAWWANT.BW_SAPBHP_BI0_PCUSTOMER WHERE BIC_ZWW_COMPY<>'' AND LENGTH(CUSTOMER) = 15)
;