
--分公司  52筆  130.955秒
SELECT B.BIC_ZWW_COMPY, SUM(A.SF_AMOUNT) AS SF_AMOUNT
FROM (
      SELECT CUSTOMER_ID
           , PROD_ID
           , SUM(SF_AMOUNT) AS SF_AMOUNT
      FROM RAWWANT.IRPT_SAPBW_ZBW_SF_PF_VIEW
      WHERE YEARMONTH ='201811'
      GROUP BY CUSTOMER_ID, PROD_ID )A
JOIN (
      SELECT CUSTOMER
           , BIC_ZWW_COMPY
      FROM RAWWANT.BW_SAPBHP_BI0_PCUSTOMER
      WHERE BIC_ZWW_COMPY<>'' AND LENGTH(CUSTOMER)=15 ) B
ON CONCAT('00000',A.CUSTOMER_ID)=B.CUSTOMER
JOIN RAWWANT.BW_SAPBHP_BI0_PMATERIAL M
ON A.PROD_ID=M.MATERIAL
GROUP BY B.BIC_ZWW_COMPY
ORDER BY B.BIC_ZWW_COMPY
;


--產品線  100筆  130.177秒
SELECT M.PRODH3, SUM(A.SF_AMOUNT) AS SF_AMOUNT
FROM (
      SELECT CUSTOMER_ID
           , PROD_ID
           , SUM(SF_AMOUNT) AS SF_AMOUNT
      FROM RAWWANT.IRPT_SAPBW_ZBW_SF_PF_VIEW
      WHERE YEARMONTH ='201811'
      GROUP BY CUSTOMER_ID, PROD_ID )A
JOIN (
      SELECT CUSTOMER
           , BIC_ZWW_COMPY
      FROM RAWWANT.BW_SAPBHP_BI0_PCUSTOMER
      WHERE BIC_ZWW_COMPY<>'' AND LENGTH(CUSTOMER)=15) B
ON CONCAT('00000',A.CUSTOMER_ID)=B.CUSTOMER
JOIN RAWWANT.BW_SAPBHP_BI0_PMATERIAL M
ON A.PROD_ID=M.MATERIAL
GROUP BY M.PRODH3
ORDER BY M.PRODH3
;
--分公司產品線 3563筆  130.807秒
SELECT B.BIC_ZWW_COMPY, M.PRODH3
     , SUM(A.SF_AMOUNT) AS SF_AMOUNT
FROM (
      SELECT CUSTOMER_ID
           , PROD_ID
           , SUM(SF_AMOUNT) AS SF_AMOUNT
      FROM RAWWANT.IRPT_SAPBW_ZBW_SF_PF_VIEW
      WHERE YEARMONTH ='201811'
      GROUP BY CUSTOMER_ID, PROD_ID )A
JOIN (
      SELECT CUSTOMER
           , BIC_ZWW_COMPY
      FROM RAWWANT.BW_SAPBHP_BI0_PCUSTOMER
      WHERE BIC_ZWW_COMPY<>'' AND LENGTH(CUSTOMER)=15) B
ON CONCAT('00000',A.CUSTOMER_ID)=B.CUSTOMER
JOIN RAWWANT.BW_SAPBHP_BI0_PMATERIAL M
ON A.PROD_ID=M.MATERIAL
GROUP BY B.BIC_ZWW_COMPY, M.PRODH3
ORDER BY B.BIC_ZWW_COMPY, M.PRODH3
;

--3714649
SELECT COUNT(1)
FROM RAWWANT.BW_SAPBHP_BI0_PCUSTOMER
;

--3640100

SELECT COUNT(1)
FROM RAWWANT.BW_SAPBHP_BI0_PCUSTOMER
WHERE BIC_ZWW_COMPY=''

;


--74549
SELECT COUNT(1)
FROM RAWWANT.BW_SAPBHP_BI0_PCUSTOMER
WHERE BIC_ZWW_COMPY<>''
;


SELECT LENGTH(CUSTOMER) AS LENGTH, COUNT(1)
FROM RAWWANT.BW_SAPBHP_BI0_PCUSTOMER
WHERE BIC_ZWW_COMPY<>''
GROUP BY LENGTH(CUSTOMER)
ORDER BY LENGTH(CUSTOMER)
;


--0
SELECT CUSTOMER_ID
FROM RAWWANT.IRPT_SAPBW_ZBW_SF_PF_VIEW
WHERE YEARMONTH ='201811' AND CONCAT('00000',CUSTOMER_ID) NOT IN (SELECT CUSTOMER FROM RAWWANT.BW_SAPBHP_BI0_PCUSTOMER WHERE BIC_ZWW_COMPY<>'' AND LENGTH(CUSTOMER) = 15)
;

--1811071385.91
SELECT SUM(SF_AMOUNT)
FROM RAWWANT.IRPT_SAPBW_ZBW_SF_PF_VIEW
WHERE YEARMONTH ='201811'
;