--分公司  48筆  0.013秒
SELECT CONCAT('W',SUBSTRING(A.COMPANY_ID,2)) AS COMPANY_ID, SUM(A.SF_AMOUNT) AS SF_AMOUNT
FROM RAWWANT.IRPT_SAPBW_ZBW_SF_PF2_VIEW A
JOIN RAWWANT.BW_SAPBHP_BI0_PMATERIAL M
ON A.PROD_ID=M.MATERIAL
WHERE A.YEARMONTH ='201811'
GROUP BY CONCAT('W',SUBSTRING(A.COMPANY_ID,2))
;
--產品線  8筆  0.011秒
SELECT M.PRODH3, SUM(A.SF_AMOUNT) AS SF_AMOUNT
FROM RAWWANT.IRPT_SAPBW_ZBW_SF_PF2_VIEW A
JOIN RAWWANT.BW_SAPBHP_BI0_PMATERIAL M
ON A.PROD_ID=M.MATERIAL
WHERE A.YEARMONTH ='201811'
GROUP BY M.PRODH3
;
--分公司產品線  130筆  0.012秒
SELECT CONCAT('W',SUBSTRING(A.COMPANY_ID,2)) AS COMPANY_ID, M.PRODH3
     , SUM(A.SF_AMOUNT) AS SF_AMOUNT
FROM RAWWANT.IRPT_SAPBW_ZBW_SF_PF2_VIEW A
JOIN RAWWANT.BW_SAPBHP_BI0_PMATERIAL M
ON A.PROD_ID=M.MATERIAL
WHERE A.YEARMONTH ='201811'
GROUP BY CONCAT('W',SUBSTRING(A.COMPANY_ID,2)), M.PRODH3
ORDER BY CONCAT('W',SUBSTRING(A.COMPANY_ID,2)), M.PRODH3
;

