SELECT {edino} AS EDI_NO
     , "MATERIAL", "OBJVERS", "DIVISION", "MATL_TYPE"
     , "PRODH1", "PRODH2", "PRODH3", "PRODH4", "PRODH5"
     , "/BIC/ZSD_PXXL", "/BIC/ZCOOIC064"
FROM "SAPBHP"."/BI0/PMATERIAL"
;