SELECT {edino} AS EDI_NO
     , "/BIC/ZKNUM", "COMP_CODE", "SALESORG", "DISTR_CHAN", "DIVISION", "CUSTOMER"
     , "MATERIAL", "MATL_GRP_1"
     , "/BIC/ZZKZYS", "/BIC/ZKAMOUNT"
FROM "SAPBHP"."/BIC/AZKZY_O0100"
;