SELECT {edino} AS EDI_NO
     , "DOC_NUMBER", "S_ORD_ITEM", "DELIV_NUMB", "/BIC/ZDN_ITEM"
     , "DOC_DATE", "MATERIAL", "CUST_SALES"
     , "CUSTOMER", "COMP_CODE", "SALESORG", "DISTR_CHAN"
     , "DIVISION", "ITEM_CATEG", "/BIC/ZCUS_WWID"
     , "/BIC/ZWGZ_KDM", "/BIC/ZWGZ_QRM"
FROM "SAPBHP"."/BIC/AZWGZ_O0100"
;