SELECT {edino} AS EDI_NO
     , "COMP_CODE", "DEBITOR", "FISCPER", "FISCVARNT", "AC_DOC_NO", "ITEM_NUM", "FI_DSBITEM", "/BIC/ZCUST_OLD"
     , "C_CTR_AREA", "AC_DOC_TYP", "PSTNG_DATE", "DEB_CRE_LC"
     , "CUSTOMER", "/BIC/ZTCODE"
FROM "SAPBHP"."/BI0/AFIAR_O0300"
;