SELECT EDI_NO
     , ID
     , MEANS_DATE
     , MEANS_TIME
     , CHOOSE
     , SYS_CODE
     , SYS_NAME
     , IS_MEANS
     , STORE_CODE
     , STORE_NAME
     , KA_STORE_CODE
     , INV_DIVISION
     , SALE_PROD_CODE
     , KA_MATERIEL_CODE
     , PROD_NAME
     , PROD_SPEC
     , MIN_PROD_UNIT
     , INV_DATE
     , INV_NUM
     , CREATED
     , CREATED_BY
     , UPDATED
     , UPDATED_BY
     , STATUS
     , SERIAL_NUM
     , STOCK_ID
     , PROD_TYPE_CODE
     , PROD_TYPE_NAME
     , MATERIAL_NAME
     , SHELF_LIFE_NUM
     , WW_STORE_NAME
     , SYS_ACCOUNT
     , SYS_OTHER_INFO
     , CLIENT_ID
     , (CASE WHEN CODE_WAREHOUSE_PLOT='-1' THEN '' ELSE CODE_WAREHOUSE_PLOT END) AS CODE_WAREHOUSE_PLOT
     , NAME_WAREHOUSE_PLOT
     , INV_BOX_NUM
     , (CASE WHEN CODE_SPLIT_GROUND='-1' THEN '' ELSE CODE_SPLIT_GROUND END) AS CODE_SPLIT_GROUND
     , NAME_SPLIT_GROUND
     , PM_CODE
     , PM_NAME
     , TERMINAL_CODE
     , MATCH_STATUS
     , REPEAT_MATCH_FLAG
     , (CASE WHEN WW_DELIVERY_BRANCH_OFFICE_CODE='-1' THEN '' ELSE WW_DELIVERY_BRANCH_OFFICE_CODE END) AS WW_DELIVERY_BRANCH_OFFICE_CODE
     , WW_DELIVERY_BRANCH_OFFICE_NAME
FROM RAWWANT.KA_WANTWANT_SYS_INV_DATA
;