SELECT EDI_NO
     , ID
     , SAP_ORDER_NO
     , ORDER_MAIN_ID
     , AUDIT_STATUS
     , SAP_OPEN_ORDER_DATE
     , SAP_DELIVERY_BRANCH
     , SAP_IS_CHECK
     , (CASE WHEN SAP_CHECK_NUM='PICOM' THEN '' ELSE SAP_CHECK_NUM END) AS SAP_CHECK_NUM
     , STATUS
     , SAP_AUDIT_NAME
     , RETURN_DATE
     , RETURN_TIME
     , CREATED
FROM RAWWANT.KA_WANTWANT_KA_SAP_PIN_CHECK
;