SELECT EDI_NO
     , ID
     , SAP_ORDER_NO
     , SAP_POSNR
     , DIFFERENCE_BOX_NUM
     , ACTUAL_DELIVER_BOX_NUM
     , SAP_HARVEST_DATE
     , SAP_RETURN_RECEIPT_DATE
     , SAP_SHIPMENT_NUM
     , SAP_SHIPMENT_NAME
     , RETURN_DATE
     , RETURN_TIME
     , CUSTOMER_RECEIVED_BOX_NUM
     , TEXT_DESC
FROM RAWWANT.KA_WANTWANT_KA_SAP_SHIPPING_RETURN
;