SELECT EDI_NO
     , COMPANY_ID, TRIM(COMPANY_NAME) AS COMPANY_NAME
     , BRANCH_ID, TRIM(BRANCH_NAME) AS BRANCH_NAME
     , MARKET_ID, TRIM(MARKET_NAME) AS MARKET_NAME
     , THIRD_ID, TRIM(THIRD_NAME) AS THIRD_NAME
FROM RAWWANT.IWANT_SALES_MARKET_FULL_VIEW
;