SELECT EDI_NO
     , RIGHT(CONCAT('0000000000', TRIM(SID)),10) AS SID
     , SMALL_MARKET_ID
     , (CASE WHEN LEFT(TRIM(CUSTOMER_ID), 2)='00' THEN CONCAT('00000', TRIM(CUSTOMER_ID)) ELSE TRIM(CUSTOMER_ID) END) AS CUSTOMER_ID
     , CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE
     , CHANNEL_ID
     , (CASE WHEN SMALL_MARKET_ID='' AND REPLACE(MARKET_ID,'-','')='' THEN '' 
             WHEN TYPE='2' AND SMALL_MARKET_ID='' AND REPLACE(MARKET_ID,'-','')<>'' THEN '1'
             WHEN TYPE='1' AND SMALL_MARKET_ID<>'' AND REPLACE(MARKET_ID,'-','')='' THEN '2'
             ELSE TYPE END) AS TYPE
     , (CASE WHEN SID=50854 THEN LEFT(MARKET_ID, 6)
             WHEN SID=80982 THEN '221205'
             WHEN SID=91081 THEN '280505'
             ELSE REPLACE(MARKET_ID,'-','')
        END) AS MARKET_ID
     , START_DATE, END_DATE
     , IS_DELETE
FROM RAWWANT.IWANT_SALES_CUSTOMER_SMALL_MARKET
WHERE IS_DELETE='0'
;