SELECT DISTINCT EDI_NO
     , '' AS SID
     , MARKET_RELATION_ID
     , MARKET_TYPE
     , (CASE WHEN MARKET_ID='-' THEN '' ELSE MARKET_ID END) AS MARKET_ID
     , (CASE WHEN TRIM(MARKET_NAME)='-' THEN '' ELSE TRIM(MARKET_NAME) END) AS MARKET_NAME
     , (CASE WHEN SMALL_MARKET_ID='-' THEN '' ELSE SMALL_MARKET_ID END) AS SMALL_MARKET_ID
     , (CASE WHEN TRIM(SMALL_MARKET_NAME)='-' THEN '' ELSE TRIM(SMALL_MARKET_NAME) END) AS SMALL_MARKET_NAME
FROM RAWWANT.IWANT_SALES_CUS_SALES_MARKET_REL
WHERE MARKET_RELATION_ID IN (SELECT MARKET_RELATION_ID FROM RAWWANT.IWANT_SALES_CUSTOMER_SALES)
;