SELECT EDI_NO
     , EMP_ID, TRIM(EMP_NAME) AS EMP_NAME
     , POS_ID, TRIM(POS_NAME) AS POS_NAME
     , POS_TYPE_ID, TRIM(POS_TYPE_NAME) AS POS_TYPE_NAME
     , COMPANY_ID, TRIM(COMPANY_NAME) AS COMPANY_NAME
     , BRANCH_ID, TRIM(BRANCH_NAME) AS BRANCH_NAME
     , DIRECTOR_EMP_ID, TRIM(DIRECTOR_EMP_NAME) AS DIRECTOR_EMP_NAME
     , DIRECTOR_POS_ID, TRIM(DIRECTOR_POS_NAME) AS DIRECTOR_POS_NAME
     , DIRECTOR_POS_TYPE_ID, TRIM(DIRECTOR_POS_TYPE_NAME) AS DIRECTOR_POS_TYPE_NAME
     , POS_PROPERTY_ID
     , CHANNEL_ID, TRIM(CHANNEL_NAME) AS CHANNEL_NAME
     , AREA_ID, TRIM(AREA_NAME) AS AREA_NAME
     , MASTER_POS
     , EMP_GENDER
     , EMP_ONBOARD_DATE1
FROM RAWWANT.IWANT_SALES_EMP_POSITION_ORG_VIEW
WHERE COMPANY_ID<>'1'
;