SELECT EDI_NO
     , SID
     , RIGHT(CONCAT('0000000000', TRIM(CUSTOMER_SMALL_MARKET_ID)),10) AS CUSTOMER_SMALL_MARKET_ID
     , PROD_LINE_ID, TRIM(PROD_LINE_NAME) AS PROD_LINE_NAME
     , STATUS
     , CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE
FROM RAWWANT.IWANT_SALES_CUS_SMALL_MARKET_PROD_LINE
WHERE STATUS='1'
  AND CUSTOMER_SMALL_MARKET_ID IN (SELECT SID FROM RAWWANT.IWANT_SALES_CUSTOMER_SMALL_MARKET WHERE IS_DELETE='0')
;