SELECT EDI_NO
     , CHANNEL_ID
     , TRIM(CHANNEL_NAME) AS CHANNEL_NAME
     , STATUS
     , ERP_CHANNEL_ID, TRIM(ERP_CHANNEL_DESC) AS ERP_CHANNEL_DESC
     , ERP_PROD_GROUP_ID, TRIM(ERP_PROD_GROUP_DESC) AS ERP_PROD_GROUP_DESC
     , DIVISION_ID, TRIM(DIVISION_NAME) AS DIVISION_NAME
FROM RAWWANT.IWANT_SALES_CHANNEL
;