SELECT DISTINCT EDI_NO
     , TRIM(MATERIAL) AS MATERIAL, OBJVERS
     , DIVISION, MATL_TYPE
     , PRODH1, PRODH2, PRODH3
     , (CASE WHEN PRODH4='1.00E+12' THEN '' ELSE PRODH4 END) AS PRODH4
     , (CASE WHEN PRODH5='1.00E+15' THEN '' ELSE PRODH5 END) AS PRODH5
     , BIC_ZSD_PXXL, BIC_ZCOOIC064
FROM RAWWANT.BW_SAPBHP_BI0_PMATERIAL
WHERE OBJVERS='A' AND LENGTH(TRIM(MATERIAL))>1
  AND (CASE WHEN TRIM(MATERIAL) IN ('C211003','C211006','C211007') AND MATL_TYPE='' THEN 0 ELSE 1 END)=1
;