SELECT EDI_NO
     , TRIM(CUSTOMER) AS CUSTOMER
     , TRIM(TXTMD) AS TXTMD
FROM RAWWANT.BW_SAPBHP_BI0_TCUSTOMER
WHERE LENGTH(CUSTOMER)>0
  AND ((ASCII(LEFT(CUSTOMER,1))>=48 AND ASCII(LEFT(CUSTOMER,1))<=57) OR (ASCII(LEFT(CUSTOMER,1))>=65 AND ASCII(LEFT(CUSTOMER,1))<=90))
;