SELECT DISTINCT EDI_NO
     , UPPER(TRIM(CUSTOMER)) AS CUSTOMER, OBJVERS
     , ACCNT_GRP, CUST_CLASS
     , (CASE WHEN SALES_OFF='00' OR LEFT(SALES_OFF,1)='X' THEN '' ELSE SALES_OFF END) AS SALES_OFF
     , BIC_ZWW_COMPY
FROM RAWWANT.BW_SAPBHP_BI0_PCUSTOMER
WHERE OBJVERS='A' AND LENGTH(CUSTOMER)>0
  AND ((ASCII(LEFT(CUSTOMER,1))>=48 AND ASCII(LEFT(CUSTOMER,1))<=57) OR (ASCII(LEFT(CUSTOMER,1))>=65 AND ASCII(LEFT(CUSTOMER,1))<=90))
;