SELECT EDI_NO
     , COMP_CODE, DEBITOR, FISCPER, FISCVARNT, AC_DOC_NO, ITEM_NUM, FI_DSBITEM, BIC_ZCUST_OLD
     , C_CTR_AREA
     , AC_DOC_TYP, PSTNG_DATE
     , DEB_CRE_LC
     , CUSTOMER
     , BIC_ZTCODE
FROM RAWWANT.BW_SAPBHP_BI0_AFIAR_O0300
;