SELECT EDI_NO
     , FISCYEAR, FISCVARNT, BILL_NUM, BILL_ITEM
     , CALMONTH
     , CALDAY
     , SUBTOTAL_1
     , ITEM_CATEG
     , CUST_SALES
     , DIVISION, MATERIAL
     , DISTR_CHAN, SALESORG, COMP_CODE
     , BIC_ZCUS_WWID, CUSTOMER
FROM RAWWANT.BW_SAPBHP_BIC_AZSD_O2100
;