SELECT EDI_NO
     , DOC_NUMBER, S_ORD_ITEM, DELIV_NUMB, BIC_ZDN_ITEM
     , DOC_DATE
     , MATERIAL
     , CUST_SALES, CUSTOMER
     , COMP_CODE, SALESORG, DISTR_CHAN
     , DIVISION
     , ITEM_CATEG
     , BIC_ZCUS_WWID
     , BIC_ZWGZ_KDM
     , BIC_ZWGZ_QRM
FROM RAWWANT.BW_SAPBHP_BIC_AZWGZ_O0100
;