--批發客戶帳餘查詢
SELECT A.C_CTR_AREA, D.SALES_OFF
     , SUM(CASE WHEN A.FISCPER ='2019002' AND A.FISCVARNT='K4' AND A.AC_DOC_TYP<>'RV' AND SUBSTRING(A."/BIC/ZTCODE",1,2)<>'VF' AND A.PSTNG_DATE='20190211' THEN A.DEB_CRE_LC ELSE 0 END) AS TODAY_AMT
     , SUM(CASE WHEN A.FISCPER< '2019002' AND A.FISCVARNT='K4'                                                                                             THEN A.DEB_CRE_LC ELSE 0 END) AS PERIOD_BEGIN
     , SUM(CASE WHEN A.FISCPER ='2019002' AND A.FISCVARNT='K4' AND A.AC_DOC_TYP<>'RV' AND SUBSTRING(A."/BIC/ZTCODE",1,2)<>'VF'                             THEN A.DEB_CRE_LC ELSE 0 END) AS CUM_AMT
     , SUM(CASE WHEN A.FISCPER ='2019002' AND A.FISCVARNT='K4' AND A.AC_DOC_TYP= 'RV'                                                                       THEN A.DEB_CRE_LC ELSE 0 END) AS SALES_WO
     , SUM(CASE WHEN A.FISCPER<='2019002' AND A.FISCVARNT='K4'                                                                                             THEN A.DEB_CRE_LC ELSE 0 END) AS PERIOD_END
FROM "SAPBHP"."/BI0/AFIAR_O0300" A
JOIN "SAPBHP"."/BI0/PCUSTOMER" D ON A.DEBITOR=D.CUSTOMER AND D.OBJVERS='A'
WHERE D.CUST_CLASS NOT IN ('O1','O2','O3','O4','O5','O6','O7','O8')
  AND SUBSTRING(A.COMP_CODE,1,1)='C'
  AND A.C_CTR_AREA NOT IN ('CDZ','FDZ','CDD','CD8','CDQ')
  AND D.ACCNT_GRP IN ('Z002','Z003')
GROUP BY A.C_CTR_AREA, D.SALES_OFF
;
