--專款分析表
SELECT A.MATL_GRP_1, B.SALES_OFF, SUM(A."/BIC/ZKAMOUNT") AS ZKAMOUNT
FROM "SAPBHP"."/BIC/AZKZY_O0100" A
JOIN "SAPBHP"."/BI0/PCUSTOMER" B ON A.CUSTOMER=B.CUSTOMER AND B.OBJVERS='A'
WHERE A.MATL_GRP_1 IN ('Z77','Z78','Z79','Z81') AND A."/BIC/ZZKZYS"=''
GROUP BY A.MATL_GRP_1, B.SALES_OFF
;
