--業績類通用報表含未過帳含財年
--GROUP BY W."/BIC/ZWWCHAN", S."/BIC/ZWW_COMPY", M.PRODH1, M.PRODH2, M.PRODH3, M.PRODH4
SELECT SUM(CASE WHEN A.CALMONTH='201802' THEN A.SUBTOTAL_1 ELSE 0 END) AS LAST_YEAR_MONTH_ALL
     , SUM(CASE WHEN A.CALMONTH='201802' THEN A.SUBTOTAL_1 ELSE 0 END)*8/20 AS LAST_YEAR_MONTH_NOW
     , SUM(CASE WHEN A.CALMONTH='201902' THEN A.SUBTOTAL_1 ELSE 0 END) AS THIS_MONTH_NOW
FROM "SAPBHP"."/BIC/AZSD_O2100" A
JOIN "SAPBHP"."/BI0/PCUSTOMER" D ON A.CUSTOMER=D.CUSTOMER AND D.OBJVERS='A'
JOIN "SAPBHP"."/BI0/PCUST_SALES" S ON A.DIVISION=S.DIVISION AND A.DISTR_CHAN=S.DISTR_CHAN AND A.SALESORG=S.SALESORG AND A.CUST_SALES=S.CUST_SALES AND S.OBJVERS='A'
JOIN "SAPBHP"."/BI0/PMATERIAL" M ON A.MATERIAL=M.MATERIAL AND M.OBJVERS='A'
JOIN "SAPBHP"."/BIC/PZCUS_WWID" W ON A.DISTR_CHAN=W.DISTR_CHAN AND A.MATERIAL=W.MATERIAL AND A.DIVISION=W.DIVISION AND A.SALESORG=W.SALESORG AND A.ITEM_CATEG=W.ITEM_CATEG AND A."/BIC/ZCUS_WWID"=W."/BIC/ZCUS_WWID" AND W.OBJVERS='A'
WHERE D.CUST_CLASS<>'OB' AND A.DISTR_CHAN<>'C6' AND S."/BIC/ZWW_COMPY"<>'' AND M.PRODH1<>'999' AND A."/BIC/ZCUS_WWID"<>'' AND M.MATL_TYPE='FERT' AND D.ACCNT_GRP IN ('Z002','Z003')
  AND A.CALMONTH IN ('201802','201902')
;
