SET FOREIGN_KEY_CHECKS=0 ;

CREATE TABLE `IWANT_SALES_STORE_INFO`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`SID` VARCHAR(38) NOT NULL,
	`STORE_ID` VARCHAR(20) NOT NULL,
	`STORE_NAME` VARCHAR(200) NOT NULL,
	`STORE_DESC` VARCHAR(500) NOT NULL,
	`ACREAGE` VARCHAR(38) NOT NULL,
	`STATUS` CHAR(1) NOT NULL,
	`FORTH_SID` VARCHAR(38) NOT NULL,
	`FIFTH_SID` VARCHAR(38) NOT NULL,
	`STORE_OWNER` VARCHAR(100) NOT NULL,
	`OWNERGENDER` CHAR(1) NOT NULL,
	`ADD1` VARCHAR(255) NOT NULL,
	`ADD1TYPESID` VARCHAR(38) NOT NULL,
	`ADD2` VARCHAR(255) NOT NULL,
	`ADD2TYPESID` VARCHAR(38) NOT NULL,
	`ADD3` VARCHAR(255) NOT NULL,
	`ADD3TYPESID` VARCHAR(38) NOT NULL,
	`ADD4` VARCHAR(255) NOT NULL,
	`POSTCODE` VARCHAR(20) NOT NULL,
	`ZIP` VARCHAR(20) NOT NULL,
	`FIXEDPHONE` VARCHAR(150) NOT NULL,
	`MOBILEPHONE` VARCHAR(50) NOT NULL,
	`LONGITUDE` DECIMAL(28,7) NOT NULL,
	`LATITUDE` DECIMAL(28,7) NOT NULL,
	`CREATE_DATE` CHAR(8) NOT NULL,
	`CREATE_USER` VARCHAR(14) NOT NULL,
	`UPDATE_DATE` CHAR(8) NOT NULL,
	`UPDATE_USER` VARCHAR(14) NOT NULL,
	CONSTRAINT `PK_IWANT_SALES_STORE_INFO` PRIMARY KEY (`SID`)
)

;

SET FOREIGN_KEY_CHECKS=1 ;
