/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 12-十一月-2018 上午 12:26:16 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 ;

/* Create Tables */

CREATE TABLE `IWANT_SALES_CHANNEL`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`CHANNEL_ID` VARCHAR(4) NOT NULL,
	`CHANNEL_NAME` VARCHAR(50) NOT NULL,
	`STATUS` CHAR(1) NOT NULL,
	`ERP_CHANNEL_ID` VARCHAR(3) NOT NULL,
	`ERP_CHANNEL_DESC` VARCHAR(50) NOT NULL,
	`ERP_PROD_GROUP_ID` VARCHAR(3) NOT NULL,
	`ERP_PROD_GROUP_DESC` VARCHAR(50) NOT NULL,
	`DIVISION_ID` VARCHAR(10) NOT NULL,
	`DIVISION_NAME` VARCHAR(50) NOT NULL,
	CONSTRAINT `PK_IWANT_SALES_CHANNEL` PRIMARY KEY (`CHANNEL_ID`)
)

;

SET FOREIGN_KEY_CHECKS=1 ;
