SET FOREIGN_KEY_CHECKS=0 ;

CREATE TABLE `IWANT_SALES_FORTH_CITY`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`SID` VARCHAR(38) NOT NULL,
	`NAME` VARCHAR(50) NOT NULL,
	`THIRD_ID` VARCHAR(50) NOT NULL,
	`STATUS` CHAR(1) NOT NULL,
	`TOTAL_PEOPLE` DECIMAL(34,4) NOT NULL,
	CONSTRAINT `PK_IWANT_SALES_FORTH_CITY` PRIMARY KEY (`SID`)
)

;

SET FOREIGN_KEY_CHECKS=1 ;
