SET FOREIGN_KEY_CHECKS=0 ;

CREATE TABLE `IWANT_SALES_CUSTOMER_SMALL_MARKET`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`SID` VARCHAR(10) NOT NULL,
	`SMALL_MARKET_ID` VARCHAR(50) NOT NULL,
	`CUSTOMER_ID` VARCHAR(50) NOT NULL,
	`CREATE_USER` VARCHAR(10) NOT NULL,
	`CREATE_DATE` CHAR(8) NOT NULL,
	`UPDATE_USER` VARCHAR(10) NOT NULL,
	`UPDATE_DATE` CHAR(8) NOT NULL,
	`CHANNEL_ID` VARCHAR(4) NOT NULL,
	`TYPE` CHAR(1) NOT NULL,
	`MARKET_ID` VARCHAR(50) NOT NULL,
	`START_DATE` CHAR(8) NOT NULL,
	`END_DATE` CHAR(8) NOT NULL,
	`IS_DELETE` VARCHAR(1) NOT NULL,
	CONSTRAINT `PK_IWANT_SALES_CUSTOMER_SMALL_MARKET` PRIMARY KEY (`SID`)
)

;

CREATE TABLE `IWANT_SALES_CUSTOMER_SALES`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`USER_ID` VARCHAR(20) NOT NULL,
	`CUSTOMER_ID` VARCHAR(50) NOT NULL,
	`CREDIT_ID` VARCHAR(20) NOT NULL,
	`START_TIME` CHAR(8) NOT NULL,
	`END_TIME` CHAR(8) NOT NULL,
	`COMPANY_ID` VARCHAR(20) NOT NULL,
	`PROD_GROUP_ID` VARCHAR(50) NOT NULL,
	`THIRD_CITY_ID` VARCHAR(50) NOT NULL,
	`CREATE_DATE` CHAR(8) NOT NULL,
	`CREATE_USER` VARCHAR(50) NOT NULL,
	`UPDATE_DATE` CHAR(8) NOT NULL,
	`UPDATE_USER` VARCHAR(50) NOT NULL,
	`STATUS` CHAR(1) NOT NULL,
	`POS_TYPE_ID` VARCHAR(3) NOT NULL,
	`POS_TYPE_NAME` VARCHAR(30) NOT NULL,
	`MARKET_RELATION_ID` BIGINT NOT NULL,
	`POS_NAME` VARCHAR(120) NOT NULL,
	`EMP_COMPANY_ID` VARCHAR(4) NOT NULL,
	`EMP_BRANCH_ID` VARCHAR(50) NOT NULL,
	CONSTRAINT `PK_IWANT_SALES_CUSTOMER_SALES` PRIMARY KEY (`USER_ID`,`CUSTOMER_ID`,`CREDIT_ID`,`START_TIME`,`END_TIME`,`CREATE_DATE`,`CREATE_USER`,`UPDATE_DATE`,`UPDATE_USER`,`POS_TYPE_ID`)
)

;

CREATE TABLE `IWANT_SALES_CUSTOMER`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`ID` VARCHAR(50) NOT NULL,
	`NAME` VARCHAR(150) NOT NULL,
	`OWNER` VARCHAR(50) NOT NULL,
	`SHORT_NAME` VARCHAR(150) NOT NULL,
	`DESCRIPTION` VARCHAR(500) NOT NULL,
	`STATUS` CHAR(5) NOT NULL,
	`BRANCH_ID` VARCHAR(50) NOT NULL,
	`ID_FRIEND` VARCHAR(50) NOT NULL,
	`THIRD_ID` VARCHAR(20) NOT NULL,
	CONSTRAINT `PK_IWANT_SALES_CUSTOMER` PRIMARY KEY (`ID`)
)

;

CREATE TABLE `IWANT_SALES_CUS_SMALL_MARKET_PROD_LINE`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`SID` BIGINT NOT NULL,
	`CUSTOMER_SMALL_MARKET_ID` VARCHAR(50) NOT NULL,
	`PROD_LINE_ID` VARCHAR(50) NOT NULL,
	`PROD_LINE_NAME` VARCHAR(250) NOT NULL,
	`STATUS` VARCHAR(1) NOT NULL,
	`CREATE_USER` VARCHAR(10) NOT NULL,
	`CREATE_DATE` CHAR(8) NOT NULL,
	`UPDATE_USER` VARCHAR(10) NOT NULL,
	`UPDATE_DATE` CHAR(8) NOT NULL,
	CONSTRAINT `PK_IWANT_SALES_CUS_SMALL_MARKET_PROD_LINE` PRIMARY KEY (`SID`)
)

;

CREATE TABLE `IWANT_SALES_CUS_SALES_MARKET_REL`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`SID` VARCHAR(20) NOT NULL,
	`MARKET_RELATION_ID` BIGINT NOT NULL,
	`MARKET_TYPE` VARCHAR(20) NOT NULL,
	`MARKET_ID` VARCHAR(50) NOT NULL,
	`MARKET_NAME` VARCHAR(200) NOT NULL,
	`SMALL_MARKET_ID` VARCHAR(50) NOT NULL,
	`SMALL_MARKET_NAME` VARCHAR(200) NOT NULL,
	CONSTRAINT `PK_IWANT_SALES_CUS_SALES_MARKET_REL` PRIMARY KEY (`MARKET_RELATION_ID`,`MARKET_ID`,`SMALL_MARKET_ID`)
)

;

SET FOREIGN_KEY_CHECKS=1 ;
