SET FOREIGN_KEY_CHECKS=0 ;

CREATE TABLE `IWANT_SALES_THIRD_CITY`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`ID` VARCHAR(50) NOT NULL,
	`NAME` VARCHAR(50) NOT NULL,
	`MARKET_ID` VARCHAR(50) NOT NULL,
	`BRANCH_ID` VARCHAR(50) NOT NULL,
	CONSTRAINT `PK_IWANT_SALES_THIRD_CITY` PRIMARY KEY (`ID`)
)

;

SET FOREIGN_KEY_CHECKS=1 ;
