SET FOREIGN_KEY_CHECKS=0 ;

CREATE TABLE `IWANT_SALES_KA_SPECIAL_SYSTEM`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`SYS_ID` VARCHAR(50) NOT NULL,
	`SYS_NAME` VARCHAR(50) NOT NULL,
	CONSTRAINT `PK_IWANT_SALES_KA_SPECIAL_SYSTEM` PRIMARY KEY (`SYS_ID`)
)

;

SET FOREIGN_KEY_CHECKS=1 ;
