DROP PROCEDURE IF EXISTS RAWWANT.SP_DAT_KA_00001_TRUNCATE_TABLE;

CREATE PROCEDURE RAWWANT.SP_DAT_KA_00001_TRUNCATE_TABLE (
    VAR_EDI_NO CHAR(12), VAR_DATA_DATE CHAR(8), OUT VAR_SP_RESULT CHAR(1)
)
BEGIN

    TRUNCATE TABLE RAWWANT.KA_WANTWANT_SYS_SALE_DATA;
    TRUNCATE TABLE RAWWANT.KA_WANTWANT_SYS_INV_DATA;

    SET VAR_SP_RESULT='Y';
    COMMIT;
END
;