DROP PROCEDURE IF EXISTS RAWWANT.SP_DAT_KA_ORDER_00001_TRUNCATE_TABLE;

CREATE PROCEDURE RAWWANT.SP_DAT_KA_ORDER_00001_TRUNCATE_TABLE (
    VAR_EDI_NO CHAR(12), VAR_DATA_DATE CHAR(8), OUT VAR_SP_RESULT CHAR(1)
)
BEGIN

    TRUNCATE TABLE RAWWANT.KA_WANTWANT_SYS_ORDER_DATA;
    TRUNCATE TABLE RAWWANT.KA_WANTWANT_KA_ORDER_CHECK_RESULT;
    TRUNCATE TABLE RAWWANT.KA_WANTWANT_KA_ORDER_CHECK_DETAIL_RESULT;
    TRUNCATE TABLE RAWWANT.KA_WANTWANT_KA_SAP_ORDER;
    TRUNCATE TABLE RAWWANT.KA_WANTWANT_KA_SAP_ORDER_DETAIL;
    TRUNCATE TABLE RAWWANT.KA_WANTWANT_KA_SAP_PIN_CHECK;
    TRUNCATE TABLE RAWWANT.KA_WANTWANT_KA_SAP_PIN_CHECK_DETAIL;
    TRUNCATE TABLE RAWWANT.KA_WANTWANT_KA_SAP_SHIPPING_RETURN;

    SET VAR_SP_RESULT='Y';
    COMMIT;
END
;