DROP PROCEDURE IF EXISTS RAWWANT.SP_DAT_BW_00001_TRUNCATE_TABLE;

CREATE PROCEDURE RAWWANT.SP_DAT_BW_00001_TRUNCATE_TABLE (
    VAR_EDI_NO CHAR(12), VAR_DATA_DATE CHAR(8), OUT VAR_SP_RESULT CHAR(1)
)
BEGIN

    TRUNCATE TABLE RAWWANT.BW_SAPBHP_BI0_TMATERIAL;
    TRUNCATE TABLE RAWWANT.BW_SAPBHP_BI0_TDIVISION;
    TRUNCATE TABLE RAWWANT.BW_SAPBHP_BI0_TPROD_HIER;
    TRUNCATE TABLE RAWWANT.BW_SAPBHP_BIC_TZCOOIC064;
    TRUNCATE TABLE RAWWANT.BW_SAPBHP_BIC_TZSD_PXXL;
    TRUNCATE TABLE RAWWANT.BW_SAPBHP_BI0_PMATERIAL;

    TRUNCATE TABLE RAWWANT.BW_SAPBHP_BI0_TCUSTOMER;
    TRUNCATE TABLE RAWWANT.BW_SAPBHP_BI0_TDISTR_CHAN;
    TRUNCATE TABLE RAWWANT.BW_SAPBHP_BI0_TSALESORG;
    TRUNCATE TABLE RAWWANT.BW_SAPBHP_BI0_TSALES_OFF;
    TRUNCATE TABLE RAWWANT.BW_SAPBHP_BIC_TZWWCHAN;
    TRUNCATE TABLE RAWWANT.BW_SAPBHP_BIC_TZWW_COMPY;
    TRUNCATE TABLE RAWWANT.BW_SAPBHP_BI0_PCUSTOMER;
    TRUNCATE TABLE RAWWANT.BW_SAPBHP_BI0_PCUST_SALES;
    TRUNCATE TABLE RAWWANT.BW_SAPBHP_BIC_PZCUS_WWID;

    TRUNCATE TABLE RAWWANT.BW_SAPBHP_BIC_AZSD_O2100;
    TRUNCATE TABLE RAWWANT.BW_SAPBHP_BIC_AZWGZ_O0100;
    TRUNCATE TABLE RAWWANT.BW_SAPBHP_BI0_AFIAR_O0300;
    TRUNCATE TABLE RAWWANT.BW_SAPBHP_BIC_AZKZY_O0100;

    TRUNCATE TABLE RAWWANT.BW_SAPBHP_BIC_AZSD_O21900;
    TRUNCATE TABLE RAWWANT.BW_SAPBHP_BI0_TC_CTR_AREA;

    SET VAR_SP_RESULT='Y';
    COMMIT;
END
;