DROP PROCEDURE IF EXISTS RAWWANT.SP_DAT_IRPT_00001_TRUNCATE_TABLE;

CREATE PROCEDURE RAWWANT.SP_DAT_IRPT_00001_TRUNCATE_TABLE (
    VAR_EDI_NO CHAR(12), VAR_DATA_DATE CHAR(8), OUT VAR_SP_RESULT CHAR(1)
)
BEGIN

    TRUNCATE TABLE RAWWANT.IRPT_SAPBW_ZBW_SF_PF_VIEW;
    TRUNCATE TABLE RAWWANT.IRPT_SAPBW_ZBW_SF_PF2_VIEW;
    TRUNCATE TABLE RAWWANT.IRPT_SAPBW_ZBW_SF_ZY_VIEW;

    SET VAR_SP_RESULT='Y';
    COMMIT;
END
;