DROP PROCEDURE IF EXISTS RAWWANT.SP_DAT_IWANT_SFA_STORE_00001_TRUNCATE_TABLE;

CREATE PROCEDURE RAWWANT.SP_DAT_IWANT_SFA_STORE_00001_TRUNCATE_TABLE (
    VAR_EDI_NO CHAR(12), VAR_DATA_DATE CHAR(8), OUT VAR_SP_RESULT CHAR(1)
)
BEGIN

    TRUNCATE TABLE RAWWANT.IWANT_SALES_STORE_INFO;

    SET VAR_SP_RESULT='Y';
    COMMIT;
END
;