DROP PROCEDURE IF EXISTS RAWWANT.SP_DAT_IWANT_00001_TRUNCATE_TABLE;

CREATE PROCEDURE RAWWANT.SP_DAT_IWANT_00001_TRUNCATE_TABLE (
    VAR_EDI_NO CHAR(12), VAR_DATA_DATE CHAR(8), OUT VAR_SP_RESULT CHAR(1)
)
BEGIN

    TRUNCATE TABLE RAWWANT.IWANT_SALES_DISTRICT;
    TRUNCATE TABLE RAWWANT.IWANT_SALES_AREA;
    TRUNCATE TABLE RAWWANT.IWANT_SALES_COMPANY;
    TRUNCATE TABLE RAWWANT.IWANT_SALES_KA_SPECIAL_SYSTEM;
    TRUNCATE TABLE RAWWANT.IWANT_SALES_SMALL_MARKET;
    TRUNCATE TABLE RAWWANT.IWANT_SALES_THIRD_CITY;
    TRUNCATE TABLE RAWWANT.IWANT_SALES_FORTH_CITY;
    TRUNCATE TABLE RAWWANT.IWANT_SALES_FIFTH_CITY;
    TRUNCATE TABLE RAWWANT.IWANT_SALES_MARKET_FULL_VIEW;
    TRUNCATE TABLE RAWWANT.IWANT_SALES_CHANNEL;
    TRUNCATE TABLE RAWWANT.IWANT_SALES_CUSTOMER;
    TRUNCATE TABLE RAWWANT.IWANT_SALES_EMP_POSITION_ORG_VIEW;
    TRUNCATE TABLE RAWWANT.IWANT_SALES_CUSTOMER_SMALL_MARKET;
    TRUNCATE TABLE RAWWANT.IWANT_SALES_CUS_SMALL_MARKET_PROD_LINE;
    TRUNCATE TABLE RAWWANT.IWANT_SALES_CUSTOMER_SALES;
    TRUNCATE TABLE RAWWANT.IWANT_SALES_CUS_SALES_MARKET_REL;

    SET VAR_SP_RESULT='Y';
    COMMIT;
END
;