SELECT EMPLOYEE AS 员工号
, EE_SNAME AS 姓名
, BIC_ZPERS_A_N AS 人事范围
, BIC_ZPERSSA_N AS 人事子范围
, ENTRYDATE AS 雇佣日期
, BIC_ZORG_T AS 部门名称
, BIC_ZORG_03_T AS 三级部门
, BIC_ZORG_04_T AS 四级部门
, BIC_ZORG_05_T AS 五级部门
, BIC_ZORG_06_T AS 六级部门
, BIC_ZORG_07_T AS 七级部门
, BIC_ZORG_08_T AS 八级部门
, HRPOSITION AS 职位代码
, BIC_ZHRPOS_N AS 职位
, BIC_ZPOS_A_N AS 职位属性
, BIC_ZHRIC205 AS 职位类型
, BIC_ZHRIC208 AS 职位区域注记
, BIC_ZHRIC207 AS 职位注记
, BIC_ZJOB_N AS 职务
, BIC_ZSGRADE AS 职等
, BIC_ZHRIC209 AS 性别
, BIC_ZHRIK029 AS 年资
FROM RAWWANT.BW_SAPBHP_BIC_AZHR_O7100
;