--RAW
CREATE DATABASE RAWEXT;
CREATE DATABASE RAWWANT;

--DW
CREATE DATABASE RAWEXT;
CREATE DATABASE RAWWANT;
CREATE DATABASE DWEXT;
CREATE DATABASE DWWANT;
CREATE DATABASE DMMDL;

--DM
CREATE DATABASE DMMDL;
CREATE DATABASE APWX;
CREATE DATABASE APDC;

--AP1
CREATE DATABASE APWANT;
CREATE DATABASE APDC;
CREATE DATABASE APWX;
