SELECT '"' || {edino} || '"'
   || ',"' || EMP_ID || '"'
   || ',"' || EMP_NAME || '"'
   || ',"' || POS_ID || '"'
   || ',"' || POS_NAME || '"'
   || ',"' || POS_TYPE_ID || '"'
   || ',"' || POS_TYPE_NAME || '"'
   || ',"' || COMPANY_ID || '"'
   || ',"' || COMPANY_NAME || '"'
   || ',"' || BRANCH_ID || '"'
   || ',"' || BRANCH_NAME || '"'
   || ',"' || DIRECTOR_EMP_ID || '"'
   || ',"' || DIRECTOR_EMP_NAME || '"'
   || ',"' || DIRECTOR_POS_ID || '"'
   || ',"' || DIRECTOR_POS_NAME || '"'
   || ',"' || DIRECTOR_POS_TYPE_ID || '"'
   || ',"' || DIRECTOR_POS_TYPE_NAME || '"'
   || ',"' || POS_PROPERTY_ID || '"'
   || ',"' || CHANNEL_ID || '"'
   || ',"' || CHANNEL_NAME || '"'
   || ',"' || AREA_ID || '"'
   || ',"' || AREA_NAME || '"'
   || ',"' || MASTER_POS || '"'
   || ',"' || EMP_GENDER || '"'
   || ',"' || EMP_ONBOARD_DATE1 || '"' AS CONTENT
FROM SALES.EMP_POSITION_ORG_VIEW
;
