SELECT EDI_NO
    , EMPLOYEE, CALMONTH
    , RECORDMODE, EE_SNAME
    , BIC_ZAMT_06, BIC_ZAMT_30
    , BIC_ZAMT_255, BIC_ZAMT_31
    , BIC_ZAMT_56, BIC_ZAMT_109
    , CURRENCY
FROM RAWWANT.BW_SAPBHP_BIC_AZHR_O7300