SELECT {edino} AS EDI_NO
     , "EMPLOYEE", "CALMONTH", "RECORDMODE"
     , "EE_SNAME", "/BIC/ZAMT_06", "/BIC/ZAMT_30"
     , "/BIC/ZAMT_255", "/BIC/ZAMT_31", "/BIC/ZAMT_56"
     , "/BIC/ZAMT_109", "CURRENCY"
FROM "SAPBHP"."/BIC/AZHR_O7300"
;