SELECT {edino} AS EDI_NO
     , "EMPLOYEE", "DATETO", "RECORDMODE"
     , "/BIC/ZORG_03", "/BIC/ZORG_04", "/BIC/ZORG_05", "/BIC/ZORG_06", "/BIC/ZORG_07", "/BIC/ZORG_08", "/BIC/ZORG_09"
     , "/BIC/ZORG_03_T", "/BIC/ZORG_04_T", "/BIC/ZORG_05_T", "/BIC/ZORG_06_T", "/BIC/ZORG_07_T", "/BIC/ZORG_08_T", "/BIC/ZORG_09_T"
     , "EE_SNAME", "PERS_AREA", "/BIC/ZPERS_A_N", "PERS_SAREA", "/BIC/ZPERSSA_N"
     , "ENTRYDATE", "/BIC/ZORGUNIT", "/BIC/ZORG_T", "HRPOSITION", "/BIC/ZHRPOS_N"
     , "/BIC/ZPOS_ATTR", "/BIC/ZPOS_A_N", "/BIC/ZHRIC189", "/BIC/ZHRIC205"
     , "/BIC/ZHRIC206", "/BIC/ZHRIC208", "/BIC/ZHRIC207", "JOB", "/BIC/ZJOB_N"
     , "/BIC/ZSGRADE", "/BIC/ZGRADE_N", "GENDER", "/BIC/ZHRIC209", "/BIC/ZHRIK029"
FROM "SAPBHP"."/BIC/AZHR_O7100"
;