DROP FUNCTION IF EXISTS APDC.FN_GET_FY_YM;

CREATE FUNCTION APDC.FN_GET_FY_YM(VAR_YMD CHAR(8), VAR_MONTH_SEQ INT) RETURNS CHAR(6)
BEGIN
    DECLARE VAR_FY_YM CHAR(6);
    DECLARE TMP_YMD_M CHAR(2);
    DECLARE TMP_FY_YMD CHAR(8);

    SET TMP_YMD_M = SUBSTRING(VAR_YMD, 5, 2);

    IF TMP_YMD_M='01' OR TMP_YMD_M='02' OR TMP_YMD_M='03' THEN
        SET TMP_FY_YMD = CONCAT(DATE_FORMAT(DATE_SUB(CAST(VAR_YMD AS DATE), INTERVAL 2 YEAR), '%Y'),
                                '0401');
    ELSEIF TMP_YMD_M IN ('04','05','06','07','08','09','10','11','12') THEN
        SET TMP_FY_YMD = CONCAT(DATE_FORMAT(DATE_SUB(CAST(VAR_YMD AS DATE), INTERVAL 1 YEAR), '%Y'),
                                '0401');
    ELSE
        SET TMP_FY_YMD = NULL;
    END IF;

    IF TMP_FY_YMD IS NOT NULL AND VAR_MONTH_SEQ>=1 AND VAR_MONTH_SEQ<=12 THEN
        SET VAR_FY_YM = DATE_FORMAT(DATE_ADD(CAST(TMP_FY_YMD AS DATE), INTERVAL VAR_MONTH_SEQ-1 MONTH), '%Y%m');
    ELSE
        SET VAR_FY_YM = NULL;
    END IF;

    RETURN VAR_FY_YM;
END
