DROP PROCEDURE IF EXISTS APDC.SP_DAT_30114_DC0021_RPT0103_DISTRICT15;

CREATE PROCEDURE APDC.SP_DAT_30114_DC0021_RPT0103_DISTRICT15 (
    VAR_EDI_DATE CHAR(8), VAR_EDI_TIME CHAR(9), VAR_DATA_DATE CHAR(8)
  , OUT VAR_SP_RESULT CHAR(1)
)
BEGIN
    
    SET @DIVISION_ID_MILK='乳飲ID' COLLATE utf8_unicode_ci;
    SET @DIVISION_ID_LEIS='休閒ID' COLLATE utf8_unicode_ci;

    --INSERT1
    --乳飲休閒同期、達成
    INSERT INTO APDC.DC0021_RPT0103_DISTRICT15
    SELECT VAR_DATA_DATE AS DATA_DATE 
         , VAR_DATA_DATE AS RPT_YMD
         , 0 AS WORK_RATIO
         , '乳飲休閒ID' AS DIVISIONC_ID
         , '乳飲休閒NM' AS DIVISIONC_NM
         , DIVISION_ID
         , NULL AS DIVISION_NM
         , DIVISIOND_ID
         , NULL AS DIVISIOND_NM
         , 'CTR_SUPV_ID' AS CTR_SUPV_ID
         , DISTRICT15_ID
         , NULL AS DISTRICT15_NM
         , 'DIST15_SUPV_ID' AS DIST15_SUPV_ID
         , 0 AS MKT_SHARE
         , SUM(CASE WHEN DIVISION_ID IN (@DIVISION_ID_MILK, @DIVISION_ID_LEIS) THEN SALES_AMT_PAST_MONTH ELSE 0 END) AS SALES_AMT_PAST_MONTH_MKLS
         , (CASE WHEN DIVISION_ID IN (@DIVISION_ID_MILK, @DIVISION_ID_LEIS) THEN ROUND(SUM(SALES_AMT_PAST_MONTH)/1000,0) ELSE 0 END) AS SALES_AMT_PAST_MONTH_MKLS_V
         , SUM(CASE WHEN DIVISION_ID IN (@DIVISION_ID_MILK, @DIVISION_ID_LEIS) THEN BILLING ELSE 0 END) AS SALES_AMT_REACH_MKLS
         , (CASE WHEN DIVISION_ID IN (@DIVISION_ID_MILK, @DIVISION_ID_LEIS) THEN ROUND(SUM(BILLING)/1000,0) ELSE 0 END) AS SALES_AMT_REACH_MKLS_V
         , 0 AS SALES_PAST_REACH_RATE_MKLS
         , 0 AS SALES_PAST_REACH_RATE_MKLS_V
         , NULL AS SALES_PAST_REACH_RATE_MKLS_F
         , 0 AS RANK_MKLS
         , 0 AS MKT_SHARE_REACH_RATE
         , SUM(CASE WHEN DIVISION_ID=@DIVISION_ID_MILK THEN SALES_AMT_PAST_MONTH ELSE 0 END) AS SALES_AMT_PAST_MONTH_MILK
         , (CASE WHEN DIVISION_ID=@DIVISION_ID_MILK THEN ROUND(SUM(SALES_AMT_PAST_MONTH)/1000,0) ELSE 0 END) AS SALES_AMT_PAST_MONTH_MILK_V
         , SUM(CASE WHEN DIVISION_ID=@DIVISION_ID_MILK THEN BILLING ELSE 0 END) AS SALES_AMT_REACH_MILK
         , (CASE WHEN DIVISION_ID=@DIVISION_ID_MILK THEN ROUND(SUM(BILLING)/1000,0) ELSE 0 END) AS SALES_AMT_REACH_MILK_V
         , 0 AS SALES_PAST_REACH_RATE_MILK
         , 0 AS SALES_PAST_REACH_RATE_MILK_V
         , NULL AS SALES_PAST_REACH_RATE_MILK_F
         , 0 AS RANK_MILK
         , SUM(CASE WHEN DIVISION_ID=@DIVISION_ID_LEIS THEN SALES_AMT_PAST_MONTH ELSE 0 END) AS SALES_AMT_PAST_MONTH_LEIS
         , (CASE WHEN DIVISION_ID=@DIVISION_ID_LEIS THEN ROUND(SUM(SALES_AMT_PAST_MONTH)/1000,0) ELSE 0 END) AS SALES_AMT_PAST_MONTH_LEIS_V
         , SUM(CASE WHEN DIVISION_ID=@DIVISION_ID_LEIS THEN BILLING ELSE 0 END) AS SALES_AMT_REACH_LEIS
         , (CASE WHEN DIVISION_ID=@DIVISION_ID_LEIS THEN ROUND(SUM(BILLING)/1000,0) ELSE 0 END) AS SALES_AMT_REACH_LEIS_V
         , 0 AS SALES_PAST_REACH_RATE_LEIS
         , 0 AS SALES_PAST_REACH_RATE_LEIS_V
         , NULL AS SALES_PAST_REACH_RATE_LEIS_F
         , 0 AS RANK_LEIS
    FROM DMMDL.DC0021_SALES_DIST_PROD_DATE_CUM
    WHERE DATA_DATE=VAR_DATA_DATE AND RPT_YMD=VAR_DATA_DATE
    GROUP BY DIVISION_ID
           , DIVISIOND_ID
           , DISTRICT15_ID
    ;

    --UPDATE2
    --標準進度
    UPDATE APDC.DC0021_RPT0103_DISTRICT15 A
    JOIN(SELECT ROUND(WORK_RATIO,3) AS WORK_RATIO
         FROM DMMDL.DC0021_WORK_RATIO_CUM
         WHERE DATA_DATE=VAR_DATA_DATE AND RPT_YMD=VAR_DATA_DATE) B
    ON A.DATA_DATE=B.DATA_DATE AND A.RPT_YMD=B.RPT_YMD
    SET A.WORK_RATIO=B.WORK_RATIO
    WHERE A.DATA_DATE=VAR_DATA_DATE AND A.RPT_YMD=VAR_DATA_DATE
    ;

    --UPDATE3
    --應有市場占比 達成率
    UPDATE APDC.DC0021_RPT0103_DISTRICT15 A
    JOIN(SELECT DISTRICT15_ID
              , DISTRICT15_MKT_SHARE AS MKT_SHARE
              , MKT_SHARE_REACH_RATE_MKLS AS MKT_SHARE_REACH_RATE
         FROM DMMDL.DC0021_MKT_SHARE_REACH_RATE_DISTRICT15_CUM
         WHERE DATA_DATE=VAR_DATA_DATE AND RPT_YMD=VAR_DATA_DATE
         GROUP BY DISTRICT15_ID) B
    ON A.DATA_DATE=B.DATA_DATE AND A.RPT_YMD=B.RPT_YMD AND A.DISTRICT15_ID=B.DISTRICT15_ID
    SET A.MKT_SHARE=B.MKT_SHARE
      , A.MKT_SHARE_REACH_RATE=B.MKT_SHARE_REACH_RATE
    WHERE A.DATA_DATE=VAR_DATA_DATE AND A.RPT_YMD=VAR_DATA_DATE
    ;

    --UPDATE4
    --同期達成率 排名
    UPDATE APDC.DC0021_RPT0103_DISTRICT15 A
    JOIN(SELECT DIVISIONC_ID
              , DIVISION_ID
              , DIVISIOND_ID
              , DISTRICT15_ID
              , ROUND(SALES_AMT_REACH_MKLS/SALES_AMT_PAST_MONTH_MKLS,3) AS SALES_PAST_REACH_RATE_MKLS
              , (CASE WHEN ROUND(SALES_AMT_REACH_MKLS/SALES_AMT_PAST_MONTH_MKLS,3)<0 THEN 0 ELSE ROUND(SALES_AMT_REACH_MKLS/SALES_AMT_PAST_MONTH_MKLS,3) END) AS SALES_PAST_REACH_RATE_MKLS_V
              , (CASE WHEN ROUND(SALES_AMT_REACH_MKLS/SALES_AMT_PAST_MONTH_MKLS,3)<WORK_RATIO THEN 'A'
                      WHEN SALES_AMT_PAST_MONTH_MKLS<=0 THEN 'B' ELSE NULL END) AS SALES_PAST_REACH_RATE_MKLS_F
              , ROW_NUMBER() OVER(ORDER BY (SALES_AMT_REACH_MKLS/SALES_AMT_PAST_MONTH_MKLS) DESC) AS RANK_MKLS
              , ROUND(SALES_AMT_REACH_MILK/SALES_AMT_PAST_MONTH_MILK,3) AS SALES_PAST_REACH_RATE_MILK
              , (CASE WHEN ROUND(SALES_AMT_REACH_MILK/SALES_AMT_PAST_MONTH_MILK,3)<0 THEN 0 ELSE ROUND(SALES_AMT_REACH_MILK/SALES_AMT_PAST_MONTH_MILK,3) END) AS SALES_PAST_REACH_RATE_MILK_V
              , (CASE WHEN ROUND(SALES_AMT_REACH_MILK/SALES_AMT_PAST_MONTH_MILK,3)<WORK_RATIO THEN 'A'
                      WHEN SALES_AMT_PAST_MONTH_MILK<=0 THEN 'B' ELSE NULL END) AS SALES_PAST_REACH_RATE_MILK_F
              , ROW_NUMBER() OVER(ORDER BY (SALES_AMT_REACH_MILK/SALES_AMT_PAST_MONTH_MILK) DESC) AS RANK_MILK
              , ROUND(SALES_AMT_REACH_LEIS/SALES_AMT_PAST_MONTH_LEIS,3) AS SALES_PAST_REACH_RATE_LEIS
              , (CASE WHEN ROUND(SALES_AMT_REACH_LEIS/SALES_AMT_PAST_MONTH_LEIS,3)<0 THEN 0 ELSE ROUND(SALES_AMT_REACH_LEIS/SALES_AMT_PAST_MONTH_LEIS,3) END) AS SALES_PAST_REACH_RATE_LEIS_V
              , (CASE WHEN ROUND(SALES_AMT_REACH_LEIS/SALES_AMT_PAST_MONTH_LEIS,3)<WORK_RATIO THEN 'A'
                      WHEN SALES_AMT_PAST_MONTH_LEIS<=0 THEN 'B' ELSE NULL END) AS SALES_PAST_REACH_RATE_LEIS_F
              , ROW_NUMBER() OVER(ORDER BY (SALES_AMT_REACH_LEIS/SALES_AMT_PAST_MONTH_LEIS) DESC) AS RANK_LEIS
         FROM APDC.DC0021_RPT0103_DISTRICT15
         WHERE DATA_DATE=VAR_DATA_DATE AND RPT_YMD=VAR_DATA_DATE
         GROUP BY DIVISIONC_ID
                , DIVISION_ID
                , DIVISIOND_ID
                , DISTRICT15_ID) B
    ON A.DATA_DATE=B.DATA_DATE AND A.RPT_YMD=B.RPT_YMD AND 
       A.DIVISIONC_ID=B.DIVISIONC_ID AND A.DIVISION_ID=B.DIVISION_ID AND A.DIVISIOND_ID=B.DIVISIOND_ID AND A.DISTRICT15_ID=B.DISTRICT15_ID AND
       A.CTR_SUPV_ID=B.CTR_SUPV_ID AND A.DIST15_SUPV_ID=B.DIST15_SUPV_ID
    SET A.SALES_PAST_REACH_RATE_MKLS=B.SALES_PAST_REACH_RATE_MKLS
      , A.SALES_PAST_REACH_RATE_MKLS_V=B.SALES_PAST_REACH_RATE_MKLS_V
      , A.SALES_PAST_REACH_RATE_MKLS_F=B.SALES_PAST_REACH_RATE_MKLS_F
      , A.RANK_MKLS=B.RANK_MKLS
      , A.SALES_PAST_REACH_RATE_MILK=B.SALES_PAST_REACH_RATE_MILK
      , A.SALES_PAST_REACH_RATE_MILK_V=B.SALES_PAST_REACH_RATE_MILK_V
      , A.SALES_PAST_REACH_RATE_MILK_F=B.SALES_PAST_REACH_RATE_MILK_F
      , A.RANK_MILK=B.RANK_MILK
      , A.SALES_PAST_REACH_RATE_LEIS=B.SALES_PAST_REACH_RATE_LEIS
      , A.SALES_PAST_REACH_RATE_LEIS_V=B.SALES_PAST_REACH_RATE_LEIS_V
      , A.SALES_PAST_REACH_RATE_LEIS_F=B.SALES_PAST_REACH_RATE_LEIS_F
      , A.RANK_LEIS=B.RANK_LEIS
    WHERE A.DATA_DATE=VAR_DATA_DATE AND A.RPT_YMD=VAR_DATA_DATE
    ;



    SET VAR_SP_RESULT='Y';
    COMMIT;
END
;