DROP PROCEDURE IF EXISTS APDC.SP_DAT_30109_DC0021_RPT0102_DIVISIOND;

CREATE PROCEDURE APDC.SP_DAT_30109_DC0021_RPT0102_DIVISIOND (
    VAR_EDI_DATE CHAR(8), VAR_EDI_TIME CHAR(9), VAR_DATA_DATE CHAR(8)
  , OUT VAR_SP_RESULT CHAR(1)
)
BEGIN
    
    SET @DIVISIOND_ID_2C='網絡科技2C' COLLATE utf8_unicode_ci;

    --INSERT1
    --SALES_AMT_REACH_D1 達成截止至D1
    --SALES_AMT_REACH_D1_V 達成截至D1(畫面數值)
    --SALES_AMT_PAST_MONTH 全月同期
    --SALES_AMT_PAST_MONTH_V 全月同期(畫面數值)
    --PAST_PROG_REACH_RATE 全月同期達成率
    --PAST_PROG_REACH_RATE_V 全月同期達成率(畫面數值)
    --SALES_PAST_REACH_RATE_EC 電子商務事業部同期達成率
    --SALES_PAST_REACH_RATE_EC_V 電子商務事業部同期達成率(畫面數值)
    INSERT INTO APDC.DC0021_RPT0102_DIVISIOND
    SELECT VAR_DATA_DATE AS DATA_DATE
         , VAR_DATA_DATE AS RPT_YMD
         , 0 AS WORK_RATIO
         , DIVISION_ID
         , NULL AS DIVISION_NM
         , DIVISIOND_ID
         , NULL AS DIVISIOND_NM
         , SUM(BILLING) AS SALES_AMT_REACH_D1
         , ROUND(SUM(BILLING)/1000,0) AS SALES_AMT_REACH_D1_V
         , SUM(SALES_AMT_PAST_MONTH) AS SALES_AMT_PAST_MONTH
         , ROUND(SUM(SALES_AMT_PAST_MONTH)/1000,0) AS SALES_AMT_PAST_MONTH_V
         , ROUND(SUM(BILLING)/SUM(SALES_AMT_PAST_MONTH),3) AS PAST_PROG_REACH_RATE
         , (CASE WHEN ROUND(SUM(BILLING)/SUM(SALES_AMT_PAST_MONTH),3)<0 THEN 0.00 ELSE ROUND(SUM(BILLING)/SUM(SALES_AMT_PAST_MONTH),3) END) AS PAST_PROG_REACH_RATE_V
         , NULL AS PAST_PROG_REACH_RATE_F
         , SUM(SALES_AMT_PAST_MONTH) AS SALES_AMT_PAST_MONTH_EC
         , ROUND(SUM(BILLING)/SUM(SALES_AMT_PAST_MONTH),3) AS SALES_PAST_REACH_RATE_EC
         , (CASE WHEN ROUND(SUM(BILLING)/SUM(SALES_AMT_PAST_MONTH),3)<0 THEN 0.00 ELSE ROUND(SUM(BILLING)/SUM(SALES_AMT_PAST_MONTH),3) END) AS SALES_PAST_REACH_RATE_EC_V
         , NULL AS SALES_PAST_REACH_RATE_EC_F
    FROM DMMDL.DC0021_SALES_DIST_PROD_DATE_CUM
    WHERE DATA_DATE=VAR_DATA_DATE AND RPT_YMD=VAR_DATA_DATE
      AND DIVISIOND_ID=@DIVISIOND_ID_2C
    GROUP BY DIVISION_ID
           , DIVISIOND_ID
    ;

    --UPDATE2
    --WORK_RATIO 標準進度
    UPDATE APDC.DC0021_RPT0102_DIVISIOND A
    JOIN(SELECT ROUND(WORK_RATIO,3) AS WORK_RATIO
         FROM DMMDL.DC0021_WORK_RATIO_CUM
         WHERE DATA_DATE=VAR_DATA_DATE AND RPT_YMD=VAR_DATA_DATE) B
    ON A.DATA_DATE=B.DATA_DATE AND A.RPT_YMD=B.RPT_YMD
    SET A.WORK_RATIO=B.WORK_RATIO
    WHERE A.DATA_DATE=VAR_DATA_DATE AND A.RPT_YMD=VAR_DATA_DATE
    ;

    --UPDATE3
    --SALES_PAST_REACH_RATE_EC_F 電子商務事業部同期達成率(畫面格式)
    UPDATE APDC.DC0021_RPT0102_DIVISIOND A
    JOIN(SELECT DIVISION_ID
              , DIVISIOND_ID
              , (CASE WHEN PAST_PROG_REACH_RATE<WORK_RATIO THEN 'A'
                      WHEN SALES_AMT_PAST_MONTH<=0 THEN 'B' ELSE NULL END) AS PAST_PROG_REACH_RATE_F
              , (CASE WHEN SALES_PAST_REACH_RATE_EC_V<WORK_RATIO THEN 'A'
                      WHEN SALES_AMT_PAST_MONTH<=0 THEN 'B' ELSE NULL END) AS SALES_PAST_REACH_RATE_EC_F
         FROM APDC.DC0021_RPT0102_DIVISIOND
         WHERE DATA_DATE=VAR_DATA_DATE AND RPT_YMD=VAR_DATA_DATE
         GROUP BY DIVISION_ID
                , DIVISIOND_ID) B
    ON A.DATA_DATE=B.DATA_DATE AND A.RPT_YMD=B.RPT_YMD AND A.DIVISION_ID=B.DIVISION_ID AND A.DIVISIOND_ID=B.DIVISIOND_ID
    SET A.PAST_PROG_REACH_RATE_F=B.PAST_PROG_REACH_RATE_F
      , A.SALES_PAST_REACH_RATE_EC_F=B.SALES_PAST_REACH_RATE_EC_F
    WHERE A.DATA_DATE=VAR_DATA_DATE AND A.RPT_YMD=VAR_DATA_DATE
    ;

    SET VAR_SP_RESULT='Y';
    COMMIT;
END
;