DROP PROCEDURE IF EXISTS APDC.SP_DAT_30119_DC0021_RPT0105_TOTAL;

CREATE PROCEDURE APDC.SP_DAT_30119_DC0021_RPT0105_TOTAL (
    VAR_EDI_DATE CHAR(8), VAR_EDI_TIME CHAR(9), VAR_DATA_DATE CHAR(8)
  , OUT VAR_SP_RESULT CHAR(1)
)
BEGIN

    SET @RPT_YMD_FY_REACH_BEGIN=APDC.FN_GET_FY_YMD(VAR_DATA_DATE,0,1,'N') COLLATE utf8_unicode_ci;
    SET @RPT_YMD_FY_REACH_END=APDC.FN_GET_FY_YMD(VAR_DATA_DATE,0,12,'Y') COLLATE utf8_unicode_ci;
    SET @RPT_YMD_FY_PAST_BEGIN=APDC.FN_GET_FY_YM(VAR_DATA_DATE,-1,1,'N') COLLATE utf8_unicode_ci;
    SET @RPT_YMD_FY_PAST_END=APDC.FN_GET_FY_YM(VAR_DATA_DATE,-1,12,'Y') COLLATE utf8_unicode_ci;
    SET @RPT_YMD_CUM_REACH_BEGIN=APDC.FN_GET_FY_YMD(VAR_DATA_DATE,1,1,'N') COLLATE utf8_unicode_ci;
    SET @RPT_YMD_CUM_REACH_LAST=APDC.FN_GET_YMD(VAR_DATA_DATE,0,-1,0,'Y') COLLATE utf8_unicode_ci;
    SET @RPT_YMD_CUM_POST_BEGIN=APDC.FN_GET_FY_YMD(VAR_DATA_DATE,0,1,'N') COLLATE utf8_unicode_ci;
    SET @RPT_YMD_CUM_POST_LAST=APDC.FN_GET_YMD(VAR_DATA_DATE,-1,-1,0,'Y') COLLATE utf8_unicode_ci;
    SET @RPT_YMD_17=17 COLLATE utf8_unicode_ci;
    SET @RPT_YMD_END=APDC.FN_GET_YMD(VAR_DATA_DATE,0,0,0,'Y') COLLATE utf8_unicode_ci;
    SET @RPT_YMD_NEXT_PAST=SUBSTRING(APDC.FN_GET_YMD(VAR_DATA_DATE,-1,1,0,'Y'),1,6) COLLATE utf8_unicode_ci;
    SET @RPT_YMD_NEXT_FCST=SUBSTRING(APDC.FN_GET_YMD(VAR_DATA_DATE,0,1,0,'Y'),1,6) COLLATE utf8_unicode_ci;
    SET @RPT_YMD_PAST=SUBSTRING(APDC.FN_GET_YMD(VAR_DATA_DATE,-1,0,0,'Y'),1,6) COLLATE utf8_unicode_ci;

    --INSERT1
    --FY1_SALES_AMT Y-1財年達成
    --FY1_SALES_AMT_V Y-1財年達成(畫面數值)
    --FY1_SALES_AMT_PAST_MONTH   Y-1財年全月同期
    --FY1_SALES_AMT_PAST_MONTH_V Y-1財年全月同期(畫面數值)  
    --FYBG_SALES_AMT_REACH   4-(M-1)月達成
    --FYBG_SALES_AMT_REACH_V 4-(M-1)月達成(畫面數值)
    --FYBG_SALES_AMT_PAST_MONTH   4-(M-1)月同期
    --FYBG_SALES_AMT_PAST_MONTH_V 4-(M-1)月同期(畫面數值) 
    --SALES_AMT_REACH_MONTH   全月達成
    --SALES_AMT_REACH_MONTH_V 全月達成(畫面數值)
    --SALES_AMT_PAST_MONTH  全月同期
    --SALES_AMT_PAST_MONTH_V 全月同期(畫面數值)
    --SALES_AMT_PAST_PROG  當日進度同期
    --SALES_AMT_PAST_PROG_V 當日進度同期(畫面數值)
    --SALES_AMT_PAST_PROG_F 當日進度同期(畫面格式)
    --NEXT_SALES_AMT_PAST_MONTH   M+1月全月同期
    --NEXT_SALES_AMT_PAST_MONTH_V M+1月全月同期(畫面數值)
    --NEXT_SALES_AMT_PAST_MONTH_F M+1月全月同期(畫面格式)
    INSERT INTO APDC.DC0021_RPT0105_TOTAL
    SELECT VAR_DATA_DATE AS DATA_DATE
         , VAR_DATA_DATE AS RPT_YMD
         , 0 AS WORK_DAY
         , 0 AS WORK_TOTAL_DAY
         , 0 AS WORK_RATIO
         , SUM(CASE WHEN RPT_YMD>=@RPT_YMD_FY_REACH_BEGIN AND RPT_YMD<=@RPT_YMD_FY_REACH_END THEN SALES_AMT ELSE 0 END) AS FY1_SALES_AMT
         , ROUND(SUM(CASE WHEN RPT_YMD>=@RPT_YMD_FY_REACH_BEGIN AND RPT_YMD<=@RPT_YMD_FY_REACH_END THEN SALES_AMT ELSE 0 END)/1000,0) AS FY1_SALES_AMT_V
         , SUM(CASE WHEN RPT_YM>=@RPT_YMD_FY_PAST_BEGIN AND RPT_YMD<=@RPT_YMD_FY_PAST_END THEN SALES_AMT_PAST_MONTH ELSE 0 END) AS FY1_SALES_AMT_PAST_MONTH
         , ROUND(SUM(CASE WHEN RPT_YMD>=@RPT_YMD_FY_PAST_BEGIN AND RPT_YMD<=@RPT_YMD_FY_PAST_END THEN SALES_AMT_PAST_MONTH ELSE 0 END)/1000,0) AS FY1_SALES_AMT_PAST_MONTH_V   
         , 0 AS FY1_PAST_GROWTH_RATE     
         , SUM(CASE WHEN RPT_YMD>=@RPT_YMD_CUM_REACH_BEGIN AND RPT_YMD<=@RPT_YMD_CUM_REACH_LAST THEN SALES_AMT ELSE 0 END) AS FYBG_SALES_AMT_REACH
         , ROUND(SUM(CASE WHEN RPT_YMD>=@RPT_YMD_CUM_REACH_BEGIN AND RPT_YMD<=@RPT_YMD_CUM_REACH_LAST THEN SALES_AMT ELSE 0 END)/1000,0) AS FYBG_SALES_AMT_REACH_V
         , SUM(CASE WHEN RPT_YMD>=@RPT_YMD_CUM_POST_BEGIN AND RPT_YMD<=@RPT_YMD_CUM_POST_END THEN SALES_AMT_PAST_MONTH ELSE 0 END) AS FYBG_SALES_AMT_PAST_MONTH
         , ROUND(SUM(CASE WHEN RPT_YMD>=@RPT_YMD_CUM_POST_BEGIN AND RPT_YMD<=@RPT_YMD_CUM_POST_END THEN SALES_AMT_PAST_MONTH ELSE 0 END)/1000,0) AS FYBG_SALES_AMT_PAST_MONTH_V
         , 0 AS FYBG_PAST_GROWTH_RATE
         , SUM(CASE WHEN RPT_YMD=VAR_DATA_DATE THEN BILLING ELSE 0 END) AS SALES_AMT_REACH_MONTH
         , ROUND(SUM(CASE WHEN RPT_YMD=VAR_DATA_DATE THEN BILLING ELSE 0 END)/1000,0) AS SALES_AMT_REACH_MONTH_V
         , SUM(CASE WHEN RPT_YMD=VAR_DATA_DATE THEN SALES_AMT_PAST_MONTH ELSE 0 END) AS SALES_AMT_PAST_MONTH
         , ROUND(SUM(CASE WHEN RPT_YMD=VAR_DATA_DATE THEN SALES_AMT_PAST_MONTH ELSE 0 END)/1000,0) AS SALES_AMT_PAST_MONTH_V
         , 0 AS PAST_MONTH_REACH_RATE
         , NULL AS PAST_MONTH_REACH_RATE_F
         , 0 AS PAST_MONTH_GROWTH_RATE
         , NULL AS PAST_MONTH_GROWTH_RATE_F
         , SUM(CASE WHEN RPT_YMD=VAR_DATA_DATE THEN SALES_AMT_PAST_MONTH_PROG ELSE 0 END) AS SALES_AMT_PAST_PROG
         , ROUND(SUM(CASE WHEN RPT_YMD=VAR_DATA_DATE THEN SALES_AMT_PAST_MONTH_PROG ELSE 0 END)/1000,0) AS SALES_AMT_PAST_PROG_V
         , (CASE WHEN PRT_YMD=@RPT_YMD_END THEN 'Z' ELSE NULL END) AS SALES_AMT_PAST_PROG_F
         , 0 AS PAST_PROG_GROWTH_RATE
         , NULL AS PAST_PROG_GROWTH_RATE_F
         , 0 AS FCST_AMT
         , 0 AS FCST_AMT_V
         , 0 AS FCST_REACH_RATE
         , 0 AS FY_CUM_SALES
         , 0 AS FY_CUM_SALES_V
         , SUM(CASE WHEN RPT_YMD>=@RPT_YMD_CUM_POST_BEGIN AND RPT_YMD<=VAR_DATA_DATE THEN SALES_AMT_PAST_MONTH ELSE 0 END) AS FY_CUM_SALES_PAST_MONTH
         , ROUND(SUM(CASE WHEN RPT_YMD>=@RPT_YMD_CUM_POST_BEGIN AND RPT_YMD<=VAR_DATA_DATE THEN SALES_AMT_PAST_MONTH ELSE 0 END)/1000,0) AS FY_CUM_SALES_PAST_MONTH_V
         , 0 AS FY_CUM_SALES_PAST_PROG
         , 0 AS FY_CUM_SALES_PAST_PROG_V
         , NULL AS FY_CUM_SALES_PAST_PROG_F
         , 0 AS FY_CUM_SALES_PAST_PROG_RATIO
         , 0 AS FY_CUM_PAST_MONTH_REACH_RATE
         , 0 AS FY_CUM_PAST_MONTH_REACH_RATE_V
         , NULL AS FY_CUM_PAST_MONTH_REACH_RATE_F
         , SUM(CASE WHEN RPT_YMD=@RPT_YMD_NEXT_PAST THEN SALES_AMT_PAST_MONTH ELSE 0 END) AS NEXT_SALES_AMT_PAST_MONTH
         , ROUND(SUM(CASE WHEN RPT_YMD=@RPT_YMD_NEXT_PAST THEN SALES_AMT_PAST_MONTH ELSE 0 END)/1000,0) AS NEXT_SALES_AMT_PAST_MONTH_V
         , (CASE WHEN RIGHT(RPT_YMD=VAR_DATA_DATE,2)<@RPT_YMD_17 THEN 'Z' ELSE NULL END) AS NEXT_SALES_AMT_PAST_MONTH_F
         , 0 AS NEXT_FCST_AMT
         , 0 AS NEXT_FCST_AMT_V
         , NULL AS NEXT_FCST_AMT_F
         , 0 AS FCST_GROWTH_RATE
         , NULL AS FCST_GROWTH_RATE_F
    FROM DMMDL.DC0021_SALES_DIST_PROD_DATE_CUM
    WHERE DATA_DATE=VAR_DATA_DATE
    ;

    --UPDATE2
    --WORK_RATIO 標準進度
    UPDATE APDC.DC0021_RPT0105_TOTAL A
    JOIN(SELECT WORK_DAY
              , WORK_TOTAL_DAY
              , ROUND(WORK_RATIO,3) AS WORK_RATIO
         FROM DMMDL.DC0021_WORK_RATIO_CUM
         WHERE DATA_DATE=VAR_DATA_DATE AND RPT_YMD=VAR_DATA_DATE) B
    ON A.DATA_DATE=B.DATA_DATE AND A.RPT_YMD=B.RPT_YMD
    SET A.WORK_DAY=B.WORK_DAY
      , A.WORK_TOTAL_DAY=B.WORK_TOTAL_DAY
      , A.WORK_RATIO=B.WORK_RATIO
    WHERE A.DATA_DATE=VAR_DATA_DATE AND A.RPT_YMD=VAR_DATA_DATE
    ;
 
    --UPDATE3
    --預估
    UPDATE APDC.DC0021_RPT0105_TOTAL A
    JOIN(SELECT SUM(CASE WHEN RPT_YMD=VAR_DATA_DATE THEN FCST_AMT ELSE 0 END) AS FCST_AMT
              , ROUND(SUM(CASE WHEN RPT_YMD=VAR_DATA_DATE THEN FCST_AMT ELSE 0 END)/1000,0) AS FCST_AMT_V
              , SUM(CASE WHEN RPT_YMD=@RPT_YMD_NEXT_FCST THEN FCST_AMT ELSE 0 END) AS NEXT_FCST_AMT
              , ROUND(SUM(CASE WHEN RPT_YMD=@RPT_YMD_NEXT_FCST THEN FCST_AMT ELSE 0 END)/1000,0) AS NEXT_FCST_AMT_V
              , (CASE WHEN RIGHT(RPT_YMD=VAR_DATA_DATE,2)<@RPT_YMD_17 THEN 'Z' ELSE NULL END) AS NEXT_FCST_AMT_F
         FROM DMMDL.DC0021_FCST_AMT_CUM
         WHERE DATA_DATE=VAR_DATA_DATE) B
    ON A.DATA_DATE=B.DATA_DATE AND A.RPT_YMD=B.RPT_YMD
    SET A.FCST_AMT=B.FCST_AMT
      , A.FCST_AMT_V=B.FCST_AMT_V
      , A.NEXT_FCST_AMT=B.NEXT_FCST_AMT
      , A.NEXT_FCST_AMT_V=B.NEXT_FCST_AMT_V
      , A.NEXT_FCST_AMT_F=B.NEXT_FCST_AMT_F
    WHERE A.DATA_DATE=VAR_DATA_DATE AND A.RPT_YMD=VAR_DATA_DATE
    ;

    --UPDATE4
    --FY1_PAST_GROWTH_RATE   Y-1財年同期成長率
    --FYBG_PAST_GROWTH_RATE  4-(M-1)月同期成長率 
    --PAST_MONTH_REACH_RATE    當月同期達成率
    --PAST_MONTH_REACH_RATE_F   當月同期達成率(畫面格式)
    --PAST_MONTH_GROWTH_RATE    當月同期成長率
    --PAST_MONTH_GROWTH_RATE_F  當月同期成長率(畫面格式)
    --PAST_PROG_GROWTH_RATE     當日同期成長率
    --PAST_PROG_GROWTH_RATE_F   當日同期成長率(畫面格式)
    --FCST_REACH_RATE          預估達成率
    --FY_CUM_SALES                 財年累計達成
    --FY_CUM_SALES_PAST_MONTH        財年累計全月同期
    --FY_CUM_SALES_PAST_PROG         財年累計進度同期
    --FY_CUM_SALES_PAST_PROG_RATIO   財年累計進度同期比
    --FCST_GROWTH_RATE   預估成長率
    --FCST_GROWTH_RATE_F 預估成長率(畫面格式)
    UPDATE APDC.DC0021_RPT0105_TOTAL A
    JOIN(SELECT (CASE WHEN RPT_YMD=VAR_DATA_DATE THEN ROUND((FY1_SALES_AMT/FY1_SALES_AMT_PAST_MONTH)-1,3) ELSE 0 END) AS FY1_PAST_GROWTH_RATE
              , (CASE WHEN RPT_YMD=VAR_DATA_DATE THEN ROUND((SALE_AMT/SALES_AMT_PAST_MONTH)-1,3) ELSE 0 END) AS FYBG_PAST_GROWTH_RATE
              , (CASE WHEN RPT_YMD=VAR_DATA_DATE THEN ROUND(SALES_AMT_REACH_MONTH/SALES_AMT_PAST_MONTH,3) ELSE 0 END) AS PAST_MONTH_REACH_RATE
              , (CASE WHEN RPT_YMD=@RPT_YMD_END THEN 'Z' ELSE NULL END) AS PAST_MONTH_REACH_RATE_F
              , (CASE WHEN RPT_YMD=VAR_DATA_DATE THEN ROUND((SALES_AMT_REACH_MONTH/SALES_AMT_PAST_MONTH)-1,3) ELSE 0 END) AS PAST_MONTH_GROWTH_RATE
              , (CASE WHEN RPT_YMD<>@RPT_YMD_END THEN 'Z' ELSE NULL END) AS PAST_MONTH_GROWTH_RATE_F
              , (CASE WHEN RPT_YMD=VAR_DATA_DATE THEN ROUND((SALES_AMT_REACH_MONTH/SALES_AMT_PAST_PROG)-1,3) ELSE 0 END) AS PAST_PROG_GROWTH_RATE
              , (CASE WHEN RPT_YMD=@RPT_YMD_END THEN 'Z'
                      WHEN ROUND((SALES_AMT_REACH_MONTH/SALES_AMT_PAST_PROG)-1,3)<0 THEN 'A' ELSE NULL END) AS PAST_PROG_GROWTH_RATE_F
              , (CASE WHEN RPT_YMD=VAR_DATA_DATE THEN ROUND(SALES_AMT_REACH_MONTH/FCST_AMT,3) ELSE 0 END) AS FCST_REACH_RATE
              , (CASE WHEN RPT_YMD=VAR_DATA_DATE THEN (FYBG_SALES_AMT_REACH+SALES_AMT_REACH_MONTH) ELSE 0 END) AS FY_CUM_SALES
              , (CASE WHEN RPT_YMD=VAR_DATA_DATE THEN ROUND((FYBG_SALES_AMT_REACH+SALES_AMT_REACH_MONTH)/1000,0) ELSE 0 END) AS FY_CUM_SALES_V
              , (CASE WHEN RPT_YMD=VAR_DATA_DATE THEN (FYBG_SALES_AMT_PAST_MONTH+SALES_AMT_PAST_PROG) ELSE 0 END) AS FY_CUM_SALES_PAST_PROG
              , (CASE WHEN RPT_YMD=VAR_DATA_DATE THEN ROUND((FYBG_SALES_AMT_PAST_MONTH+SALES_AMT_PAST_PROG)/1000,0) ELSE 0 END) AS FY_CUM_SALES_PAST_PROG_V
              , (CASE WHEN RPT_YMD=@RPT_YMD_END THEN 'Z' ELSE NULL END) AS FY_CUM_SALES_PAST_PROG_F
              , (CASE WHEN RPT_YMD=@RPT_YMD_END THEN 'Z' ELSE NULL END) AS FY_CUM_PAST_MONTH_REACH_RATE_F
              , (CASE WHEN RPT_YMD=VAR_DATA_DATE THEN ROUND((NEXT_FCST_AMT/NEXT_SALES_AMT_PAST_MONTH)-1,3) ELSE 0 END) AS FCST_GROWTH_RATE
              , (CASE WHEN RIGHT(RPT_YMD=VAR_DATA_DATE,2)<@RPT_YMD_17 THEN 'Z' ELSE NULL END) AS FCST_GROWTH_RATE_F     
         FROM APDC.DC0021_RPT0105_TOTAL
         WHERE DATA_DATE=VAR_DATA_DATE) B
    ON A.DATA_DATE=B.DATA_DATE AND A.RPT_YMD=B.RPT_YMD
    SET A.FY1_PAST_GROWTH_RATE=B.FY1_PAST_GROWTH_RATE
      , A.FYBG_PAST_GROWTH_RATE=B.FYBG_PAST_GROWTH_RATE
      , A.PAST_MONTH_REACH_RATE=B.PAST_MONTH_REACH_RATE
      , A.PAST_MONTH_REACH_RATE_F=B.PAST_MONTH_REACH_RATE_F
      , A.PAST_MONTH_GROWTH_RATE=B.PAST_MONTH_GROWTH_RATE
      , A.PAST_MONTH_GROWTH_RATE_F=B.PAST_MONTH_GROWTH_RATE_F
      , A.PAST_PROG_GROWTH_RATE=B.PAST_PROG_GROWTH_RATE
      , A.PAST_PROG_GROWTH_RATE_F=B.PAST_PROG_GROWTH_RATE_F
      , A.FCST_REACH_RATE=B.FCST_REACH_RATE
      , A.FY_CUM_SALES=B.FY_CUM_SALES
      , A.FY_CUM_SALES_V=B.FY_CUM_SALES_V
      , A.FY_CUM_SALES_PAST_PROG=B.FY_CUM_SALES_PAST_PROG
      , A.FY_CUM_SALES_PAST_PROG_V=B.FY_CUM_SALES_PAST_PROG_V
      , A.FY_CUM_SALES_PAST_PROG_F=B.FY_CUM_SALES_PAST_PROG_F
      , A.FY_CUM_PAST_MONTH_REACH_RATE_F=B.FY_CUM_PAST_MONTH_REACH_RATE_F
      , A.FCST_GROWTH_RATE=B.FCST_GROWTH_RATE
      , A.FCST_GROWTH_RATE_F=B.FCST_GROWTH_RATE_F
    WHERE A.DATA_DATE=VAR_DATA_DATE AND A.RPT_YMD=VAR_DATA_DATE
    ;

    --UPDATE5
    --FY_CUM_PAST_MONTH_REACH_RATE   財年累計全月同期達成率
    UPDATE APDC.DC0021_RPT0105_TOTAL A
    JOIN(SELECT ROUND((FY_CUM_SALES/FY_CUM_SALES_PAST_PROG)-1,3) AS FY_CUM_SALES_PAST_PROG_RATIO
              , ROUND(FY_CUM_SALES/FY_CUM_SALES_PAST_MONTH,3) AS FY_CUM_PAST_MONTH_REACH_RATE
              , (CASE WHEN ROUND(FY_CUM_SALES/FY_CUM_SALES_PAST_MONTH,3)<0 THEN 0.00 ELSE ROUND(FY_CUM_SALES/FY_CUM_SALES_PAST_MONTH,3) END) AS FY_CUM_PAST_MONTH_REACH_RATE_V
         FROM APDC.DC0021_RPT0105_TOTAL
         WHERE DATA_DATE=VAR_DATA_DATE AND RPT_YMD=VAR_DATA_DATE) B
    ON A.DATA_DATE=B.DATA_DATE AND A.RPT_YMD=B.RPT_YMD
    SET A.FY_CUM_SALES_PAST_PROG_RATIO=B.FY_CUM_SALES_PAST_PROG_RATIO
      , A.FY_CUM_PAST_MONTH_REACH_RATE=B.FY_CUM_PAST_MONTH_REACH_RATE
      , A.FY_CUM_PAST_MONTH_REACH_RATE_V=B.FY_CUM_PAST_MONTH_REACH_RATE_V
    WHERE A.DATA_DATE=VAR_DATA_DATE AND A.RPT_YMD=VAR_DATA_DATE
    ;

    SET VAR_SP_RESULT='Y';
    COMMIT;
END
;