DROP PROCEDURE IF EXISTS APDC.SP_DAT_30112_DC0021_RPT0103_DIVISION;

CREATE PROCEDURE APDC.SP_DAT_30112_DC0021_RPT0103_DIVISION (
    VAR_EDI_DATE CHAR(8), VAR_EDI_TIME CHAR(9), VAR_DATA_DATE CHAR(8)
  , OUT VAR_SP_RESULT CHAR(1)
)
BEGIN
    
    SET @DIVISION_ID_MILK='乳飲ID'
    SET @DIVISION_ID_LEIS='休閒ID'

    --乳飲,休閒
    --INSERT1
    INSERT INTO APDC.DC0021_RPT0103_DIVISION
    SELECT VAR_DATA_DATE AS DATA_DATE 
         , VAR_DATA_DATE AS RPT_YMD
         , 0 AS WORK_RATIO
         , '乳飲休閒ID' AS DIVISIONC_ID
         , '乳飲休閒NM' AS DIVISIONC_NM
         , DIVISION_ID
         , NULL AS DIVISION_NM
         , SUM(CASE WHEN DIVISION_ID=@DIVISION_ID_MILK THEN SALES_AMT_PAST_MONTH ELSE 0 END) AS SALES_AMT_PAST_MONTH_MILK
         , ROUND(SUM(CASE WHEN DIVISION_ID=@DIVISION_ID_MILK THEN SALES_AMT_PAST_MONTH ELSE 0 END)/1000,0) AS SALES_AMT_PAST_MONTH_MILK_V
         , SUM(CASE WHEN DIVISION_ID=@DIVISION_ID_MILK THEN BILLING ELSE 0 END) AS SALES_AMT_REACH_MILK
         , ROUND(SUM(CASE WHEN DIVISION_ID=@DIVISION_ID_MILK THEN BILLING ELSE 0 END)/1000,0) AS SALES_AMT_REACH_MILK_V
         , 0 AS SALES_PAST_REACH_RATE_MILK
         , 0 AS SALES_PAST_REACH_RATE_MILK_V
         , NULL AS SALES_PAST_REACH_RATE_MILK_F
         , SUM(CASE WHEN DIVISION_ID=@DIVISION_ID_LEIS THEN SALES_AMT_PAST_MONTH ELSE 0 END) AS SALES_AMT_PAST_MONTH_LEIS
         , ROUND(SUM(CASE WHEN DIVISION_ID=@DIVISION_ID_LEIS THEN SALES_AMT_PAST_MONTH ELSE 0 END)/1000,0) AS SALES_AMT_PAST_MONTH_LEIS_V
         , SUM(CASE WHEN DIVISION_ID=@DIVISION_ID_LEIS THEN BILLING ELSE 0 END) AS SALES_AMT_REACH_LEIS
         , ROUND(SUM(CASE WHEN DIVISION_ID=@DIVISION_ID_LEIS THEN BILLING ELSE 0 END)/1000,0) AS SALES_AMT_REACH_LEIS_V
         , 0 AS SALES_PAST_REACH_RATE_LEIS
         , 0 AS SALES_PAST_REACH_RATE_LEIS_V
         , NULL AS SALES_PAST_REACH_RATE_LEIS_F
    FROM DMMDL.DC0021_SALES_DIST_PROD_DATE_CUM
    WHERE DATA_DATE=VAR_DATA_DATE AND RPT_YMD=VAR_DATA_DATE
    GROUP BY DIVISION_ID
    ;

    --UPDATE2
    --標準進度
    UPDATE APDC.DC0021_RPT0103_DIVISION A
    JOIN(SELECT ROUND(WORK_RATIO,3) AS WORK_RATIO
         FROM DMMDL.DC0021_WORK_RATIO_CUM
         WHERE DATA_DATE=VAR_DATA_DATE AND RPT_YMD=VAR_DATA_DATE) B
    ON A.DATA_DATE=B.DATA_DATE AND A.RPT_YMD=B.RPT_YMD
    SET A.WORK_RATIO=B.WORK_RATIO
    WHERE A.DATA_DATE=VAR_DATA_DATE AND A.RPT_YMD=VAR_DATA_DATE
    ;

    --UPDATE3
    --乳飲,休閒事業部同期達成率
    UPDATE APDC.DC0021_RPT0103_DIVISION A
    JOIN(SELECT DIVISIONC_ID
              , DIVISION_ID
              , ROUND(SALES_AMT_REACH_MILK/SALES_AMT_PAST_MONTH_MILK,3) AS SALES_PAST_REACH_RATE_MILK
              , (CASE WHEN (SALES_AMT_REACH_MILK/SALES_AMT_PAST_MONTH_MILK)<0 THEN 0.00 ELSE ROUND(SALES_AMT_REACH_MILK/SALES_AMT_PAST_MONTH_MILK,3) END) AS SALES_PAST_REACH_RATE_MILK_V
              , (CASE WHEN (SALES_AMT_REACH_MILK/SALES_AMT_PAST_MONTH_MILK)<WORK_RATIO THEN 'A'
                      WHEN SALES_AMT_PAST_MONTH_MILK<=0 THEN 'B' ELSE NULL END) AS SALES_PAST_REACH_RATE_MILK_F
              , ROUND(SALES_AMT_REACH_LEIS/SALES_AMT_PAST_MONTH_LEIS,3) AS SALES_PAST_REACH_RATE_LEIS
              , (CASE WHEN (SALES_AMT_REACH_LEIS/SALES_AMT_PAST_MONTH_LEIS)<0 THEN 0.00 ELSE ROUND(SALES_AMT_REACH_LEIS/SALES_AMT_PAST_MONTH_LEIS,3) END) AS SALES_PAST_REACH_RATE_LEIS_V
              , (CASE WHEN (SALES_AMT_REACH_LEIS/SALES_AMT_PAST_MONTH_LEIS)<WORK_RATIO THEN 'A'
                      WHEN SALES_AMT_PAST_MONTH_LEIS<=0 THEN 'B' ELSE NULL END) AS SALES_PAST_REACH_RATE_LEIS_F
         FROM APDC.DC0021_RPT0103_DIVISION
         WHERE DATA_DATE=VAR_DATA_DATE AND RPT_YMD=VAR_DATA_DATE
         GROUP BY DIVISIONC_ID
                , DIVISION_ID
    ON A.DATA_DATE=B.DATA_DATE AND A.RPT_YMD=B.RPT_YMD AND A.DIVISIONC_ID=B.DIVISIONC_ID AND A.DIVISION_ID=B.DIVISION_ID
    SET A.SALES_PAST_REACH_RATE_MILK=B.SALES_PAST_REACH_RATE_MILK
      , A.SALES_PAST_REACH_RATE_MILK_V=B.SALES_PAST_REACH_RATE_MILK_V
      , A.SALES_PAST_REACH_RATE_MILK_F=B.SALES_PAST_REACH_RATE_MILK_F
      , A.SALES_PAST_REACH_RATE_LEIS=B.SALES_PAST_REACH_RATE_LEIS
      , A.SALES_PAST_REACH_RATE_LEIS_V=B.SALES_PAST_REACH_RATE_LEIS_V
      , A.SALES_PAST_REACH_RATE_LEIS_F=B.SALES_PAST_REACH_RATE_LEIS_F
    WHERE A.DATA_DATE=VAR_DATA_DATE AND A.RPT_YMD=VAR_DATA_DATE
    ;


    SET VAR_SP_RESULT='Y';
    COMMIT;
END
;