DROP PROCEDURE IF EXISTS APDC.SP_DAT_30122_DC0021_RPT0105_DIVISION;

CREATE PROCEDURE APDC.SP_DAT_30122_DC0021_RPT0105_DIVISION (
    VAR_EDI_DATE CHAR(8), VAR_EDI_TIME CHAR(9), VAR_DATA_DATE CHAR(8)
  , OUT VAR_SP_RESULT CHAR(1)
)
BEGIN

    SET @RPT_YMD_FY_REACH_BEGIN=APDC.FN_GET_FY_YMD(VAR_DATA_DATE,0,1,'N') COLLATE utf8_unicode_ci;
    SET @RPT_YMD_FY_REACH_END=APDC.FN_GET_FY_YMD(VAR_DATA_DATE,0,12,'Y') COLLATE utf8_unicode_ci;
    SET @RPT_YMD_FY_PAST_BEGIN=APDC.FN_GET_FY_YM(VAR_DATA_DATE,-1,1,'N') COLLATE utf8_unicode_ci;
    SET @RPT_YMD_FY_PAST_END=APDC.FN_GET_FY_YM(VAR_DATA_DATE,-1,12,'Y') COLLATE utf8_unicode_ci;
    SET @RPT_YMD_CUM_REACH_BEGIN=APDC.FN_GET_FY_YMD(VAR_DATA_DATE,1,1,'N') COLLATE utf8_unicode_ci;
    SET @RPT_YMD_CUM_REACH_LAST=APDC.FN_GET_YMD(VAR_DATA_DATE,0,-1,0,'Y') COLLATE utf8_unicode_ci;
    SET @RPT_YMD_CUM_POST_BEGIN=APDC.FN_GET_FY_YMD(VAR_DATA_DATE,0,1,'N') COLLATE utf8_unicode_ci;
    SET @RPT_YMD_CUM_POST_LAST=APDC.FN_GET_YMD(VAR_DATA_DATE,-1,-1,0,'Y') COLLATE utf8_unicode_ci;
    SET @RPT_YMD_17=17 COLLATE utf8_unicode_ci;
    SET @RPT_YMD_END=APDC.FN_GET_YMD(VAR_DATA_DATE,0,0,0,'Y') COLLATE utf8_unicode_ci;
    SET @RPT_YMD_NEXT_PAST=SUBSTRING(APDC.FN_GET_YMD(VAR_DATA_DATE,-1,1,0,'Y'),1,6) COLLATE utf8_unicode_ci;
    SET @RPT_YMD_NEXT_FCST=SUBSTRING(APDC.FN_GET_YMD(VAR_DATA_DATE,0,1,0,'Y'),1,6) COLLATE utf8_unicode_ci;
    SET @RPT_YMD_PAST=SUBSTRING(APDC.FN_GET_YMD(VAR_DATA_DATE,-1,0,0,'Y'),1,6) COLLATE utf8_unicode_ci;
    
    --INSERT1
    --FY1_SALES_AMT   Y-1財年達成
    --FY1_SALES_AMT_V Y-1財年達成(畫面數值)
    --FY1_SALES_AMT_PAST_MONTH   Y-1財年全月同期
    --FY1_SALES_AMT_PAST_MONTH_V Y-1財年全月同期(畫面數值)
    --FYBG_SALES_AMT_REACH   4-(M-1)月達成
    --FYBG_SALES_AMT_REACH_V 4-(M-1)月達成(畫面數值)
    --FYBG_SALES_AMT_PAST_MONTH   4-(M-1)月同期
    --FYBG_SALES_AMT_PAST_MONTH_V 4-(M-1)月同期(畫面數值)
    --SALES_AMT_REACH_MONTH   全月達成
    --SALES_AMT_REACH_MONTH_V 全月達成(畫面數值)
    --SALES_AMT_PAST_MONTH   全月同期
    --SALES_AMT_PAST_MONTH_V 全月同期(畫面數值)
    --SALES_AMT_PAST_PROG   當日進度同期
    --SALES_AMT_PAST_PROG_V 當日進度同期(畫面數值)
    --SALES_AMT_PAST_PROG_F 當日進度同期(畫面格式)
    --FCST_AMT   全月預估
    --FCST_AMT_V 全月預估(畫面數值)
    --NEXT_SALES_AMT_PAST_MONTH   M+1月全月同期
    --NEXT_SALES_AMT_PAST_MONTH_V M+1月全月同期(畫面數值)
    --NEXT_SALES_AMT_PAST_MONTH_F M+1月全月同期(畫面格式)
    --NEXT_FCST_AMT   M+1月預估
    --NEXT_FCST_AMT_V M+1月預估(畫面數值)
    --NEXT_FCST_AMT_F M+1月預估(畫面格式)
    INSERT INTO APDC.DC0021_RPT0105_DIVISION
    SELECT VAR_DATA_DATE AS DATA_DATE
         , VAR_DATA_DATE AS RPT_YMD
         , 0 AS WORK_RATIO
         , 'DIVISIONC_ID' AS DIVISIONC_ID
         , 'DIVISIONC_NM' AS DIVISIONC_NM
         , DIVISION_ID
         , NULL AS DIVISION_NM
         , SUM(CASE WHEN RPT_YMD>=@RPT_YMD_FY_REACH_BEGIN AND RPT_YMD<=@RPT_YMD_FY_REACH_END THEN SALES_AMT ELSE 0 END) AS FY1_SALES_AMT
         , ROUND(SUM(CASE WHEN RPT_YMD>=@RPT_YMD_FY_REACH_BEGIN AND RPT_YMD<=@RPT_YMD_FY_REACH_END THEN SALES_AMT ELSE 0 END)/1000,0) AS FY1_SALES_AMT_V
         , SUM(CASE WHEN RPT_YM>=@RPT_YMD_FY_PAST_BEGIN AND RPT_YMD<=@RPT_YMD_FY_PAST_END THEN SALES_AMT_PAST_MONTH ELSE 0 END) AS FY1_SALES_AMT_PAST_MONTH
         , ROUND(SUM(CASE WHEN RPT_YMD>=@RPT_YMD_FY_PAST_BEGIN AND RPT_YMD<=@RPT_YMD_FY_PAST_END THEN SALES_AMT_PAST_MONTH ELSE 0 END)/1000,0) AS FY1_SALES_AMT_PAST_MONTH_V
         , 0 AS FY1_PAST_GROWTH_RATE
         , NULL AS FY1_PAST_GROWTH_RATE_F
         , SUM(CASE WHEN RPT_YMD>=@RPT_YMD_CUM_REACH_BEGIN AND RPT_YMD<=@RPT_YMD_CUM_REACH_LAST THEN SALES_AMT ELSE 0 END) AS FYBG_SALES_AMT_REACH
         , ROUND(SUM(CASE WHEN RPT_YMD>=@RPT_YMD_CUM_REACH_BEGIN AND RPT_YMD<=@RPT_YMD_CUM_REACH_LAST THEN SALES_AMT ELSE 0 END)/1000,0) AS FYBG_SALES_AMT_REACH_V
         , SUM(CASE WHEN RPT_YMD>=@RPT_YMD_CUM_POST_BEGIN AND RPT_YMD<=@RPT_YMD_CUM_POST_END THEN SALES_AMT_PAST_MONTH ELSE 0 END) AS FYBG_SALES_AMT_PAST_MONTH
         , ROUND(SUM(CASE WHEN RPT_YMD>=@RPT_YMD_CUM_POST_BEGIN AND RPT_YMD<=@RPT_YMD_CUM_POST_END THEN SALES_AMT_PAST_MONTH ELSE 0 END)/1000,0) AS FYBG_SALES_AMT_PAST_MONTH_V
         , 0 AS FYBG_PAST_GROWTH_RATE
         , NULL AS FYBG_PAST_GROWTH_RATE_F
         , SUM(CASE WHEN RPT_YMD=VAR_DATA_DATE THEN BILLING ELSE 0 END) AS SALES_AMT_REACH_MONTH
         , ROUND(SUM(CASE WHEN RPT_YMD=VAR_DATA_DATE THEN BILLING ELSE 0 END)/1000,0) AS SALES_AMT_REACH_MONTH_V
         , 0 AS SALES_AMT_REACH_MONTH_MAX
         , 0 AS SALES_AMT_REACH_MONTH_DISTR
         , SUM(CASE WHEN RPT_YMD=VAR_DATA_DATE THEN SALES_AMT_PAST_MONTH ELSE 0 END) AS SALES_AMT_PAST_MONTH
         , ROUND(SUM(CASE WHEN RPT_YMD=VAR_DATA_DATE THEN SALES_AMT_PAST_MONTH ELSE 0 END)/1000,0) AS SALES_AMT_PAST_MONTH_V
         , 0 AS PAST_MONTH_REACH_RATE
         , 0 AS FY_CUM_PAST_MONTH_REACH_RATE_V
         , NULL AS PAST_MONTH_REACH_RATE_F
         , 0 AS PAST_MONTH_REACH_RATE_TOTAL
         , 0 AS PAST_MONTH_GROWTH_RATE
         , NULL AS PAST_MONTH_GROWTH_RATE_F
         , SUM(CASE WHEN RPT_YMD=VAR_DATA_DATE THEN SALES_AMT_PAST_MONTH_PROG ELSE 0 END) AS SALES_AMT_PAST_PROG
         , ROUND(SUM(CASE WHEN RPT_YMD=VAR_DATA_DATE THEN SALES_AMT_PAST_MONTH_PROG ELSE 0 END)/1000,0) AS SALES_AMT_PAST_PROG_V
         , (CASE WHEN PRT_YMD=@RPT_YMD_END THEN 'Z' ELSE NULL END) AS SALES_AMT_PAST_PROG_F
         , 0 AS PAST_PROG_GROWTH_RATE
         , NULL AS PAST_PROG_GROWTH_RATE_F
         , 0 AS FCST_AMT
         , 0 AS FCST_AMT_V
         , 0 AS FCST_REACH_RATE
         , NULL AS FCST_REACH_RATE_F
         , 0 AS FCST_REACH_RATE_TOTAL
         , 0 AS FY_CUM_SALES
         , 0 AS FY_CUM_SALES_V
         , SUM(CASE WHEN RPT_YMD>=@RPT_YMD_CUM_POST_BEGIN AND RPT_YMD<=VAR_DATA_DATE THEN SALES_AMT_PAST_MONTH ELSE 0 END) AS FY_CUM_SALES_PAST_MONTH
         , ROUND(SUM(CASE WHEN RPT_YMD>=@RPT_YMD_CUM_POST_BEGIN AND RPT_YMD<=VAR_DATA_DATE THEN SALES_AMT_PAST_MONTH ELSE 0 END)/1000,0) AS FY_CUM_SALES_PAST_MONTH_V
         , 0 AS FY_CUM_SALES_PAST_PROG
         , 0 AS FY_CUM_SALES_PAST_PROG_V
         , NULL AS FY_CUM_SALES_PAST_PROG_F
         , 0 AS FY_CUM_SALES_PAST_PROG_RATIO
         , NULL AS FY_CUM_SALES_PAST_PROG_RATIO_F
         , 0 AS FY_CUM_PAST_MONTH_REACH_RATE
         , 0 AS FY_CUM_PAST_MONTH_REACH_RATE_V
         , NULL AS FY_CUM_PAST_MONTH_REACH_RATE_F
         , 0 AS FY_CUM_PAST_MONTH_REACH_RATE_TOTAL
         , SUM(CASE WHEN RPT_YMD=@RPT_YMD_NEXT_PAST THEN SALES_AMT_PAST_MONTH ELSE 0 END) AS NEXT_SALES_AMT_PAST_MONTH
         , ROUND(SUM(CASE WHEN RPT_YMD=@RPT_YMD_NEXT_PAST THEN SALES_AMT_PAST_MONTH ELSE 0 END)/1000,0) AS NEXT_SALES_AMT_PAST_MONTH_V
         , (CASE WHEN RIGHT(RPT_YMD=VAR_DATA_DATE,2)<@RPT_YMD_17 THEN 'Z' ELSE NULL END) AS NEXT_SALES_AMT_PAST_MONTH_F
         , 0 AS NEXT_FCST_AMT
         , 0 AS NEXT_FCST_AMT_V
         , NULL AS NEXT_FCST_AMT_F
         , 0 AS FCST_GROWTH_RATE
         , NULL AS FCST_GROWTH_RATE_F
    FROM DMMDL.DC0021_SALES_DIST_PROD_DATE_CUM
    WHERE DATA_DATE=VAR_DATA_DATE
    GROUP BY DIVISION_ID
    ;
    
    --UPDATE2
    --WORK_RATIO 標準進度
    UPDATE APDC.DC0021_RPT0105_DIVISION A
    JOIN(SELECT ROUND(WORK_RATIO,3) AS WORK_RATIO
         FROM DMMDL.DC0021_WORK_RATIO_CUM
         WHERE DATA_DATE=VAR_DATA_DATE AND RPT_YMD=VAR_DATA_DATE) B
    ON A.DATA_DATE=B.DATA_DATE AND A.RPT_YMD=B.RPT_YMD
    SET A.WORK_RATIO=B.WORK_RATIO
    WHERE A.DATA_DATE=VAR_DATA_DATE AND A.RPT_YMD=VAR_DATA_DATE
    ;

    --UPDATE3
    --預估
    UPDATE APDC.DC0021_RPT0105_DIVISION A
    JOIN(SELECT DIVISION
              , SUM(CASE WHEN RPT_YMD=VAR_DATA_DATE THEN FCST_AMT ELSE 0 END) AS FCST_AMT
              , ROUND(SUM(CASE WHEN RPT_YMD=VAR_DATA_DATE THEN FCST_AMT ELSE 0 END)/1000,0) AS FCST_AMT_V
              , SUM(CASE WHEN RPT_YMD=@RPT_YMD_NEXT_FCST THEN FCST_AMT ELSE 0 END) AS NEXT_FCST_AMT
              , ROUND(SUM(CASE WHEN RPT_YMD=@RPT_YMD_NEXT_FCST THEN FCST_AMT ELSE 0 END)/1000,0) AS NEXT_FCST_AMT_V
              , (CASE WHEN RIGHT(RPT_YMD=VAR_DATA_DATE,2)<@RPT_YMD_17 THEN 'Z' ELSE NULL END) AS NEXT_FCST_AMT_F
         FROM DMMDL.DC0021_FCST_AMT_CUM
         WHERE DATA_DATE=VAR_DATA_DATE
         GROUP BY DIVISION) B
    ON A.DATA_DATE=B.DATA_DATE AND A.RPT_YMD=B.RPT_YMD
    SET A.FCST_AMT=B.FCST_AMT
      , A.FCST_AMT_V=B.FCST_AMT_V
      , A.NEXT_FCST_AMT=B.NEXT_FCST_AMT
      , A.NEXT_FCST_AMT_V=B.NEXT_FCST_AMT_V
      , A.NEXT_FCST_AMT_F=B.NEXT_FCST_AMT_F
    WHERE A.DATA_DATE=VAR_DATA_DATE
    ;

    --UPDATE4
    --PAST_MONTH_REACH_RATE_TOTAL 當月同期達成率(總計)
    --FCST_REACH_RATE_TOTAL 預估達成率(總計)
    --FY_CUM_PAST_MONTH_REACH_RATE_TOTAL 財年累計全月同期達成率(總計)
    UPDATE APDC.DC0021_RPT0105_DIVISION A  
    JOIN(SELECT PAST_MONTH_REACH_RATE AS PAST_MONTH_REACH_RATE_TOTAL
              , FCST_REACH_RATE AS FCST_REACH_RATE_TOTAL
              , FY_CUM_PAST_MONTH_REACH_RATE AS FY_CUM_PAST_MONTH_REACH_RATE_TOTAL
         FROM APDC.DC0021_RPT0105_TOTAL
         WHERE DATA_DATE=VAR_DATA_DATE AND RPT_YMD=VAR_DATA_DATE) B
    ON A.DATA_DATE=B.DATA_DATE AND A.RPT_YMD=B.RPT_YMD
    SET A.PAST_MONTH_REACH_RATE_TOTAL=B.PAST_MONTH_REACH_RATE_TOTAL
      , A.FCST_REACH_RATE_TOTAL=B.FCST_REACH_RATE_TOTAL
      , A.FY_CUM_PAST_MONTH_REACH_RATE_TOTAL=B.FY_CUM_PAST_MONTH_REACH_RATE_TOTAL
    WHERE A.DATA_DATE=VAR_DATA_DATE AND A.RPT_YMD=VAR_DATA_DATE
    ;
    
    --UPDATE5
    --SALES_AMT_REACH_MONTH_MAX 全月達成-最大
    UPDATE APDC.DC0021_RPT0105_DIVISION A
    JOIN(SELECT MAX(SALES_AMT_REACH_MONTH) AS SALES_AMT_REACH_MONTH_MAX
         FROM APDC.DC0021_RPT0105_SALES_AMT_REACH_MONTH
         WHERE DATA_DATE=VAR_DATA_DATE AND RPT_YMD=VAR_DATA_DATE) B
    ON A.DATA_DATE=B.DATA_DATE AND A.RPT_YMD=B.RPT_YMD
    SET A.SALES_AMT_REACH_MONTH_MAX=B.SALES_AMT_REACH_MONTH_MAX
    WHERE A.DATA_DATE=VAR_DATA_DATE AND A.RPT_YMD=VAR_DATA_DATE
    ;

    --UPDATE6
    --FY1_PAST_GROWTH_RATE   Y-1財年同期成長率
    --FY1_PAST_GROWTH_RATE_F Y-1財年同期成長率(畫面格式)
    --FYBG_PAST_GROWTH_RATE   4-(M-1)月同期成長率
    --FYBG_PAST_GROWTH_RATE_F 4-(M-1)月同期成長率(畫面格式)
    --PAST_MONTH_REACH_RATE     當月同期達成率
    --PAST_MONTH_REACH_RATE_V   當月同期達成率(畫面數值)
    --PAST_MONTH_REACH_RATE_F   當月同期達成率(畫面格式)
    --PAST_MONTH_GROWTH_RATE    當月同期成長率
    --PAST_MONTH_GROWTH_RATE_F  當月同期成長率(畫面格式)
    --PAST_PROG_GROWTH_RATE     當日同期成長率
    --PAST_PROG_GROWTH_RATE_F   當日同期成長率(畫面格式)
    --FCST_REACH_RATE           預估達成率
    --FCST_REACH_RATE_F         預估達成率(畫面格式)
    --FY_CUM_SALES                   財年累計達成
    --FY_CUM_SALES_PAST_MONTH        財年累計全月同期
    --FY_CUM_SALES_PAST_MONTH_F      財年累計全月同期(畫面格式)
    --FY_CUM_SALES_PAST_PROG         財年累計進度同期
    --FCST_GROWTH_RATE   預估成長率
    --FCST_GROWTH_RATE_F 預估成長率(畫面格式)
    --SALES_AMT_REACH_MONTH_DISTR 全月達成-分佈
    UPDATE APDC.DC0021_RPT0105_DIVISION A
    JOIN(SELECT DIVISIONC_ID
              , DIVISION_ID
              , (CASE WHEN RPT_YMD=VAR_DATA_DATE THEN ROUND((FY1_SALES_AMT/FY1_SALES_AMT_PAST_MONTH)-1,3) ELSE 0 END) AS FY1_PAST_GROWTH_RATE
              , (CASE WHEN ROUND((FY1_SALES_AMT/FY1_SALES_AMT_PAST_MONTH)-1,3)<0 THEN 'A'
                      WHEN FY1_SALES_AMT_PAST_MONTH<=0 THEN 'B' ELSE NULL END) AS FY1_PAST_GROWTH_RATE_F
              , (CASE WHEN RPT_YMD=VAR_DATA_DATE THEN ROUND((SALE_AMT/SALES_AMT_PAST_MONTH)-1,3) ELSE 0 END) AS FYBG_PAST_GROWTH_RATE
              , (CASE WHEN ROUND((SALE_AMT/SALES_AMT_PAST_MONTH)-1,3)<0 THEN 'A'
                      WHEN SALES_AMT_PAST_MONTH<=0 THEN 'B' ELSE NULL END) AS FYBG_PAST_GROWTH_RATE_F
              , (CASE WHEN RPT_YMD=VAR_DATA_DATE THEN ROUND(SALES_AMT_REACH_MONTH/SALES_AMT_PAST_MONTH,3) ELSE 0 END) AS PAST_MONTH_REACH_RATE
              , (CASE WHEN RPT_YMD=VAR_DATA_DATE THEN ROUND(SALES_AMT_REACH_MONTH/SALES_AMT_PAST_MONTH,3)
                      WHEN ROUND(SALES_AMT_REACH_MONTH/SALES_AMT_PAST_MONTH,3)<0 THEN 0.00 ELSE ROUND(SALES_AMT_REACH_MONTH/SALES_AMT_PAST_MONTH,3) END) AS PAST_MONTH_REACH_RATE_V
              , (CASE WHEN RPT_YMD=@RPT_YMD_END THEN 'Z'
                      WHEN ROUND(SALES_AMT_REACH_MONTH/SALES_AMT_PAST_MONTH,3)<PAST_MONTH_REACH_RATE_TOTAL THEN 'A'
                      WHEN SALES_AMT_PAST_MONTH<=0 THEN 'B' ELSE NULL END) AS PAST_MONTH_REACH_RATE_F
              , (CASE WHEN RPT_YMD=VAR_DATA_DATE THEN ROUND((SALES_AMT_REACH_MONTH/SALES_AMT_PAST_MONTH)-1,3) ELSE 0 END) AS PAST_MONTH_GROWTH_RATE
              , (CASE WHEN RPT_YMD<>@RPT_YMD_END THEN 'Z'
                      WHEN ROUND((SALES_AMT_REACH_MONTH/SALES_AMT_PAST_MONTH)-1,3)<0 THEN 'A'
                      WHEN SALES_AMT_PAST_MONTH<=0 THEN 'B' ELSE NULL END) AS PAST_MONTH_GROWTH_RATE_F
              , (CASE WHEN RPT_YMD=VAR_DATA_DATE THEN ROUND(SALES_AMT_REACH_MONTH/SALES_AMT_PAST_PROG,3) ELSE 0 END) AS PAST_PROG_GROWTH_RATE
              , (CASE WHEN RPT_YMD=@RPT_YMD_END THEN 'Z'
                      WHEN ROUND(SALES_AMT_REACH_MONTH/SALES_AMT_PAST_PROG,3)<0 THEN 'A'
                      WHEN SALES_AMT_PAST_PROG<=0 THEN 'B' ELSE NULL END) AS PAST_PROG_GROWTH_RATE_F
              , (CASE WHEN RPT_YMD=VAR_DATA_DATE THEN ROUND(SALES_AMT_REACH_MONTH/FCST_AMT,3) ELSE 0 END) AS FCST_REACH_RATE
              , (CASE WHEN ROUND(SALES_AMT_REACH_MONTH/FCST_AMT,3)<FCST_REACH_RATE_TOTAL THEN 'A' ELSE NULL END) AS FCST_REACH_RATE_F 
              , (CASE WHEN RPT_YMD=VAR_DATA_DATE THEN (FYBG_SALES_AMT_REACH+SALES_AMT_REACH_MONTH) ELSE 0 END) AS FY_CUM_SALES
              , (CASE WHEN RPT_YMD=VAR_DATA_DATE THEN ROUND((FYBG_SALES_AMT_REACH+SALES_AMT_REACH_MONTH)/1000,0) ELSE 0 END) AS FY_CUM_SALES_V
              , (CASE WHEN RPT_YMD=VAR_DATA_DATE THEN (FYBG_SALES_AMT_PAST_MONTH+SALES_AMT_PAST_PROG) ELSE 0 END) AS FY_CUM_SALES_PAST_PROG
              , (CASE WHEN RPT_YMD=VAR_DATA_DATE THEN ROUND((FYBG_SALES_AMT_PAST_MONTH+SALES_AMT_PAST_PROG)/1000,0) ELSE 0 END) AS FY_CUM_SALES_PAST_PROG_V
              , (CASE WHEN RPT_YMD=@RPT_YMD_END THEN 'Z' ELSE NULL END) AS FY_CUM_SALES_PAST_PROG_F
              , (CASE WHEN RPT_YMD=VAR_DATA_DATE THEN ROUND(NEXT_FCST_AMT/NEXT_SALES_AMT_PAST_MONTH,3) ELSE 0 END) AS FCST_GROWTH_RATE
              , (CASE WHEN RIGHT(RPT_YMD=VAR_DATA_DATE,2)<@RPT_YMD_17 THEN 'Z'
                      WHEN ROUND(NEXT_FCST_AMT/NEXT_SALES_AMT_PAST_MONTH,3)<0 THEN 'A' ELSE NULL END) AS FCST_GROWTH_RATE_F
              , (CASE WHEN RPT_YMD=VAR_DATA_DATE THEN ROUND(SALES_AMT_REACH_MONTH/SALES_AMT_REACH_MONTH_MAX,3) ELSE 0 END) AS SALES_AMT_REACH_MONTH_DISTR
         FROM APDC.DC0021_RPT0105_DIVISION
         WHERE DATA_DATE=VAR_DATA_DATE
         GROUP BY DIVISIONC_ID
                , DIVISION_ID) B
    ON A.DATA_DATE=B.DATA_DATE AND A.RPT_YMD=B.RPT_YMD AND A.DIVISIONC_ID=B.DIVISIONC_ID AND A.DIVISION_ID=B.DIVISION_ID
    SET A.FY1_PAST_GROWTH_RATE=B.FY1_PAST_GROWTH_RATE
      , A.FY1_PAST_GROWTH_RATE_F=B.FY1_PAST_GROWTH_RATE_F
      , A.FYBG_PAST_GROWTH_RATE=B.FYBG_PAST_GROWTH_RATE
      , A.FYBG_PAST_GROWTH_RATE_F=B.FYBG_PAST_GROWTH_RATE_F
      , A.PAST_MONTH_REACH_RATE=B.PAST_MONTH_REACH_RATE
      , A.PAST_MONTH_REACH_RATE_V=B.PAST_MONTH_REACH_RATE_V
      , A.PAST_MONTH_REACH_RATE_F=B.PAST_MONTH_REACH_RATE_F
      , A.PAST_MONTH_GROWTH_RATE=B.PAST_MONTH_GROWTH_RATE
      , A.PAST_MONTH_GROWTH_RATE_F=B.PAST_MONTH_GROWTH_RATE_F
      , A.PAST_PROG_GROWTH_RATE=B.PAST_PROG_GROWTH_RATE
      , A.PAST_PROG_GROWTH_RATE_F=B.PAST_PROG_GROWTH_RATE_F
      , A.FCST_REACH_RATE=B.FCST_REACH_RATE
      , A.FCST_REACH_RATE_F=B.FCST_REACH_RATE_F
      , A.FY_CUM_SALES=B.FY_CUM_SALES
      , A.FY_CUM_SALES_V=B.FY_CUM_SALES_V
      , A.FY_CUM_SALES_PAST_PROG=B.FY_CUM_SALES_PAST_PROG
      , A.FY_CUM_SALES_PAST_PROG_V=B.FY_CUM_SALES_PAST_PROG_V
      , A.FY_CUM_SALES_PAST_PROG_F=B.FY_CUM_SALES_PAST_PROG_F
      , A.FCST_GROWTH_RATE=B.FCST_GROWTH_RATE
      , A.FCST_GROWTH_RATE_F=B.FCST_GROWTH_RATE_F
      , A.SALES_AMT_REACH_MONTH_DISTR=B.SALES_AMT_REACH_MONTH_DISTR
    WHERE A.DATA_DATE=VAR_DATA_DATE AND A.RPT_YMD=VAR_DATA_DATE
    ;

    --UPDATE7
    --FY_CUM_SALES_PAST_PROG_RATIO   財年累計進度同期比
    --FY_CUM_SALES_PAST_PROG_RATIO_F 財年累計進度同期比(畫面格式)
    --FY_CUM_PAST_MONTH_REACH_RATE   財年累計全月同期達成率
    --FY_CUM_PAST_MONTH_REACH_RATE_V 財年累計全月同期達成率(畫面數值)
    --FY_CUM_PAST_MONTH_REACH_RATE_F 財年累計全月同期達成率(畫面格式)
    UPDATE APDC.DC0021_RPT0105_DIVISION A
    JOIN(SELECT DIVISIONC_ID
              , DIVISION_ID
              , (CASE WHEN RPT_YMD=VAR_DATA_DATE THEN ROUND((FY_CUM_SALES/FY_CUM_SALES_PAST_PROG)-1,3) ELSE 0 END) AS FY_CUM_SALES_PAST_PROG_RATIO
              , (CASE WHEN ROUND((FY_CUM_SALES/FY_CUM_SALES_PAST_PROG)-1,3)<0 THEN 'A' ELSE NULL END) AS FY_CUM_SALES_PAST_PROG_RATIO_F
              , (CASE WHEN RPT_YMD=VAR_DATA_DATE THEN ROUND(FY_CUM_SALES/FY_CUM_SALES_PAST_MONTH,3) ELSE 0 END) AS FY_CUM_PAST_MONTH_REACH_RATE
              , (CASE WHEN RPT_YMD=VAR_DATA_DATE THEN ROUND(FY_CUM_SALES/FY_CUM_SALES_PAST_MONTH,3)
                      WHEN ROUND(FY_CUM_SALES/FY_CUM_SALES_PAST_MONTH,3)<0 THEN 0.00 ELSE ROUND(FY_CUM_SALES/FY_CUM_SALES_PAST_MONTH,3) END) AS FY_CUM_PAST_MONTH_REACH_RATE_V
              , (CASE WHEN RPT_YMD=@RPT_YMD_END THEN 'Z'
                      WHEN ROUND(FY_CUM_SALES/FY_CUM_SALES_PAST_MONTH,3)<FY_CUM_PAST_MONTH_REACH_RATE_TOTAL THEN 'A' ELSE NULL END) AS FY_CUM_PAST_MONTH_REACH_RATE_F
         FROM APDC.DC0021_RPT0105_DIVISION
         WHERE DATA_DATE=VAR_DATA_DATE
         GROUP BY DIVISIONC_ID
                , DIVISION_ID) B
    ON A.DATA_DATE=B.DATA_DATE AND A.RPT_YMD=B.RPT_YMD AND A.DIVISIONC_ID=B.DIVISIONC_ID AND A.DIVISION_ID=B.DIVISION_ID
    SET A.FY_CUM_SALES_PAST_PROG_RATIO=B.FY_CUM_SALES_PAST_PROG_RATIO
      , A.FY_CUM_SALES_PAST_PROG_RATIO_F=B.FY_CUM_SALES_PAST_PROG_RATIO_F
      , A.FY_CUM_PAST_MONTH_REACH_RATE=B.FY_CUM_PAST_MONTH_REACH_RATE
      , A.FY_CUM_PAST_MONTH_REACH_RATE_V=B.FY_CUM_PAST_MONTH_REACH_RATE_V
      , A.FY_CUM_PAST_MONTH_REACH_RATE_F=B.FY_CUM_PAST_MONTH_REACH_RATE_F
    WHERE A.DATA_DATE=VAR_DATA_DATE AND A.RPT_YMD=VAR_DATA_DATE

    SET VAR_SP_RESULT='Y';
    COMMIT;
END
;