DROP PROCEDURE IF EXISTS APDC.SP_DAT_30110_DC0021_RPT0102_COM;

CREATE PROCEDURE APDC.SP_DAT_30110_DC0021_RPT0102_COM (
    VAR_EDI_DATE CHAR(8), VAR_EDI_TIME CHAR(9), VAR_DATA_DATE CHAR(8)
  , OUT VAR_SP_RESULT CHAR(1)
)
BEGIN
    

    SET @DIVISION_ID_MILK='乳飲' COLLATE utf8_unicode_ci;
    SET @DIVISION_ID_LEIS='休閒' COLLATE utf8_unicode_ci;
    SET @DIVISION_ID_BEV1N='飲一北' COLLATE utf8_unicode_ci;
    SET @DIVISION_ID_BEV1S='飲一南' COLLATE utf8_unicode_ci;
    SET @DIVISION_ID_BEV2='飲二' COLLATE utf8_unicode_ci;
    SET @DIVISION_ID_ICE='冰品' COLLATE utf8_unicode_ci;
    SET @DIVISION_ID_MAT='母嬰' COLLATE utf8_unicode_ci;
    SET @DIVISION_ID_CDCN='冷鏈' COLLATE utf8_unicode_ci;
    SET @DIVISION_ID_BULK='開心散裝' COLLATE utf8_unicode_ci;
    SET @DIVISIOND_ID_WL='旺禮個體' COLLATE utf8_unicode_ci;
    SET @DIVISIOND_ID_WLALL='旺禮禮包' COLLATE utf8_unicode_ci;
    SET @DIVISION_ID_KA='現渠' COLLATE utf8_unicode_ci;
    SET @DIVISION_ID_EC='電子商務' COLLATE utf8_unicode_ci;

    --INSERT1
    --SALES_AMT_REACH_D1 達成截至D1
    --SALES_AMT_PAST_MONTH 全月同期
    --PAST_PROG_REACH_RATE 全月同期達成率
    --SALES_AMT_REACH_D1_V 達成截至D1(畫面數值)
    --SALES_AMT_PAST_MONTH_V 全月同期(畫面數值)
    --PAST_PROG_REACH_RATE_V 全月同期達成率(畫面數值)
    --RANK_PAST 同期排名
    --SALES_PAST_REACH_RATE 各事業部同期達成率
    --SALES_PAST_REACH_RATE_V 各事業部同期達成率(畫面數值)
    INSERT INTO APDC.DC0021_RPT0102_COM
    SELECT VAR_DATA_DATE AS DATA_DATE
         , VAR_DATA_DATE AS RPT_YMD
         , 0 AS WORK_RATIO
         , DISTRICT15_ID
         , NULL AS DISTRICT15_NM
         , COM_ID
         , NULL AS COM_NM
         , 'MKT_DIR_ID' AS MKT_DIR_ID
         , 0 AS MKT_SHARE
         , 0 AS POPU
         , 0 AS POPU_V
         , SUM(BILLING) AS SALES_AMT_REACH_D1
         , ROUND(SUM(BILLING)/1000,0) AS SALES_AMT_REACH_D1_V
         , 0 AS SALES_AMT_REACH_D1_MAX
         , 0 AS SALES_AMT_REACH_D1_DISTR
         , SUM(SALES_AMT_PAST_MONTH) AS SALES_AMT_PAST_MONTH
         , ROUND(SUM(SALES_AMT_PAST_MONTH)/1000,0) AS SALES_AMT_PAST_MONTH_V
         , ROUND(SUM(BILLING)/SUM(SALES_AMT_PAST_MONTH),3) AS PAST_PROG_REACH_RATE
         , (CASE WHEN ROUND(SUM(BILLING)/SUM(SALES_AMT_PAST_MONTH),3)<0 THEN 0.00 ELSE ROUND(SUM(BILLING)/SUM(SALES_AMT_PAST_MONTH),3) END) AS PAST_PROG_REACH_RATE_V
         , NULL AS PAST_PROG_REACH_RATE_F
         , 0 AS PAST_PROG_REACH_RATE_TOTAL
         , ROW_NUMBER() OVER(ORDER BY ROUND(SUM(BILLING)/SUM(SALES_AMT_PAST_MONTH),3) DESC) AS RANK_PAST
         , NULL AS RANK_PAST_F
         , 0 AS FCST_AMT
         , 0 AS FCST_AMT_V
         , 0 AS FCST_REACH_RATE
         , NULL AS FCST_REACH_RATE_F
         , 0 AS MKT_SHARE_REACH_RATE
         , NULL AS MKT_SHARE_REACH_RATE_F
         , (CASE WHEN DIVISION_ID IN (@DIVISION_ID_MILK, @DIVISION_ID_LEIS) THEN SUM(SALES_AMT_PAST_MONTH) ELSE 0 END) AS SALES_AMT_PAST_MONTH_MKLS
         , (CASE WHEN DIVISION_ID IN (@DIVISION_ID_MILK, @DIVISION_ID_LEIS) THEN ROUND(SUM(BILLING)/SUM(SALES_AMT_PAST_MONTH),3) ELSE 0 END) AS SALES_PAST_REACH_RATE_MKLS
         , (CASE WHEN DIVISION_ID IN (@DIVISION_ID_MILK, @DIVISION_ID_LEIS) THEN ROUND(SUM(BILLING)/SUM(SALES_AMT_PAST_MONTH),3)
                 WHEN ROUND(SUM(BILLING)/SUM(SALES_AMT_PAST_MONTH),3)<0 THEN 0.00 ELSE ROUND(SUM(BILLING)/SUM(SALES_AMT_PAST_MONTH),3) END) AS SALES_PAST_REACH_RATE_MKLS_V
         , NULL AS SALES_PAST_REACH_RATE_MKLS_F
         , (CASE WHEN DIVISION_ID=@DIVISION_ID_BEV1S THEN SUM(SALES_AMT_PAST_MONTH) ELSE 0 END) AS SALES_AMT_PAST_MONTH_BEV1S
         , (CASE WHEN DIVISION_ID=@DIVISION_ID_BEV1S THEN ROUND(SUM(BILLING)/SUM(SALES_AMT_PAST_MONTH),3) ELSE 0 END) AS SALES_PAST_REACH_RATE_BEV1S
         , (CASE WHEN DIVISION_ID=@DIVISION_ID_BEV1S THEN ROUND(SUM(BILLING)/SUM(SALES_AMT_PAST_MONTH),3)
                 WHEN ROUND(SUM(BILLING)/SUM(SALES_AMT_PAST_MONTH),3)<0 THEN 0.00 ELSE ROUND(SUM(BILLING)/SUM(SALES_AMT_PAST_MONTH),3) END) AS SALES_PAST_REACH_RATE_BEV1S_V
         , NULL AS SALES_PAST_REACH_RATE_BEV1S_F
         , (CASE WHEN DIVISION_ID=@DIVISION_ID_BEV1N THEN SUM(SALES_AMT_PAST_MONTH) ELSE 0 END) AS SALES_AMT_PAST_MONTH_BEV1N
         , (CASE WHEN DIVISION_ID=@DIVISION_ID_BEV1N THEN ROUND(SUM(BILLING)/SUM(SALES_AMT_PAST_MONTH),3) ELSE 0 END) AS SALES_PAST_REACH_RATE_BEV1N
         , (CASE WHEN DIVISION_ID=@DIVISION_ID_BEV1N THEN ROUND(SUM(BILLING)/SUM(SALES_AMT_PAST_MONTH),3)
                 WHEN ROUND(SUM(BILLING)/SUM(SALES_AMT_PAST_MONTH),3)<0 THEN 0.00 ELSE ROUND(SUM(BILLING)/SUM(SALES_AMT_PAST_MONTH),3) END) AS SALES_PAST_REACH_RATE_BEV1N_V
         , NULL AS SALES_PAST_REACH_RATE_BEV1N_F
         , (CASE WHEN DIVISION_ID=@DIVISION_ID_BEV2 THEN SUM(SALES_AMT_PAST_MONTH) ELSE 0 END) AS SALES_AMT_PAST_MONTH_BEV2
         , (CASE WHEN DIVISION_ID=@DIVISION_ID_BEV2 THEN ROUND(SUM(BILLING)/SUM(SALES_AMT_PAST_MONTH),3) ELSE 0 END) AS SALES_PAST_REACH_RATE_BEV2
         , (CASE WHEN DIVISION_ID=@DIVISION_ID_BEV2 THEN ROUND(SUM(BILLING)/SUM(SALES_AMT_PAST_MONTH),3)
                 WHEN ROUND(SUM(BILLING)/SUM(SALES_AMT_PAST_MONTH),3)<0 THEN 0.00 ELSE ROUND(SUM(BILLING)/SUM(SALES_AMT_PAST_MONTH),3) END) AS SALES_PAST_REACH_RATE_BEV2_V
         , NULL AS SALES_PAST_REACH_RATE_BEV2_F
         , (CASE WHEN DIVISION_ID=@DIVISION_ID_ICE THEN SUM(SALES_AMT_PAST_MONTH) ELSE 0 END) AS SALES_AMT_PAST_MONTH_ICE
         , (CASE WHEN DIVISION_ID=@DIVISION_ID_ICE THEN ROUND(SUM(BILLING)/SUM(SALES_AMT_PAST_MONTH),3) ELSE 0 END) AS SALES_PAST_REACH_RATE_ICE
         , (CASE WHEN DIVISION_ID=@DIVISION_ID_ICE THEN ROUND(SUM(BILLING)/SUM(SALES_AMT_PAST_MONTH),3)
                 WHEN ROUND(SUM(BILLING)/SUM(SALES_AMT_PAST_MONTH),3)<0 THEN 0.00 ELSE ROUND(SUM(BILLING)/SUM(SALES_AMT_PAST_MONTH),3) END) AS SALES_PAST_REACH_RATE_ICE_V
         , NULL AS SALES_PAST_REACH_RATE_ICE_F
         , (CASE WHEN DIVISION_ID=@DIVISION_ID_BULK THEN SUM(SALES_AMT_PAST_MONTH) ELSE 0 END) AS SALES_AMT_PAST_MONTH_BULK
         , (CASE WHEN DIVISION_ID=@DIVISION_ID_BULK THEN ROUND(SUM(BILLING)/SUM(SALES_AMT_PAST_MONTH),3) ELSE 0 END) AS SALES_PAST_REACH_RATE_BULK
         , (CASE WHEN DIVISION_ID=@DIVISION_ID_BULK THEN ROUND(SUM(BILLING)/SUM(SALES_AMT_PAST_MONTH),3)
                 WHEN ROUND(SUM(BILLING)/SUM(SALES_AMT_PAST_MONTH),3)<0 THEN 0.00 ELSE ROUND(SUM(BILLING)/SUM(SALES_AMT_PAST_MONTH),3) END) AS SALES_PAST_REACH_RATE_BULK_V
         , NULL AS SALES_PAST_REACH_RATE_BULK_F
         , (CASE WHEN DIVISION_ID=@DIVISION_ID_MAT THEN SUM(SALES_AMT_PAST_MONTH) ELSE 0 END) AS SALES_AMT_PAST_MONTH_MAT
         , (CASE WHEN DIVISION_ID=@DIVISION_ID_MAT THEN ROUND(SUM(BILLING)/SUM(SALES_AMT_PAST_MONTH),3) ELSE 0 END) AS SALES_PAST_REACH_RATE_MAT
         , (CASE WHEN DIVISION_ID=@DIVISION_ID_MAT THEN ROUND(SUM(BILLING)/SUM(SALES_AMT_PAST_MONTH),3)
                 WHEN ROUND(SUM(BILLING)/SUM(SALES_AMT_PAST_MONTH),3)<0 THEN 0.00 ELSE ROUND(SUM(BILLING)/SUM(SALES_AMT_PAST_MONTH),3) END) AS SALES_PAST_REACH_RATE_MAT_V
         , NULL AS SALES_PAST_REACH_RATE_MAT_F
         , (CASE WHEN DIVISION_ID=@DIVISION_ID_CDCN THEN SUM(SALES_AMT_PAST_MONTH) ELSE 0 END) AS SALES_AMT_PAST_MONTH_CDCN
         , (CASE WHEN DIVISION_ID=@DIVISION_ID_CDCN THEN ROUND(SUM(BILLING)/SUM(SALES_AMT_PAST_MONTH),3) ELSE 0 END) AS SALES_PAST_REACH_RATE_CDCN
         , (CASE WHEN DIVISION_ID=@DIVISION_ID_CDCN THEN ROUND(SUM(BILLING)/SUM(SALES_AMT_PAST_MONTH),3)
                 WHEN ROUND(SUM(BILLING)/SUM(SALES_AMT_PAST_MONTH),3)<0 THEN 0.00 ELSE ROUND(SUM(BILLING)/SUM(SALES_AMT_PAST_MONTH),3) END) AS SALES_PAST_REACH_RATE_CDCN_V
         , NULL AS SALES_PAST_REACH_RATE_CDCN_F
         , (CASE WHEN DIVISIOND_ID=@DIVISIOND_ID_WLALL THEN SUM(SALES_AMT_PAST_MONTH) ELSE 0 END) AS SALES_AMT_PAST_MONTH_WLALL
         , (CASE WHEN DIVISIOND_ID=@DIVISIOND_ID_WLALL THEN ROUND(SUM(BILLING)/SUM(SALES_AMT_PAST_MONTH),3) ELSE 0 END) AS SALES_PAST_REACH_RATE_WLALL
         , (CASE WHEN DIVISIOND_ID=@DIVISIOND_ID_WLALL THEN ROUND(SUM(BILLING)/SUM(SALES_AMT_PAST_MONTH),3)
                 WHEN ROUND(SUM(BILLING)/SUM(SALES_AMT_PAST_MONTH),3)<0 THEN 0.00 ELSE ROUND(SUM(BILLING)/SUM(SALES_AMT_PAST_MONTH),3) END) AS SALES_PAST_REACH_RATE_WLALL_V
         , NULL AS SALES_PAST_REACH_RATE_WLALL_F
         , (CASE WHEN DIVISIOND_ID=@DIVISIOND_ID_WL THEN SUM(SALES_AMT_PAST_MONTH) ELSE 0 END) AS SALES_AMT_PAST_MONTH_WL
         , (CASE WHEN DIVISIOND_ID=@DIVISIOND_ID_WL THEN ROUND(SUM(BILLING)/SUM(SALES_AMT_PAST_MONTH),3) ELSE 0 END) AS SALES_PAST_REACH_RATE_WL
         , (CASE WHEN DIVISIOND_ID=@DIVISIOND_ID_WL THEN ROUND(SUM(BILLING)/SUM(SALES_AMT_PAST_MONTH),3)
                 WHEN ROUND(SUM(BILLING)/SUM(SALES_AMT_PAST_MONTH),3)<0 THEN 0.00 ELSE ROUND(SUM(BILLING)/SUM(SALES_AMT_PAST_MONTH),3) END) AS SALES_PAST_REACH_RATE_WL_V
         , NULL AS SALES_PAST_REACH_RATE_WL_F
         , (CASE WHEN DIVISION_ID=@DIVISION_ID_KA THEN SUM(SALES_AMT_PAST_MONTH) ELSE 0 END) AS SALES_AMT_PAST_MONTH_KA
         , (CASE WHEN DIVISION_ID=@DIVISION_ID_KA THEN ROUND(SUM(BILLING)/SUM(SALES_AMT_PAST_MONTH),3) ELSE 0 END) AS SALES_PAST_REACH_RATE_KA
         , (CASE WHEN DIVISION_ID=@DIVISION_ID_KA THEN ROUND(SUM(BILLING)/SUM(SALES_AMT_PAST_MONTH),3)
                 WHEN ROUND(SUM(BILLING)/SUM(SALES_AMT_PAST_MONTH),3)<0 THEN 0.00 ELSE ROUND(SUM(BILLING)/SUM(SALES_AMT_PAST_MONTH),3) END) AS SALES_PAST_REACH_RATE_KA_V
         , NULL AS SALES_PAST_REACH_RATE_KA_F
         , (CASE WHEN DIVISION_ID=@DIVISION_ID_EC THEN SUM(SALES_AMT_PAST_MONTH) ELSE 0 END) AS SALES_AMT_PAST_MONTH_EC
         , (CASE WHEN DIVISION_ID=@DIVISION_ID_EC THEN ROUND(SUM(BILLING)/SUM(SALES_AMT_PAST_MONTH),3) ELSE 0 END) AS SALES_PAST_REACH_RATE_EC
         , (CASE WHEN DIVISION_ID=@DIVISION_ID_EC THEN ROUND(SUM(BILLING)/SUM(SALES_AMT_PAST_MONTH),3)
                 WHEN ROUND(SUM(BILLING)/SUM(SALES_AMT_PAST_MONTH),3)<0 THEN 0.00 ELSE ROUND(SUM(BILLING)/SUM(SALES_AMT_PAST_MONTH),3) END) AS SALES_PAST_REACH_RATE_EC_V
         , NULL AS SALES_PAST_REACH_RATE_EC_F
    FROM DMMDL.DC0021_SALES_DIST_PROD_DATE_CUM
    WHERE DATA_DATE=VAR_DATA_DATE AND RPT_YMD=VAR_DATA_DATE
    GROUP BY DISTRICT15_ID
           , COM_ID
    ;
    
    --UPDATE2
    --WORK_RATIO 標準進度
    UPDATE APDC.DC0021_RPT0102_COM A
    JOIN(SELECT ROUND(WORK_RATIO,3) AS WORK_RATIO
         FROM DMMDL.DC0021_WORK_RATIO_CUM
         WHERE DATA_DATE=VAR_DATA_DATE AND RPT_YMD=VAR_DATA_DATE) B
    ON A.DATA_DATE=B.DATA_DATE AND A.RPT_YMD=B.RPT_YMD
    SET A.WORK_RATIO=B.WORK_RATIO
    WHERE A.DATA_DATE=VAR_DATA_DATE AND A.RPT_YMD=VAR_DATA_DATE
    ;

    --UPDATE3
    --MKT_SHARE 應有市場占比
    --MKT_SHARE_REACH_RATE 應有市場達成率
    UPDATE APDC.DC0021_RPT0102_COM A
    JOIN(SELECT COM_ID
              , ROUND(COM_MKT_SHARE,5) AS MKT_SHARE
              , ROUND(MKT_SHARE_REACH_RATE,3) AS MKT_SHARE_REACH_RATE
              , (CASE WHEN MKT_SHARE_REACH_RATE=1 THEN 'A' ELSE NULL) AS MKT_SHARE_REACH_RATE_F
         FROM DMMDL.DC0021_MKT_SHARE_REACH_RATE_COM_CUM
         WHERE DATA_DATE=VAR_DATA_DATE AND RPT_YMD=VAR_DATA_DATE
         GROUP BY COM_ID) B
    ON A.DATA_DATE=B.DATA_DATE AND A.RPT_YMD=B.RPT_YMD AND A.COM_ID=B.COM_ID
    SET A.MKT_SHARE=B.MKT_SHARE
      , A.MKT_SHARE_REACH_RATE=B.MKT_SHARE_REACH_RATE
      , A.MKT_SHARE_REACH_RATE_F=B.MKT_SHARE_REACH_RATE_F
    WHERE A.DATA_DATE=VAR_DATA_DATE AND A.RPT_YMD=VAR_DATA_DATE
    ;

    --UPDATE4
    --人口數(萬)
    UPDATE APDC.DC0021_RPT0102_COM A
    JOIN(SELECT COM_ID
              , POPU
              , ROUND(POPU/10000,0) AS POPU_V
         FROM DMMDL.DC0021_POPU_COM
         WHERE DATA_DATE=VAR_DATA_DATE AND RPT_YMD=VAR_DATA_DATE
         GROUP BY COM_ID) B
    ON A.DATA_DATE=B.DATA_DATE AND A.RPT_YMD=B.RPT_YMD AND A.COM_ID=B.COM_ID
    SET A.POPU=B.POPU
      , A.POPU_V=B.POPU_V
    WHERE A.DATA_DATE=VAR_DATA_DATE AND A.RPT_YMD=VAR_DATA_DATE
    ;
    
    --UPDATE5
    --PAST_PROG_REACH_RATE_TOTAL 全國全月同期達成率
    UPDATE APDC.DC0021_RPT0102_COM A
    JOIN(SELECT ROUND(SUM(BILLING)/SUM(SALES_AMT_PAST_MONTH),3) AS PAST_PROG_REACH_RATE_TOTAL
         FROM DMMDL.DC0021_SALES_DIST_PROD_DATE_CUM
         WHERE DATA_DATE=VAR_DATA_DATE AND RPT_YMD=VAR_DATA_DATE) B
    ON A.DATA_DATE=B.DATA_DATE AND A.RPT_YMD=B.RPT_YMD AND A.DISTRICT15_ID=B.DISTRICT15_ID AND A.COM_ID=B.COM_ID
    SET A.PAST_PROG_REACH_RATE_TOTAL=B.PAST_PROG_REACH_RATE_TOTAL
    WHERE A.DATA_DATE=VAR_DATA_DATE AND A.RPT_YMD=VAR_DATA_DATE
    ;

    --UPDATE6
    --FCST_AMT 全月預估
    --FCST_AMT_V 全月預估(畫面數值)
    UPDATE APDC.DC0021_RPT0102_COM A
    JOIN(SELECT DISTRICT15_ID
              , COM_ID
              , SUM(FCST_AMT) AS FCST_AMT
              , ROUND(SUM(FCST_AMT)/1000,0) AS FCST_AMT_V
         FROM DMMDL.DC0021_FCST_AMT_CUM
         WHERE DATA_DATE=VAR_DATA_DATE AND RPT_YMD=VAR_DATA_DATE 
         GROUP BY DISTRICT15_ID
                , COM_ID) B
    ON A.DATA_DATE=B.DATA_DATE AND A.RPT_YMD=B.RPT_YMD AND A.DISTRICT15_ID=B.DISTRICT15_ID AND A.COM_ID=B.COM_ID
    SET A.FCST_AMT=B.FCST_AMT
      , A.FCST_AMT_V=B.FCST_AMT_V
    WHERE A.DATA_DATE=VAR_DATA_DATE AND A.RPT_YMD=VAR_DATA_DATE
    ;
   
    --UPDATE7
    --SALES_AMT_REACH_D1_RATE 達成截至D1分佈
    --PAST_PROG_REACH_RATE_F 全月同期達成率(畫面格式)
    --FCST_REACH_RATE 預估達成率
    --FCST_REACH_RATE_F 預估達成率(畫面格式)
    --SALES_PAST_REACH_RATE_F 事業部同期達成率(畫面格式)
    --RANK_PAST_F 同期排名(畫面格式)前三名/後五名
    UPDATE APDC.DC0021_RPT0102_COM A
    JOIN(SELECT DISTRICT15_ID
              , COM_ID
              , MAX(SALES_AMT_REACH_D1) AS SALES_AMT_REACH_D1_MAX
              , ROUND(SALES_AMT_REACH_D1/MAX(SALES_AMT_REACH_D1),3) AS SALES_AMT_REACH_D1_DISTR
              , (CASE WHEN ROUND(SALES_AMT_REACH_D1/SALES_AMT_PAST_MONTH,3)<PAST_PROG_REACH_RATE_TOTAL THEN 'A'
                      WHEN SALES_AMT_PAST_MONTH<=0 THEN 'B' ELSE NULL END) AS PAST_PROG_REACH_RATE_F
              , ROUND(SALES_AMT_REACH_D1/FCST_AMT,3) AS FCST_REACH_RATE
              , (CASE WHEN ROUND(SALES_AMT_REACH_D1/FCST_AMT,3)<WORK_RATIO THEN 'A' ELSE NULL END) AS FCST_REACH_RATE_F
              , (CASE WHEN SALES_PAST_REACH_RATE_MKLS_V<WORK_RATIO THEN 'A'
                      WHEN SALES_AMT_PAST_MONTH_MKLS<=0 THEN 'B' ELSE NULL END) AS SALES_PAST_REACH_RATE_MKLS_F
              , (CASE WHEN SALES_PAST_REACH_RATE_BEV1S_V<WORK_RATIO THEN 'A'
                      WHEN SALES_AMT_PAST_MONTH_BEV1S<=0 THEN 'B' ELSE NULL END) AS SALES_PAST_REACH_RATE_BEV1S_F
              , (CASE WHEN SALES_PAST_REACH_RATE_BEV1N_V<WORK_RATIO THEN 'A'
                      WHEN SALES_AMT_PAST_MONTH_BEV1N<=0 THEN 'B' ELSE NULL END) AS SALES_PAST_REACH_RATE_BEV1N_F
              , (CASE WHEN SALES_PAST_REACH_RATE_BEV2_V<WORK_RATIO THEN 'A'
                      WHEN SALES_AMT_PAST_MONTH_BEV2<=0 THEN 'B' ELSE NULL END) AS SALES_PAST_REACH_RATE_BEV2_F
              , (CASE WHEN SALES_PAST_REACH_RATE_ICE_V<WORK_RATIO THEN 'A'
                      WHEN SALES_AMT_PAST_MONTH_ICE<=0 THEN 'B' ELSE NULL END) AS SALES_PAST_REACH_RATE_ICE_F
              , (CASE WHEN SALES_PAST_REACH_RATE_BULK_V<WORK_RATIO THEN 'A'
                      WHEN SALES_AMT_PAST_MONTH_BULK<=0 THEN 'B' ELSE NULL END) AS SALES_PAST_REACH_RATE_BULK_F
              , (CASE WHEN SALES_PAST_REACH_RATE_MAT_V<WORK_RATIO THEN 'A'
                      WHEN SALES_AMT_PAST_MONTH_MAT<=0 THEN 'B' ELSE NULL END) AS SALES_PAST_REACH_RATE_MAT_F
              , (CASE WHEN SALES_PAST_REACH_RATE_CDCN_V<WORK_RATIO THEN 'A'
                      WHEN SALES_AMT_PAST_MONTH_CDCN<=0 THEN 'B' ELSE NULL END) AS SALES_PAST_REACH_RATE_CDCN_F
              , (CASE WHEN SALES_PAST_REACH_RATE_WLALL_V<WORK_RATIO THEN 'A'
                      WHEN SALES_AMT_PAST_MONTH_WLALL<=0 THEN 'B' ELSE NULL END) AS SALES_PAST_REACH_RATE_WLALL_F
              , (CASE WHEN SALES_PAST_REACH_RATE_WL_V<WORK_RATIO THEN 'A'
                      WHEN SALES_AMT_PAST_MONTH_WL<=0 THEN 'B' ELSE NULL END) AS SALES_PAST_REACH_RATE_WL_F
              , (CASE WHEN SALES_PAST_REACH_RATE_KA_V<WORK_RATIO THEN 'A'
                      WHEN SALES_AMT_PAST_MONTH_KA<=0 THEN 'B' ELSE NULL END) AS SALES_PAST_REACH_RATE_KA_F
              , (CASE SALES_PAST_REACH_RATE_EC_V<WORK_RATIO THEN 'A'
                      WHEN SALES_AMT_PAST_MONTH_EC<=0 THEN 'B' ELSE NULL END) AS SALES_PAST_REACH_RATE_EC_F
              , (CASE WHEN RANK_PAST<=3 THEN 'A'
                      WHEN RANK_PAST>=48 THEN 'B' ELSE NULL END) AS RANK_PAST_F
         FROM APDC.DC0021_RPT0102_COM
         WHERE DATA_DATE=VAR_DATA_DATE AND RPT_YMD=VAR_DATA_DATE
         GROUP BY DISTRICT15_ID
                , COM_ID) B
    ON A.DATA_DATE=B.DATA_DATE AND A.RPT_YMD=B.RPT_YMD AND A.DISTRICT15_ID=B.DISTRICT15_ID AND A.COM_ID=B.COM_ID AND A.MKT_DIR_ID=B.MKT_DIR_ID
    SET A.SALES_AMT_REACH_D1_MAX=B.SALES_AMT_REACH_D1_MAX
      , A.SALES_AMT_REACH_D1_DISTR=B.SALES_AMT_REACH_D1_DISTR
      , A.PAST_PROG_REACH_RATE_F=B.PAST_PROG_REACH_RATE_F
      , A.FCST_REACH_RATE=B.FCST_REACH_RATE
      , A.FCST_REACH_RATE_F=B.FCST_REACH_RATE_F
      , A.SALES_PAST_REACH_RATE_MKLS_F=B.SALES_PAST_REACH_RATE_MKLS_F
      , A.SALES_PAST_REACH_RATE_BEV1S_F=B.SALES_PAST_REACH_RATE_BEV1S_F
      , A.SALES_PAST_REACH_RATE_BEV1N_F=B.SALES_PAST_REACH_RATE_BEV1N_F
      , A.SALES_PAST_REACH_RATE_BEV2_F=B.SALES_PAST_REACH_RATE_BEV2_F
      , A.SALES_PAST_REACH_RATE_ICE_F=B.SALES_PAST_REACH_RATE_ICE_F
      , A.SALES_PAST_REACH_RATE_BULK_F=B.SALES_PAST_REACH_RATE_BULK_F
      , A.SALES_PAST_REACH_RATE_MAT_F=B.SALES_PAST_REACH_RATE_MAT_F
      , A.SALES_PAST_REACH_RATE_CDCN_F=B.SALES_PAST_REACH_RATE_CDCN_F
      , A.SALES_PAST_REACH_RATE_WLALL_F=B.SALES_PAST_REACH_RATE_WLALL_F
      , A.SALES_PAST_REACH_RATE_WL_F=B.SALES_PAST_REACH_RATE_WL_F
      , A.SALES_PAST_REACH_RATE_KA_F=B.SALES_PAST_REACH_RATE_KA_F
      , A.SALES_PAST_REACH_RATE_EC_F=B.SALES_PAST_REACH_RATE_EC_F
      , A.RANK_PAST_F=B.RANK_PAST_F
    WHERE A.DATA_DATE=VAR_DATA_DATE AND A.RPT_YMD=VAR_DATA_DATE
    ;
   
    

    SET VAR_SP_RESULT='Y';
    COMMIT;
END
;