DROP PROCEDURE IF EXISTS APDC.SP_DAT_30121_DC0021_RPT0105_SALES_AMT_REACH_MONTH;

CREATE PROCEDURE APDC.SP_DAT_30121_DC0021_RPT0105_SALES_AMT_REACH_MONTH (
    VAR_EDI_DATE CHAR(8), VAR_EDI_TIME CHAR(9), VAR_DATA_DATE CHAR(8)
  , OUT VAR_SP_RESULT CHAR(1)
)
BEGIN
    
    SET @DIVISION_ID_MILK='乳飲' COLLATE utf8_unicode_ci;
    SET @DIVISION_ID_LEIS='休閒' COLLATE utf8_unicode_ci;
    SET @DIVISION_ID_BEV1S='飲一南' COLLATE utf8_unicode_ci;
    SET @DIVISION_ID_BEV1N='飲一北' COLLATE utf8_unicode_ci;
    SET @DIVISION_ID_WL='旺禮' COLLATE utf8_unicode_ci;

    --INSERT1
    --SALES_AMT_REACH_MONTH 全月達成
    INSERT INTO APDC.DC0021_RPT0105_SALES_AMT_REACH_MONTH A
    SELECT VAR_DATA_DATE AS DATA_DATE
         , VAR_DATA_DATE AS RPT_YMD
         , DISTRICT15_ID AS ITEM_ID
         , 'DISTRICT15_NM' AS ITEM_NM
         , SUM(BILLING) AS SALES_AMT_REACH_MONTH
    FROM DMMDL.DC0021_SALES_DIST_PROD_DATE_CUM
    WHERE DATA_DATE=VAR_DATA_DATE AND RPT_YMD=VAR_DATA_DATE AND DIVISION_ID IN (@DIVISION_ID_MILK, @DIVISION_ID_LEIS)
    GROUP BY DISTRICT15_ID
    ;

    --INSERT2
    INSERT INTO APDC.DC0021_RPT0105_SALES_AMT_REACH_MONTH A
    SELECT VAR_DATA_DATE AS DATA_DATE
         , VAR_DATA_DATE AS RPT_YMD
         , DIVISIOND_ID AS ITEM_ID
         , 'DIVISIOND_NM' AS ITEM_NM
         , SUM(BILLING) AS SALES_AMT_REACH_MONTH
    FROM DMMDL.DC0021_SALES_DIST_PROD_DATE_CUM
    WHERE DATA_DATE=VAR_DATA_DATE AND RPT_YMD=VAR_DATA_DATE AND DIVISION_ID IN (@DIVISION_ID_BEV1S, @DIVISION_ID_BEV1N, @DIVISION_ID_WL)
    GROUP BY DIVISIOND_ID
    ;

    --INSERT3
    INSERT INTO APDC.DC0021_RPT0105_SALES_AMT_REACH_MONTH A
    SELECT VAR_DATA_DATE AS DATA_DATE
         , VAR_DATA_DATE AS RPT_YMD
         , DIVISION_ID AS ITEM_ID
         , 'DIVISION_NM' AS ITEM_NM
         , SUM(BILLING) AS SALES_AMT_REACH_MONTH
    FROM DMMDL.DC0021_SALES_DIST_PROD_DATE_CUM
    WHERE DATA_DATE=VAR_DATA_DATE AND RPT_YMD=VAR_DATA_DATE AND DIVISION_ID NOT IN (@DIVISION_ID_MILK, @DIVISION_ID_LEIS,@DIVISION_ID_BEV1S, @DIVISION_ID_BEV1N, @DIVISION_ID_WL)
    GROUP BY DIVISION_ID 
    ;



    SET VAR_SP_RESULT='Y';
    COMMIT;
END
;