SELECT '"' || {edino} || '"'
   || ',"' || SID || '"'
   || ',"' || STORE_ID || '"' 
   || ',"' || REPLACE(REPLACE(REPLACE(REPLACE(STORE_NAME, CHR(13)), CHR(10)),'\','\\'), '"', '\"') || '"'
   || ',"' || REPLACE(REPLACE(REPLACE(REPLACE(STORE_DESC, CHR(13)), CHR(10)),'\','\\'), '"', '\"') || '"'
   || ',"' || NVL(ACREAGE,-99999) || '"'
   || ',"' || STATUS || '"'
   || ',"' || FORTH_SID || '"'
   || ',"' || FIFTH_SID || '"'
   || ',"' || REPLACE(REPLACE(REPLACE(REPLACE(STORE_OWNER, CHR(13)), CHR(10)),'\','\\'), '"', '\"') || '"'
   || ',"' || OWNERGENDER || '"'
   || ',"' || REPLACE(REPLACE(REPLACE(REPLACE(ADD1, CHR(13)), CHR(10)),'\','\\'), '"', '\"') || '"'
   || ',"' || ADD1TYPESID || '"'
   || ',"' || REPLACE(REPLACE(REPLACE(REPLACE(ADD2, CHR(13)), CHR(10)),'\','\\'), '"', '\"') || '"'
   || ',"' || ADD2TYPESID || '"'
   || ',"' || REPLACE(REPLACE(REPLACE(REPLACE(ADD3, CHR(13)), CHR(10)),'\','\\'), '"', '\"') || '"'
   || ',"' || ADD3TYPESID || '"'
   || ',"' || REPLACE(REPLACE(REPLACE(REPLACE(ADD4, CHR(13)), CHR(10)),'\','\\'), '"', '\"') || '"'
   || ',"' || POSTCODE || '"'
   || ',"' || ZIP || '"'
   || ',"' || FIXEDPHONE || '"'
   || ',"' || MOBILEPHONE || '"'
   || ',"' || NVL(LONGITUDE,-99999) || '"'
   || ',"' || NVL(LATITUDE,-99999) || '"'
   || ',"' || TO_CHAR(CREATE_DATE,'YYYYMMDD') || '"'
   || ',"' || CREATE_USER || '"'
   || ',"' || TO_CHAR(UPDATE_DATE,'YYYYMMDD') || '"'
   || ',"' || UPDATE_USER || '"'   AS CONTENT
FROM SALES.STORE_INFO
;