/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 16-¤T¤ë-2018 ¤U¤È 02:18:16 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 ;

/* Create Tables */

CREATE TABLE `MODEL_HEAD`
(
	`PROJECT_ID` CHAR(6) NOT NULL,
	`MODEL_ID` CHAR(50) NOT NULL,
	`DATA_DATE` CHAR(8) NOT NULL,
	`IS_ENABLE` CHAR(1) 	 NULL,
	CONSTRAINT `PK_MODEL_HEAD` PRIMARY KEY (`PROJECT_ID`,`MODEL_ID`,`DATA_DATE`)
)

;

SET FOREIGN_KEY_CHECKS=1 ;
