/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 06-十二月-2017 下午 06:10:05 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 ;

/* Create Tables */

CREATE TABLE `PL_SAWA_CUST`
(
	`QRCODE_SID` INT NOT NULL,
	`QRCODE_DATE` CHAR(17) NOT NULL,
	`POI_CODE` VARCHAR(10) NOT NULL,
	`POI_NM` NVARCHAR(200) NOT NULL,
	`CUST_NM` NVARCHAR(200) NOT NULL,
	`CUST_TEL` VARCHAR(20) NOT NULL,
	`CUST_BIRTHDAY` CHAR(8) NOT NULL,
	`CUST_GENDER` CHAR(1) NOT NULL,
	`CUST_EMAIL` VARCHAR(50) 	 NULL,
	`CUST_PICTURE_NM` NVARCHAR(200) NOT NULL,
	`PICTURE_RECOG` VARCHAR(10) 	 NULL,
	CONSTRAINT `PK_PL_SAWA_CUST` PRIMARY KEY (`QRCODE_SID`)
)

;

SET FOREIGN_KEY_CHECKS=1 ;
