DROP PROCEDURE IF EXISTS APWANT.SP_APWANT_MODEL_0201_MODEL_HEAD;

CREATE PROCEDURE APWANT.SP_APWANT_MODEL_0201_MODEL_HEAD (
    OUT VAR_SP_RESULT CHAR(1)
)
BEGIN
    SET @VAR_SP_RESULT = VAR_SP_RESULT;

    /*市場樣貌*/
    INSERT INTO APWANT.MODEL_HEAD VALUES('DC0005','DC0005_20170818_01','20170818','Y');
    /*終端管理*/
    INSERT INTO APWANT.MODEL_HEAD VALUES('DC0006','DC0006_20170818_01','20170818','Y');
    
    /*SRC*/
    INSERT INTO APWANT.MODEL_HEAD
    SELECT 'CM'AS PROJECT_ID, 'SRC_ORG_REL' AS MODEL_ID
         , DATA_DATE, 'Y' AS IS_ENABLE
    FROM APWANT.SRC_ORG_REL
    GROUP BY DATA_DATE
    ;
    
    INSERT INTO APWANT.MODEL_HEAD
    SELECT 'CM'AS PROJECT_ID, 'SRC_PROD_SKU' AS MODEL_ID
         , DATA_DATE, 'Y' AS IS_ENABLE
    FROM APWANT.SRC_PROD_SKU
    GROUP BY DATA_DATE
    ;
    
    /*DC0013*/
    INSERT INTO APWANT.MODEL_HEAD
    SELECT 'DC0013'AS PROJECT_ID, 'DIST_BAL_REACH' AS MODEL_ID
         , DATA_DATE, 'Y' AS IS_ENABLE
    FROM APWANT.DIST_BAL_REACH
    GROUP BY DATA_DATE
    ;
    
    INSERT INTO APWANT.MODEL_HEAD
    SELECT 'DC0013'AS PROJECT_ID, 'DIST_EMP_MARKET' AS MODEL_ID
         , DATA_DATE, 'Y' AS IS_ENABLE
    FROM APWANT.DIST_EMP_MARKET
    GROUP BY DATA_DATE
    ;
    
    INSERT INTO APWANT.MODEL_HEAD
    SELECT 'DC0013'AS PROJECT_ID, 'DIST_EVAL' AS MODEL_ID
         , DATA_DATE, 'Y' AS IS_ENABLE
    FROM APWANT.DIST_EVAL
    GROUP BY DATA_DATE
    ;
    
    INSERT INTO APWANT.MODEL_HEAD
    SELECT 'DC0013'AS PROJECT_ID, 'DIST_EVAL_OFFICE' AS MODEL_ID
         , DATA_DATE, 'Y' AS IS_ENABLE
    FROM APWANT.DIST_EVAL_OFFICE
    GROUP BY DATA_DATE
    ;
    
    INSERT INTO APWANT.MODEL_HEAD
    SELECT 'DC0013'AS PROJECT_ID, 'DIST_INDEX_AVG_SCORES' AS MODEL_ID
         , DATA_DATE, 'Y' AS IS_ENABLE
    FROM APWANT.DIST_INDEX_AVG_SCORES
    GROUP BY DATA_DATE
    ;
    
    INSERT INTO APWANT.MODEL_HEAD
    SELECT 'DC0013'AS PROJECT_ID, 'DIST_SALES_MONTH' AS MODEL_ID
         , DATA_DATE, 'Y' AS IS_ENABLE
    FROM APWANT.DIST_SALES_MONTH
    GROUP BY DATA_DATE
    ;
    
    INSERT INTO APWANT.MODEL_HEAD
    SELECT 'DC0013'AS PROJECT_ID, 'DIST_SCORES' AS MODEL_ID
         , DATA_DATE, 'Y' AS IS_ENABLE
    FROM APWANT.DIST_SCORES
    GROUP BY DATA_DATE
    ;
    
    INSERT INTO APWANT.MODEL_HEAD
    SELECT 'DC0013'AS PROJECT_ID, 'DIST_STATUS' AS MODEL_ID
         , DATA_DATE, 'Y' AS IS_ENABLE
    FROM APWANT.DIST_STATUS
    GROUP BY DATA_DATE
    ;
    
    INSERT INTO APWANT.MODEL_HEAD
    SELECT 'DC0013'AS PROJECT_ID, 'DIST_STOCK' AS MODEL_ID
         , DATA_DATE, 'Y' AS IS_ENABLE
    FROM APWANT.DIST_STOCK
    GROUP BY DATA_DATE
    ;
    
    /*DC0014*/
    INSERT INTO APWANT.MODEL_HEAD
    SELECT 'DC0014'AS PROJECT_ID, 'EMP_DIST_STATUS' AS MODEL_ID
         , DATA_DATE, 'Y' AS IS_ENABLE
    FROM APWANT.EMP_DIST_STATUS
    GROUP BY DATA_DATE
    ;
    
    INSERT INTO APWANT.MODEL_HEAD
    SELECT 'DC0014'AS PROJECT_ID, 'EMP_DIST_STATUS_DISTRICT' AS MODEL_ID
         , DATA_DATE, 'Y' AS IS_ENABLE
    FROM APWANT.EMP_DIST_STATUS_DISTRICT
    GROUP BY DATA_DATE
    ;
    
    INSERT INTO APWANT.MODEL_HEAD
    SELECT 'DC0014'AS PROJECT_ID, 'EMP_DIST_STATUS_OFFICE' AS MODEL_ID
         , DATA_DATE, 'Y' AS IS_ENABLE
    FROM APWANT.EMP_DIST_STATUS_OFFICE
    GROUP BY DATA_DATE
    ;
    
    INSERT INTO APWANT.MODEL_HEAD
    SELECT 'DC0014'AS PROJECT_ID, 'EMP_LIST' AS MODEL_ID
         , DATA_DATE, 'Y' AS IS_ENABLE
    FROM APWANT.EMP_LIST
    GROUP BY DATA_DATE
    ;
    
    INSERT INTO APWANT.MODEL_HEAD
    SELECT 'DC0014'AS PROJECT_ID, 'EMP_TERM_STATUS' AS MODEL_ID
         , DATA_DATE, 'Y' AS IS_ENABLE
    FROM APWANT.EMP_TERM_STATUS
    GROUP BY DATA_DATE
    ;
    
    INSERT INTO APWANT.MODEL_HEAD
    SELECT 'DC0014'AS PROJECT_ID, 'EMP_TERM_STATUS_DISTRICT' AS MODEL_ID
         , DATA_DATE, 'Y' AS IS_ENABLE
    FROM APWANT.EMP_TERM_STATUS_DISTRICT
    GROUP BY DATA_DATE
    ;
    
    INSERT INTO APWANT.MODEL_HEAD
    SELECT 'DC0014'AS PROJECT_ID, 'EMP_TERM_STATUS_OFFICE' AS MODEL_ID
         , DATA_DATE, 'Y' AS IS_ENABLE
    FROM APWANT.EMP_TERM_STATUS_OFFICE
    GROUP BY DATA_DATE
    ;
    
    /*DC0016*/
    INSERT INTO APWANT.MODEL_HEAD
    SELECT 'DC0016'AS PROJECT_ID, 'CHANNEL_EVAL_BRANCH' AS MODEL_ID
         , DATA_DATE, 'Y' AS IS_ENABLE
    FROM APWANT.CHANNEL_EVAL_BRANCH
    GROUP BY DATA_DATE
    ;
    
    INSERT INTO APWANT.MODEL_HEAD
    SELECT 'DC0016'AS PROJECT_ID, 'CHANNEL_EVAL_DISTRICT' AS MODEL_ID
         , DATA_DATE, 'Y' AS IS_ENABLE
    FROM APWANT.CHANNEL_EVAL_DISTRICT
    GROUP BY DATA_DATE
    ;
    
    INSERT INTO APWANT.MODEL_HEAD
    SELECT 'DC0016'AS PROJECT_ID, 'CHANNEL_EVAL_OFFICE' AS MODEL_ID
         , DATA_DATE, 'Y' AS IS_ENABLE
    FROM APWANT.CHANNEL_EVAL_OFFICE
    GROUP BY DATA_DATE
    ;
    
    INSERT INTO APWANT.MODEL_HEAD
    SELECT 'DC0016'AS PROJECT_ID, 'CHANNEL_EVAL_OFFICE_OOS_RISK' AS MODEL_ID
         , DATA_DATE, 'Y' AS IS_ENABLE
    FROM APWANT.CHANNEL_EVAL_OFFICE_OOS_RISK
    GROUP BY DATA_DATE
    ;
    
    INSERT INTO APWANT.MODEL_HEAD
    SELECT 'DC0016'AS PROJECT_ID, 'CHANNEL_EVAL_OFFICE_OVERTIME_STOCK' AS MODEL_ID
         , DATA_DATE, 'Y' AS IS_ENABLE
    FROM APWANT.CHANNEL_EVAL_OFFICE_OVERTIME_STOCK
    GROUP BY DATA_DATE
    ;
    
    INSERT INTO APWANT.MODEL_HEAD
    SELECT 'DC0016'AS PROJECT_ID, 'CHANNEL_EVAL_OFFICE_PROD' AS MODEL_ID
         , DATA_DATE, 'Y' AS IS_ENABLE
    FROM APWANT.CHANNEL_EVAL_OFFICE_PROD
    GROUP BY DATA_DATE
    ;
    
    INSERT INTO APWANT.MODEL_HEAD
    SELECT 'DC0016'AS PROJECT_ID, 'CHANNEL_PL3_BRANCH' AS MODEL_ID
         , DATA_DATE, 'Y' AS IS_ENABLE
    FROM APWANT.CHANNEL_PL3_BRANCH
    GROUP BY DATA_DATE
    ;
    
    INSERT INTO APWANT.MODEL_HEAD
    SELECT 'DC0016'AS PROJECT_ID, 'CHANNEL_PL3_SPECIAL_CHANNEL' AS MODEL_ID
         , DATA_DATE, 'Y' AS IS_ENABLE
    FROM APWANT.CHANNEL_PL3_SPECIAL_CHANNEL
    GROUP BY DATA_DATE
    ;
    
    INSERT INTO APWANT.MODEL_HEAD
    SELECT 'DC0016'AS PROJECT_ID, 'CHANNEL_SALES_PROD' AS MODEL_ID
         , DATA_DATE, 'Y' AS IS_ENABLE
    FROM APWANT.CHANNEL_SALES_PROD
    GROUP BY DATA_DATE
    ;
    
    INSERT INTO APWANT.MODEL_HEAD
    SELECT 'DC0016'AS PROJECT_ID, 'CHANNEL_TRA_COUNT' AS MODEL_ID
         , DATA_DATE, 'Y' AS IS_ENABLE
    FROM APWANT.CHANNEL_TRA_COUNT
    GROUP BY DATA_DATE
    ;
    
    /*DC0017*/
    INSERT INTO APWANT.MODEL_HEAD
    SELECT 'DC0017'AS PROJECT_ID, 'PROD_INDICA_STATUS_OFFICE' AS MODEL_ID
         , DATA_DATE, 'Y' AS IS_ENABLE
    FROM APWANT.PROD_INDICA_STATUS_OFFICE
    GROUP BY DATA_DATE
    ;
    
    INSERT INTO APWANT.MODEL_HEAD
    SELECT 'DC0017'AS PROJECT_ID, 'PROD_PROFILE_OFFICE_PL3' AS MODEL_ID
         , DATA_DATE, 'Y' AS IS_ENABLE
    FROM APWANT.PROD_PROFILE_OFFICE_PL3
    GROUP BY DATA_DATE
    ;
    
    INSERT INTO APWANT.MODEL_HEAD
    SELECT 'DC0017'AS PROJECT_ID, 'PROD_PROFILE_PL3' AS MODEL_ID
         , DATA_DATE, 'Y' AS IS_ENABLE
    FROM APWANT.PROD_PROFILE_PL3
    GROUP BY DATA_DATE
    ;
    
    INSERT INTO APWANT.MODEL_HEAD
    SELECT 'DC0017'AS PROJECT_ID, 'PROD_SALES_INTERVAL_PL3' AS MODEL_ID
         , DATA_DATE, 'Y' AS IS_ENABLE
    FROM APWANT.PROD_SALES_INTERVAL_PL3
    GROUP BY DATA_DATE
    ;
    
    INSERT INTO APWANT.MODEL_HEAD
    SELECT 'DC0017'AS PROJECT_ID, 'PROD_SEASON' AS MODEL_ID
         , DATA_DATE, 'Y' AS IS_ENABLE
    FROM APWANT.PROD_SEASON
    GROUP BY DATA_DATE
    ;
    
    INSERT INTO APWANT.MODEL_HEAD
    SELECT 'DC0017'AS PROJECT_ID, 'PROD_SEASON_DISTRICT_PL3' AS MODEL_ID
         , DATA_DATE, 'Y' AS IS_ENABLE
    FROM APWANT.PROD_SEASON_DISTRICT_PL3
    GROUP BY DATA_DATE
    ;
    
    INSERT INTO APWANT.MODEL_HEAD
    SELECT 'DC0017'AS PROJECT_ID, 'PROD_SEASON_OFFICE_PL3' AS MODEL_ID
         , DATA_DATE, 'Y' AS IS_ENABLE
    FROM APWANT.PROD_SEASON_OFFICE_PL3
    GROUP BY DATA_DATE
    ;
    
    INSERT INTO APWANT.MODEL_HEAD
    SELECT 'DC0017'AS PROJECT_ID, 'PROD_SEASON_PL3' AS MODEL_ID
         , DATA_DATE, 'Y' AS IS_ENABLE
    FROM APWANT.PROD_SEASON_PL3
    GROUP BY DATA_DATE
    ;
    
    /*DC0018*/
    INSERT INTO APWANT.MODEL_HEAD
    SELECT 'DC0018'AS PROJECT_ID, 'OFFICE_CHANNEL_GROUP_INDICA' AS MODEL_ID
         , DATA_DATE, 'Y' AS IS_ENABLE
    FROM APWANT.OFFICE_CHANNEL_GROUP_INDICA
    GROUP BY DATA_DATE
    ;
    
    INSERT INTO APWANT.MODEL_HEAD
    SELECT 'DC0018'AS PROJECT_ID, 'OFFICE_EVAL' AS MODEL_ID
         , DATA_DATE, 'Y' AS IS_ENABLE
    FROM APWANT.OFFICE_EVAL
    GROUP BY DATA_DATE
    ;
    
    INSERT INTO APWANT.MODEL_HEAD
    SELECT 'DC0018'AS PROJECT_ID, 'OFFICE_OTHER_INDICA' AS MODEL_ID
         , DATA_DATE, 'Y' AS IS_ENABLE
    FROM APWANT.OFFICE_OTHER_INDICA
    GROUP BY DATA_DATE
    ;
    
    SET @VAR_SP_RESULT = 'Y';
    
    SET VAR_SP_RESULT=@VAR_SP_RESULT;
    COMMIT;
END
;