DROP PROCEDURE IF EXISTS APWANT.SP_APWANT_SRC_0104_SRC_PROD;

CREATE PROCEDURE APWANT.SP_APWANT_SRC_0104_SRC_PROD (
    VAR_DATA_DATE CHAR(8), VAR_UPD_USER_ID VARCHAR(8)
  , OUT VAR_SP_RESULT CHAR(1)
)
BEGIN
    SET @VAR_DATA_DATE = VAR_DATA_DATE;
    SET @VAR_UPD_USER_ID = VAR_UPD_USER_ID;
    SET @VAR_SP_RESULT = VAR_SP_RESULT;
    
    INSERT INTO APWANT.SRC_PROD
    SELECT DISTINCT PROD_LEVEL1_ID, PROD_LEVEL3_ID
         , @VAR_UPD_USER_ID AS UPD_USER_ID, NOW() AS UPD_DT
    FROM APWANT.SRC_PROD_SKU
    WHERE DATA_DATE=@VAR_DATA_DATE AND LEFT(PROD_LEVEL1_ID,1)='D'
    ;
    
    SET @VAR_SP_RESULT = 'Y';
    
    SET VAR_SP_RESULT=@VAR_SP_RESULT;
    COMMIT;
END
;
