DROP PROCEDURE IF EXISTS APWANT.SP_SYS_USER_FUN_LOG;

CREATE PROCEDURE APWANT.SP_SYS_USER_FUN_LOG (
    VAR_USER_ID VARCHAR(8), VAR_SYS_ID VARCHAR(6)
  , VAR_FUN_GROUP VARCHAR(20), VAR_FUN_ID VARCHAR(50)
  , VAR_SESSION_ID VARCHAR(40), VAR_IP_ADDRESS VARCHAR(40)
  , OUT VAR_SP_RESULT CHAR(1)
)
BEGIN
    SET @VAR_USER_ID = VAR_USER_ID;
    SET @VAR_SYS_ID = VAR_SYS_ID;
    SET @VAR_FUN_GROUP = VAR_FUN_GROUP;
    SET @VAR_FUN_ID = VAR_FUN_ID;
    SET @VAR_SESSION_ID = VAR_SESSION_ID;
    SET @VAR_IP_ADDRESS = VAR_IP_ADDRESS;
    SET @VAR_SP_RESULT = VAR_SP_RESULT;

    SET @VAR_NOW_DT = NOW();
    SET @VAR_CN = 0;

    SELECT COUNT(1) INTO @VAR_CN
    FROM SYS_USER_FUN_LOG
    WHERE USER_ID=@VAR_USER_ID AND SYS_ID=@VAR_SYS_ID
      AND FUN_GROUP=@VAR_FUN_GROUP AND FUN_ID=@VAR_FUN_ID
      AND LAST_USE_DT=@VAR_NOW_DT;

    IF @VAR_CN=0 THEN
        INSERT INTO APWANT.SYS_USER_FUN_LOG VALUES (
            @VAR_USER_ID, @VAR_SYS_ID
          , @VAR_FUN_GROUP, @VAR_FUN_ID
          , @VAR_SESSION_ID, @VAR_IP_ADDRESS
          , @VAR_NOW_DT
        );
    ELSE
        UPDATE APWANT.SYS_USER_FUN_LOG SET
            SESSION_ID=@VAR_SESSION_ID, IP_ADDRESS=@VAR_IP_ADDRESS
        WHERE USER_ID=@VAR_USER_ID AND SYS_ID=@VAR_SYS_ID
          AND FUN_GROUP=@VAR_FUN_GROUP AND FUN_ID=@VAR_FUN_ID
          AND LAST_USE_DT=@VAR_NOW_DT;
    END IF;

    SET @VAR_SP_RESULT = 'Y';

    SET VAR_SP_RESULT=@VAR_SP_RESULT;
    COMMIT;
END
;