DROP PROCEDURE IF EXISTS APWANT.SP_APWANT_SRC_0103_SRC_CHANNEL;

CREATE PROCEDURE APWANT.SP_APWANT_SRC_0103_SRC_CHANNEL (
    VAR_DATA_DATE CHAR(8), VAR_UPD_USER_ID VARCHAR(8)
  , OUT VAR_SP_RESULT CHAR(1)
)
BEGIN
    SET @VAR_DATA_DATE = VAR_DATA_DATE;
    SET @VAR_UPD_USER_ID = VAR_UPD_USER_ID;
    SET @VAR_SP_RESULT = VAR_SP_RESULT;
    
    INSERT INTO APWANT.SRC_CHANNEL
    SELECT P.PROD_GROUP_ID, P.PROD_GROUPD_ID
         , R.CHANNEL_DISTRICT8_ID, R.BRANCH_ID
         , P.OFFICE_ID
         , @VAR_UPD_USER_ID AS UPD_USER_ID, NOW() AS UPD_DT
    FROM (SELECT PROD_GROUP_ID, PROD_GROUPD_ID, OFFICE_ID
          FROM APWANT.SRC_ORG_PROD
          WHERE DATA_DATE=@VAR_DATA_DATE
          GROUP BY PROD_GROUP_ID, PROD_GROUPD_ID, OFFICE_ID) P
    JOIN (SELECT OFFICE_ID
               , MIN(CHANNEL_DISTRICT8_ID) AS CHANNEL_DISTRICT8_ID
               , MIN(BRANCH_ID) AS BRANCH_ID
          FROM APWANT.SRC_ORG_REL
          WHERE DATA_DATE=@VAR_DATA_DATE
          GROUP BY OFFICE_ID) R
    ON P.OFFICE_ID=R.OFFICE_ID
    ;
    
    SET @VAR_SP_RESULT = 'Y';
    
    SET VAR_SP_RESULT=@VAR_SP_RESULT;
    COMMIT;
END
;
