USE APWANT;

INSERT INTO APWANT.SYS_ROLE VALUES ('WANTWX','SYSADMIN','系统管理员','80005096',NOW());
INSERT INTO APWANT.SYS_ROLE VALUES ('WANTWX','TOPMAN','最高管理者','80005096',NOW());
INSERT INTO APWANT.SYS_ROLE VALUES ('WANTWX','DISTRICTMAN','大区管理者','80005096',NOW());
INSERT INTO APWANT.SYS_ROLE VALUES ('WANTWX','BRANCHMAN','分公司管理者','80005096',NOW());
INSERT INTO APWANT.SYS_ROLE VALUES ('WANTWX','OFFICEMAN','营业所管理者','80005096',NOW());
INSERT INTO APWANT.SYS_ROLE VALUES ('WANTWX','PRODMAN','产品品类管理者','80005096',NOW());

INSERT INTO APWANT.SYS_ROLE VALUES ('WANTDC','SYSADMIN','系统管理员','80005096',NOW());
