SET FOREIGN_KEY_CHECKS=0 ;

CREATE TABLE `CM_WORKDAY`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`DATA_DATE` CHAR(8) NOT NULL,
	`WORKDAY_YM` VARCHAR(6) NOT NULL,
	`WORKDAY_YMD` VARCHAR(8) NOT NULL,
	`WORKDAY_YN` VARCHAR(1) 	 NULL,
	`WORKDAYS` INT NOT NULL,
	`WORKDAY_TOTAL` INT NOT NULL,
	CONSTRAINT `PK_CM_WORKDAY` PRIMARY KEY (`WORKDAY_YMD`)
)

;

CREATE TABLE `CM_SALES_CREDIT`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`DATA_DATE` CHAR(8) NOT NULL,
	`SALES_CREDIT_ID` VARCHAR(4) NOT NULL,
	`SALES_CREDIT_NM` VARCHAR(60) 	 NULL,
	`SALES_CREDIT_DESC` VARCHAR(300) 	 NULL,
	CONSTRAINT `PK_CM_SALES_CREDIT` PRIMARY KEY (`SALES_CREDIT_ID`)
)

;

CREATE TABLE `CM_KA_SYSTEM`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`DATA_DATE` CHAR(8) NOT NULL,
	`KA_SYSTEM_ID` VARCHAR(2) NOT NULL,
	`KA_SYSTEM_NM` VARCHAR(60) 	 NULL,
	`KA_SYSTEM_CODE` VARCHAR(10) 	 NULL,
	`KA_SYSTEM_ACT` VARCHAR(10) 	 NULL,
	CONSTRAINT `PK_CM_KA_SYSTEM` PRIMARY KEY (`KA_SYSTEM_ID`)
)

;

CREATE TABLE `CM_EMP_POS_TYPE`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`DATA_DATE` CHAR(8) NOT NULL,
	`EMP_POS_TYPE` VARCHAR(3) NOT NULL,
	`EMP_POS_TYPE_NM` VARCHAR(60) 	 NULL,
	CONSTRAINT `PK_CM_EMP_POS_TYPE` PRIMARY KEY (`EMP_POS_TYPE`)
)

;

CREATE TABLE `CM_EMP_POS_TITLE`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`DATA_DATE` CHAR(8) NOT NULL,
	`EMP_POS_TITLE_ID` VARCHAR(8) NOT NULL,
	`EMP_POS_TITLE_NM` VARCHAR(60) 	 NULL,
	CONSTRAINT `PK_CM_EMP_POS_TITLE` PRIMARY KEY (`EMP_POS_TITLE_ID`)
)

;

CREATE TABLE `CM_EMP_POS_PROP`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`DATA_DATE` CHAR(8) NOT NULL,
	`EMP_POS_PROP_ID` VARCHAR(3) NOT NULL,
	`EMP_POS_PROP_NM` VARCHAR(60) 	 NULL,
	CONSTRAINT `PK_CM_EMP_POS_PROP` PRIMARY KEY (`EMP_POS_PROP_ID`)
)

;

CREATE TABLE `CM_EMP_POS_LEVEL`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`DATA_DATE` CHAR(8) NOT NULL,
	`EMP_POS_LEVEL_ID` VARCHAR(2) NOT NULL,
	`EMP_POS_LEVEL_NM` VARCHAR(60) 	 NULL,
	CONSTRAINT `PK_CM_EMP_POS_LEVEL` PRIMARY KEY (`EMP_POS_LEVEL_ID`)
)

;

CREATE TABLE `CM_EMP_POS`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`DATA_DATE` CHAR(8) NOT NULL,
	`EMP_POS_ID` VARCHAR(8) NOT NULL,
	`EMP_POS_NM` VARCHAR(60) 	 NULL,
	CONSTRAINT `PK_CM_EMP_POS` PRIMARY KEY (`EMP_POS_ID`)
)

;

CREATE TABLE `CM_CODE`
(
	`CODE_KIND` VARCHAR(10) NOT NULL,
	`CODE_ID` VARCHAR(10) NOT NULL,
	`CODE_PARENT` VARCHAR(10) 	 NULL,
	`CODE_NM` VARCHAR(150) 	 NULL,
	`IS_DELETED` CHAR(1) NOT NULL,
	`SORT_ORDER` VARCHAR(10) 	 NULL,
	`UPD_USER_ID` VARCHAR(50) NOT NULL,
	`UPD_DT` DATETIME(0) NOT NULL,
	CONSTRAINT `PK_CM_CODE` PRIMARY KEY (`CODE_KIND`,`CODE_ID`)
)

;

CREATE TABLE `CM_AREA_TWSP`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`DATA_DATE` CHAR(8) NOT NULL,
	`AREA_TWSP_ID` VARCHAR(5) NOT NULL,
	`AREA_TWSP_NM` VARCHAR(60) 	 NULL,
	`AREA_COTY_ID` VARCHAR(4) 	 NULL,
	`TOTAL_PEOPLE` INT 	 NULL,
	`STATUS` CHAR(1) 	 NULL,
	CONSTRAINT `PK_CM_AREA_TWSP` PRIMARY KEY (`AREA_TWSP_ID`)
)

;

CREATE TABLE `CM_AREA_HAME`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`DATA_DATE` CHAR(8) NOT NULL,
	`AREA_HAME_ID` VARCHAR(5) NOT NULL,
	`AREA_HAME_NM` VARCHAR(150) 	 NULL,
	`AREA_HAME_LV_ID` CHAR(12) 	 NULL,
	`AREA_TWSP_ID` VARCHAR(5) 	 NULL,
	`STATUS` CHAR(1) 	 NULL,
	CONSTRAINT `PK_CM_AREA_HAME` PRIMARY KEY (`AREA_HAME_ID`)
)

;

CREATE TABLE `CM_AREA_COTY`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`DATA_DATE` CHAR(8) NOT NULL,
	`AREA_COTY_ID` VARCHAR(4) NOT NULL,
	`AREA_COTY_NM` VARCHAR(60) 	 NULL,
	`IWANT_MARKET_ID` VARCHAR(6) 	 NULL,
	`IWANT_OFF_ID` VARCHAR(4) 	 NULL,
	CONSTRAINT `PK_CM_AREA_COTY` PRIMARY KEY (`AREA_COTY_ID`)
)

;

SET FOREIGN_KEY_CHECKS=1 ;
