SET FOREIGN_KEY_CHECKS=0 ;

CREATE TABLE `CUST_SD_SALES_COM_PROD`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`DATA_DATE` CHAR(8) NOT NULL,
	`PROD_DIV_ID` VARCHAR(2) NOT NULL,
	`PROD_MATL_ID` VARCHAR(18) NOT NULL,
	`SALES_CHAN_ID` VARCHAR(2) NOT NULL,
	`SALES_COM_ID` VARCHAR(4) NOT NULL,
	`CUST_ID` VARCHAR(15) NOT NULL,
	`SALES_DOC_ITEM_CATEG` VARCHAR(4) NOT NULL,
	`WANT_CHAN_ID` VARCHAR(10) 	 NULL,
	CONSTRAINT `PK_CUST_SD_SALES_COM_PROD` PRIMARY KEY (`SALES_CHAN_ID`,`PROD_MATL_ID`,`PROD_DIV_ID`,`SALES_COM_ID`,`SALES_DOC_ITEM_CATEG`,`CUST_ID`)
)

;

CREATE TABLE `CUST_SD_SALES_COM`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`DATA_DATE` CHAR(8) NOT NULL,
	`PROD_DIV_ID` VARCHAR(2) NOT NULL,
	`SALES_CHAN_ID` VARCHAR(2) NOT NULL,
	`SALES_COM_ID` VARCHAR(4) NOT NULL,
	`SALES_OFF_ID` VARCHAR(4) 	 NULL,
	`CUST_ID` VARCHAR(15) NOT NULL,
	`WANT_COM_ID` VARCHAR(4) 	 NULL,
	CONSTRAINT `PK_CUST_SD_SALES_COM` PRIMARY KEY (`PROD_DIV_ID`,`SALES_CHAN_ID`,`SALES_COM_ID`,`CUST_ID`)
)

;

CREATE TABLE `CUST_SD`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`DATA_DATE` CHAR(8) NOT NULL,
	`CUST_ID` VARCHAR(15) NOT NULL,
	`CUST_ACCT_GRP` VARCHAR(4) 	 NULL,
	`CUST_CLASS` VARCHAR(2) 	 NULL,
	`SALES_OFF_ID` VARCHAR(4) 	 NULL,
	`WANT_COM_ID` VARCHAR(4) 	 NULL,
	CONSTRAINT `PK_CUST_SD` PRIMARY KEY (`CUST_ID`)
)

;

CREATE TABLE `CUST_MAIN`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`DATA_DATE` CHAR(8) NOT NULL,
	`CUST_ID` VARCHAR(15) NOT NULL,
	`CUST_NM` VARCHAR(60) 	 NULL,
	`CUST_ABBR` VARCHAR(60) 	 NULL,
	CONSTRAINT `PK_CUST_MAIN` PRIMARY KEY (`CUST_ID`)
)

;

CREATE TABLE `CUST_IWANT_MARKET_PROD`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`DATA_DATE` CHAR(8) NOT NULL,
	`SEQ_NO` VARCHAR(10) NOT NULL,
	`MARKET_SEQ_NO` VARCHAR(10) NOT NULL,
	`PROD_LINE_ID` VARCHAR(20) NOT NULL,
	CONSTRAINT `PK_CUST_IWANT_MARKET_PROD` PRIMARY KEY (`MARKET_SEQ_NO`,`PROD_LINE_ID`)
)

;

CREATE TABLE `CUST_IWANT_MARKET`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`DATA_DATE` CHAR(8) NOT NULL,
	`SEQ_NO` VARCHAR(10) NOT NULL,
	`CUST_ID` VARCHAR(15) NOT NULL,
	`MARKET_TYPE` CHAR(1) NOT NULL,
	`IWANT_MARKET_ID` VARCHAR(6) NOT NULL,
	`IWANT_MARKET_SMALL_ID` VARCHAR(9) 	 NULL,
	`IWANT_CHAN_ID` VARCHAR(4) NOT NULL,
	`START_YMD` CHAR(8) NOT NULL,
	`END_YMD` CHAR(8) NOT NULL,
	CONSTRAINT `PK_CUST_IWANT_MARKET` PRIMARY KEY (`SEQ_NO`)
)

;

CREATE TABLE `CUST_IWANT_EMP_SALES`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`DATA_DATE` CHAR(8) NOT NULL,
	`CUST_ID` VARCHAR(15) NOT NULL,
	`IWANT_CHAN_ID` VARCHAR(4) NOT NULL,
	`EMP_ID` VARCHAR(8) NOT NULL,
	`EMP_POS_TYPE` VARCHAR(3) NOT NULL,
	`EMP_IWANT_COM_ID` VARCHAR(3) 	 NULL,
	`EMP_IWANT_OFF_ID` VARCHAR(4) 	 NULL,
	`START_YMD` CHAR(8) NOT NULL,
	`END_YMD` CHAR(8) NOT NULL,
	`STATUS` CHAR(1) NOT NULL,
	`EMP_SALES_MARKET_SEQ_NO` VARCHAR(10) 	 NULL,
	CONSTRAINT `PK_CUST_IWANT_EMP_SALES` PRIMARY KEY (`CUST_ID`,`IWANT_CHAN_ID`,`EMP_ID`,`EMP_POS_TYPE`,`START_YMD`,`END_YMD`)
)

;

CREATE TABLE `CUST_IWANT`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`DATA_DATE` CHAR(8) NOT NULL,
	`CUST_ID` VARCHAR(15) NOT NULL,
	`CUST_DESC` VARCHAR(300) 	 NULL,
	`CUST_OWNER_NM` VARCHAR(60) 	 NULL,
	`CUST_PARENT_ID` VARCHAR(10) 	 NULL,
	`IWANT_OFF_ID` VARCHAR(4) 	 NULL,
	`AREA_COTY_ID` VARCHAR(4) 	 NULL,
	CONSTRAINT `PK_CUST_IWANT` PRIMARY KEY (`CUST_ID`)
)

;

SET FOREIGN_KEY_CHECKS=1 ;
