SET FOREIGN_KEY_CHECKS=0 ;

CREATE TABLE `EDI_JOB`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`EDI_JOB_ID` VARCHAR(100) NOT NULL,
	`EDI_JOB_TYPE` VARCHAR(50) NOT NULL,
	`EDI_OBJ_NM` VARCHAR(100) 	 NULL,
	`EDI_DEP_JOB_ID` VARCHAR(100) 	 NULL,
	`STATUS_ID` VARCHAR(10) NOT NULL,
	`RESULT_ID` VARCHAR(10) 	 NULL,
	`DT_BEGIN` DATETIME(0) 	 NULL,
	`DT_END` DATETIME(0) 	 NULL,
	`DATA_COUNT` INT 	 NULL,
	`DATA_VOLUME` BIGINT 	 UNSIGNED NULL,
	`DATA_COUNT_DIF` INT 	 NULL,
	`UPD_USER_ID` VARCHAR(50) NOT NULL,
	`UPD_DT` DATETIME(0) NOT NULL,
	CONSTRAINT `PK_EDI_JOB` PRIMARY KEY (`EDI_NO`,`EDI_JOB_ID`)
)

;

CREATE TABLE `EDI_FLOW_DWWANT_KA`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`POS_DATE_MIN` CHAR(8) NOT NULL,
	`POS_DATE_MAX` CHAR(8) NOT NULL,
	`INV_DATE_MIN` CHAR(8) NOT NULL,
	`INV_DATE_MAX` CHAR(8) NOT NULL,
	CONSTRAINT `PK_EDI_FLOW_DWWANT_KA` PRIMARY KEY (`EDI_NO`)
)

;

CREATE TABLE `EDI_FLOW`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`EDI_ID` VARCHAR(6) NOT NULL,
	`EDI_FLOW_ID` VARCHAR(50) NOT NULL,
	`EDI_DATE` CHAR(8) 	 NULL,
	`EDI_TIME` CHAR(9) 	 NULL,
	`DATA_DATE` CHAR(8) NOT NULL,
	`STATUS_ID` VARCHAR(10) NOT NULL,
	`RESULT_ID` VARCHAR(10) 	 NULL,
	`DT_BEGIN` DATETIME(0) 	 NULL,
	`DT_END` DATETIME(0) 	 NULL,
	`IS_AUTOMATIC` CHAR(1) NOT NULL,
	`AUTO_SCHEDULE` DATETIME(0) 	 NULL,
	`AUTO_EDI_NO` CHAR(12) 	 NULL,
	`IS_DELETED` CHAR(1) NOT NULL,
	`UPD_USER_ID` VARCHAR(50) NOT NULL,
	`UPD_DT` DATETIME(0) NOT NULL,
	CONSTRAINT `PK_EDI_FLOW` PRIMARY KEY (`EDI_NO`)
)

;

SET FOREIGN_KEY_CHECKS=1 ;
