SET FOREIGN_KEY_CHECKS=0 ;

CREATE TABLE `ORDR_REQ_CUST_TT`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`DATA_DATE` CHAR(8) NOT NULL,
	`REQ_YM` CHAR(6) NOT NULL,
	`PROD_MATL_ID` VARCHAR(18) NOT NULL,
	`PROD_DIV_ID` VARCHAR(2) NOT NULL,
	`SALES_CHAN_ID` VARCHAR(2) NOT NULL,
	`IWANT_CHAN_ID` VARCHAR(4) NOT NULL,
	`IWANT_COM_ID` VARCHAR(3) NOT NULL,
	`AREA_COTY_ID` VARCHAR(4) NOT NULL,
	`CUST_ID` VARCHAR(15) NOT NULL,
	`REQ_QTY_PKG` DECIMAL(21,4) NOT NULL,
	`REQ_AMT` DECIMAL(21,4) NOT NULL,
	`REQ_QTY_PKG_NEXT` DECIMAL(21,4) NOT NULL,
	`REQ_AMT_NEXT` DECIMAL(21,4) NOT NULL,
	CONSTRAINT `PK_ORDR_REQ_CUST_TT` PRIMARY KEY (`REQ_YM`,`PROD_MATL_ID`,`IWANT_CHAN_ID`,`CUST_ID`)
)

;

CREATE TABLE `ORDR_REQ_CUST_KA`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`DATA_DATE` CHAR(8) NOT NULL,
	`REQ_YM` CHAR(6) NOT NULL,
	`PROD_MATL_ID` VARCHAR(18) NOT NULL,
	`PROD_DIV_ID` VARCHAR(2) NOT NULL,
	`SALES_CHAN_ID` VARCHAR(2) NOT NULL,
	`IWANT_CHAN_ID` VARCHAR(4) NOT NULL,
	`IWANT_COM_ID` VARCHAR(3) NOT NULL,
	`AREA_COTY_ID` VARCHAR(4) NOT NULL,
	`KA_SYSTEM_ID` VARCHAR(2) NOT NULL,
	`TERM_ID` VARCHAR(10) NOT NULL,
	`CUST_ID` VARCHAR(15) 	 NULL,
	`CUST_ID_WH` VARCHAR(15) 	 NULL,
	`REQ_QTY_PKG` DECIMAL(21,4) NOT NULL,
	`REQ_AMT` DECIMAL(21,4) NOT NULL,
	`REQ_QTY_PKG_NEXT` DECIMAL(21,4) NOT NULL,
	`REQ_AMT_NEXT` DECIMAL(21,4) NOT NULL,
	CONSTRAINT `PK_ORDR_REQ_CUST_KA` PRIMARY KEY (`REQ_YM`,`PROD_MATL_ID`,`TERM_ID`)
)

;

CREATE TABLE `ORDR_REQ_COM`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`DATA_DATE` CHAR(8) NOT NULL,
	`REQ_YM` CHAR(6) NOT NULL,
	`PROD_MATL_ID` VARCHAR(18) NOT NULL,
	`PROD_DIV_ID` VARCHAR(2) NOT NULL,
	`SALES_CHAN_ID` VARCHAR(2) NOT NULL,
	`IWANT_CHAN_ID` VARCHAR(4) NOT NULL,
	`IWANT_COM_ID` VARCHAR(3) NOT NULL,
	`IWANT_REGN_ID` VARCHAR(3) NOT NULL,
	`REQ_QTY_PKG` DECIMAL(21,4) NOT NULL,
	`REQ_AMT` DECIMAL(21,4) NOT NULL,
	`REQ_QTY_PKG_NEXT` DECIMAL(21,4) NOT NULL,
	`REQ_AMT_NEXT` DECIMAL(21,4) NOT NULL,
	CONSTRAINT `PK_ORDR_REQ_COM` PRIMARY KEY (`REQ_YM`,`PROD_MATL_ID`,`IWANT_CHAN_ID`,`IWANT_COM_ID`,`IWANT_REGN_ID`)
)

;

CREATE TABLE `ORDR_REQ`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`DATA_DATE` CHAR(8) NOT NULL,
	`REQ_YM` CHAR(6) NOT NULL,
	`WANT_CHAN_ID` VARCHAR(10) NOT NULL,
	`WANT_COM_ID` VARCHAR(4) NOT NULL,
	`SALES_OFF_ID` VARCHAR(4) 	 NULL,
	`PROD_MATL_ID` VARCHAR(18) NOT NULL,
	`CUST_ID` VARCHAR(15) NOT NULL,
	`KA_SYSTEM_ID` VARCHAR(2) 	 NULL,
	`REQ_QTY_PKG` DECIMAL(21,4) NOT NULL,
	`REQ_AMT` DECIMAL(21,4) NOT NULL,
	`REQ_QTY_PKG_NEXT` DECIMAL(21,4) NOT NULL,
	`REQ_AMT_NEXT` DECIMAL(21,4) NOT NULL,
	CONSTRAINT `PK_ORDR_REQ` PRIMARY KEY (`REQ_YM`,`WANT_CHAN_ID`,`WANT_COM_ID`,`PROD_MATL_ID`,`CUST_ID`)
)

;

CREATE TABLE `ORDR_KA_SYS`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`DATA_DATE` CHAR(8) NOT NULL,
	`ORDR_SEQ` BIGINT NOT NULL,
	`ORDR_MAIN_ID` VARCHAR(40) NOT NULL,
	`KA_SYSTEM_CODE` VARCHAR(10) NOT NULL,
	`SYSTEM_ACCT` VARCHAR(50) NOT NULL,
	`SYSTEM_ACCT_INFO` VARCHAR(100) 	 NULL,
	`SYSTEM_STORE_WH_CODE` VARCHAR(10) 	 NULL,
	`SYSTEM_STORE_WH_NM` VARCHAR(150) 	 NULL,
	`SYSTEM_DEV_CODE` VARCHAR(10) 	 NULL,
	`SYSTEM_DEV_NM` VARCHAR(150) 	 NULL,
	`SYSTEM_ORDR_CAT` VARCHAR(100) 	 NULL,
	`SYSTEM_ORDR_INFO` VARCHAR(100) 	 NULL,
	`CUST_ID` VARCHAR(15) 	 NULL,
	`CUST_ID_DE` VARCHAR(15) 	 NULL,
	`CUST_NM_DE` VARCHAR(150) 	 NULL,
	`SALES_COM_ID_DE` VARCHAR(4) 	 NULL,
	`SALES_COM_ID_BL` VARCHAR(4) 	 NULL,
	`SALES_CHAN_ID` VARCHAR(2) 	 NULL,
	`PROD_DIV_ID` VARCHAR(2) 	 NULL,
	`SYSTEM_ORDR_NO` VARCHAR(64) NOT NULL,
	`SYSTEM_ORDR_DATE` CHAR(8) NOT NULL,
	`SYSTEM_DEV_TIME` CHAR(14) 	 NULL,
	`SYSTEM_ORDR_TYPE` VARCHAR(10) 	 NULL,
	`SYSTEM_GOOD_AGE` INT 	 NULL,
	`ORDR_LINE_NUM` INT NOT NULL,
	`SYSTEM_PROD_CODE` VARCHAR(20) 	 NULL,
	`SYSTEM_ORDR_PROD_CODE` VARCHAR(20) NOT NULL,
	`SYSTEM_ORDR_PROD_NM` VARCHAR(150) NOT NULL,
	`PROD_MATL_ID` VARCHAR(18) 	 NULL,
	`PROD_IS_SELL_TERM` CHAR(1) 	 NULL,
	`PROD_ALLOW_DATE` CHAR(8) 	 NULL,
	`SYSTEM_PROD_SPEC` VARCHAR(100) 	 NULL,
	`SYSTEM_SKU_UNIT` VARCHAR(20) 	 NULL,
	`SYSTEM_SKU_PER_PKG` DECIMAL(21,4) 	 NULL,
	`SYSTEM_SKU_AMT` DECIMAL(21,4) 	 NULL,
	`SYSTEM_SKU_QTY` DECIMAL(21,4) 	 NULL,
	`PROD_AMT_PKG` DECIMAL(21,4) 	 NULL,
	`PROD_QTY_PKG` DECIMAL(21,4) 	 NULL,
	`ORDR_STATUS` VARCHAR(10) NOT NULL,
	`ORDR_IS_INVALID` CHAR(1) NOT NULL,
	`ORDR_INVALID_RMK` VARCHAR(200) 	 NULL,
	`ORDR_LINE_IS_INVALID` CHAR(1) NOT NULL,
	`ORDR_LINE_RESIDUAL_TYPE` VARCHAR(10) 	 NULL,
	CONSTRAINT `PK_ORDR_KA_SYS` PRIMARY KEY (`ORDR_MAIN_ID`,`ORDR_LINE_NUM`)
)

;

CREATE TABLE `ORDR_KA`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`DATA_DATE` CHAR(8) NOT NULL,
	`ORDR_MAIN_ID` VARCHAR(40) NOT NULL,
	`KA_SYSTEM_CODE` VARCHAR(10) NOT NULL,
	`CUST_ID` VARCHAR(15) 	 NULL,
	`SALES_COM_ID_DE` VARCHAR(4) 	 NULL,
	`SALES_COM_ID_BL` VARCHAR(4) 	 NULL,
	`SALES_CHAN_ID` VARCHAR(2) 	 NULL,
	`PROD_DIV_ID` VARCHAR(2) 	 NULL,
	`SYSTEM_ORDR_NO` VARCHAR(64) NOT NULL,
	`SYSTEM_ORDR_DATE` CHAR(8) NOT NULL,
	`SYSTEM_DEV_TIME` CHAR(14) 	 NULL,
	`ORDR_LINE_NUM` INT NOT NULL,
	`SYSTEM_ORDR_PROD_NM` VARCHAR(150) NOT NULL,
	`PROD_MATL_ID` VARCHAR(18) 	 NULL,
	`PROD_AMT_PKG` DECIMAL(21,4) 	 NULL,
	`PROD_QTY_PKG` DECIMAL(21,4) 	 NULL,
	`ORDR_STATUS` VARCHAR(10) NOT NULL,
	`ORDR_IS_INVALID` CHAR(1) NOT NULL,
	`ORDR_INVALID_RMK` VARCHAR(200) 	 NULL,
	`ORDR_LINE_IS_INVALID` CHAR(1) NOT NULL,
	`ORDR_LINE_RESIDUAL_TYPE` VARCHAR(10) 	 NULL,
	`SAP_QTY_PKG_APPD_SUM` DECIMAL(21,4) 	 NULL,
	`SAP_QTY_PKG_APPD_SUM_DIR` DECIMAL(21,4) 	 NULL,
	`SAP_QTY_PKG_APPD_SUM_DIF` DECIMAL(21,4) 	 NULL,
	`SHIP_QTY_PKG_DEV_SUM` INT 	 NULL,
	`SHIP_QTY_PKG_DIF_SUM` INT 	 NULL,
	`SHIP_QTY_PKG_ACT_SUM` INT 	 NULL,
	`SHIP_QTY_PKG_ACT_SUM_DIF` DECIMAL(21,4) 	 NULL,
	`TRAS_OPEN_ORDR_DATE` CHAR(8) 	 NULL,
	`TRAS_PROD_AMT_PKG` DECIMAL(21,4) 	 NULL,
	`TRAS_RETURN_PHASE` VARCHAR(10) 	 NULL,
	`TRAS_RETURN_RMK` VARCHAR(200) 	 NULL,
	`TRAS_RETURN_LINE_TIME` CHAR(14) 	 NULL,
	CONSTRAINT `PK_ORDR_KA` PRIMARY KEY (`ORDR_MAIN_ID`,`ORDR_LINE_NUM`)
)

;

SET FOREIGN_KEY_CHECKS=1 ;
