SET FOREIGN_KEY_CHECKS=0 ;

CREATE TABLE `TRAS_KA_POS_STORE_M`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`DATA_DATE` CHAR(8) NOT NULL,
	`KA_SYSTEM_CODE` VARCHAR(10) NOT NULL,
	`KA_STORE_CODE` VARCHAR(4) NOT NULL,
	`KA_STORE_NM` VARCHAR(150) NOT NULL,
	`SALES_COM_ID_SA` VARCHAR(4) NOT NULL,
	`SALES_COM_ID_WH` VARCHAR(4) NOT NULL,
	`SALES_COM_ID_DE` VARCHAR(4) NOT NULL,
	`POS_YM` CHAR(6) NOT NULL,
	`POS_QTY_PCS_D` DECIMAL(21,4) NOT NULL,
	`POS_QTY_PKG_D` DECIMAL(21,4) NOT NULL,
	`POS_AMT_D` DECIMAL(21,4) NOT NULL,
	`POS_QTY_PCS_M` DECIMAL(21,4) NOT NULL,
	`POS_QTY_PKG_M` DECIMAL(21,4) NOT NULL,
	`POS_AMT_M` DECIMAL(21,4) NOT NULL,
	CONSTRAINT `PK_TRAS_KA_POS_STORE_M` PRIMARY KEY (`POS_YM`,`KA_SYSTEM_CODE`,`KA_STORE_CODE`)
)

;

CREATE TABLE `TRAS_KA_POS_MATL_W`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`DATA_DATE` CHAR(8) NOT NULL,
	`KA_SYSTEM_CODE` VARCHAR(10) NOT NULL,
	`KA_STORE_CODE` VARCHAR(4) NOT NULL,
	`KA_STORE_NM` VARCHAR(150) NOT NULL,
	`SALES_COM_ID_SA` VARCHAR(4) NOT NULL,
	`SALES_COM_ID_WH` VARCHAR(4) NOT NULL,
	`SALES_COM_ID_DE` VARCHAR(4) NOT NULL,
	`PROD_MATL_ID` VARCHAR(18) NOT NULL,
	`POS_WEEK_NUM` CHAR(6) NOT NULL,
	`POS_WEEK_FIRST_DATE` CHAR(8) NOT NULL,
	`POS_WEEK_LAST_DATE` CHAR(8) NOT NULL,
	`POS_QTY_PCS` DECIMAL(21,4) NOT NULL,
	`POS_QTY_PKG` DECIMAL(21,4) NOT NULL,
	`POS_AMT` DECIMAL(21,4) NOT NULL,
	CONSTRAINT `PK_TRAS_KA_POS_MATL_W` PRIMARY KEY (`POS_WEEK_NUM`,`KA_SYSTEM_CODE`,`PROD_MATL_ID`,`KA_STORE_CODE`)
)

;

CREATE TABLE `TRAS_KA_POS_MATL_M`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`DATA_DATE` CHAR(8) NOT NULL,
	`KA_SYSTEM_CODE` VARCHAR(10) NOT NULL,
	`KA_STORE_CODE` VARCHAR(4) NOT NULL,
	`KA_STORE_NM` VARCHAR(150) NOT NULL,
	`SALES_COM_ID_SA` VARCHAR(4) NOT NULL,
	`SALES_COM_ID_WH` VARCHAR(4) NOT NULL,
	`SALES_COM_ID_DE` VARCHAR(4) NOT NULL,
	`PROD_MATL_ID` VARCHAR(18) NOT NULL,
	`POS_YM` CHAR(6) NOT NULL,
	`POS_QTY_PCS_D` DECIMAL(21,4) NOT NULL,
	`POS_QTY_PKG_D` DECIMAL(21,4) NOT NULL,
	`POS_AMT_D` DECIMAL(21,4) NOT NULL,
	`POS_QTY_PCS_M` DECIMAL(21,4) NOT NULL,
	`POS_QTY_PKG_M` DECIMAL(21,4) NOT NULL,
	`POS_AMT_M` DECIMAL(21,4) NOT NULL,
	CONSTRAINT `PK_TRAS_KA_POS_MATL_M` PRIMARY KEY (`POS_YM`,`KA_SYSTEM_CODE`,`PROD_MATL_ID`,`KA_STORE_CODE`)
)

;

CREATE TABLE `TRAS_KA_POS_MATL_D`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`DATA_DATE` CHAR(8) NOT NULL,
	`KA_SYSTEM_CODE` VARCHAR(10) NOT NULL,
	`KA_STORE_CODE` VARCHAR(4) NOT NULL,
	`KA_STORE_NM` VARCHAR(150) NOT NULL,
	`SALES_COM_ID_SA` VARCHAR(4) NOT NULL,
	`SALES_COM_ID_WH` VARCHAR(4) NOT NULL,
	`SALES_COM_ID_DE` VARCHAR(4) NOT NULL,
	`PROD_MATL_ID` VARCHAR(18) NOT NULL,
	`POS_DATE` CHAR(8) NOT NULL,
	`POS_QTY_PCS` DECIMAL(21,4) NOT NULL,
	`POS_QTY_PKG` DECIMAL(21,4) NOT NULL,
	`POS_AMT` DECIMAL(21,4) NOT NULL,
	CONSTRAINT `PK_TRAS_KA_POS_MATL_D` PRIMARY KEY (`POS_DATE`,`KA_SYSTEM_CODE`,`PROD_MATL_ID`,`KA_STORE_CODE`)
)

;

CREATE TABLE `TRAS_KA_POS`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`DATA_DATE` CHAR(8) NOT NULL,
	`POS_SEQ` BIGINT NOT NULL,
	`KA_SYSTEM_CODE` VARCHAR(10) NOT NULL,
	`SYSTEM_ACCT` VARCHAR(50) NOT NULL,
	`SYSTEM_ACCT_INFO` VARCHAR(100) 	 NULL,
	`SYSTEM_STORE_CODE` VARCHAR(10) 	 NULL,
	`SYSTEM_STORE_NM` VARCHAR(150) 	 NULL,
	`KA_STORE_CODE` VARCHAR(4) 	 NULL,
	`KA_STORE_NM` VARCHAR(150) 	 NULL,
	`SALES_COM_ID_SA` VARCHAR(4) 	 NULL,
	`SALES_COM_ID_WH` VARCHAR(4) 	 NULL,
	`SALES_COM_ID_DE` VARCHAR(4) 	 NULL,
	`SYSTEM_PROD_CODE` VARCHAR(20) 	 NULL,
	`SYSTEM_PROD_NM` VARCHAR(150) 	 NULL,
	`SYSTEM_PROD_SPEC` VARCHAR(50) 	 NULL,
	`SYSTEM_PROD_UNIT` VARCHAR(10) 	 NULL,
	`KA_PROD_SEQ` INT 	 NULL,
	`PROD_MATL_ID` VARCHAR(18) 	 NULL,
	`POS_CRAWL_DATE` CHAR(8) NOT NULL,
	`POS_CRAWL_TIME` CHAR(6) NOT NULL,
	`POS_SOURCE` CHAR(1) NOT NULL,
	`POS_STATUS` CHAR(1) NOT NULL,
	`POS_TYPE` CHAR(1) NOT NULL,
	`POS_SETTLE_TYPE` CHAR(1) NOT NULL,
	`POS_DATE` CHAR(8) NOT NULL,
	`POS_QTY_PCS` DECIMAL(21,4) 	 NULL,
	`POS_QTY_PKG` DECIMAL(21,4) 	 NULL,
	`POS_AMT` DECIMAL(21,4) 	 NULL,
	CONSTRAINT `PK_TRAS_KA_POS` PRIMARY KEY (`POS_SEQ`)
)

;

CREATE TABLE `TRAS_KA_ORDR_SHIP_D`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`DATA_DATE` CHAR(8) NOT NULL,
	`SHIP_D_SEQ` BIGINT NOT NULL,
	`SAP_ORDR_NO` VARCHAR(20) NOT NULL,
	`SAP_LINE_NUM` INT NOT NULL,
	`SHIP_QTY_PKG_DEV` INT NOT NULL,
	`SHIP_QTY_PKG_DIF` INT NOT NULL,
	`SHIP_QTY_PKG_ACT` INT NOT NULL,
	`SHIP_ACT_DATE` CHAR(8) NOT NULL,
	`SHIP_REC_DATE` CHAR(8) NOT NULL,
	`SHIP_USER` VARCHAR(8) NOT NULL,
	`RETURN_LINE_TIME` CHAR(14) NOT NULL,
	`RETURN_LINE_RMK` VARCHAR(200) 	 NULL,
	CONSTRAINT `PK_TRAS_KA_ORDR_SHIP_D` PRIMARY KEY (`SHIP_D_SEQ`)
)

;

CREATE TABLE `TRAS_KA_ORDR_SHIP`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`DATA_DATE` CHAR(8) NOT NULL,
	`SAP_ORDR_NO` VARCHAR(20) NOT NULL,
	`SAP_LINE_NUM` INT NOT NULL,
	`SHIP_QTY_PKG_DEV` INT NOT NULL,
	`SHIP_QTY_PKG_DIF` INT NOT NULL,
	`SHIP_QTY_PKG_ACT` INT NOT NULL,
	`SHIP_ACT_DATE` CHAR(8) NOT NULL,
	`SHIP_REC_DATE` CHAR(8) NOT NULL,
	`SHIP_USER` VARCHAR(8) NOT NULL,
	`RETURN_LINE_TIME` CHAR(14) NOT NULL,
	`RETURN_LINE_RMK` VARCHAR(200) 	 NULL,
	CONSTRAINT `PK_TRAS_KA_ORDR_SHIP` PRIMARY KEY (`SAP_ORDR_NO`,`SAP_LINE_NUM`)
)

;

CREATE TABLE `TRAS_KA_ORDR_OPEN_M`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`DATA_DATE` CHAR(8) NOT NULL,
	`OPEN_SEQ` BIGINT NOT NULL,
	`OPEN_NO` VARCHAR(15) NOT NULL,
	`CHECK_NO` VARCHAR(15) NOT NULL,
	`ORDR_MAIN_ID` VARCHAR(40) NOT NULL,
	`SYSTEM_ORDR_NO` VARCHAR(64) NOT NULL,
	`CUST_ID` VARCHAR(15) NOT NULL,
	`CUST_ID_DE` VARCHAR(15) NOT NULL,
	`SALES_COM_ID_DE` VARCHAR(4) 	 NULL,
	`SALES_COM_ID_BL` VARCHAR(4) NOT NULL,
	`SALES_CHAN_ID` VARCHAR(2) NOT NULL,
	`PROD_DIV_ID` VARCHAR(2) NOT NULL,
	`IS_FACT_DEV` CHAR(1) NOT NULL,
	`OPEN_ORDR_DATE` CHAR(8) NOT NULL,
	`OPEN_STATUS` VARCHAR(10) NOT NULL,
	`OPEN_USER` VARCHAR(8) NOT NULL,
	`OPEN_TIME` CHAR(14) NOT NULL,
	`RETURN_TIME` CHAR(14) NOT NULL,
	`RETURN_RMK` VARCHAR(200) 	 NULL,
	`SAP_ORDR_NO` VARCHAR(10) 	 NULL,
	CONSTRAINT `PK_TRAS_KA_ORDR_OPEN_M` PRIMARY KEY (`OPEN_NO`)
)

;

CREATE TABLE `TRAS_KA_ORDR_OPEN_D`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`DATA_DATE` CHAR(8) NOT NULL,
	`OPEN_D_SEQ` BIGINT NOT NULL,
	`OPEN_NO` VARCHAR(15) NOT NULL,
	`ORDR_LINE_NUM` INT NOT NULL,
	`PROD_MATL_ID` VARCHAR(18) NOT NULL,
	`PROD_MATL_ID_REPL` VARCHAR(18) 	 NULL,
	`PROD_AMT_PKG` DECIMAL(21,4) NOT NULL,
	`PROD_QTY_PKG` DECIMAL(21,4) NOT NULL,
	`STORE_PLACE_CODE` VARCHAR(4) 	 NULL,
	`RETURN_LINE_RMK` VARCHAR(200) 	 NULL,
	`SAP_LINE_NUM` INT NOT NULL,
	`SAP_AMT_PKG` DECIMAL(21,4) NOT NULL,
	`SAP_QTY_PKG` DECIMAL(21,4) NOT NULL,
	CONSTRAINT `PK_TRAS_KA_ORDR_OPEN_D` PRIMARY KEY (`OPEN_NO`,`ORDR_LINE_NUM`)
)

;

CREATE TABLE `TRAS_KA_ORDR_OPEN_AMT`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`DATA_DATE` CHAR(8) NOT NULL,
	`CUST_ID` VARCHAR(15) NOT NULL,
	`OPEN_ORDR_DATE` CHAR(8) NOT NULL,
	`PROD_MATL_ID` VARCHAR(18) NOT NULL,
	`SAP_AMT_PKG` DECIMAL(21,4) NOT NULL,
	CONSTRAINT `PK_TRAS_KA_ORDR_OPEN_AMT` PRIMARY KEY (`CUST_ID`,`OPEN_ORDR_DATE`,`PROD_MATL_ID`)
)

;

CREATE TABLE `TRAS_KA_ORDR_OPEN`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`DATA_DATE` CHAR(8) NOT NULL,
	`OPEN_NO` VARCHAR(15) NOT NULL,
	`CHECK_NO` VARCHAR(15) NOT NULL,
	`ORDR_MAIN_ID` VARCHAR(40) NOT NULL,
	`SYSTEM_ORDR_NO` VARCHAR(64) NOT NULL,
	`CUST_ID` VARCHAR(15) NOT NULL,
	`CUST_ID_DE` VARCHAR(15) NOT NULL,
	`SALES_COM_ID_DE` VARCHAR(4) 	 NULL,
	`SALES_COM_ID_BL` VARCHAR(4) NOT NULL,
	`SALES_CHAN_ID` VARCHAR(2) NOT NULL,
	`PROD_DIV_ID` VARCHAR(2) NOT NULL,
	`IS_FACT_DEV` CHAR(1) NOT NULL,
	`OPEN_ORDR_DATE` CHAR(8) NOT NULL,
	`OPEN_STATUS` VARCHAR(10) NOT NULL,
	`OPEN_USER` VARCHAR(8) NOT NULL,
	`OPEN_TIME` CHAR(14) NOT NULL,
	`RETURN_TIME` CHAR(14) NOT NULL,
	`RETURN_RMK` VARCHAR(200) 	 NULL,
	`SAP_ORDR_NO` VARCHAR(10) 	 NULL,
	`ORDR_LINE_NUM` INT NOT NULL,
	`PROD_MATL_ID` VARCHAR(18) NOT NULL,
	`PROD_MATL_ID_REPL` VARCHAR(18) 	 NULL,
	`PROD_AMT_PKG` DECIMAL(21,4) NOT NULL,
	`PROD_QTY_PKG` DECIMAL(21,4) NOT NULL,
	`STORE_PLACE_CODE` VARCHAR(4) 	 NULL,
	`RETURN_LINE_RMK` VARCHAR(200) 	 NULL,
	`SAP_LINE_NUM` INT NOT NULL,
	`SAP_AMT_PKG` DECIMAL(21,4) NOT NULL,
	`SAP_QTY_PKG` DECIMAL(21,4) NOT NULL,
	CONSTRAINT `PK_TRAS_KA_ORDR_OPEN` PRIMARY KEY (`OPEN_NO`,`ORDR_LINE_NUM`)
)

;

CREATE TABLE `TRAS_KA_ORDR_CHECK_M`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`DATA_DATE` CHAR(8) NOT NULL,
	`CHECK_SEQ` BIGINT NOT NULL,
	`CHECK_NO` VARCHAR(15) NOT NULL,
	`ORDR_MAIN_ID` VARCHAR(40) NOT NULL,
	`SYSTEM_ORDR_NO` VARCHAR(64) NOT NULL,
	`CUST_ID` VARCHAR(15) NOT NULL,
	`CUST_ID_DE` VARCHAR(15) NOT NULL,
	`SALES_COM_ID_DE` VARCHAR(4) 	 NULL,
	`SALES_COM_ID_BL` VARCHAR(4) NOT NULL,
	`SALES_CHAN_ID` VARCHAR(2) NOT NULL,
	`PROD_DIV_ID` VARCHAR(2) NOT NULL,
	`IS_FACT_DEV` CHAR(1) NOT NULL,
	`OPEN_ORDR_DATE` CHAR(8) NOT NULL,
	`CHECK_STATUS` VARCHAR(10) NOT NULL,
	`CHECK_USER` VARCHAR(8) 	 NULL,
	`CHECK_TIME` CHAR(14) NOT NULL,
	`RETURN_TIME` CHAR(14) NOT NULL,
	`IS_OVER_DUE` CHAR(1) NOT NULL,
	CONSTRAINT `PK_TRAS_KA_ORDR_CHECK_M` PRIMARY KEY (`CHECK_NO`)
)

;

CREATE TABLE `TRAS_KA_ORDR_CHECK_D`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`DATA_DATE` CHAR(8) NOT NULL,
	`CHECK_D_SEQ` BIGINT NOT NULL,
	`CHECK_NO` VARCHAR(15) NOT NULL,
	`ORDR_LINE_NUM` INT NOT NULL,
	`PROD_MATL_ID` VARCHAR(18) NOT NULL,
	`PROD_MATL_ID_REPL` VARCHAR(18) 	 NULL,
	`PROD_IS_SELL_TERM` CHAR(1) 	 NULL,
	`PROD_ALLOW_DATE` CHAR(8) NOT NULL,
	`PROD_AMT_PKG` DECIMAL(21,4) NOT NULL,
	`PROD_QTY_PKG` DECIMAL(21,4) NOT NULL,
	`RETURN_LINE_RMK` VARCHAR(200) 	 NULL,
	`RETURN_DIST_RMK` VARCHAR(200) 	 NULL,
	CONSTRAINT `PK_TRAS_KA_ORDR_CHECK_D` PRIMARY KEY (`CHECK_NO`,`ORDR_LINE_NUM`)
)

;

CREATE TABLE `TRAS_KA_ORDR_CHECK`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`DATA_DATE` CHAR(8) NOT NULL,
	`CHECK_NO` VARCHAR(15) NOT NULL,
	`ORDR_MAIN_ID` VARCHAR(40) NOT NULL,
	`SYSTEM_ORDR_NO` VARCHAR(64) NOT NULL,
	`CUST_ID` VARCHAR(15) NOT NULL,
	`CUST_ID_DE` VARCHAR(15) NOT NULL,
	`SALES_COM_ID_DE` VARCHAR(4) 	 NULL,
	`SALES_COM_ID_BL` VARCHAR(4) NOT NULL,
	`SALES_CHAN_ID` VARCHAR(2) NOT NULL,
	`PROD_DIV_ID` VARCHAR(2) NOT NULL,
	`IS_FACT_DEV` CHAR(1) NOT NULL,
	`OPEN_ORDR_DATE` CHAR(8) NOT NULL,
	`CHECK_STATUS` VARCHAR(10) NOT NULL,
	`CHECK_USER` VARCHAR(8) 	 NULL,
	`CHECK_TIME` CHAR(14) NOT NULL,
	`RETURN_TIME` CHAR(14) NOT NULL,
	`IS_OVER_DUE` CHAR(1) NOT NULL,
	`ORDR_LINE_NUM` INT NOT NULL,
	`PROD_MATL_ID` VARCHAR(18) NOT NULL,
	`PROD_MATL_ID_REPL` VARCHAR(18) 	 NULL,
	`PROD_IS_SELL_TERM` CHAR(1) 	 NULL,
	`PROD_ALLOW_DATE` CHAR(8) NOT NULL,
	`PROD_AMT_PKG` DECIMAL(21,4) NOT NULL,
	`PROD_QTY_PKG` DECIMAL(21,4) NOT NULL,
	`RETURN_LINE_RMK` VARCHAR(200) 	 NULL,
	`RETURN_DIST_RMK` VARCHAR(200) 	 NULL,
	CONSTRAINT `PK_TRAS_KA_ORDR_CHECK` PRIMARY KEY (`CHECK_NO`,`ORDR_LINE_NUM`)
)

;

CREATE TABLE `TRAS_KA_ORDR_APPD_M`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`DATA_DATE` CHAR(8) NOT NULL,
	`APPD_SEQ` BIGINT NOT NULL,
	`ORDR_MAIN_ID` VARCHAR(40) NOT NULL,
	`SAP_ORDR_NO` VARCHAR(10) NOT NULL,
	`SALES_COM_ID_DE` VARCHAR(4) 	 NULL,
	`OPEN_ORDR_DATE` CHAR(8) NOT NULL,
	`APPD_USER` VARCHAR(8) 	 NULL,
	`RETURN_TIME` CHAR(14) NOT NULL,
	CONSTRAINT `PK_TRAS_KA_ORDR_APPD_M` PRIMARY KEY (`APPD_SEQ`)
)

;

CREATE TABLE `TRAS_KA_ORDR_APPD_D`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`DATA_DATE` CHAR(8) NOT NULL,
	`APPD_SEQ` BIGINT NOT NULL,
	`APPD_D_SEQ` BIGINT NOT NULL,
	`SAP_LINE_NUM` INT NOT NULL,
	`SAP_AMT_PKG` DECIMAL(21,4) NOT NULL,
	`SAP_QTY_PKG` DECIMAL(21,4) NOT NULL,
	`APPD_STATUS` VARCHAR(10) NOT NULL,
	`RETURN_LINE_RMK` VARCHAR(200) 	 NULL,
	CONSTRAINT `PK_TRAS_KA_ORDR_APPD_D` PRIMARY KEY (`APPD_SEQ`,`SAP_LINE_NUM`)
)

;

CREATE TABLE `TRAS_KA_ORDR_APPD`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`DATA_DATE` CHAR(8) NOT NULL,
	`ORDR_MAIN_ID` VARCHAR(40) NOT NULL,
	`SAP_ORDR_NO` VARCHAR(10) NOT NULL,
	`SALES_COM_ID_DE` VARCHAR(4) 	 NULL,
	`OPEN_ORDR_DATE` CHAR(8) NOT NULL,
	`APPD_USER` VARCHAR(8) 	 NULL,
	`RETURN_TIME` CHAR(14) NOT NULL,
	`SAP_LINE_NUM` INT NOT NULL,
	`SAP_AMT_PKG` DECIMAL(21,4) NOT NULL,
	`SAP_QTY_PKG` DECIMAL(21,4) NOT NULL,
	`APPD_STATUS` VARCHAR(10) NOT NULL,
	`RETURN_LINE_RMK` VARCHAR(200) 	 NULL,
	CONSTRAINT `PK_TRAS_KA_ORDR_APPD` PRIMARY KEY (`SAP_ORDR_NO`,`SAP_LINE_NUM`)
)

;

CREATE TABLE `TRAS_KA_ORDR`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`DATA_DATE` CHAR(8) NOT NULL,
	`ORDR_MAIN_ID` VARCHAR(40) NOT NULL,
	`KA_SYSTEM_CODE` VARCHAR(10) NOT NULL,
	`SYSTEM_ORDR_NO` VARCHAR(64) NOT NULL,
	`SYSTEM_ORDR_DATE` CHAR(8) NOT NULL,
	`SYSTEM_DEV_TIME` CHAR(14) 	 NULL,
	`CUST_ID` VARCHAR(15) NOT NULL,
	`SALES_COM_ID_DE_ORDR` VARCHAR(4) 	 NULL,
	`SALES_COM_ID_DE` VARCHAR(4) NOT NULL,
	`SALES_COM_ID_BL` VARCHAR(4) NOT NULL,
	`SALES_CHAN_ID` VARCHAR(2) NOT NULL,
	`PROD_DIV_ID` VARCHAR(2) NOT NULL,
	`IS_FACT_DEV` CHAR(1) NOT NULL,
	`OPEN_ORDR_DATE` CHAR(8) NOT NULL,
	`SAP_ORDR_NO` VARCHAR(10) NOT NULL,
	`SAP_LINE_NUM` INT NOT NULL,
	`ORDR_LINE_NUM` INT NOT NULL,
	`SYSTEM_ORDR_PROD_NM` VARCHAR(150) NOT NULL,
	`PROD_MATL_ID_SYS` VARCHAR(18) NOT NULL,
	`PROD_MATL_ID_OPEN` VARCHAR(18) NOT NULL,
	`STORE_PLACE_CODE` VARCHAR(4) 	 NULL,
	`IS_STORE_PLACE_DIR` CHAR(1) NOT NULL,
	`PROD_AMT_PKG_SYS` DECIMAL(21,4) 	 NULL,
	`PROD_QTY_PKG_SYS` DECIMAL(21,4) 	 NULL,
	`PROD_AMT_PKG_OPEN` DECIMAL(21,4) NOT NULL,
	`PROD_QTY_PKG_OPEN` DECIMAL(21,4) NOT NULL,
	`SAP_AMT_PKG_OPEN` DECIMAL(21,4) NOT NULL,
	`SAP_QTY_PKG_OPEN` DECIMAL(21,4) NOT NULL,
	`SAP_AMT_PKG_APPD` DECIMAL(21,4) NOT NULL,
	`SAP_QTY_PKG_APPD` DECIMAL(21,4) NOT NULL,
	`SHIP_QTY_PKG_DEV` INT 	 NULL,
	`SHIP_QTY_PKG_DIF` INT 	 NULL,
	`SHIP_QTY_PKG_ACT` INT 	 NULL,
	CONSTRAINT `PK_TRAS_KA_ORDR` PRIMARY KEY (`SAP_ORDR_NO`,`SAP_LINE_NUM`)
)

;

CREATE TABLE `TRAS_KA_MRK_STORE`
(
	`KA_SYSTEM_CODE` VARCHAR(10) NOT NULL,
	`SYSTEM_STORE_CODE` VARCHAR(20) NOT NULL,
	`SYSTEM_STORE_NM` VARCHAR(150) 	 NULL,
	`MRK_STORE_POS` VARCHAR(50) 	 NULL,
	`MRK_STORE_INV` VARCHAR(50) 	 NULL,
	CONSTRAINT `PK_TRAS_KA_MRK_STORE` PRIMARY KEY (`KA_SYSTEM_CODE`,`SYSTEM_STORE_CODE`)
)

;

CREATE TABLE `TRAS_KA_MRK_PROD`
(
	`KA_SYSTEM_CODE` VARCHAR(10) NOT NULL,
	`SYSTEM_PROD_CODE` VARCHAR(20) NOT NULL,
	`SYSTEM_PROD_NM` VARCHAR(150) 	 NULL,
	`MRK_PROD` VARCHAR(10) NOT NULL,
	CONSTRAINT `PK_TRAS_KA_MRK_PROD` PRIMARY KEY (`KA_SYSTEM_CODE`,`SYSTEM_PROD_CODE`)
)

;

CREATE TABLE `TRAS_KA_INV_WH_D`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`DATA_DATE` CHAR(8) NOT NULL,
	`KA_SYSTEM_CODE` VARCHAR(10) NOT NULL,
	`KA_WH_CODE` VARCHAR(6) NOT NULL,
	`KA_WH_NM` VARCHAR(150) NOT NULL,
	`SALES_COM_ID_WH` VARCHAR(4) NOT NULL,
	`SALES_COM_ID_DE` VARCHAR(4) NOT NULL,
	`PROD_MATL_ID` VARCHAR(18) NOT NULL,
	`INV_DATE` CHAR(8) NOT NULL,
	`INV_QTY_PCS` DECIMAL(21,4) NOT NULL,
	`INV_QTY_PKG` DECIMAL(21,4) NOT NULL,
	CONSTRAINT `PK_TRAS_KA_INV_WH_D` PRIMARY KEY (`INV_DATE`,`KA_SYSTEM_CODE`,`PROD_MATL_ID`,`KA_WH_CODE`)
)

;

CREATE TABLE `TRAS_KA_INV_STORE_D`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`DATA_DATE` CHAR(8) NOT NULL,
	`KA_SYSTEM_CODE` VARCHAR(10) NOT NULL,
	`KA_STORE_CODE` VARCHAR(4) NOT NULL,
	`KA_STORE_NM` VARCHAR(150) NOT NULL,
	`SALES_COM_ID_SA` VARCHAR(4) NOT NULL,
	`SALES_COM_ID_WH` VARCHAR(4) NOT NULL,
	`SALES_COM_ID_DE` VARCHAR(4) NOT NULL,
	`PROD_MATL_ID` VARCHAR(18) NOT NULL,
	`INV_DATE` CHAR(8) NOT NULL,
	`INV_QTY_PCS` DECIMAL(21,4) NOT NULL,
	`INV_QTY_PKG` DECIMAL(21,4) NOT NULL,
	CONSTRAINT `PK_TRAS_KA_INV_STORE_D` PRIMARY KEY (`INV_DATE`,`KA_SYSTEM_CODE`,`PROD_MATL_ID`,`KA_STORE_CODE`)
)

;

CREATE TABLE `TRAS_KA_INV`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`DATA_DATE` CHAR(8) NOT NULL,
	`INV_SEQ` VARCHAR(50) NOT NULL,
	`KA_SYSTEM_CODE` VARCHAR(10) NOT NULL,
	`SYSTEM_ACCT` VARCHAR(50) NOT NULL,
	`SYSTEM_ACCT_INFO` VARCHAR(100) 	 NULL,
	`SYSTEM_STORE_CODE` VARCHAR(10) 	 NULL,
	`SYSTEM_STORE_NM` VARCHAR(150) 	 NULL,
	`KA_STORE_CODE` VARCHAR(6) 	 NULL,
	`KA_STORE_NM` VARCHAR(150) 	 NULL,
	`SALES_COM_ID_SA` VARCHAR(4) 	 NULL,
	`SALES_COM_ID_WH` VARCHAR(4) 	 NULL,
	`SALES_COM_ID_DE` VARCHAR(4) 	 NULL,
	`SYSTEM_PROD_CODE` VARCHAR(20) 	 NULL,
	`SYSTEM_PROD_NM` VARCHAR(150) 	 NULL,
	`SYSTEM_PROD_SPEC` VARCHAR(50) 	 NULL,
	`SYSTEM_PROD_UNIT` VARCHAR(10) 	 NULL,
	`KA_PROD_SEQ` INT 	 NULL,
	`PROD_MATL_ID` VARCHAR(18) 	 NULL,
	`INV_CRAWL_DATE` CHAR(8) NOT NULL,
	`INV_CRAWL_TIME` CHAR(6) NOT NULL,
	`INV_SOURCE` CHAR(1) NOT NULL,
	`INV_STATUS` CHAR(1) NOT NULL,
	`INV_TYPE` CHAR(1) 	 NULL,
	`INV_DATE` CHAR(8) NOT NULL,
	`INV_QTY_PCS` DECIMAL(21,4) 	 NULL,
	`INV_QTY_PKG` DECIMAL(21,4) 	 NULL,
	CONSTRAINT `PK_TRAS_KA_INV` PRIMARY KEY (`INV_SEQ`)
)

;

CREATE TABLE `TRAS_CUST_SALES`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`DATA_DATE` CHAR(8) NOT NULL,
	`POSTED_YM` VARCHAR(6) NOT NULL,
	`WANT_CHAN_ID` VARCHAR(10) NOT NULL,
	`WANT_COM_ID` VARCHAR(4) NOT NULL,
	`PROD_MATL_ID` VARCHAR(18) NOT NULL,
	`CUST_ID` VARCHAR(15) NOT NULL,
	`POSTED_AMT` DECIMAL(21,4) NOT NULL,
	`POSTING_AMT` DECIMAL(21,4) NOT NULL,
	CONSTRAINT `PK_TRAS_CUST_SALES` PRIMARY KEY (`POSTED_YM`,`WANT_CHAN_ID`,`WANT_COM_ID`,`PROD_MATL_ID`,`CUST_ID`)
)

;

CREATE TABLE `TRAS_CUST_POSTING_SALES`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`DATA_DATE` CHAR(8) NOT NULL,
	`WANT_CHAN_ID` VARCHAR(10) NOT NULL,
	`WANT_COM_ID` VARCHAR(4) NOT NULL,
	`PROD_MATL_ID` VARCHAR(18) NOT NULL,
	`CUST_ID` VARCHAR(15) NOT NULL,
	`POSTING_AMT` DECIMAL(21,4) NOT NULL,
	CONSTRAINT `PK_TRAS_CUST_POSTING_SALES` PRIMARY KEY (`WANT_CHAN_ID`,`WANT_COM_ID`,`PROD_MATL_ID`,`CUST_ID`)
)

;

CREATE TABLE `TRAS_CUST_POSTING`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`DATA_DATE` CHAR(8) NOT NULL,
	`SALES_DOC_NUM` VARCHAR(15) NOT NULL,
	`SALES_DOC_ITEM` VARCHAR(6) NOT NULL,
	`SALES_DOC_ITEM_CATEG` VARCHAR(4) NOT NULL,
	`SALES_DOC_YMD` VARCHAR(8) NOT NULL,
	`DELIV_NUM` VARCHAR(15) NOT NULL,
	`DELIV_ITEM` VARCHAR(6) NOT NULL,
	`PROD_DIV_ID` VARCHAR(2) NOT NULL,
	`PROD_MATL_ID` VARCHAR(18) NOT NULL,
	`SALES_CHAN_ID` VARCHAR(2) NOT NULL,
	`SALES_COM_ID` VARCHAR(4) NOT NULL,
	`SALES_COM_CODE` VARCHAR(4) NOT NULL,
	`CUST_ID` VARCHAR(15) NOT NULL,
	`POSTING_BILL_AMT` DECIMAL(21,4) NOT NULL,
	`POSTING_CONF_AMT` DECIMAL(21,4) NOT NULL,
	CONSTRAINT `PK_TRAS_CUST_POSTING` PRIMARY KEY (`SALES_DOC_NUM`,`SALES_DOC_ITEM`,`DELIV_NUM`,`DELIV_ITEM`)
)

;

CREATE TABLE `TRAS_CUST_POSTED_SALES_D`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`DATA_DATE` CHAR(8) NOT NULL,
	`POSTED_YMD` VARCHAR(8) NOT NULL,
	`WANT_CHAN_ID` VARCHAR(10) NOT NULL,
	`WANT_COM_ID` VARCHAR(4) NOT NULL,
	`PROD_MATL_ID` VARCHAR(18) NOT NULL,
	`CUST_ID` VARCHAR(15) NOT NULL,
	`POSTED_AMT` DECIMAL(21,4) NOT NULL,
	CONSTRAINT `PK_TRAS_CUST_POSTED_SALES_D` PRIMARY KEY (`POSTED_YMD`,`WANT_CHAN_ID`,`WANT_COM_ID`,`PROD_MATL_ID`,`CUST_ID`)
)

;

CREATE TABLE `TRAS_CUST_POSTED_SALES`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`DATA_DATE` CHAR(8) NOT NULL,
	`POSTED_YM` VARCHAR(6) NOT NULL,
	`WANT_CHAN_ID` VARCHAR(10) NOT NULL,
	`WANT_COM_ID` VARCHAR(4) NOT NULL,
	`PROD_MATL_ID` VARCHAR(18) NOT NULL,
	`CUST_ID` VARCHAR(15) NOT NULL,
	`POSTED_AMT` DECIMAL(21,4) NOT NULL,
	CONSTRAINT `PK_TRAS_CUST_POSTED_SALES` PRIMARY KEY (`POSTED_YM`,`WANT_CHAN_ID`,`WANT_COM_ID`,`PROD_MATL_ID`,`CUST_ID`)
)

;

CREATE TABLE `TRAS_CUST_POSTED`
(
	`EDI_NO` CHAR(12) NOT NULL,
	`DATA_DATE` CHAR(8) NOT NULL,
	`SALES_DOC_ITEM_CATEG` VARCHAR(4) NOT NULL,
	`POSTED_YM` VARCHAR(6) NOT NULL,
	`POSTED_YMD` VARCHAR(8) NOT NULL,
	`FISC_YEAR` VARCHAR(4) NOT NULL,
	`FISC_VARNT` VARCHAR(2) NOT NULL,
	`BILL_NUM` VARCHAR(10) NOT NULL,
	`BILL_ITEM` VARCHAR(6) NOT NULL,
	`PROD_DIV_ID` VARCHAR(2) NOT NULL,
	`PROD_MATL_ID` VARCHAR(18) 	 NULL,
	`SALES_CHAN_ID` VARCHAR(2) NOT NULL,
	`SALES_COM_ID` VARCHAR(4) NOT NULL,
	`SALES_COM_CODE` VARCHAR(4) NOT NULL,
	`CUST_ID` VARCHAR(15) NOT NULL,
	`POSTED_AMT` DECIMAL(21,4) NOT NULL,
	CONSTRAINT `PK_TRAS_CUST_POSTED` PRIMARY KEY (`FISC_YEAR`,`FISC_VARNT`,`BILL_NUM`,`BILL_ITEM`)
)

;

ALTER TABLE `TRAS_KA_POS_STORE_M` 
 ADD INDEX `IX_TRAS_KA_POS_STORE_M` (`SALES_COM_ID_SA` ASC,`SALES_COM_ID_WH` ASC)
;

ALTER TABLE `TRAS_KA_POS_STORE_M` 
 ADD INDEX `IX_TRAS_KA_POS_STORE_M_2` (`KA_SYSTEM_CODE` ASC,`KA_STORE_CODE` ASC)
;

ALTER TABLE `TRAS_KA_POS_STORE_M` 
 ADD INDEX `IX_TRAS_KA_POS_STORE_M_3` (`POS_YM` ASC)
;

ALTER TABLE `TRAS_KA_POS_MATL_W` 
 ADD INDEX `IX_TRAS_KA_POS_MATL_W` (`SALES_COM_ID_SA` ASC,`SALES_COM_ID_WH` ASC)
;

ALTER TABLE `TRAS_KA_POS_MATL_M` 
 ADD INDEX `IX_TRAS_KA_POS_MATL_M` (`SALES_COM_ID_SA` ASC,`SALES_COM_ID_WH` ASC)
;

ALTER TABLE `TRAS_KA_POS_MATL_M` 
 ADD INDEX `IX_TRAS_KA_POS_MATL_M_2` (`KA_SYSTEM_CODE` ASC,`KA_STORE_CODE` ASC)
;

ALTER TABLE `TRAS_KA_POS_MATL_M` 
 ADD INDEX `IX_TRAS_KA_POS_MATL_M_3` (`POS_YM` ASC)
;

ALTER TABLE `TRAS_KA_POS_MATL_D` 
 ADD INDEX `IX_TRAS_KA_POS_MATL_D` (`SALES_COM_ID_SA` ASC,`SALES_COM_ID_WH` ASC)
;

ALTER TABLE `TRAS_KA_POS_MATL_D` 
 ADD INDEX `IX_TRAS_KA_POS_MATL_D_2` (`KA_SYSTEM_CODE` ASC,`KA_STORE_CODE` ASC)
;

ALTER TABLE `TRAS_KA_POS_MATL_D` 
 ADD INDEX `IX_TRAS_KA_POS_MATL_D_3` (`POS_DATE` ASC)
;

ALTER TABLE `TRAS_KA_POS` 
 ADD INDEX `IX_TRAS_KA_POS` (`KA_SYSTEM_CODE` ASC,`KA_STORE_CODE` ASC,`PROD_MATL_ID` ASC)
;

ALTER TABLE `TRAS_KA_POS` 
 ADD INDEX `IX_TRAS_KA_POS_3` (`SALES_COM_ID_SA` ASC,`SALES_COM_ID_WH` ASC,`SALES_COM_ID_DE` ASC)
;

ALTER TABLE `TRAS_KA_POS` 
 ADD INDEX `IX_TRAS_KA_POS_2` (`POS_DATE` ASC,`POS_STATUS` ASC,`POS_TYPE` ASC,`POS_SETTLE_TYPE` ASC)
;

ALTER TABLE `TRAS_KA_POS` 
 ADD INDEX `IX_TRAS_KA_POS_4` (`KA_SYSTEM_CODE` ASC,`SYSTEM_PROD_CODE` ASC)
;

ALTER TABLE `TRAS_KA_POS` 
 ADD INDEX `IX_TRAS_KA_POS_5` (`KA_SYSTEM_CODE` ASC,`SYSTEM_STORE_CODE` ASC)
;

ALTER TABLE `TRAS_KA_ORDR_SHIP_D` 
 ADD INDEX `IX_TRAS_KA_ORDR_SHIP_D` (`SAP_ORDR_NO` ASC,`SAP_LINE_NUM` ASC)
;

ALTER TABLE `TRAS_KA_ORDR_OPEN_M` 
 ADD INDEX `IX_TRAS_KA_ORDR_OPEN_M` (`ORDR_MAIN_ID` ASC)
;

ALTER TABLE `TRAS_KA_ORDR_OPEN_M` 
 ADD INDEX `IX_TRAS_KA_ORDR_OPEN_M_2` (`SYSTEM_ORDR_NO` ASC)
;

ALTER TABLE `TRAS_KA_ORDR_OPEN` 
 ADD INDEX `IX_TRAS_KA_ORDR_OPEN` (`ORDR_MAIN_ID` ASC,`ORDR_LINE_NUM` ASC)
;

ALTER TABLE `TRAS_KA_ORDR_OPEN` 
 ADD INDEX `IX_TRAS_KA_ORDR_OPEN_2` (`SYSTEM_ORDR_NO` ASC)
;

ALTER TABLE `TRAS_KA_ORDR_OPEN` 
 ADD INDEX `IX_TRAS_KA_ORDR_OPEN_3` (`SAP_ORDR_NO` ASC,`SAP_LINE_NUM` ASC)
;

ALTER TABLE `TRAS_KA_ORDR_CHECK_M` 
 ADD INDEX `IX_TRAS_KA_ORDR_CHECK_M` (`ORDR_MAIN_ID` ASC)
;

ALTER TABLE `TRAS_KA_ORDR_CHECK_M` 
 ADD INDEX `IX_TRAS_KA_ORDR_CHECK_M_2` (`SYSTEM_ORDR_NO` ASC)
;

ALTER TABLE `TRAS_KA_ORDR_CHECK` 
 ADD INDEX `IX_TRAS_KA_ORDR_CHECK` (`ORDR_MAIN_ID` ASC,`ORDR_LINE_NUM` ASC)
;

ALTER TABLE `TRAS_KA_ORDR_CHECK` 
 ADD INDEX `IX_TRAS_KA_ORDR_CHECK_2` (`SYSTEM_ORDR_NO` ASC)
;

ALTER TABLE `TRAS_KA_ORDR_APPD_M` 
 ADD INDEX `IX_TRAS_KA_ORDR_APPD_M` (`ORDR_MAIN_ID` ASC)
;

ALTER TABLE `TRAS_KA_ORDR_APPD_M` 
 ADD INDEX `IX_TRAS_KA_ORDR_APPD_M_2` (`SAP_ORDR_NO` ASC)
;

ALTER TABLE `TRAS_KA_ORDR_APPD` 
 ADD INDEX `IX_TRAS_KA_ORDR_APPD` (`ORDR_MAIN_ID` ASC)
;

ALTER TABLE `TRAS_KA_INV_WH_D` 
 ADD INDEX `IX_TRAS_KA_INV_WH_D` (`SALES_COM_ID_WH` ASC,`SALES_COM_ID_DE` ASC)
;

ALTER TABLE `TRAS_KA_INV_WH_D` 
 ADD INDEX `IX_TRAS_KA_INV_WH_D_2` (`KA_SYSTEM_CODE` ASC,`KA_WH_CODE` ASC)
;

ALTER TABLE `TRAS_KA_INV_WH_D` 
 ADD INDEX `IX_TRAS_KA_INV_WH_D_3` (`INV_DATE` ASC)
;

ALTER TABLE `TRAS_KA_INV_STORE_D` 
 ADD INDEX `IX_TRAS_KA_INV_STORE_D` (`SALES_COM_ID_SA` ASC,`SALES_COM_ID_WH` ASC)
;

ALTER TABLE `TRAS_KA_INV_STORE_D` 
 ADD INDEX `IX_TRAS_KA_INV_STORE_D_2` (`KA_SYSTEM_CODE` ASC,`KA_STORE_CODE` ASC)
;

ALTER TABLE `TRAS_KA_INV_STORE_D` 
 ADD INDEX `IX_TRAS_KA_INV_STORE_D_3` (`INV_DATE` ASC)
;

ALTER TABLE `TRAS_KA_INV` 
 ADD INDEX `IX_TRAS_KA_INV` (`KA_SYSTEM_CODE` ASC,`KA_STORE_CODE` ASC,`PROD_MATL_ID` ASC)
;

ALTER TABLE `TRAS_KA_INV` 
 ADD INDEX `IX_TRAS_KA_INV_3` (`SALES_COM_ID_SA` ASC,`SALES_COM_ID_WH` ASC,`SALES_COM_ID_DE` ASC)
;

ALTER TABLE `TRAS_KA_INV` 
 ADD INDEX `IX_TRAS_KA_INV_2` (`INV_DATE` ASC,`INV_STATUS` ASC,`INV_TYPE` ASC)
;

ALTER TABLE `TRAS_KA_INV` 
 ADD INDEX `IX_TRAS_KA_INV_4` (`KA_SYSTEM_CODE` ASC,`SYSTEM_PROD_CODE` ASC)
;

ALTER TABLE `TRAS_KA_INV` 
 ADD INDEX `IX_TRAS_KA_INV_5` (`KA_SYSTEM_CODE` ASC,`SYSTEM_STORE_CODE` ASC)
;

ALTER TABLE `TRAS_CUST_POSTING` 
 ADD INDEX `IX_TRAS_CUST_POSTING` (`SALES_COM_ID` ASC,`PROD_MATL_ID` ASC,`CUST_ID` ASC)
;

ALTER TABLE `TRAS_CUST_POSTED` 
 ADD INDEX `IX_TRAS_CUST_POSTED` (`POSTED_YM` ASC,`SALES_COM_ID` ASC,`PROD_MATL_ID` ASC,`CUST_ID` ASC)
;

SET FOREIGN_KEY_CHECKS=1 ;
