DROP FUNCTION IF EXISTS DWWANT.FN_GET_EDI_NO;

CREATE FUNCTION DWWANT.FN_GET_EDI_NO(VAR_DATE CHAR(8)) RETURNS CHAR(12)
BEGIN
    DECLARE VAR_EDI_NO CHAR(12);
    
    SELECT CONCAT(VAR_DATE,
                  RIGHT(CONCAT('000',CONVERT(CONVERT(IFNULL(SUBSTRING(CONVERT(MAX(EDI_NO), CHAR), 9, 4), '0000'), INT)+1, CHAR)),4)
                 ) INTO VAR_EDI_NO
    FROM DWWANT.EDI_FLOW
    WHERE SUBSTRING(EDI_NO,1,8)=VAR_DATE;
    
    RETURN VAR_EDI_NO;
END