DROP FUNCTION IF EXISTS DWWANT.FN_GET_CM_EMP_POS_PROP_NM;

CREATE FUNCTION DWWANT.FN_GET_CM_EMP_POS_PROP_NM(VAR_EMP_POS_PROP_ID VARCHAR(3)) RETURNS VARCHAR(60)
BEGIN
    DECLARE VAR_EMP_POS_PROP_NM VARCHAR(60);

    SELECT EMP_POS_PROP_NM INTO VAR_EMP_POS_PROP_NM 
    FROM DWWANT.CM_EMP_POS_PROP
    WHERE EMP_POS_PROP_ID=VAR_EMP_POS_PROP_ID;

    RETURN VAR_EMP_POS_PROP_NM;
END
