DROP FUNCTION IF EXISTS DWWANT.FN_GET_ORG_EMP_GENDER_NM;

CREATE FUNCTION DWWANT.FN_GET_ORG_EMP_GENDER_NM(VAR_ORG_EMP_GENDER CHAR(1)) RETURNS VARCHAR(150)
BEGIN
    DECLARE VAR_ORG_EMP_GENDER_NM VARCHAR(150);

    SELECT (CASE VAR_ORG_EMP_GENDER WHEN 'F' THEN '女' WHEN 'M' THEN '男' ELSE NULL END) INTO VAR_ORG_EMP_GENDER_NM;

    RETURN VAR_ORG_EMP_GENDER_NM;
END
