DROP FUNCTION IF EXISTS DWWANT.FN_GET_CM_EMP_POS_LEVEL_NM;

CREATE FUNCTION DWWANT.FN_GET_CM_EMP_POS_LEVEL_NM(VAR_EMP_POS_LEVEL_ID VARCHAR(2)) RETURNS VARCHAR(60)
BEGIN
    DECLARE VAR_EMP_POS_LEVEL_NM VARCHAR(60);

    SELECT EMP_POS_LEVEL_NM INTO VAR_EMP_POS_LEVEL_NM 
    FROM DWWANT.CM_EMP_POS_LEVEL
    WHERE EMP_POS_LEVEL_ID=VAR_EMP_POS_LEVEL_ID;

    RETURN VAR_EMP_POS_LEVEL_NM;
END
