DROP FUNCTION IF EXISTS DWWANT.FN_GET_ORG_WANT_CHAN_ID;

CREATE FUNCTION DWWANT.FN_GET_ORG_WANT_CHAN_ID(VAR_SALES_CHAN_ID VARCHAR(2), VAR_PROD_DIV_ID VARCHAR(2)) RETURNS VARCHAR(10)
BEGIN
    DECLARE VAR_WANT_CHAN_ID VARCHAR(10);

    SELECT WANT_CHAN_ID INTO VAR_WANT_CHAN_ID 
    FROM DWWANT.ORG_WANT_CHAN_PROD
    WHERE SALES_CHAN_ID=VAR_SALES_CHAN_ID AND PROD_DIV_ID=VAR_PROD_DIV_ID;

    RETURN VAR_WANT_CHAN_ID;
END
