DROP FUNCTION IF EXISTS DWWANT.FN_GET_ORG_SALES_COM_ABR;

CREATE FUNCTION DWWANT.FN_GET_ORG_SALES_COM_ABR(VAR_SALES_COM_ID VARCHAR(4)) RETURNS VARCHAR(60)
BEGIN
    DECLARE VAR_SALES_COM_ABR VARCHAR(60);

    SELECT SALES_COM_ABR INTO VAR_SALES_COM_ABR
    FROM DWWANT.ORG_SALES_COM
    WHERE SALES_COM_ID=VAR_SALES_COM_ID;

    RETURN VAR_SALES_COM_ABR;
END
