DROP FUNCTION IF EXISTS DWWANT.FN_GET_PROD_MATL_NM;

CREATE FUNCTION DWWANT.FN_GET_PROD_MATL_NM(VAR_PROD_MATL_ID VARCHAR(18)) RETURNS VARCHAR(60)
BEGIN
    DECLARE VAR_PROD_MATL_NM VARCHAR(60);

    SELECT PROD_MATL_NM INTO VAR_PROD_MATL_NM 
    FROM DWWANT.PROD_MATL
    WHERE PROD_MATL_ID=VAR_PROD_MATL_ID;

    RETURN VAR_PROD_MATL_NM;
END
