DROP FUNCTION IF EXISTS DWWANT.FN_GET_PROD_HIER_NM;

CREATE FUNCTION DWWANT.FN_GET_PROD_HIER_NM(VAR_PROD_H_ID VARCHAR(20)) RETURNS VARCHAR(60)
BEGIN
    DECLARE VAR_PROD_H_NM VARCHAR(60);

    SELECT PROD_H_NM INTO VAR_PROD_H_NM 
    FROM DWWANT.PROD_HIER
    WHERE PROD_H_ID=VAR_PROD_H_ID;

    RETURN VAR_PROD_H_NM;
END
