DROP FUNCTION IF EXISTS DWWANT.FN_GET_CM_EMP_POS_NM;

CREATE FUNCTION DWWANT.FN_GET_CM_EMP_POS_NM(VAR_EMP_POS_ID VARCHAR(8)) RETURNS VARCHAR(60)
BEGIN
    DECLARE VAR_EMP_POS_NM VARCHAR(60);

    SELECT EMP_POS_NM INTO VAR_EMP_POS_NM 
    FROM DWWANT.CM_EMP_POS
    WHERE EMP_POS_ID=VAR_EMP_POS_ID;

    RETURN VAR_EMP_POS_NM;
END
