DROP FUNCTION IF EXISTS DWWANT.FN_GET_CM_EMP_POS_TITLE_NM;

CREATE FUNCTION DWWANT.FN_GET_CM_EMP_POS_TITLE_NM(VAR_EMP_POS_TITLE_ID VARCHAR(8)) RETURNS VARCHAR(60)
BEGIN
    DECLARE VAR_EMP_POS_TITLE_NM VARCHAR(60);

    SELECT EMP_POS_TITLE_NM INTO VAR_EMP_POS_TITLE_NM 
    FROM DWWANT.CM_EMP_POS_TITLE
    WHERE EMP_POS_TITLE_ID=VAR_EMP_POS_TITLE_ID;

    RETURN VAR_EMP_POS_TITLE_NM;
END
