DROP FUNCTION IF EXISTS DWWANT.FN_GET_WEEK_FIRST_DATE;

CREATE FUNCTION DWWANT.FN_GET_WEEK_FIRST_DATE(VAR_DATE CHAR(8)) RETURNS CHAR(8)
BEGIN
    DECLARE VAR_WEEK_NUM CHAR(6);
    DECLARE VAR_YEAR CHAR(4);
    DECLARE VAR_NUM CHAR(2);

    DECLARE VAR_TEMP_FIRST_DATE CHAR(8);
    DECLARE VAR_INDEX INT;
    DECLARE VAR_TEMP DATETIME;

    SET VAR_WEEK_NUM = DWWANT.FN_GET_WEEK_NUM(VAR_DATE);
    SET VAR_YEAR = LEFT(VAR_WEEK_NUM, 4);
    SET VAR_NUM = RIGHT(VAR_WEEK_NUM, 2);

    IF WEEK(CONCAT(VAR_YEAR, '0101'), 5)=1 THEN
        SET VAR_NUM = RIGHT(CONCAT('0', CONVERT(CONVERT(VAR_NUM, INT) - 1, CHAR)), 2);
    END IF;

    IF VAR_NUM='00' THEN

        SET VAR_TEMP_FIRST_DATE = CONCAT(VAR_YEAR, '0101');
        SET VAR_INDEX = 1;

        VAR_WHILE : WHILE VAR_INDEX>=-7 DO
            SET VAR_INDEX = VAR_INDEX - 1;
            SET VAR_TEMP = DATE_ADD(CONVERT(VAR_TEMP_FIRST_DATE, DATE), INTERVAL VAR_INDEX DAY);
            IF WEEKDAY(VAR_TEMP)=0 THEN
                SET VAR_TEMP_FIRST_DATE = DWWANT.FN_GET_DATE(VAR_TEMP);
                LEAVE VAR_WHILE;
            END IF;
        END WHILE;

        RETURN VAR_TEMP_FIRST_DATE;

    ELSE
        RETURN DWWANT.FN_GET_DATE(STR_TO_DATE(CONCAT(VAR_YEAR, VAR_NUM, ' Monday'), '%X%V %W'));
    END IF;
END
