DROP FUNCTION IF EXISTS DWWANT.FN_GET_CUST_NM;

CREATE FUNCTION DWWANT.FN_GET_CUST_NM(VAR_CUST_ID VARCHAR(15)) RETURNS VARCHAR(60)
BEGIN
    DECLARE VAR_CUST_NM VARCHAR(60);

    SELECT CUST_NM INTO VAR_CUST_NM 
    FROM DWWANT.CUST_MAIN
    WHERE CUST_ID=VAR_CUST_ID;

    RETURN VAR_CUST_NM;
END
