DROP FUNCTION IF EXISTS DWWANT.FN_GET_ORG_WANT_COM_NM;

CREATE FUNCTION DWWANT.FN_GET_ORG_WANT_COM_NM(VAR_WANT_COM_ID VARCHAR(4)) RETURNS VARCHAR(60)
BEGIN
    DECLARE VAR_WANT_COM_NM VARCHAR(60);

    SELECT WANT_COM_NM INTO VAR_WANT_COM_NM 
    FROM DWWANT.ORG_WANT_COM
    WHERE WANT_COM_ID=VAR_WANT_COM_ID;

    RETURN VAR_WANT_COM_NM;
END
