DROP FUNCTION IF EXISTS DWWANT.FN_GET_ORG_HR_COM_NM;

CREATE FUNCTION DWWANT.FN_GET_ORG_HR_COM_NM(VAR_HR_COM_ID VARCHAR(8)) RETURNS VARCHAR(60)
BEGIN
    DECLARE VAR_HR_COM_NM VARCHAR(60);

    SELECT HR_COM_NM INTO VAR_HR_COM_NM 
    FROM DWWANT.ORG_HR_COM
    WHERE HR_COM_ID=VAR_HR_COM_ID;

    RETURN VAR_HR_COM_NM;
END
