DROP FUNCTION IF EXISTS DWWANT.FN_GET_ORG_SALES_COM_NM;

CREATE FUNCTION DWWANT.FN_GET_ORG_SALES_COM_NM(VAR_SALES_COM_ID VARCHAR(4)) RETURNS VARCHAR(60)
BEGIN
    DECLARE VAR_SALES_COM_NM VARCHAR(60);

    SELECT SALES_COM_NM INTO VAR_SALES_COM_NM 
    FROM DWWANT.ORG_SALES_COM
    WHERE SALES_COM_ID=VAR_SALES_COM_ID;

    RETURN VAR_SALES_COM_NM;
END
