DROP FUNCTION IF EXISTS DWWANT.FN_IS_NUMERIC;

CREATE FUNCTION DWWANT.FN_IS_NUMERIC(VAR_COL VARCHAR(22)) RETURNS CHAR COLLATE UTF8_GENERAL_CI
BEGIN
    DECLARE VAR_IS_NUMERIC INT;
    SELECT VAR_COL REGEXP '^(([0-9+-.]{1})|([+-]?[0-9]*(([.]{1}[0-9]*)|([.]?[0-9]+))))$' INTO VAR_IS_NUMERIC;
    IF VAR_IS_NUMERIC=0 THEN
        RETURN 'N';
    ELSE
        RETURN 'Y';
    END IF;
END