DROP FUNCTION IF EXISTS DWWANT.FN_GET_WEEK_LAST_DATE;

CREATE FUNCTION DWWANT.FN_GET_WEEK_LAST_DATE(VAR_DATE CHAR(8)) RETURNS CHAR(8)
BEGIN
    DECLARE VAR_WEEK_NUM CHAR(6);
    DECLARE VAR_YEAR CHAR(4);
    DECLARE VAR_NUM CHAR(2);

    SET VAR_WEEK_NUM = DWWANT.FN_GET_WEEK_NUM(VAR_DATE);
    SET VAR_YEAR = LEFT(VAR_WEEK_NUM, 4);
    SET VAR_NUM = RIGHT(VAR_WEEK_NUM, 2);

    IF WEEK(CONCAT(VAR_YEAR, '0101'), 5)=1 THEN
        SET VAR_NUM = RIGHT(CONCAT('0', CONVERT(CONVERT(VAR_NUM, INT) - 1, CHAR)), 2);
    END IF;

    IF VAR_NUM='00' THEN
        RETURN DWWANT.FN_GET_DATE(DATE_ADD(STR_TO_DATE(CONCAT(VAR_YEAR, '01', ' Monday'), '%X%V %W'), INTERVAL -1 DAY));
    ELSE
        RETURN DWWANT.FN_GET_DATE(DATE_ADD(CONVERT(DWWANT.FN_GET_WEEK_FIRST_DATE(VAR_DATE), DATE), INTERVAL 6 DAY));
    END IF;
END
