DROP PROCEDURE IF EXISTS DWWANT.SP_KA_ORDER_00001_DELETE_DATA;

CREATE PROCEDURE DWWANT.SP_KA_ORDER_00001_DELETE_DATA (
    VAR_EDI_NO CHAR(12), VAR_DATA_DATE CHAR(8), OUT VAR_SP_RESULT CHAR(1)
)
BEGIN
    DECLARE VAR_DATE_MIN CHAR(8);

    SET VAR_DATE_MIN = CONCAT(DATE_FORMAT(DATE_ADD(STR_TO_DATE(VAR_DATA_DATE, '%Y%m%d'), INTERVAL -3 MONTH), '%Y%m'), '01');

    DELETE FROM DWWANT.ORDR_KA_SYS 
    WHERE SYSTEM_ORDR_DATE>=VAR_DATE_MIN AND SYSTEM_ORDR_DATE<=VAR_DATA_DATE;



    DELETE FROM DWWANT.TRAS_KA_ORDR_CHECK
    WHERE OPEN_ORDR_DATE>=VAR_DATE_MIN AND OPEN_ORDR_DATE<=VAR_DATA_DATE;

    DELETE FROM DWWANT.TRAS_KA_ORDR_CHECK_D
    WHERE SUBSTRING(CHECK_NO, 2, 8)>=VAR_DATE_MIN AND SUBSTRING(CHECK_NO, 2, 8)<=VAR_DATA_DATE;

    DELETE FROM DWWANT.TRAS_KA_ORDR_CHECK_M
    WHERE SUBSTRING(CHECK_NO, 2, 8)>=VAR_DATE_MIN AND SUBSTRING(CHECK_NO, 2, 8)<=VAR_DATA_DATE;



    DELETE FROM DWWANT.TRAS_KA_ORDR_OPEN
    WHERE OPEN_ORDR_DATE>=VAR_DATE_MIN AND OPEN_ORDR_DATE<=VAR_DATA_DATE;

    DELETE FROM DWWANT.TRAS_KA_ORDR_OPEN_D
    WHERE SUBSTRING(OPEN_NO, 2, 8)>=VAR_DATE_MIN AND SUBSTRING(OPEN_NO, 2, 8)<=VAR_DATA_DATE;

    DELETE FROM DWWANT.TRAS_KA_ORDR_OPEN_M
    WHERE SUBSTRING(OPEN_NO, 2, 8)>=VAR_DATE_MIN AND SUBSTRING(OPEN_NO, 2, 8)<=VAR_DATA_DATE;



    DELETE FROM DWWANT.TRAS_KA_ORDR_APPD
    WHERE OPEN_ORDR_DATE>=VAR_DATE_MIN AND OPEN_ORDR_DATE<=VAR_DATA_DATE;

    DELETE FROM DWWANT.TRAS_KA_ORDR_APPD_D
    WHERE APPD_SEQ IN (SELECT APPD_SEQ 
                       FROM DWWANT.TRAS_KA_ORDR_APPD_M
                       WHERE OPEN_ORDR_DATE>=VAR_DATE_MIN AND OPEN_ORDR_DATE<=VAR_DATA_DATE);

    DELETE FROM DWWANT.TRAS_KA_ORDR_APPD_M
    WHERE OPEN_ORDR_DATE>=VAR_DATE_MIN AND OPEN_ORDR_DATE<=VAR_DATA_DATE;



    DELETE FROM DWWANT.TRAS_KA_ORDR_SHIP
    WHERE SHIP_REC_DATE>=VAR_DATE_MIN AND SHIP_REC_DATE<=VAR_DATA_DATE;

    DELETE FROM DWWANT.TRAS_KA_ORDR_SHIP_D
    WHERE SHIP_REC_DATE>=VAR_DATE_MIN AND SHIP_REC_DATE<=VAR_DATA_DATE;



    DELETE FROM DWWANT.TRAS_KA_ORDR_OPEN_AMT
    WHERE OPEN_ORDR_DATE>=VAR_DATE_MIN AND OPEN_ORDR_DATE<=VAR_DATA_DATE;

    DELETE FROM DWWANT.TRAS_KA_ORDR
    WHERE SYSTEM_ORDR_DATE>=VAR_DATE_MIN AND SYSTEM_ORDR_DATE<=VAR_DATA_DATE;

    DELETE FROM DWWANT.ORDR_KA
    WHERE SYSTEM_ORDR_DATE>=VAR_DATE_MIN AND SYSTEM_ORDR_DATE<=VAR_DATA_DATE;

    SET VAR_SP_RESULT='Y';
    COMMIT;
END
;