DROP PROCEDURE IF EXISTS DWWANT.SP_DC0024_ORDER_00001_DELETE_DATA;

CREATE PROCEDURE DWWANT.SP_DC0024_ORDER_00001_DELETE_DATA (
    VAR_EDI_NO CHAR(12), VAR_DATA_DATE CHAR(8), OUT VAR_SP_RESULT CHAR(1)
)
BEGIN

    TRUNCATE TABLE DMMDL.DC0024_ORDR_TRAS_D;
    TRUNCATE TABLE DMMDL.DC0024_ORDR_SYS_D;

    SET VAR_SP_RESULT='Y';
    COMMIT;
END
;