DROP PROCEDURE IF EXISTS DWWANT.SP_MAIN_30109_FI;

CREATE PROCEDURE DWWANT.SP_MAIN_30109_FI (
    VAR_EDI_NO CHAR(12), VAR_DATA_DATE CHAR(8), OUT VAR_SP_RESULT CHAR(1)
)
BEGIN
    DECLARE VAR_FISC_PER CHAR(7);

    SET VAR_FISC_PER = CONCAT(LEFT(VAR_DATA_DATE, 4), '0', SUBSTRING(VAR_DATA_DATE, 5, 2));

    INSERT INTO DWWANT.FI_CUST_BAL
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , (CASE WHEN F.FISCPER=''       THEN 'NULL' ELSE F.FISCPER       END) AS FISC_PER
         , (CASE WHEN F.FISCVARNT=''     THEN 'NULL' ELSE F.FISCVARNT     END) AS FISC_VARNT
         , (CASE WHEN F.FI_DSBITEM=''    THEN 'NULL' ELSE F.FI_DSBITEM    END) AS FISC_DSB_ITEM
         , (CASE WHEN F.AC_DOC_NO=''     THEN 'NULL' ELSE F.AC_DOC_NO     END) AS AC_DOC_NUM
         , (CASE WHEN F.ITEM_NUM=''      THEN 'NULL' ELSE F.ITEM_NUM      END) AS AC_DOC_ITEM
         , (CASE WHEN F.AC_DOC_TYP=''    THEN  NULL  ELSE F.AC_DOC_TYP    END) AS AC_DOC_TYPE
         , (CASE WHEN F.PSTNG_DATE=''    THEN  NULL  ELSE F.PSTNG_DATE    END) AS AC_DOC_POST_YMD
         , (CASE WHEN F.COMP_CODE=''     THEN 'NULL' ELSE F.COMP_CODE     END) AS SALES_COM_CODE
         , (CASE WHEN F.DEBITOR=''       THEN 'NULL' ELSE F.DEBITOR       END) AS CUST_ID
         , (CASE WHEN F.C_CTR_AREA=''    THEN  NULL  ELSE F.C_CTR_AREA    END) AS SALES_CREDIT_ID
         , (CASE WHEN F.BIC_ZTCODE=''    THEN  NULL  ELSE F.BIC_ZTCODE    END) AS SALES_TRAS_CODE
         , F.DEB_CRE_LC AS BAL_AMT
    FROM RAWWANT.BW_SAPBHP_BI0_AFIAR_O0300 F
    ;

    INSERT INTO DWWANT.FI_CUST_SPEC
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , (CASE WHEN S.BIC_ZKNUM=''    THEN 'NULL' ELSE S.BIC_ZKNUM    END) AS SPEC_NUM
         , (CASE WHEN S.DIVISION=''     THEN 'NULL' ELSE S.DIVISION     END) AS PROD_DIV_ID
         , (CASE WHEN S.DISTR_CHAN=''   THEN 'NULL' ELSE S.DISTR_CHAN   END) AS SALES_CHAN_ID
         , (CASE WHEN S.SALESORG=''     THEN 'NULL' ELSE S.SALESORG     END) AS SALES_COM_ID
         , (CASE WHEN S.COMP_CODE=''    THEN 'NULL' ELSE S.COMP_CODE    END) AS SALES_COM_CODE
         , (CASE WHEN S.CUSTOMER=''     THEN 'NULL' ELSE S.CUSTOMER     END) AS CUST_ID
         , (CASE WHEN S.MATERIAL=''     THEN  NULL  ELSE S.MATERIAL     END) AS PROD_MATL_ID
         , (CASE WHEN S.MATL_GRP_1=''   THEN  NULL  ELSE S.MATL_GRP_1   END) AS PROD_MATL_GRP1_ID
         , (CASE WHEN S.BIC_ZZKZYS=''   THEN  NULL  ELSE S.BIC_ZZKZYS   END) AS SPEC_STATUS
         , S.BIC_ZKAMOUNT AS SPEC_AMT
    FROM RAWWANT.BW_SAPBHP_BIC_AZKZY_O0100 S
    ;

    INSERT INTO DWWANT.FI_CUST_STMT
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , IFNULL(A.SALES_CREDIT_ID, 'NULL') AS SALES_CREDIT_ID
         , IFNULL(D.WANT_COM_ID, 'NULL') AS WANT_COM_ID
         , IFNULL(D.SALES_OFF_ID, 'NULL') AS SALES_OFF_ID
         , A.CUST_ID
         , SUM(CASE WHEN A.FISC_PER=VAR_FISC_PER AND A.FISC_VARNT='K4' AND A.AC_DOC_TYPE<>'RV' AND
                         (SUBSTRING(A.SALES_TRAS_CODE,1,2)<>'VF' OR A.SALES_TRAS_CODE IS NULL) AND A.AC_DOC_POST_YMD=VAR_DATA_DATE THEN A.BAL_AMT 
                    ELSE 0
               END)*-1 AS TODAY_AMT
         , SUM(CASE WHEN A.FISC_PER<VAR_FISC_PER AND A.FISC_VARNT='K4' THEN A.BAL_AMT
                    ELSE 0
               END)*-1 AS PERIOD_BEGIN
         , SUM(CASE WHEN A.FISC_PER=VAR_FISC_PER AND A.FISC_VARNT='K4' AND A.AC_DOC_TYPE<>'RV' AND 
                         (SUBSTRING(A.SALES_TRAS_CODE,1,2)<>'VF' OR A.SALES_TRAS_CODE IS NULL) THEN A.BAL_AMT
                    ELSE 0
               END)*-1 AS CUM_AMT
         , SUM(CASE WHEN A.FISC_PER=VAR_FISC_PER AND A.FISC_VARNT='K4' AND A.AC_DOC_TYPE= 'RV' THEN A.BAL_AMT
                    ELSE 0
               END) AS SALES_WO
         , SUM(CASE WHEN A.FISC_PER<=VAR_FISC_PER AND A.FISC_VARNT='K4' THEN A.BAL_AMT
                    ELSE 0
               END)*-1 AS PERIOD_END
    FROM DWWANT.FI_CUST_BAL A
    JOIN DWWANT.CUST_SD D ON A.CUST_ID=D.CUST_ID
    WHERE (D.CUST_CLASS NOT IN ('O1','O2','O3','O4','O5','O6','O7','O8') OR D.CUST_CLASS IS NULL)
      AND SUBSTRING(A.SALES_COM_CODE,1,1)='C'
      AND (A.SALES_CREDIT_ID NOT IN ('CDZ','FDZ','CDD','CD8','CDQ') OR A.SALES_CREDIT_ID IS NULL)
      AND D.CUST_ACCT_GRP IN ('Z002','Z003')
    GROUP BY IFNULL(A.SALES_CREDIT_ID, 'NULL'), IFNULL(D.WANT_COM_ID, 'NULL'), IFNULL(D.SALES_OFF_ID, 'NULL'), A.CUST_ID
    ;

    SET VAR_SP_RESULT='Y';
    COMMIT;
END
;