DROP PROCEDURE IF EXISTS DWWANT.SP_DC0024_RPT_30501_STORE_MATL_M;

CREATE PROCEDURE DWWANT.SP_DC0024_RPT_30501_STORE_MATL_M (
    VAR_EDI_NO CHAR(12), VAR_DATA_DATE CHAR(8), OUT VAR_SP_RESULT CHAR(1)
)
BEGIN

    DECLARE VAR_AUTO_EDI_NO CHAR(12);
    DECLARE VAR_POS_DATE_MIN CHAR(8);
    DECLARE VAR_POS_DATE_MAX CHAR(8);

    SELECT AUTO_EDI_NO INTO VAR_AUTO_EDI_NO
    FROM DWWANT.EDI_FLOW
    WHERE EDI_NO=VAR_EDI_NO;

    SELECT AUTO_EDI_NO INTO VAR_AUTO_EDI_NO
    FROM DWWANT.EDI_FLOW
    WHERE EDI_NO=VAR_AUTO_EDI_NO;

    SELECT POS_DATE_MIN, POS_DATE_MAX INTO VAR_POS_DATE_MIN, VAR_POS_DATE_MAX
    FROM DWWANT.EDI_FLOW_DWWANT_KA
    WHERE EDI_NO=VAR_AUTO_EDI_NO;

    INSERT INTO DMMDL.DC0024_STORE_MATL_M
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , A.KA_SYSTEM_CODE, DWWANT.FN_GET_CM_KA_SYSTEM_NM(A.KA_SYSTEM_CODE) AS KA_SYSTEM_NM
         , A.KA_STORE_CODE, MIN(A.KA_STORE_NM) AS KA_STORE_NM
         , MAX(A.SALES_COM_ID_SA) AS SALES_COM_ID_SA, DWWANT.FN_GET_ORG_SALES_COM_ABR(MAX(A.SALES_COM_ID_SA)) AS SALES_COM_ABR_SA
         , MAX(A.SALES_COM_ID_WH) AS SALES_COM_ID_WH, DWWANT.FN_GET_ORG_SALES_COM_ABR(MAX(A.SALES_COM_ID_WH)) AS SALES_COM_ABR_WH
         , MAX(A.SALES_COM_ID_DE) AS SALES_COM_ID_DE, DWWANT.FN_GET_ORG_SALES_COM_ABR(MAX(A.SALES_COM_ID_DE)) AS SALES_COM_ABR_DE
         , MAX(P.PROD_H1_ID) AS PROD_H1_ID, DWWANT.FN_GET_PROD_HIER_NM(MAX(P.PROD_H1_ID)) AS PROD_H1_NM
         , MAX(P.PROD_H2_ID) AS PROD_H2_ID, DWWANT.FN_GET_PROD_HIER_NM(MAX(P.PROD_H2_ID)) AS PROD_H2_NM
         , A.PROD_MATL_ID, MAX(P.PROD_MATL_NM) AS PROD_MATL_NM
         , MIN(A.POS_YM) AS POS_YM
         , SUM(A.POS_QTY_PCS_D) AS POS_QTY_PCS_D, SUM(A.POS_QTY_PKG_D) AS POS_QTY_PKG_D, SUM(A.POS_AMT_D) AS POS_AMT_D
         , SUM(A.POS_QTY_PCS_M) AS POS_QTY_PCS_M, SUM(A.POS_QTY_PKG_M) AS POS_QTY_PKG_M, SUM(A.POS_AMT_M) AS POS_AMT_M
    FROM DWWANT.TRAS_KA_POS_MATL_M A
    LEFT JOIN DWWANT.PROD_MATL P ON A.PROD_MATL_ID=P.PROD_MATL_ID
    WHERE A.POS_YM=LEFT(VAR_POS_DATE_MIN, 6)
    GROUP BY A.KA_SYSTEM_CODE, A.KA_STORE_CODE, A.PROD_MATL_ID
    ;

    INSERT INTO DMMDL.DC0024_STORE_M
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , KA_SYSTEM_CODE, DWWANT.FN_GET_CM_KA_SYSTEM_NM(KA_SYSTEM_CODE) AS KA_SYSTEM_NM
         , KA_STORE_CODE, MIN(KA_STORE_NM) AS KA_STORE_NM
         , MAX(SALES_COM_ID_SA) AS SALES_COM_ID_SA, DWWANT.FN_GET_ORG_SALES_COM_ABR(MAX(SALES_COM_ID_SA)) AS SALES_COM_ABR_SA
         , MAX(SALES_COM_ID_WH) AS SALES_COM_ID_WH, DWWANT.FN_GET_ORG_SALES_COM_ABR(MAX(SALES_COM_ID_WH)) AS SALES_COM_ABR_WH
         , MAX(SALES_COM_ID_DE) AS SALES_COM_ID_DE, DWWANT.FN_GET_ORG_SALES_COM_ABR(MAX(SALES_COM_ID_DE)) AS SALES_COM_ABR_DE
         , MIN(POS_YM) AS POS_YM
         , SUM(POS_QTY_PCS_D) AS POS_QTY_PCS_D, SUM(POS_QTY_PKG_D) AS POS_QTY_PKG_D, SUM(POS_AMT_D) AS POS_AMT_D
         , SUM(POS_QTY_PCS_M) AS POS_QTY_PCS_M, SUM(POS_QTY_PKG_M) AS POS_QTY_PKG_M, SUM(POS_AMT_M) AS POS_AMT_M
    FROM DWWANT.TRAS_KA_POS_STORE_M A
    WHERE A.POS_YM=LEFT(VAR_POS_DATE_MIN, 6)
    GROUP BY KA_SYSTEM_CODE, KA_STORE_CODE
    ;

    SET VAR_SP_RESULT='Y';
    COMMIT;
END
;