DROP PROCEDURE IF EXISTS DWWANT.SP_DC0021_00001_DELETE_DATA;

CREATE PROCEDURE DWWANT.SP_DC0021_00001_DELETE_DATA (
    VAR_EDI_NO CHAR(12), VAR_DATA_DATE CHAR(8), OUT VAR_SP_RESULT CHAR(1)
)
BEGIN

    DELETE FROM DMMDL.DC0021_CUST_SALES WHERE DATA_DATE=VAR_DATA_DATE;
    DELETE FROM DMMDL.DC0021_CUST_STMT WHERE DATA_DATE=VAR_DATA_DATE;
    DELETE FROM DMMDL.DC0021_REQ WHERE DATA_DATE=VAR_DATA_DATE;

    DELETE FROM DMMDL.DC0021_SALES_RPT01_HEAD WHERE DATA_DATE=VAR_DATA_DATE;
    DELETE FROM DMMDL.DC0021_SALES_RPT01 WHERE DATA_DATE=VAR_DATA_DATE;

    SET VAR_SP_RESULT='Y';
    COMMIT;
END
;