DROP PROCEDURE IF EXISTS DWWANT.SP_KA_ORDER_30104_TRAS_KA_ORDR_APPD;

CREATE PROCEDURE DWWANT.SP_KA_ORDER_30104_TRAS_KA_ORDR_APPD (
    VAR_EDI_NO CHAR(12), VAR_DATA_DATE CHAR(8), OUT VAR_SP_RESULT CHAR(1)
)
BEGIN
    DECLARE VAR_DATE_MIN CHAR(8);

    SET VAR_DATE_MIN = CONCAT(DATE_FORMAT(DATE_ADD(STR_TO_DATE(VAR_DATA_DATE, '%Y%m%d'), INTERVAL -3 MONTH), '%Y%m'), '01');

    INSERT INTO DWWANT.TRAS_KA_ORDR_APPD_M
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , K.ID AS APPD_SEQ
         , (CASE WHEN K.ORDER_MAIN_ID='' THEN NULL ELSE K.ORDER_MAIN_ID END) AS ORDR_MAIN_ID
         , (CASE WHEN K.SAP_ORDER_NO='' THEN NULL ELSE K.SAP_ORDER_NO END) AS SAP_ORDR_NO
         , (CASE WHEN K.SAP_DELIVERY_BRANCH='' THEN NULL ELSE K.SAP_DELIVERY_BRANCH END) AS SALES_COM_ID_DE
         , (CASE WHEN K.SAP_OPEN_ORDER_DATE='' THEN NULL ELSE K.SAP_OPEN_ORDER_DATE END) AS OPEN_ORDR_DATE
         , (CASE WHEN K.SAP_CHECK_NUM='' THEN NULL ELSE K.SAP_CHECK_NUM END) AS APPD_USER
         , (CASE WHEN K.RETURN_TIME='' THEN NULL ELSE K.RETURN_TIME END) AS RETURN_TIME
    FROM RAWWANT.KA_WANTWANT_KA_SAP_PIN_CHECK K
    ;

    INSERT INTO DWWANT.TRAS_KA_ORDR_APPD_D
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , (CASE WHEN K.SAP_PIN_CHECK_ID=-99999 THEN NULL ELSE K.SAP_PIN_CHECK_ID END) AS APPD_SEQ
         , K.ID AS APPD_D_SEQ
         , (CASE WHEN K.SAP_POSNR=-99999 THEN NULL ELSE K.SAP_POSNR END) AS SAP_LINE_NUM
         , (CASE WHEN K.SAP_PER_PRICE=-99999 THEN NULL ELSE K.SAP_PER_PRICE END) AS SAP_AMT_PKG
         , (CASE WHEN K.SAP_ORDER_CREATE_NUM=-99999 THEN NULL ELSE K.SAP_ORDER_CREATE_NUM END) AS SAP_QTY_PKG
         , (CASE WHEN K.AUDIT_STATUS=-99999 THEN NULL ELSE CONVERT(K.AUDIT_STATUS, CHAR) END) AS APPD_STATUS
         , (CASE WHEN K.SAP_REASON_REJECTION='' THEN NULL ELSE K.SAP_REASON_REJECTION END) AS RETURN_LINE_RMK
    FROM RAWWANT.KA_WANTWANT_KA_SAP_PIN_CHECK_DETAIL K
    ;

    INSERT INTO DWWANT.TRAS_KA_ORDR_APPD
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , M.ORDR_MAIN_ID, M.SAP_ORDR_NO
         , M.SALES_COM_ID_DE, M.OPEN_ORDR_DATE
         , M.APPD_USER, M.RETURN_TIME
         , D.SAP_LINE_NUM
         , D.SAP_AMT_PKG, D.SAP_QTY_PKG
         , D.APPD_STATUS, D.RETURN_LINE_RMK
    FROM (SELECT SAP_ORDR_NO, MAX(RETURN_TIME) AS RETURN_TIME_MAX
          FROM DWWANT.TRAS_KA_ORDR_APPD_M
          GROUP BY SAP_ORDR_NO) X
    JOIN DWWANT.TRAS_KA_ORDR_APPD_M M
    ON X.SAP_ORDR_NO=M.SAP_ORDR_NO AND X.RETURN_TIME_MAX=M.RETURN_TIME
    JOIN DWWANT.TRAS_KA_ORDR_APPD_D D
    ON M.APPD_SEQ=D.APPD_SEQ
    WHERE M.OPEN_ORDR_DATE>=VAR_DATE_MIN AND M.OPEN_ORDR_DATE<=VAR_DATA_DATE
    ;

    SET VAR_SP_RESULT='Y';
    COMMIT;
END
;
