DROP PROCEDURE IF EXISTS DWWANT.SP_DC0021_30103_REQ;

CREATE PROCEDURE DWWANT.SP_DC0021_30103_REQ (
    VAR_EDI_NO CHAR(12), VAR_DATA_DATE CHAR(8), OUT VAR_SP_RESULT CHAR(1)
)
BEGIN
    DECLARE VAR_RPT_YM CHAR(6);
    DECLARE VAR_RPT_YM_NEXT CHAR(6);

    SET VAR_RPT_YM = SUBSTR(VAR_DATA_DATE, 1, 6);
    SET VAR_RPT_YM_NEXT = SUBSTR(DWWANT.FN_GET_DATE(DATE_ADD(CONVERT(VAR_DATA_DATE, DATE), INTERVAL 1 MONTH)), 1, 6);

    INSERT INTO DMMDL.DC0021_REQ
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , A.REQ_YM
         , A.WANT_CHAN_ID, W.WANT_CHAN_NM
         , A.WANT_COM_ID, C.WANT_COM_NM
         , IFNULL(A.PROD_H1_ID, 'NULL') AS PROD_H1_ID, H1.PROD_H_NM AS PROD_H1_NM
         , IFNULL(A.PROD_H2_ID, 'NULL') AS PROD_H2_ID, H2.PROD_H_NM AS PROD_H2_NM
         , IFNULL(A.PROD_H3_ID, 'NULL') AS PROD_H3_ID, H3.PROD_H_NM AS PROD_H3_NM
         , A.REQ_QTY_PKG, A.REQ_AMT
         , NULL AS BU01_ID, NULL AS BU01_NM
    FROM (SELECT R.REQ_YM, R.WANT_CHAN_ID, R.WANT_COM_ID, P.PROD_H1_ID, P.PROD_H2_ID, P.PROD_H3_ID
               , SUM(R.REQ_QTY_PKG) AS REQ_QTY_PKG, SUM(R.REQ_AMT) AS REQ_AMT
          FROM DWWANT.ORDR_REQ R
          JOIN DWWANT.PROD_MATL P ON R.PROD_MATL_ID=P.PROD_MATL_ID
          WHERE R.REQ_YM IN (VAR_RPT_YM, VAR_RPT_YM_NEXT)
            AND R.WANT_CHAN_ID IN ('WW0016','WW0047','WW0052','WW0053')
            AND P.PROD_H2_ID<>'D11M01'
          GROUP BY R.REQ_YM, R.WANT_CHAN_ID, R.WANT_COM_ID, P.PROD_H1_ID, P.PROD_H2_ID, P.PROD_H3_ID) A
    LEFT JOIN DWWANT.ORG_WANT_CHAN W ON A.WANT_CHAN_ID=W.WANT_CHAN_ID
    LEFT JOIN DWWANT.ORG_WANT_COM C ON A.WANT_COM_ID=C.WANT_COM_ID
    LEFT JOIN DWWANT.PROD_HIER H1 ON A.PROD_H1_ID=H1.PROD_H_ID
    LEFT JOIN DWWANT.PROD_HIER H2 ON A.PROD_H2_ID=H2.PROD_H_ID
    LEFT JOIN DWWANT.PROD_HIER H3 ON A.PROD_H3_ID=H3.PROD_H_ID
    WHERE A.REQ_AMT<>0 OR A.REQ_QTY_PKG<>0
    ;

    UPDATE DMMDL.DC0021_REQ SET
        BU01_ID=(CASE WHEN WANT_CHAN_ID IN ('WW0052','WW0053','WW0047') AND WANT_COM_ID IN ('W10','W12','W31','W32','WX5','WX6','WXI') THEN 'BU01'
                      WHEN WANT_CHAN_ID IN ('WW0052','WW0053','WW0047') AND WANT_COM_ID IN ('W11','W13','W14','W46','WX1','WXC') THEN 'BU02'
                      WHEN WANT_CHAN_ID IN ('WW0052','WW0053','WW0047') AND WANT_COM_ID IN ('W27','W28','W29','W77','WXD','WXE','WXG') THEN 'BU03'
                      WHEN WANT_CHAN_ID IN ('WW0052','WW0053','WW0047') AND WANT_COM_ID IN ('W34','W55','WX2','WXF') THEN 'BU04'
                      WHEN WANT_CHAN_ID IN ('WW0052','WW0053','WW0047') AND WANT_COM_ID IN ('W18','W49','W50','W75','WX8','WX9','WXA','WXB') THEN 'BU05'
                      WHEN WANT_CHAN_ID IN ('WW0052','WW0053','WW0047') AND WANT_COM_ID IN ('W19','W20','W21','W22','W23','W24','W76','WX3') THEN 'BU06'
                      WHEN WANT_CHAN_ID IN ('WW0052','WW0053','WW0047') AND WANT_COM_ID IN ('W35','W36','W37','W38','WX4','WXH') THEN 'BU07'
                      WHEN WANT_CHAN_ID IN ('WW0052','WW0053','WW0047')  AND WANT_COM_ID IN ('W25','W39','W40','W44','W78','WX7') THEN 'BU08'
                      WHEN WANT_CHAN_ID='WW0016' THEN 'BU11'
                      ELSE 'NULL'
                 END)
    WHERE DATA_DATE=VAR_DATA_DATE
    ;
    
    UPDATE DMMDL.DC0021_REQ SET
        BU01_NM=DMMDL.FN_GET_CM_CODE_NM('0001', BU01_ID)
    WHERE DATA_DATE=VAR_DATA_DATE
    ;

    SET VAR_SP_RESULT='Y';
    COMMIT;
END
;