DROP PROCEDURE IF EXISTS DWWANT.SP_KA_30102_KA_INV;

CREATE PROCEDURE DWWANT.SP_KA_30102_KA_INV (
    VAR_EDI_NO CHAR(12), VAR_DATA_DATE CHAR(8), OUT VAR_SP_RESULT CHAR(1)
)
BEGIN

    INSERT INTO DWWANT.TRAS_KA_INV
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , K.ID AS INV_SEQ
         , (CASE WHEN K.SYS_CODE='' THEN NULL ELSE K.SYS_CODE END) AS KA_SYSTEM_CODE
         , (CASE WHEN K.SYS_ACCOUNT='' THEN NULL ELSE K.SYS_ACCOUNT END) AS SYSTEM_ACCT
         , (CASE WHEN K.SYS_OTHER_INFO='' THEN NULL ELSE K.SYS_OTHER_INFO END) AS SYSTEM_ACCT_INFO
         , (CASE WHEN K.STORE_CODE='' THEN NULL ELSE K.STORE_CODE END) AS SYSTEM_STORE_CODE
         , (CASE WHEN K.STORE_NAME='' THEN NULL ELSE K.STORE_NAME END) AS SYSTEM_STORE_NM
         , (CASE WHEN K.KA_STORE_CODE='' THEN NULL 
                 ELSE (CASE WHEN LENGTH(K.KA_STORE_CODE)=11 THEN RIGHT(K.KA_STORE_CODE,6) 
                            WHEN LENGTH(K.KA_STORE_CODE)=9 THEN RIGHT(K.KA_STORE_CODE,4) 
                       END)
            END) AS KA_STORE_CODE
         , (CASE WHEN K.WW_STORE_NAME='' THEN NULL ELSE K.WW_STORE_NAME END) AS KA_STORE_NM
         , (CASE WHEN K.CODE_SPLIT_GROUND='' THEN NULL ELSE K.CODE_SPLIT_GROUND END) AS SALES_COM_ID_SA
         , (CASE WHEN K.CODE_WAREHOUSE_PLOT='' THEN NULL ELSE K.CODE_WAREHOUSE_PLOT END) AS SALES_COM_ID_WH
         , (CASE WHEN K.WW_DELIVERY_BRANCH_OFFICE_CODE='' THEN NULL ELSE K.WW_DELIVERY_BRANCH_OFFICE_CODE END) AS SALES_COM_ID_DE
         , (CASE WHEN K.SALE_PROD_CODE='' THEN NULL ELSE K.SALE_PROD_CODE END) AS SYSTEM_PROD_CODE
         , (CASE WHEN K.PROD_NAME='' THEN NULL ELSE K.PROD_NAME END) AS SYSTEM_PROD_NM
         , (CASE WHEN K.PROD_SPEC='' THEN NULL ELSE K.PROD_SPEC END) AS SYSTEM_PROD_SPEC
         , (CASE WHEN K.MIN_PROD_UNIT='' THEN NULL ELSE LEFT(K.MIN_PROD_UNIT,10) END) AS SYSTEM_PROD_UNIT
         , (CASE WHEN K.SERIAL_NUM<>'' AND DWWANT.FN_IS_NUMERIC(K.SERIAL_NUM)='Y' THEN CONVERT(K.SERIAL_NUM, INT) ELSE NULL END) AS KA_PROD_SEQ
         , (CASE WHEN K.KA_MATERIEL_CODE='' THEN NULL ELSE K.KA_MATERIEL_CODE END) AS PROD_MATL_ID
         , (CASE WHEN K.MEANS_DATE='' THEN NULL ELSE K.MEANS_DATE END) AS INV_CRAWL_DATE
         , (CASE WHEN K.MEANS_TIME='' THEN NULL ELSE K.MEANS_TIME END) AS INV_CRAWL_TIME
         , (CASE WHEN K.IS_MEANS='Y' THEN 'O' ELSE 'F' END) AS INV_SOURCE
         , (CASE WHEN K.MATCH_STATUS IS NULL THEN NULL ELSE CONVERT(K.MATCH_STATUS, CHAR) END) AS INV_STATUS
         , (CASE WHEN K.INV_DIVISION='' THEN NULL ELSE K.INV_DIVISION END) AS INV_TYPE
         , (CASE WHEN K.INV_DATE='' THEN NULL ELSE K.INV_DATE END) AS INV_DATE
         , (CASE WHEN K.INV_NUM=-99999 THEN NULL ELSE K.INV_NUM END) AS INV_QTY_PCS
         , (CASE WHEN K.INV_BOX_NUM=-99999 THEN NULL ELSE K.INV_BOX_NUM END) AS INV_QTY_PKG
    FROM RAWWANT.KA_WANTWANT_SYS_INV_DATA K
    ;

    SET VAR_SP_RESULT='Y';
    COMMIT;
END
;