DROP PROCEDURE IF EXISTS DWWANT.SP_DC0024_ORDER_30102_SYS;

CREATE PROCEDURE DWWANT.SP_DC0024_ORDER_30102_SYS (
    VAR_EDI_NO CHAR(12), VAR_DATA_DATE CHAR(8), OUT VAR_SP_RESULT CHAR(1)
)
BEGIN
    DECLARE VAR_DATE_MIN CHAR(8);

    SET VAR_DATE_MIN = CONCAT(DATE_FORMAT(DATE_ADD(STR_TO_DATE(VAR_DATA_DATE, '%Y%m%d'), INTERVAL -3 MONTH), '%Y%m'), '01');

    INSERT INTO DMMDL.DC0024_ORDR_SYS_D
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , R.KA_SYSTEM_CODE
         , DWWANT.FN_GET_CM_KA_SYSTEM_NM(R.KA_SYSTEM_CODE) AS KA_SYSTEM_NM
         , R.SYSTEM_ORDR_DATE
         , R.ORDR_MAIN_ID
         , R.SYSTEM_ORDR_NO
         , R.SALES_COM_ID_DE
         , DWWANT.FN_GET_ORG_SALES_COM_ABR(R.SALES_COM_ID_DE) AS SALES_COM_NM_DE
         , R.SALES_COM_ID_BL
         , DWWANT.FN_GET_ORG_SALES_COM_ABR(R.SALES_COM_ID_BL) AS SALES_COM_NM_BL
         , R.SALES_CHAN_ID
         , R.PROD_DIV_ID
         , R.CUST_ID
         , LEFT(R.SYSTEM_DEV_TIME, 8) AS SYSTEM_DEV_DATE
        
         , R.ORDR_LINE_NUM
         , R.SYSTEM_ORDR_PROD_NM
         , (SELECT PROD_H1_ID from DWWANT.PROD_MATL WHERE PROD_MATL_ID=R.PROD_MATL_ID) AS PROD_H1_ID
         , DWWANT.FN_GET_PROD_HIER_NM((SELECT PROD_H1_ID from DWWANT.PROD_MATL WHERE PROD_MATL_ID=R.PROD_MATL_ID)) AS PROD_H1_NM
         , (SELECT PROD_H2_ID from DWWANT.PROD_MATL WHERE PROD_MATL_ID=R.PROD_MATL_ID) AS PROD_H2_ID
         , DWWANT.FN_GET_PROD_HIER_NM((SELECT PROD_H2_ID from DWWANT.PROD_MATL WHERE PROD_MATL_ID=R.PROD_MATL_ID)) AS PROD_H2_NM
         , R.PROD_MATL_ID
         , DWWANT.FN_GET_PROD_MATL_NM(R.PROD_MATL_ID) AS PROD_MATL_NM
         , R.PROD_AMT_PKG
         , R.TRAS_PROD_AMT_PKG
         , R.PROD_QTY_PKG
         , R.SAP_QTY_PKG_APPD_SUM_DIR
         , R.SAP_QTY_PKG_APPD_SUM
         , R.SAP_QTY_PKG_APPD_SUM_DIF
         , R.SHIP_QTY_PKG_DIF_SUM
         , R.SHIP_QTY_PKG_DEV_SUM
         , R.SHIP_QTY_PKG_ACT_SUM
         , R.SHIP_QTY_PKG_ACT_SUM_DIF
        
         , DWWANT.FN_GET_CM_CODE_NM('0008', R.TRAS_RETURN_PHASE) AS TRAS_RETURN_PHASE_NM
         , R.TRAS_RETURN_RMK
    FROM DWWANT.ORDR_KA R
    WHERE R.KA_SYSTEM_CODE IN ('C005','C010','H001','H002','H005','H007','H009','H010','H011','H013',
                               'H016','H017','H018','H021','H042','H060','S004','S006','S009','S010',
                               'S011','S014','S018','S020','S026','S030','S031','S044','S052','S063',
                               'S110','S151','S219')
      AND R.SYSTEM_ORDR_DATE>=VAR_DATE_MIN AND R.SYSTEM_ORDR_DATE<=VAR_DATA_DATE
    ORDER BY R.KA_SYSTEM_CODE, R.SYSTEM_ORDR_DATE, R.SYSTEM_ORDR_NO, R.ORDR_LINE_NUM
    ;

    SET VAR_SP_RESULT='Y';
    COMMIT;
END
;