DROP PROCEDURE IF EXISTS DWWANT.SP_HR_00001_DELETE_DATA;

CREATE PROCEDURE DWWANT.SP_HR_00001_DELETE_DATA (
    VAR_EDI_NO CHAR(12), VAR_DATA_DATE CHAR(8), OUT VAR_SP_RESULT CHAR(1)
)
BEGIN

    TRUNCATE TABLE DWWANT.CM_EMP_POS;
    TRUNCATE TABLE DWWANT.CM_EMP_POS_PROP;
    TRUNCATE TABLE DWWANT.CM_EMP_POS_TITLE;
    TRUNCATE TABLE DWWANT.CM_EMP_POS_LEVEL;

    TRUNCATE TABLE DWWANT.ORG_HR_COM;
    TRUNCATE TABLE DWWANT.ORG_HR_OFF;

    TRUNCATE TABLE DWWANT.ORG_EMP;
    TRUNCATE TABLE DWWANT.ORG_EMP_SALES_HR;

    SET VAR_SP_RESULT='Y';
    COMMIT;
END
;