DROP PROCEDURE IF EXISTS DWWANT.SP_MAIN_00001_DELETE_DATA;

CREATE PROCEDURE DWWANT.SP_MAIN_00001_DELETE_DATA (
    VAR_EDI_NO CHAR(12), VAR_DATA_DATE CHAR(8), OUT VAR_SP_RESULT CHAR(1)
)
BEGIN
    DECLARE VAR_YM_BEGIN CHAR(6);
    DECLARE VAR_YMD_BEGIN CHAR(8);

    SET VAR_YM_BEGIN = SUBSTR(DWWANT.FN_GET_DATE(DATE_ADD(VAR_DATA_DATE, INTERVAL -2 YEAR)), 1, 6);
    SET VAR_YMD_BEGIN = DWWANT.FN_GET_DATE(DATE_ADD(VAR_DATA_DATE, INTERVAL -31 DAY));

    TRUNCATE TABLE DWWANT.CM_WORKDAY;

    TRUNCATE TABLE DWWANT.CM_AREA_COTY;
    TRUNCATE TABLE DWWANT.CM_AREA_TWSP;
    TRUNCATE TABLE DWWANT.CM_AREA_HAME;

    TRUNCATE TABLE DWWANT.CM_SALES_CREDIT;

    TRUNCATE TABLE DWWANT.CM_KA_SYSTEM;

    TRUNCATE TABLE DWWANT.CM_EMP_POS_TYPE;

    TRUNCATE TABLE DWWANT.ORG_SALES_CHAN;
    TRUNCATE TABLE DWWANT.ORG_SALES_COM;
    TRUNCATE TABLE DWWANT.ORG_SALES_OFF;

    TRUNCATE TABLE DWWANT.ORG_WANT_CHAN;
    TRUNCATE TABLE DWWANT.ORG_WANT_COM;

    TRUNCATE TABLE DWWANT.ORG_IWANT_BU;
    TRUNCATE TABLE DWWANT.ORG_IWANT_CHAN;
    TRUNCATE TABLE DWWANT.ORG_IWANT_COM;
    TRUNCATE TABLE DWWANT.ORG_IWANT_OFF;
    TRUNCATE TABLE DWWANT.ORG_IWANT_REGN;

    TRUNCATE TABLE DWWANT.ORG_IWANT_DIST;
    TRUNCATE TABLE DWWANT.ORG_IWANT_MARKET;
    TRUNCATE TABLE DWWANT.ORG_IWANT_MARKET_SMALL;

    TRUNCATE TABLE DWWANT.ORG_EMP_SALES_IWANT;

    TRUNCATE TABLE DWWANT.PROD_DIV;
    TRUNCATE TABLE DWWANT.PROD_HIER;
    TRUNCATE TABLE DWWANT.PROD_G1;
    TRUNCATE TABLE DWWANT.PROD_G2;
    TRUNCATE TABLE DWWANT.PROD_MATL;

    TRUNCATE TABLE DWWANT.CUST_MAIN;
    TRUNCATE TABLE DWWANT.CUST_SD;
    TRUNCATE TABLE DWWANT.CUST_SD_SALES_COM;
    TRUNCATE TABLE DWWANT.CUST_SD_SALES_COM_PROD;
    TRUNCATE TABLE DWWANT.CUST_IWANT;
    TRUNCATE TABLE DWWANT.CUST_IWANT_MARKET;
    TRUNCATE TABLE DWWANT.CUST_IWANT_MARKET_PROD;
    TRUNCATE TABLE DWWANT.CUST_IWANT_EMP_SALES;

    DELETE FROM DWWANT.ORDR_REQ_CUST_TT WHERE REQ_YM>=VAR_YM_BEGIN;
    DELETE FROM DWWANT.ORDR_REQ_CUST_KA WHERE REQ_YM>=VAR_YM_BEGIN;
    DELETE FROM DWWANT.ORDR_REQ_COM WHERE REQ_YM>=VAR_YM_BEGIN;

    DELETE FROM DWWANT.ORDR_REQ WHERE REQ_YM>=VAR_YM_BEGIN;

    DELETE FROM DWWANT.TRAS_CUST_POSTED WHERE POSTED_YM>=VAR_YM_BEGIN;
    TRUNCATE TABLE DWWANT.TRAS_CUST_POSTING;

    DELETE FROM DWWANT.TRAS_CUST_POSTED_SALES_D WHERE POSTED_YMD>=VAR_YMD_BEGIN;
    DELETE FROM DWWANT.TRAS_CUST_POSTED_SALES WHERE POSTED_YM>=VAR_YM_BEGIN;
    TRUNCATE TABLE DWWANT.TRAS_CUST_POSTING_SALES;

    DELETE FROM DWWANT.TRAS_CUST_SALES WHERE POSTED_YM>=VAR_YM_BEGIN;

    TRUNCATE TABLE DWWANT.FI_CUST_BAL;
    TRUNCATE TABLE DWWANT.FI_CUST_SPEC;

    TRUNCATE TABLE DWWANT.FI_CUST_STMT;

    SET VAR_SP_RESULT='Y';
    COMMIT;
END
;