DROP PROCEDURE IF EXISTS DWWANT.SP_MAIN_30107_ORDR;

CREATE PROCEDURE DWWANT.SP_MAIN_30107_ORDR (
    VAR_EDI_NO CHAR(12), VAR_DATA_DATE CHAR(8), OUT VAR_SP_RESULT CHAR(1)
)
BEGIN
    DECLARE VAR_YM_BEGIN CHAR(6);

    SET VAR_YM_BEGIN = SUBSTR(DWWANT.FN_GET_DATE(DATE_ADD(VAR_DATA_DATE, INTERVAL -2 YEAR)), 1, 6);

    INSERT INTO DWWANT.ORDR_REQ_CUST_TT
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , (CASE WHEN R.YEARMONTH=''          THEN 'NULL' ELSE R.YEARMONTH                    END) AS REQ_YM
         , (CASE WHEN R.PROD_ID=''            THEN 'NULL' ELSE R.PROD_ID                      END) AS PROD_MATL_ID
         , (CASE WHEN R.PROD_GROUP=''         THEN  NULL  ELSE R.PROD_GROUP                   END) AS PROD_DIV_ID
         , (CASE WHEN R.SALES_CHANNEL=''      THEN  NULL  ELSE R.SALES_CHANNEL                END) AS SALES_CHAN_ID
         , (CASE WHEN R.CHANNEL_ID=''         THEN 'NULL' ELSE R.CHANNEL_ID                   END) AS IWANT_CHAN_ID
         , (CASE WHEN R.COMPANY_ID=''         THEN  NULL  ELSE R.COMPANY_ID                   END) AS IWANT_COM_ID
         , (CASE WHEN R.THIRD_ID=''           THEN  NULL  ELSE R.THIRD_ID                     END) AS AREA_COTY_ID
         , (CASE WHEN R.CUSTOMER_ID=''        THEN 'NULL' ELSE CONCAT('00000', R.CUSTOMER_ID) END) AS CUST_ID
         , (CASE WHEN R.SF_QUANTITY=-99999    THEN  NULL  ELSE R.SF_QUANTITY                  END) AS REQ_QTY_PKG
         , (CASE WHEN R.SF_AMOUNT=-99999      THEN  NULL  ELSE R.SF_AMOUNT                    END) AS REQ_AMT
         , (CASE WHEN R.NEXT_SF_QTY=-99999    THEN  NULL  ELSE R.NEXT_SF_QTY                  END) AS REQ_QTY_PKG_NEXT
         , (CASE WHEN R.NEXT_SF_AMOUNT=-99999 THEN  NULL  ELSE R.NEXT_SF_AMOUNT               END) AS REQ_AMT_NEXT
    FROM RAWWANT.IRPT_SAPBW_ZBW_SF_PF_VIEW R
    WHERE LENGTH(R.YEARMONTH)=6
    ;

    INSERT INTO DWWANT.ORDR_REQ_CUST_KA
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , (CASE WHEN R.YEARMONTH=''          THEN 'NULL' ELSE R.YEARMONTH                        END) AS REQ_YM
         , (CASE WHEN R.PROD_ID=''            THEN 'NULL' ELSE R.PROD_ID                          END) AS PROD_MATL_ID
         , (CASE WHEN R.PROD_GROUP=''         THEN  NULL  ELSE R.PROD_GROUP                       END) AS PROD_DIV_ID
         , (CASE WHEN R.SALES_CHANNEL=''      THEN  NULL  ELSE R.SALES_CHANNEL                    END) AS SALES_CHAN_ID
         , (CASE WHEN R.CHANNEL_ID=''         THEN  NULL  ELSE R.CHANNEL_ID                       END) AS IWANT_CHAN_ID
         , (CASE WHEN R.COMPANY_ID=''         THEN  NULL  ELSE R.COMPANY_ID                       END) AS IWANT_COM_ID
         , (CASE WHEN R.THIRD_ID=''           THEN  NULL  ELSE R.THIRD_ID                         END) AS AREA_COTY_ID
         , (CASE WHEN R.SYS_ID=''             THEN  NULL  ELSE R.SYS_ID                           END) AS KA_SYSTEM_ID
         , (CASE WHEN R.STORE_ID=''           THEN 'NULL' ELSE R.STORE_ID                         END) AS TERM_ID
         , (CASE WHEN R.ERP_ID=''             THEN  NULL  ELSE CONCAT('0000000', R.ERP_ID)        END) AS CUST_ID
         , (CASE WHEN R.KEYACCOUNT_ID=''      THEN  NULL  ELSE CONCAT('0000000', R.KEYACCOUNT_ID) END) AS CUST_ID_WH
         , (CASE WHEN R.SF_QUANTITY=-99999    THEN  NULL  ELSE R.SF_QUANTITY                      END) AS REQ_QTY_PKG
         , (CASE WHEN R.SF_AMOUNT=-99999      THEN  NULL  ELSE R.SF_AMOUNT                        END) AS REQ_AMT
         , (CASE WHEN R.NEXT_SF_QTY=-99999    THEN  NULL  ELSE R.NEXT_SF_QTY                      END) AS REQ_QTY_PKG_NEXT
         , (CASE WHEN R.NEXT_SF_AMOUNT=-99999 THEN  NULL  ELSE R.NEXT_SF_AMOUNT                   END) AS REQ_AMT_NEXT
    FROM RAWWANT.IRPT_SAPBW_ZBW_SF_ZY_VIEW R
    ;

    INSERT INTO DWWANT.ORDR_REQ_COM
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , (CASE WHEN R.YEARMONTH=''          THEN 'NULL' ELSE R.YEARMONTH      END) AS REQ_YM
         , (CASE WHEN R.PROD_ID=''            THEN 'NULL' ELSE R.PROD_ID        END) AS PROD_MATL_ID
         , (CASE WHEN R.PROD_GROUP=''         THEN  NULL  ELSE R.PROD_GROUP     END) AS PROD_DIV_ID
         , (CASE WHEN R.SALES_CHANNEL=''      THEN  NULL  ELSE R.SALES_CHANNEL  END) AS SALES_CHAN_ID
         , (CASE WHEN R.CHANNEL_ID=''         THEN 'NULL' ELSE R.CHANNEL_ID     END) AS IWANT_CHAN_ID
         , (CASE WHEN R.COMPANY_ID=''         THEN 'NULL' ELSE R.COMPANY_ID     END) AS IWANT_COM_ID
         , (CASE WHEN R.AREA_ID=''            THEN 'NULL' ELSE R.AREA_ID        END) AS IWANT_REGN_ID
         , (CASE WHEN R.SF_QUANTITY=-99999    THEN  NULL  ELSE R.SF_QUANTITY    END) AS REQ_QTY_PKG
         , (CASE WHEN R.SF_AMOUNT=-99999      THEN  NULL  ELSE R.SF_AMOUNT      END) AS REQ_AMT
         , (CASE WHEN R.NEXT_SF_QTY=-99999    THEN  NULL  ELSE R.NEXT_SF_QTY    END) AS REQ_QTY_PKG_NEXT
         , (CASE WHEN R.NEXT_SF_AMOUNT=-99999 THEN  NULL  ELSE R.NEXT_SF_AMOUNT END) AS REQ_AMT_NEXT
    FROM RAWWANT.IRPT_SAPBW_ZBW_SF_PF2_VIEW R
    ;

     INSERT INTO DWWANT.ORDR_REQ
     SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
          , A.REQ_YM, A.WANT_CHAN_ID, A.WANT_COM_ID, A.SALES_OFF_ID, A.PROD_MATL_ID, A.CUST_ID, A.KA_SYSTEM_ID
          , SUM(A.REQ_QTY_PKG) AS REQ_QTY_PKG, SUM(A.REQ_AMT) AS REQ_AMT
          , SUM(A.REQ_QTY_PKG_NEXT) AS REQ_QTY_PKG_NEXT, SUM(A.REQ_AMT_NEXT) AS REQ_AMT_NEXT
     FROM (SELECT R.REQ_YM
                , DWWANT.FN_GET_ORG_WANT_CHAN_ID(R.SALES_CHAN_ID, R.PROD_DIV_ID) AS WANT_CHAN_ID
                , C.WANT_COM_ID, C.SALES_OFF_ID
                , R.PROD_MATL_ID
                , R.CUST_ID
                , NULL AS KA_SYSTEM_ID
                , R.REQ_QTY_PKG, R.REQ_AMT, R.REQ_QTY_PKG_NEXT, R.REQ_AMT_NEXT
           FROM DWWANT.ORDR_REQ_CUST_TT R
           JOIN DWWANT.CUST_SD C ON R.CUST_ID=C.CUST_ID
           WHERE R.REQ_YM>=VAR_YM_BEGIN
           UNION ALL
           SELECT R.REQ_YM
                , DWWANT.FN_GET_ORG_WANT_CHAN_ID(R.SALES_CHAN_ID, R.PROD_DIV_ID) AS WANT_CHAN_ID
                , C.WANT_COM_ID, C.SALES_OFF_ID
                , R.PROD_MATL_ID
                , (CASE WHEN R.CUST_ID IS NOT NULL THEN R.CUST_ID ELSE R.CUST_ID_WH END) AS CUST_ID
                , R.KA_SYSTEM_ID
                , R.REQ_QTY_PKG, R.REQ_AMT, R.REQ_QTY_PKG_NEXT, R.REQ_AMT_NEXT
           FROM DWWANT.ORDR_REQ_CUST_KA R
           JOIN DWWANT.CUST_SD C ON (CASE WHEN R.CUST_ID IS NOT NULL THEN R.CUST_ID ELSE R.CUST_ID_WH END)=C.CUST_ID
           WHERE R.REQ_YM>=VAR_YM_BEGIN
           UNION ALL
           SELECT R.REQ_YM
                , DWWANT.FN_GET_ORG_WANT_CHAN_ID(R.SALES_CHAN_ID, R.PROD_DIV_ID) AS WANT_CHAN_ID
                , CONCAT('W',SUBSTRING(R.IWANT_COM_ID,2)) AS WANT_COM_ID, NULL AS SALES_OFF_ID
                , R.PROD_MATL_ID
                , 'NULL' AS CUST_ID
                , NULL AS KA_SYSTEM_ID
                , R.REQ_QTY_PKG, R.REQ_AMT, R.REQ_QTY_PKG_NEXT, R.REQ_AMT_NEXT
           FROM DWWANT.ORDR_REQ_COM R
           WHERE R.REQ_YM>=VAR_YM_BEGIN) A
     GROUP BY A.REQ_YM, A.WANT_CHAN_ID, A.WANT_COM_ID, A.SALES_OFF_ID, A.PROD_MATL_ID, A.CUST_ID, A.KA_SYSTEM_ID
     ;

    SET VAR_SP_RESULT='Y';
    COMMIT;
END
;