DROP PROCEDURE IF EXISTS DWWANT.SP_KA_ORDER_30101_ORDR_KA_SYS;

CREATE PROCEDURE DWWANT.SP_KA_ORDER_30101_ORDR_KA_SYS (
    VAR_EDI_NO CHAR(12), VAR_DATA_DATE CHAR(8), OUT VAR_SP_RESULT CHAR(1)
)
BEGIN

    INSERT INTO DWWANT.ORDR_KA_SYS
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , K.ID AS ORDR_SEQ
         , (CASE WHEN K.ORDER_MAIN_ID='' THEN NULL ELSE K.ORDER_MAIN_ID END) AS ORDR_MAIN_ID
         , (CASE WHEN K.SYS_CODE='' THEN NULL ELSE K.SYS_CODE END) AS KA_SYSTEM_CODE
         , (CASE WHEN K.SYS_ACCOUNT='' THEN NULL ELSE K.SYS_ACCOUNT END) AS SYSTEM_ACCT
         , (CASE WHEN K.SYS_OTHER_INFO='' THEN NULL ELSE K.SYS_OTHER_INFO END) AS SYSTEM_ACCT_INFO
         , (CASE WHEN K.STORE_CODE='' THEN NULL ELSE K.STORE_CODE END) AS SYSTEM_STORE_WH_CODE
         , (CASE WHEN K.STORE_NAME='' THEN NULL ELSE K.STORE_NAME END) AS SYSTEM_STORE_WH_NM
         , (CASE WHEN K.DELIVER_ADDRESS_CODE='' THEN NULL ELSE K.DELIVER_ADDRESS_CODE END) AS SYSTEM_DEV_CODE
         , (CASE WHEN K.DELIVER_ADDRESS_DESC='' THEN NULL ELSE K.DELIVER_ADDRESS_DESC END) AS SYSTEM_DEV_NM
         , (CASE WHEN K.SAP_TEXT='' THEN NULL ELSE K.SAP_TEXT END) AS SYSTEM_ORDR_CAT
         , (CASE WHEN K.JUDGE_FIELD='' THEN NULL ELSE K.JUDGE_FIELD END) AS SYSTEM_ORDR_INFO
         , (CASE WHEN K.SAP_CUST_CODE='' THEN NULL ELSE K.SAP_CUST_CODE END) AS CUST_ID
         , (CASE WHEN K.SAP_BILL_DELIVER_CODE='' THEN NULL ELSE K.SAP_BILL_DELIVER_CODE END) AS CUST_ID_DE
         , (CASE WHEN K.SAP_BILL_DELIVER_NAME='' THEN NULL ELSE K.SAP_BILL_DELIVER_NAME END) AS CUST_NM_DE
         , (CASE WHEN K.KA_DELIVER_COMP_CODE='' THEN NULL ELSE K.KA_DELIVER_COMP_CODE END) AS SALES_COM_ID_DE
         , (CASE WHEN K.KA_BILL_COMP_CODE='' THEN NULL ELSE K.KA_BILL_COMP_CODE END) AS SALES_COM_ID_BL
         , (CASE WHEN K.KA_BILL_DITCH_CODE='' THEN NULL ELSE K.KA_BILL_DITCH_CODE END) AS SALES_CHAN_ID
         , (CASE WHEN K.KA_BILL_PROD_CODE='' THEN NULL ELSE K.KA_BILL_PROD_CODE END) AS PROD_DIV_ID
         , (CASE WHEN K.ORDER_NO='' THEN NULL ELSE K.ORDER_NO END) AS SYSTEM_ORDR_NO
         , (CASE WHEN K.ORDER_DATE='' THEN NULL ELSE SUBSTRING(K.ORDER_DATE, 1, 8) END) AS SYSTEM_ORDR_DATE
         , (CASE WHEN (CASE WHEN K.DELIVER_TIME='' THEN NULL ELSE K.DELIVER_TIME END) IS NULL
                 THEN (CASE WHEN K.DELIVER_DATE='' THEN NULL ELSE K.DELIVER_DATE END)
                 ELSE (CASE WHEN K.DELIVER_TIME='' THEN NULL ELSE K.DELIVER_TIME END) END) AS SYSTEM_DEV_TIME
         , (CASE WHEN K.ORDER_DIVISION='' THEN NULL ELSE K.ORDER_DIVISION END) AS SYSTEM_ORDR_TYPE
         , (CASE WHEN K.GOOD_AGE=-99999 THEN NULL ELSE K.GOOD_AGE END) AS SYSTEM_GOOD_AGE
         , (CASE WHEN K.ORDER_NUM=-99999 THEN NULL ELSE K.ORDER_NUM END) AS ORDR_LINE_NUM
         , (CASE WHEN K.SALE_PROD_CODE='' THEN NULL ELSE K.SALE_PROD_CODE END) AS SYSTEM_PROD_CODE
         , (CASE WHEN K.PROD_CODE='' THEN NULL ELSE K.PROD_CODE END) AS SYSTEM_ORDR_PROD_CODE
         , (CASE WHEN K.PROD_NAME='' THEN NULL ELSE K.PROD_NAME END) AS SYSTEM_ORDR_PROD_NM
         , (CASE WHEN K.KA_MATERIEL_CODE='' THEN NULL ELSE K.KA_MATERIEL_CODE END) AS PROD_MATL_ID
         , (CASE WHEN K.IS_BUY_TERM='' THEN NULL ELSE K.IS_BUY_TERM END) AS PROD_IS_SELL_TERM
         , (CASE WHEN K.ALLOW_DATA=-99999 THEN NULL 
                 ELSE DATE_FORMAT(DATE_ADD(STR_TO_DATE(SUBSTRING(K.ORDER_DATE, 1, 8), '%Y%m%d'), INTERVAL K.ALLOW_DATA*-1 DAY), '%Y%m%d') END) AS PROD_ALLOW_DATE
         , (CASE WHEN K.PROD_SPEC='' THEN NULL ELSE K.PROD_SPEC END) AS SYSTEM_PROD_SPEC
         , (CASE WHEN K.MIN_PROD_UNIT='' THEN NULL ELSE K.MIN_PROD_UNIT END) AS SYSTEM_SKU_UNIT
         , (CASE WHEN K.MIN_UNIT_BOX_NUM=-99999 THEN NULL ELSE K.MIN_UNIT_BOX_NUM END) AS SYSTEM_SKU_PER_PKG
         , (CASE WHEN K.MIN_UNIT_PRICE=-99999 THEN NULL ELSE K.MIN_UNIT_PRICE END) AS SYSTEM_SKU_AMT
         , (CASE WHEN K.MIN_UNIT_ORDER_NUM=-99999 THEN NULL ELSE K.MIN_UNIT_ORDER_NUM END) AS SYSTEM_SKU_QTY
         , (CASE WHEN K.SAP_BOX_PRICE=-99999 THEN NULL ELSE K.SAP_BOX_PRICE END) AS PROD_AMT_PKG
         , (CASE WHEN K.SAP_ORDER_NUM=-99999 THEN NULL ELSE K.SAP_ORDER_NUM END) AS PROD_QTY_PKG
         , (CASE WHEN K.MATCH_STATUS=-9 THEN NULL ELSE CONVERT(K.MATCH_STATUS, CHAR) END) AS ORDR_STATUS
         , (CASE WHEN K.IS_INVALID='' THEN NULL ELSE K.IS_INVALID END) AS ORDR_IS_INVALID
         , (CASE WHEN K.ORDER_INVALID_REASON='' THEN NULL ELSE K.ORDER_INVALID_REASON END) AS ORDR_INVALID_RMK
         , (CASE WHEN K.IS_OPEN_ITEM=-9 THEN NULL ELSE (CASE WHEN K.IS_OPEN_ITEM=0 THEN 'N' ELSE 'Y' END) END) AS ORDR_LINE_IS_INVALID
         , (CASE WHEN K.RESIDUAL_BOX_REASON='' THEN NULL ELSE K.RESIDUAL_BOX_REASON END) AS ORDR_LINE_RESIDUAL_TYPE
    FROM RAWWANT.KA_WANTWANT_SYS_ORDER_DATA K
    ;

    SET VAR_SP_RESULT='Y';
    COMMIT;
END
;