DROP PROCEDURE IF EXISTS DWWANT.SP_DC0024_RPT_30301_POS_RPT01;

CREATE PROCEDURE DWWANT.SP_DC0024_RPT_30301_POS_RPT01 (
    VAR_EDI_NO CHAR(12), VAR_DATA_DATE CHAR(8), OUT VAR_SP_RESULT CHAR(1)
)
BEGIN
    DECLARE VAR_AUTO_EDI_NO CHAR(12);
    DECLARE VAR_POS_DATE_MIN CHAR(8);
    DECLARE VAR_POS_DATE_MAX CHAR(8);
    DECLARE VAR_POS_WEEK_NUM_MIN CHAR(6);
    DECLARE VAR_POS_WEEK_NUM_MAX CHAR(6);
    DECLARE VAR_POS_DATE CHAR(8);

    SELECT AUTO_EDI_NO INTO VAR_AUTO_EDI_NO
    FROM DWWANT.EDI_FLOW
    WHERE EDI_NO=VAR_EDI_NO;

    SELECT AUTO_EDI_NO INTO VAR_AUTO_EDI_NO
    FROM DWWANT.EDI_FLOW
    WHERE EDI_NO=VAR_AUTO_EDI_NO;

    SELECT POS_DATE_MIN, POS_DATE_MAX INTO VAR_POS_DATE_MIN, VAR_POS_DATE_MAX
    FROM DWWANT.EDI_FLOW_DWWANT_KA
    WHERE EDI_NO=VAR_AUTO_EDI_NO;

    SET VAR_POS_WEEK_NUM_MIN = DWWANT.FN_GET_WEEK_NUM(VAR_POS_DATE_MIN);
    SET VAR_POS_WEEK_NUM_MAX = DWWANT.FN_GET_WEEK_NUM(VAR_POS_DATE_MAX);
    SET VAR_POS_DATE = DWWANT.FN_GET_DATE(DATE_ADD(CONVERT(VAR_DATA_DATE, DATE), INTERVAL -1 DAY));

    INSERT INTO DMMDL.DC0024_WEEK_NUM
    SELECT DISTINCT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , DWWANT.FN_GET_WEEK_NUM(WORKDAY_YMD) AS WEEK_NUM
         , DWWANT.FN_GET_WEEK_FIRST_DATE(WORKDAY_YMD) AS WEEK_FIRST_DATE
         , DWWANT.FN_GET_WEEK_LAST_DATE(WORKDAY_YMD) AS WEEK_LAST_DATE
    FROM DWWANT.CM_WORKDAY
    WHERE WORKDAY_YMD>=VAR_POS_DATE_MIN AND WORKDAY_YMD<=VAR_POS_DATE_MAX
    ;

    INSERT INTO DMMDL.DC0024_POS_RPT01
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , VAR_POS_DATE AS POS_DATE
    ;

    INSERT INTO DMMDL.DC0024_POS_RPT01_SYSTEM
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , P.KA_SYSTEM_CODE, S.KA_SYSTEM_NM
         , S.KA_SYSTEM_ACT, DWWANT.FN_GET_CM_CODE_NM('0004', S.KA_SYSTEM_ACT) AS KA_SYSTEM_ACT_NM
         , P.POS_WEEK_NUM
         , SUM(P.POS_QTY_PCS) AS POS_QTY_PCS
         , SUM(P.POS_QTY_PKG) AS POS_QTY_PKG
         , SUM(P.POS_AMT) AS POS_AMT
         , COUNT(DISTINCT P.PROD_MATL_ID) AS POS_SKU
    FROM DWWANT.TRAS_KA_POS_MATL_W P
    LEFT JOIN (SELECT KA_SYSTEM_CODE, MAX(KA_SYSTEM_NM) AS KA_SYSTEM_NM, MAX(KA_SYSTEM_ACT) AS KA_SYSTEM_ACT
               FROM DWWANT.CM_KA_SYSTEM
               WHERE KA_SYSTEM_CODE IS NOT NULL
               GROUP BY KA_SYSTEM_CODE) S
    ON P.KA_SYSTEM_CODE=S.KA_SYSTEM_CODE
    WHERE P.POS_WEEK_NUM>=VAR_POS_WEEK_NUM_MIN AND P.POS_WEEK_NUM<=VAR_POS_WEEK_NUM_MAX
    GROUP BY P.KA_SYSTEM_CODE, P.POS_WEEK_NUM
    ;
    
    INSERT INTO DMMDL.DC0024_POS_RPT01_COM
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , P.SALES_COM_ID_SA, DWWANT.FN_GET_ORG_SALES_COM_ABR(P.SALES_COM_ID_SA) AS SALES_COM_ABR_SA
         , P.POS_WEEK_NUM
         , SUM(P.POS_QTY_PCS) AS POS_QTY_PCS
         , SUM(P.POS_QTY_PKG) AS POS_QTY_PKG
         , SUM(P.POS_AMT) AS POS_AMT
         , COUNT(DISTINCT P.PROD_MATL_ID) AS POS_SKU
    FROM DWWANT.TRAS_KA_POS_MATL_W P
    WHERE P.POS_WEEK_NUM>=VAR_POS_WEEK_NUM_MIN AND P.POS_WEEK_NUM<=VAR_POS_WEEK_NUM_MAX
    GROUP BY P.SALES_COM_ID_SA, P.POS_WEEK_NUM
    ;
    
    INSERT INTO DMMDL.DC0024_POS_RPT01_STORE
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , P.KA_SYSTEM_CODE, MAX(S.KA_SYSTEM_NM) AS KA_SYSTEM_NM
         , MAX(S.KA_SYSTEM_ACT) AS KA_SYSTEM_ACT, DWWANT.FN_GET_CM_CODE_NM('0004', MAX(S.KA_SYSTEM_ACT)) AS KA_SYSTEM_ACT_NM
         , P.POS_WEEK_NUM
         , P.KA_STORE_CODE, MAX(P.KA_STORE_NM) AS KA_STORE_NM
         , P.SALES_COM_ID_SA, DWWANT.FN_GET_ORG_SALES_COM_ABR(P.SALES_COM_ID_SA) AS SALES_COM_ABR_SA
         , P.SALES_COM_ID_WH, DWWANT.FN_GET_ORG_SALES_COM_ABR(P.SALES_COM_ID_WH) AS SALES_COM_ABR_WH
         , SUM(P.POS_QTY_PCS) AS POS_QTY_PCS
         , SUM(P.POS_QTY_PKG) AS POS_QTY_PKG
         , SUM(P.POS_AMT) AS POS_AMT
         , COUNT(DISTINCT P.PROD_MATL_ID) AS POS_SKU
    FROM DWWANT.TRAS_KA_POS_MATL_W P
    LEFT JOIN (SELECT KA_SYSTEM_CODE, MAX(KA_SYSTEM_NM) AS KA_SYSTEM_NM, MAX(KA_SYSTEM_ACT) AS KA_SYSTEM_ACT
               FROM DWWANT.CM_KA_SYSTEM
               WHERE KA_SYSTEM_CODE IS NOT NULL
               GROUP BY KA_SYSTEM_CODE) S
    ON P.KA_SYSTEM_CODE=S.KA_SYSTEM_CODE
    WHERE P.POS_WEEK_NUM>=VAR_POS_WEEK_NUM_MIN AND P.POS_WEEK_NUM<=VAR_POS_WEEK_NUM_MAX
    GROUP BY P.KA_SYSTEM_CODE, P.POS_WEEK_NUM
           , P.KA_STORE_CODE, P.SALES_COM_ID_SA, P.SALES_COM_ID_WH
    ;

    INSERT INTO DMMDL.DC0024_POS_RPT01_PRODH1
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , P.KA_SYSTEM_CODE, MAX(S.KA_SYSTEM_NM) AS KA_SYSTEM_NM
         , MAX(S.KA_SYSTEM_ACT) AS KA_SYSTEM_ACT, DWWANT.FN_GET_CM_CODE_NM('0004', MAX(S.KA_SYSTEM_ACT)) AS KA_SYSTEM_ACT_NM
         , P.POS_WEEK_NUM
         , M.PROD_H1_ID, MAX(M.PROD_H1_NM) AS PROD_H1_NM
         , P.SALES_COM_ID_SA, DWWANT.FN_GET_ORG_SALES_COM_ABR(P.SALES_COM_ID_SA) AS SALES_COM_ABR_SA
         , SUM(P.POS_QTY_PCS) AS POS_QTY_PCS
         , SUM(P.POS_QTY_PKG) AS POS_QTY_PKG
         , SUM(P.POS_AMT) AS POS_AMT
         , COUNT(DISTINCT P.PROD_MATL_ID) AS POS_SKU
    FROM DWWANT.TRAS_KA_POS_MATL_W P
    LEFT JOIN (SELECT KA_SYSTEM_CODE, MAX(KA_SYSTEM_NM) AS KA_SYSTEM_NM, MAX(KA_SYSTEM_ACT) AS KA_SYSTEM_ACT
               FROM DWWANT.CM_KA_SYSTEM
               WHERE KA_SYSTEM_CODE IS NOT NULL
               GROUP BY KA_SYSTEM_CODE) S
    ON P.KA_SYSTEM_CODE=S.KA_SYSTEM_CODE
    LEFT JOIN (SELECT M.PROD_MATL_ID, M.PROD_H1_ID, H.PROD_H_NM AS PROD_H1_NM
               FROM DWWANT.PROD_MATL M
               LEFT JOIN DWWANT.PROD_HIER H ON M.PROD_H1_ID=H.PROD_H_ID
               WHERE M.PROD_H1_ID IS NOT NULL) M
    ON P.PROD_MATL_ID=M.PROD_MATL_ID
    WHERE P.POS_WEEK_NUM>=VAR_POS_WEEK_NUM_MIN AND P.POS_WEEK_NUM<=VAR_POS_WEEK_NUM_MAX
    GROUP BY P.KA_SYSTEM_CODE, P.POS_WEEK_NUM
           , M.PROD_H1_ID, P.SALES_COM_ID_SA
    ;
    
    SET VAR_SP_RESULT='Y';
    COMMIT;
END
;