DROP PROCEDURE IF EXISTS DWWANT.SP_MAIN_30105_CUST;

CREATE PROCEDURE DWWANT.SP_MAIN_30105_CUST (
    VAR_EDI_NO CHAR(12), VAR_DATA_DATE CHAR(8), OUT VAR_SP_RESULT CHAR(1)
)
BEGIN

    INSERT INTO DWWANT.CUST_MAIN
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , (CASE WHEN T.CUSTOMER=''    THEN 'NULL' ELSE T.CUSTOMER   END) AS CUST_ID
         , (CASE WHEN T.TXTMD=''       THEN  NULL  ELSE T.TXTMD      END) AS CUST_NM
         , (CASE WHEN C.SHORT_NAME=''  THEN  NULL  ELSE C.SHORT_NAME END) AS CUST_ABBR
    FROM RAWWANT.BW_SAPBHP_BI0_TCUSTOMER T
    LEFT JOIN RAWWANT.IWANT_SALES_CUSTOMER C
    ON T.CUSTOMER=C.ID
    ;

    INSERT INTO DWWANT.CUST_SD
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , (CASE WHEN C.CUSTOMER=''      THEN 'NULL' ELSE C.CUSTOMER      END) AS CUST_ID
         , (CASE WHEN C.ACCNT_GRP=''     THEN  NULL  ELSE C.ACCNT_GRP     END) AS CUST_ACCT_GRP
         , (CASE WHEN C.CUST_CLASS=''    THEN  NULL  ELSE C.CUST_CLASS    END) AS CUST_CLASS
         , (CASE WHEN C.SALES_OFF=''     THEN  NULL  ELSE C.SALES_OFF     END) AS SALES_OFF_ID
         , (CASE WHEN C.BIC_ZWW_COMPY='' THEN  NULL  ELSE C.BIC_ZWW_COMPY END) AS WANT_COM_ID
    FROM RAWWANT.BW_SAPBHP_BI0_PCUSTOMER C
    ;

    INSERT INTO DWWANT.CUST_SD_SALES_COM
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , (CASE WHEN O.DIVISION=''      THEN 'NULL' ELSE O.DIVISION      END) AS PROD_DIV_ID
         , (CASE WHEN O.DISTR_CHAN=''    THEN 'NULL' ELSE O.DISTR_CHAN    END) AS SALES_CHAN_ID
         , (CASE WHEN O.SALESORG=''      THEN 'NULL' ELSE O.SALESORG      END) AS SALES_COM_ID
         , (CASE WHEN O.SALES_OFF=''     THEN  NULL  ELSE O.SALES_OFF     END) AS SALES_OFF_ID
         , (CASE WHEN O.CUST_SALES=''    THEN 'NULL' ELSE O.CUST_SALES    END) AS CUST_ID
         , (CASE WHEN O.BIC_ZWW_COMPY='' THEN  NULL  ELSE O.BIC_ZWW_COMPY END) AS WANT_COM_ID
    FROM RAWWANT.BW_SAPBHP_BI0_PCUST_SALES O
    WHERE O.DIVISION<>'' AND O.DISTR_CHAN<>'' AND O.SALESORG<>'' AND O.CUST_SALES<>''
    ;

    INSERT INTO DWWANT.CUST_SD_SALES_COM_PROD
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , (CASE WHEN P.DIVISION=''      THEN 'NULL' ELSE P.DIVISION      END) AS PROD_DIV_ID
         , (CASE WHEN P.MATERIAL=''      THEN 'NULL' ELSE P.MATERIAL      END) AS PROD_MATL_ID
         , (CASE WHEN P.DISTR_CHAN=''    THEN 'NULL' ELSE P.DISTR_CHAN    END) AS SALES_CHAN_ID
         , (CASE WHEN P.SALESORG=''      THEN 'NULL' ELSE P.SALESORG      END) AS SALES_COM_ID
         , (CASE WHEN P.BIC_ZCUS_WWID='' THEN 'NULL' ELSE P.BIC_ZCUS_WWID END) AS CUST_ID
         , (CASE WHEN P.ITEM_CATEG=''    THEN 'NULL' ELSE P.ITEM_CATEG    END) AS SALES_DOC_ITEM_CATEG
         , (CASE WHEN P.BIC_ZWWCHAN=''   THEN  NULL  ELSE P.BIC_ZWWCHAN   END) AS WANT_CHAN_ID
    FROM RAWWANT.BW_SAPBHP_BIC_PZCUS_WWID P
    WHERE P.DIVISION<>'' AND P.MATERIAL<>'' AND P.DISTR_CHAN<>'' AND P.SALESORG<>'' AND P.BIC_ZCUS_WWID<>'' AND P.ITEM_CATEG<>''
    ;

    INSERT INTO DWWANT.CUST_IWANT
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , (CASE WHEN C.ID=''          THEN 'NULL' ELSE C.ID          END) AS CUST_ID
         , (CASE WHEN C.DESCRIPTION='' THEN  NULL  ELSE C.DESCRIPTION END) AS CUST_DESC
         , (CASE WHEN C.OWNER=''       THEN  NULL  ELSE C.OWNER       END) AS CUST_OWNER_NM
         , (CASE WHEN C.ID_FRIEND=''   THEN  NULL  ELSE C.ID_FRIEND   END) AS CUST_PARENT_ID
         , (CASE WHEN C.BRANCH_ID=''   THEN  NULL  ELSE C.BRANCH_ID   END) AS IWANT_OFF_ID
         , (CASE WHEN C.THIRD_ID=''    THEN  NULL  ELSE C.THIRD_ID    END) AS AREA_COTY_ID
    FROM RAWWANT.IWANT_SALES_CUSTOMER C
    ;

    INSERT INTO DWWANT.CUST_IWANT_MARKET
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , (CASE WHEN S.SID=''             THEN 'NULL' ELSE S.SID             END) AS SEQ_NO
         , (CASE WHEN S.CUSTOMER_ID=''     THEN  NULL  ELSE S.CUSTOMER_ID     END) AS CUST_ID
         , (CASE WHEN S.TYPE=''            THEN  NULL  ELSE S.TYPE            END) AS MARKET_TYPE
         , (CASE WHEN S.MARKET_ID=''       THEN  NULL  ELSE S.MARKET_ID       END) AS IWANT_MARKET_ID
         , (CASE WHEN S.SMALL_MARKET_ID='' THEN  NULL  ELSE S.SMALL_MARKET_ID END) AS IWANT_MARKET_SMALL_ID
         , (CASE WHEN S.CHANNEL_ID=''      THEN  NULL  ELSE S.CHANNEL_ID      END) AS IWANT_CHAN_ID
         , (CASE WHEN S.START_DATE=''      THEN  NULL  ELSE S.START_DATE      END) AS START_YMD
         , (CASE WHEN S.END_DATE=''        THEN  NULL  ELSE S.END_DATE        END) AS END_YMD
    FROM RAWWANT.IWANT_SALES_CUSTOMER_SMALL_MARKET S
    ;

    INSERT INTO DWWANT.CUST_IWANT_MARKET_PROD
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , RIGHT(CONCAT('0000000000', TRIM(SID)),10) AS SEQ_NO
         , (CASE WHEN P.CUSTOMER_SMALL_MARKET_ID='' THEN 'NULL' ELSE P.CUSTOMER_SMALL_MARKET_ID END) AS MARKET_SEQ_NO
         , (CASE WHEN P.PROD_LINE_ID=''             THEN 'NULL' ELSE P.PROD_LINE_ID             END) AS PROD_LINE_ID
    FROM RAWWANT.IWANT_SALES_CUS_SMALL_MARKET_PROD_LINE P
    ;

    INSERT INTO DWWANT.CUST_IWANT_EMP_SALES
    SELECT DISTINCT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , (CASE WHEN S.CUSTOMER_ID=''    THEN 'NULL' ELSE S.CUSTOMER_ID    END) AS CUST_ID
         , (CASE WHEN S.CREDIT_ID=''      THEN 'NULL' ELSE S.CREDIT_ID      END) AS IWANT_CHAN_ID
         , (CASE WHEN S.USER_ID=''        THEN 'NULL' ELSE S.USER_ID        END) AS EMP_ID
         , (CASE WHEN S.POS_TYPE_ID=''    THEN 'NVL'  ELSE S.POS_TYPE_ID    END) AS EMP_POS_TYPE
         , (CASE WHEN S.EMP_COMPANY_ID='' THEN  NULL  ELSE S.EMP_COMPANY_ID END) AS EMP_IWANT_COM_ID
         , (CASE WHEN S.EMP_BRANCH_ID=''  THEN  NULL  ELSE S.EMP_BRANCH_ID  END) AS EMP_IWANT_OFF_ID
         , (CASE WHEN S.START_TIME=''     THEN 'NULL' ELSE S.START_TIME     END) AS START_YMD
         , (CASE WHEN S.END_TIME=''       THEN 'NULL' ELSE S.END_TIME       END) AS END_YMD
         , (CASE WHEN S.STATUS=''         THEN  NULL  ELSE S.STATUS         END) AS STATUS
         , (CASE WHEN MARKET_RELATION_ID=-99999 THEN NULL ELSE RIGHT(CONCAT('0000000000', MARKET_RELATION_ID),10) END) AS EMP_SALES_MARKET_SEQ_NO
    FROM RAWWANT.IWANT_SALES_CUSTOMER_SALES S
    ;

    SET VAR_SP_RESULT='Y';
    COMMIT;
END
;