DROP PROCEDURE IF EXISTS DWWANT.SP_EDI_INSERT_NEW_FLOW;

CREATE PROCEDURE DWWANT.SP_EDI_INSERT_NEW_FLOW (
    VAR_EDI_ID VARCHAR(6), VAR_EDI_FLOW_ID VARCHAR(50)
  , VAR_EDI_DATE CHAR(8), VAR_DATA_DATE CHAR(8)
  , VAR_UPD_USER_ID VARCHAR(50)
  , OUT VAR_SP_RESULT CHAR(1)
)
BEGIN
    SET @VAR_CN = 0;

    SELECT COUNT(1) INTO @VAR_CN
    FROM DWWANT.EDI_FLOW
    WHERE EDI_ID=VAR_EDI_ID AND EDI_FLOW_ID=VAR_EDI_FLOW_ID
        AND DATA_DATE=VAR_DATA_DATE AND IS_AUTOMATIC='Y';

    IF @VAR_CN=0 THEN
        INSERT INTO DWWANT.EDI_FLOW VALUES (
                DWWANT.FN_GET_EDI_NO(VAR_EDI_DATE), VAR_EDI_ID, VAR_EDI_FLOW_ID
            , NULL, NULL
            , VAR_DATA_DATE, 'W', NULL, NULL, NULL
            , 'Y', NOW(), NULL, 'N'
            , VAR_UPD_USER_ID, NOW()
        );
    END IF;

    SET VAR_SP_RESULT='Y';
    COMMIT;
END
;