DROP PROCEDURE IF EXISTS DWWANT.SP_HR_30102_ORG;

CREATE PROCEDURE DWWANT.SP_HR_30102_ORG (
    VAR_EDI_NO CHAR(12), VAR_DATA_DATE CHAR(8), OUT VAR_SP_RESULT CHAR(1)
)
BEGIN

    INSERT INTO DWWANT.ORG_HR_COM
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , (CASE WHEN H.BIC_ZORG_06=''   THEN 'NULL' ELSE H.BIC_ZORG_06   END) AS HR_COM_ID
         , (CASE WHEN H.BIC_ZORG_06_T='' THEN  NULL  ELSE H.BIC_ZORG_06_T END) AS HR_COM_NM
    FROM (SELECT MAX(EDI_NO) AS EDI_NO
               , BIC_ZORG_06, MAX(BIC_ZORG_06_T) AS BIC_ZORG_06_T
          FROM RAWWANT.BW_SAPBHP_BIC_AZHR_O7100
          WHERE BIC_ZORG_06<>''
          GROUP BY BIC_ZORG_06) H
    ORDER BY H.BIC_ZORG_06
    ;

    INSERT INTO DWWANT.ORG_HR_OFF
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , (CASE WHEN H.BIC_ZORG_08=''   THEN 'NULL' ELSE H.BIC_ZORG_08   END) AS HR_OFF_ID
         , (CASE WHEN H.BIC_ZORG_08_T='' THEN  NULL  ELSE H.BIC_ZORG_08_T END) AS HR_OFF_NM
         , (CASE WHEN H.BIC_ZORG_08_T LIKE '%营业所' THEN 'O'
                 WHEN H.BIC_ZORG_08_T LIKE '%课' THEN 'U'
                 WHEN H.BIC_ZORG_08_T LIKE '%室' THEN 'R'
                 ELSE NULL
            END) AS HR_OFF_TYPE
    FROM (SELECT MAX(EDI_NO) AS EDI_NO
               , BIC_ZORG_08, MAX(BIC_ZORG_08_T) AS BIC_ZORG_08_T
          FROM RAWWANT.BW_SAPBHP_BIC_AZHR_O7100
          WHERE BIC_ZORG_08<>''
          GROUP BY BIC_ZORG_08) H
    ORDER BY H.BIC_ZORG_08
    ;

    INSERT INTO DWWANT.ORG_EMP
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , (CASE WHEN E.EMP_ID='' THEN 'NULL' ELSE E.EMP_ID END) AS EMP_ID
         , (CASE WHEN E.EMP_NM='' THEN  NULL  ELSE E.EMP_NM END) AS EMP_NM
         , E.EMP_GENDER
    FROM (SELECT H.EDI_NO
               , H.EMPLOYEE AS EMP_ID, H.EE_SNAME AS EMP_NM
               , (CASE WHEN H.GENDER='1' THEN 'M' WHEN H.GENDER='2' THEN 'F' ELSE NULL END) AS EMP_GENDER
          FROM RAWWANT.BW_SAPBHP_BIC_AZHR_O7100 H
          UNION
          SELECT MAX(E.EDI_NO) AS EDI_NO
               , E.EMP_ID, MAX(E.EMP_NAME) AS EMP_NM
               , NULL AS EMP_GENDER
          FROM RAWWANT.IWANT_SALES_EMP_POSITION_ORG_VIEW E
          LEFT JOIN RAWWANT.BW_SAPBHP_BIC_AZHR_O7100 H
          ON E.EMP_ID=H.EMPLOYEE
          WHERE H.EMPLOYEE IS NULL
          GROUP BY E.EMP_ID) E
     ORDER BY E.EMP_ID
     ;

    INSERT INTO DWWANT.ORG_EMP_SALES_HR
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , (CASE WHEN H.EMPLOYEE=''      THEN 'NULL' ELSE H.EMPLOYEE      END) AS EMP_ID
         , (CASE WHEN H.BIC_ZORG_06=''   THEN  NULL  ELSE H.BIC_ZORG_06   END) AS HR_COM_ID
         , (CASE WHEN H.BIC_ZORG_08=''   THEN  NULL  ELSE H.BIC_ZORG_08   END) AS HR_OFF_ID
         , '1' AS EMP_POS_PRIORITY
         , (CASE WHEN H.HRPOSITION=''    THEN  NULL  ELSE H.HRPOSITION    END) AS EMP_POS_ID
         , (CASE WHEN H.BIC_ZHRIC189=''  THEN  NULL  ELSE H.BIC_ZHRIC189  END) AS EMP_POS_TYPE
         , (CASE WHEN H.BIC_ZPOS_ATTR='' THEN  NULL  ELSE H.BIC_ZPOS_ATTR END) AS EMP_POS_PROP_ID
         , (CASE WHEN H.BIC_ZHRIC207=''  THEN  NULL  ELSE H.BIC_ZHRIC207  END) AS EMP_POS_FLAG
         , (CASE WHEN H.JOB=''           THEN  NULL  ELSE H.JOB           END) AS EMP_POS_TITLE_ID
         , (CASE WHEN H.BIC_ZSGRADE=''   THEN  NULL  ELSE H.BIC_ZSGRADE   END) AS EMP_POS_LEVEL_ID
         , (CASE WHEN H.ENTRYDATE=''     THEN  NULL  ELSE H.ENTRYDATE     END) AS ONBOARD_YMD
         , H.BIC_ZHRIK029 AS SENIORITY
    FROM RAWWANT.BW_SAPBHP_BIC_AZHR_O7100 H
    WHERE H.EMPLOYEE<>'' AND H.BIC_ZORG_06<>'' AND H.BIC_ZORG_08<>'' AND H.BIC_ZPOS_ATTR<>''
    ;

    SET VAR_SP_RESULT='Y';
    COMMIT;
END
;