DROP PROCEDURE IF EXISTS DWWANT.SP_MAIN_30103_PROD;

CREATE PROCEDURE DWWANT.SP_MAIN_30103_PROD (
    VAR_EDI_NO CHAR(12), VAR_DATA_DATE CHAR(8), OUT VAR_SP_RESULT CHAR(1)
)
BEGIN

    INSERT INTO DWWANT.PROD_DIV
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , (CASE WHEN D.DIVISION='' THEN 'NULL' ELSE D.DIVISION END) AS PROD_DIV_ID
         , (CASE WHEN D.TXTSH=''    THEN  NULL  ELSE D.TXTSH    END) AS PROD_DIV_NM
    FROM RAWWANT.BW_SAPBHP_BI0_TDIVISION D
    ;

    INSERT INTO DWWANT.PROD_DIV
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , (CASE WHEN P.DIVISION='' THEN 'NULL' ELSE P.DIVISION END) AS PROD_DIV_ID
         , NULL AS PROD_DIV_NM
    FROM RAWWANT.BW_SAPBHP_BI0_PMATERIAL P
    WHERE P.DIVISION<>'' AND P.DIVISION NOT IN (SELECT DIVISION FROM RAWWANT.BW_SAPBHP_BI0_TDIVISION)
    ;

    INSERT INTO DWWANT.PROD_HIER
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , (CASE WHEN H.PROD_HIER='' THEN 'NULL' ELSE H.PROD_HIER END) AS PROD_H_ID
         , (CASE WHEN H.TXTLG=''     THEN  NULL  ELSE H.TXTLG     END) AS PROD_H_NM
    FROM RAWWANT.BW_SAPBHP_BI0_TPROD_HIER H
    ;

    INSERT INTO DWWANT.PROD_HIER
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , (CASE WHEN P.PRODH1='' THEN 'NULL' ELSE P.PRODH1 END) AS PROD_H_ID
         , NULL AS PROD_H_NM
    FROM RAWWANT.BW_SAPBHP_BI0_PMATERIAL P
    WHERE P.PRODH1<>'' AND P.PRODH1 NOT IN (SELECT PROD_HIER FROM RAWWANT.BW_SAPBHP_BI0_TPROD_HIER)
    ;

    INSERT INTO DWWANT.PROD_HIER
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , (CASE WHEN P.PRODH2='' THEN 'NULL' ELSE P.PRODH2 END) AS PROD_H_ID
         , NULL AS PROD_H_NM
    FROM RAWWANT.BW_SAPBHP_BI0_PMATERIAL P
    WHERE P.PRODH2<>'' AND P.PRODH2 NOT IN (SELECT PROD_HIER FROM RAWWANT.BW_SAPBHP_BI0_TPROD_HIER)
    ;

    INSERT INTO DWWANT.PROD_HIER
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , (CASE WHEN P.PRODH3='' THEN 'NULL' ELSE P.PRODH3 END) AS PROD_H_ID
         , NULL AS PROD_H_NM
    FROM RAWWANT.BW_SAPBHP_BI0_PMATERIAL P
    WHERE P.PRODH3<>'' AND P.PRODH3 NOT IN (SELECT PROD_HIER FROM RAWWANT.BW_SAPBHP_BI0_TPROD_HIER)
    ;

    INSERT INTO DWWANT.PROD_HIER
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , (CASE WHEN P.PRODH4='' THEN 'NULL' ELSE P.PRODH4 END) AS PROD_H_ID
         , NULL AS PROD_H_NM
    FROM RAWWANT.BW_SAPBHP_BI0_PMATERIAL P
    WHERE P.PRODH4<>'' AND P.PRODH4 NOT IN (SELECT PROD_HIER FROM RAWWANT.BW_SAPBHP_BI0_TPROD_HIER)
    ;

    INSERT INTO DWWANT.PROD_HIER
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , (CASE WHEN P.PRODH5='' THEN 'NULL' ELSE P.PRODH5 END) AS PROD_H_ID
         , NULL AS PROD_H_NM
    FROM RAWWANT.BW_SAPBHP_BI0_PMATERIAL P
    WHERE P.PRODH5<>'' AND P.PRODH5 NOT IN (SELECT PROD_HIER FROM RAWWANT.BW_SAPBHP_BI0_TPROD_HIER)
    ;

    INSERT INTO DWWANT.PROD_G1
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , (CASE WHEN G.BIC_ZCOOIC064='' THEN 'NULL' ELSE G.BIC_ZCOOIC064 END) AS PROD_G1_ID
         , (CASE WHEN G.TXTSH=''         THEN  NULL  ELSE G.TXTSH         END) AS PROD_G1_NM
    FROM RAWWANT.BW_SAPBHP_BIC_TZCOOIC064 G
    ;

    INSERT INTO DWWANT.PROD_G1
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , (CASE WHEN P.BIC_ZCOOIC064='' THEN 'NULL' ELSE P.BIC_ZCOOIC064 END) AS PROD_G1_ID
         , NULL AS PROD_G1_NM
    FROM RAWWANT.BW_SAPBHP_BI0_PMATERIAL P
    WHERE P.BIC_ZCOOIC064<>'' AND P.BIC_ZCOOIC064 NOT IN (SELECT BIC_ZCOOIC064 FROM RAWWANT.BW_SAPBHP_BIC_TZCOOIC064)
    ;

    INSERT INTO DWWANT.PROD_G2
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , (CASE WHEN G.BIC_ZSD_PXXL='' THEN 'NULL' ELSE G.BIC_ZSD_PXXL END) AS PROD_G2_ID
         , (CASE WHEN G.TXTSH=''        THEN  NULL  ELSE G.TXTSH        END) AS PROD_G2_NM
    FROM RAWWANT.BW_SAPBHP_BIC_TZSD_PXXL G
    ;

    INSERT INTO DWWANT.PROD_G2
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , (CASE WHEN P.BIC_ZSD_PXXL='' THEN 'NULL' ELSE P.BIC_ZSD_PXXL END) AS PROD_G2_ID
         , NULL AS PROD_G2_NM
    FROM RAWWANT.BW_SAPBHP_BI0_PMATERIAL P
    WHERE P.BIC_ZSD_PXXL<>'' AND P.BIC_ZSD_PXXL NOT IN (SELECT BIC_ZSD_PXXL FROM RAWWANT.BW_SAPBHP_BIC_TZSD_PXXL)
    ;

    INSERT INTO DWWANT.PROD_MATL
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , (CASE WHEN P.MATERIAL=''                 THEN 'NULL' ELSE P.MATERIAL      END) AS PROD_MATL_ID
         , (CASE WHEN T.TXTMD='' OR T.TXTMD IS NULL THEN  NULL  ELSE T.TXTMD         END) AS PROD_MATL_NM
         , (CASE WHEN P.MATL_TYPE=''                THEN  NULL  ELSE P.MATL_TYPE     END) AS PROD_MATL_TYPE
         , (CASE WHEN P.DIVISION=''                 THEN  NULL  ELSE P.DIVISION      END) AS PROD_DIV_ID
         , (CASE WHEN P.PRODH1=''                   THEN  NULL  ELSE P.PRODH1        END) AS PROD_H1_ID
         , (CASE WHEN P.PRODH2=''                   THEN  NULL  ELSE P.PRODH2        END) AS PROD_H2_ID
         , (CASE WHEN P.PRODH3=''                   THEN  NULL  ELSE P.PRODH3        END) AS PROD_H3_ID
         , (CASE WHEN P.PRODH4=''                   THEN  NULL  ELSE P.PRODH4        END) AS PROD_H4_ID
         , (CASE WHEN P.PRODH5=''                   THEN  NULL  ELSE P.PRODH5        END) AS PROD_H5_ID
         , (CASE WHEN P.BIC_ZCOOIC064=''            THEN  NULL  ELSE P.BIC_ZCOOIC064 END) AS PROD_G1_ID
         , (CASE WHEN P.BIC_ZSD_PXXL=''             THEN  NULL  ELSE P.BIC_ZSD_PXXL  END) AS PROD_G2_ID
    FROM RAWWANT.BW_SAPBHP_BI0_PMATERIAL P
    LEFT JOIN RAWWANT.BW_SAPBHP_BI0_TMATERIAL T
    ON P.MATERIAL=T.MATERIAL
    ;

    SET VAR_SP_RESULT='Y';
    COMMIT;
END
;