DROP PROCEDURE IF EXISTS DWWANT.SP_KA_30203_KA_M;

CREATE PROCEDURE DWWANT.SP_KA_30203_KA_M (
    VAR_EDI_NO CHAR(12), VAR_DATA_DATE CHAR(8), OUT VAR_SP_RESULT CHAR(1)
)
BEGIN
    DECLARE VAR_POS_DATE_MIN CHAR(8);
    DECLARE VAR_POS_DATE_MAX CHAR(8);

    SELECT POS_DATE_MIN, POS_DATE_MAX INTO VAR_POS_DATE_MIN, VAR_POS_DATE_MAX
    FROM DWWANT.EDI_FLOW_DWWANT_KA
    WHERE EDI_NO=VAR_EDI_NO;

    INSERT INTO DWWANT.TRAS_KA_POS_MATL_M
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , KA_SYSTEM_CODE
         , KA_STORE_CODE, MAX(KA_STORE_NM) AS KA_STORE_NM
         , MIN(SALES_COM_ID_SA) AS SALES_COM_ID_SA
         , MIN(SALES_COM_ID_WH) AS SALES_COM_ID_WH
         , MIN(SALES_COM_ID_DE) AS SALES_COM_ID_DE
         , PROD_MATL_ID
         , LEFT(POS_DATE, 6) AS POS_YM
         , SUM(CASE WHEN POS_SETTLE_TYPE='D' THEN IFNULL(POS_QTY_PCS, 0) ELSE 0 END) AS POS_QTY_PCS_D
         , SUM(CASE WHEN POS_SETTLE_TYPE='D' THEN IFNULL(POS_QTY_PKG, 0) ELSE 0 END) AS POS_QTY_PKG_D
         , SUM(CASE WHEN POS_SETTLE_TYPE='D' THEN IFNULL(POS_AMT, 0) ELSE 0 END) AS POS_AMT_D
         , SUM(CASE WHEN POS_SETTLE_TYPE='M' THEN IFNULL(POS_QTY_PCS, 0) ELSE 0 END) AS POS_QTY_PCS_M
         , SUM(CASE WHEN POS_SETTLE_TYPE='M' THEN IFNULL(POS_QTY_PKG, 0) ELSE 0 END) AS POS_QTY_PKG_M
         , SUM(CASE WHEN POS_SETTLE_TYPE='M' THEN IFNULL(POS_AMT, 0) ELSE 0 END) AS POS_AMT_M
    FROM DWWANT.TRAS_KA_POS
    WHERE LEFT(POS_DATE, 6)=LEFT(VAR_POS_DATE_MIN, 6)
       AND POS_STATUS='0' AND POS_TYPE='S' AND POS_SETTLE_TYPE IN ('D', 'M')
       AND (IFNULL(POS_QTY_PCS, 0)<>0 OR IFNULL(POS_AMT, 0)<>0)
    GROUP BY KA_SYSTEM_CODE, KA_STORE_CODE, PROD_MATL_ID, LEFT(POS_DATE, 6)
    ;

    INSERT INTO DWWANT.TRAS_KA_POS_STORE_M
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , KA_SYSTEM_CODE
         , KA_STORE_CODE, MAX(KA_STORE_NM) AS KA_STORE_NM
         , MIN(SALES_COM_ID_SA) AS SALES_COM_ID_SA
         , MIN(SALES_COM_ID_WH) AS SALES_COM_ID_WH
         , MIN(SALES_COM_ID_DE) AS SALES_COM_ID_DE
         , LEFT(POS_DATE, 6) AS POS_YM
         , SUM(CASE WHEN POS_SETTLE_TYPE='D' THEN IFNULL(POS_QTY_PCS, 0) ELSE 0 END) AS POS_QTY_PCS_D
         , SUM(CASE WHEN POS_SETTLE_TYPE='D' THEN IFNULL(POS_QTY_PKG, 0) ELSE 0 END) AS POS_QTY_PKG_D
         , SUM(CASE WHEN POS_SETTLE_TYPE='D' THEN IFNULL(POS_AMT, 0) ELSE 0 END) AS POS_AMT_D
         , SUM(CASE WHEN POS_SETTLE_TYPE='M' THEN IFNULL(POS_QTY_PCS, 0) ELSE 0 END) AS POS_QTY_PCS_M
         , SUM(CASE WHEN POS_SETTLE_TYPE='M' THEN IFNULL(POS_QTY_PKG, 0) ELSE 0 END) AS POS_QTY_PKG_M
         , SUM(CASE WHEN POS_SETTLE_TYPE='M' THEN IFNULL(POS_AMT, 0) ELSE 0 END) AS POS_AMT_M
    FROM DWWANT.TRAS_KA_POS
    WHERE LEFT(POS_DATE, 6)=LEFT(VAR_POS_DATE_MIN, 6)
       AND POS_STATUS='0' AND POS_TYPE='D' AND POS_SETTLE_TYPE IN ('D', 'M')
       AND (IFNULL(POS_QTY_PCS, 0)<>0 OR IFNULL(POS_AMT, 0)<>0)
    GROUP BY KA_SYSTEM_CODE, KA_STORE_CODE, LEFT(POS_DATE, 6)
    ;

    SET VAR_SP_RESULT='Y';
    COMMIT;
END
;