DROP PROCEDURE IF EXISTS DWWANT.SP_MAIN_30101_CM;

CREATE PROCEDURE DWWANT.SP_MAIN_30101_CM (
    VAR_EDI_NO CHAR(12), VAR_DATA_DATE CHAR(8), OUT VAR_SP_RESULT CHAR(1)
)
BEGIN

    INSERT INTO DWWANT.CM_WORKDAY
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , (CASE WHEN W.CALMONTH=''      THEN 'NULL' ELSE W.CALMONTH      END) AS WORKDAY_YM
         , (CASE WHEN W.CALDAY=''        THEN 'NULL' ELSE W.CALDAY        END) AS WORKDAY_YMD
         , (CASE WHEN W.BIC_ZWD_FLAG=''  THEN  NULL  ELSE W.BIC_ZWD_FLAG  END) AS WORKDAY_YN
         , W.BIC_ZWD_M2D AS WORKDAYS
         , W.BIC_ZWD_M_SUM AS WORKDAY_TOTAL
    FROM RAWWANT.BW_SAPBHP_BIC_AZSD_O21900 W
    ;

    INSERT INTO DWWANT.CM_SALES_CREDIT
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , (CASE WHEN C.C_CTR_AREA='' THEN 'NULL' ELSE C.C_CTR_AREA END) AS SALES_CREDIT_ID
         , (CASE WHEN C.TXTMD=''      THEN  NULL  ELSE C.TXTMD     END) AS SALES_CREDIT_NM
         , (CASE WHEN C.TXTLG=''      THEN  NULL  ELSE C.TXTLG      END) AS SALES_CREDIT_DESC
    FROM RAWWANT.BW_SAPBHP_BI0_TC_CTR_AREA C
    ;

    INSERT INTO DWWANT.CM_AREA_COTY
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , (CASE WHEN D.ID=''           THEN  'NULL'   ELSE D.ID           END) AS AREA_COTY_ID       
         , (CASE WHEN D.NAME=''         THEN   NULL    ELSE D.NAME         END) AS AREA_COTY_NM
         , (CASE WHEN D.MARKET_ID=''    THEN   NULL    ELSE D.MARKET_ID    END) AS IWANT_MARKET_ID
         , (CASE WHEN D.BRANCH_ID=''    THEN   NULL    ELSE D.BRANCH_ID    END) AS IWANT_BRANCH_ID
    FROM RAWWANT.IWANT_SALES_THIRD_CITY D
    ;

    INSERT INTO DWWANT.CM_AREA_TWSP
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , (CASE WHEN D.SID=''              THEN  'NULL'  ELSE D.SID                        END) AS AREA_TWSP_ID
         , (CASE WHEN D.NAME=''             THEN   NULL   ELSE D.NAME                       END) AS AREA_TWSP_NM
         , (CASE WHEN D.THIRD_ID=''         THEN   NULL   ELSE D.THIRD_ID                   END) AS AREA_COTY_ID
         , (CASE WHEN D.TOTAL_PEOPLE=-99999 THEN   NULL   ELSE FLOOR(D.TOTAL_PEOPLE*10000)  END) AS TOTAL_PEOPLE
         , (CASE WHEN D.STATUS=''           THEN   NULL   ELSE D.STATUS                     END) AS STATUS
    FROM RAWWANT.IWANT_SALES_FORTH_CITY D
    ;

    INSERT INTO DWWANT.CM_AREA_HAME
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , (CASE WHEN D.SID=''          THEN  'NULL'  ELSE D.SID            END) AS AREA_HAME_ID
         , (CASE WHEN D.NAME=''         THEN   NULL   ELSE D.NAME           END) AS AREA_HAME_NM
         , (CASE WHEN D.FIFTH_LV_ID=''  THEN   NULL   ELSE D.FIFTH_LV_ID    END) AS AREA_HAME_LV_ID
         , (CASE WHEN D.FORTH_SID=''    THEN   NULL   ELSE D.FORTH_SID      END) AS AREA_TWSP_ID
         , (CASE WHEN D.STATUS=''       THEN   NULL   ELSE D.STATUS         END) AS STATUS
    FROM RAWWANT.IWANT_SALES_FIFTH_CITY D
    ;

    INSERT INTO DWWANT.CM_KA_SYSTEM
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , (CASE WHEN W.SYS_ID=''   THEN 'NULL' ELSE W.SYS_ID   END) AS KA_SYSTEM_ID
         , (CASE WHEN W.SYS_NAME='' THEN  NULL
                 WHEN W.SYS_ID='IV' THEN 'DTS' 
                 ELSE SUBSTRING(W.SYS_NAME, RAWWANT.FN_GET_ALPHANUMERIC_INDEX(W.SYS_NAME)+1)
            END) AS KA_SYSTEM_NM
         , (CASE WHEN W.SYS_NAME='' THEN  NULL
                 WHEN W.SYS_ID='IV' THEN 'O490' 
                 ELSE SUBSTRING(W.SYS_NAME, 1, RAWWANT.FN_GET_ALPHANUMERIC_INDEX(W.SYS_NAME))
            END) AS KA_SYSTEM_CODE
         , NULL AS KA_SYSTEM_ACT
    FROM RAWWANT.IWANT_SALES_KA_SPECIAL_SYSTEM W
    ;

    UPDATE DWWANT.CM_KA_SYSTEM SET
        KA_SYSTEM_NM=(CASE WHEN TRIM(KA_SYSTEM_NM)='' THEN NULL ELSE TRIM(KA_SYSTEM_NM) END)
      , KA_SYSTEM_CODE=(CASE WHEN TRIM(KA_SYSTEM_CODE)='' THEN NULL ELSE TRIM(KA_SYSTEM_CODE) END)
    ;

    UPDATE DWWANT.CM_KA_SYSTEM SET
        KA_SYSTEM_ACT=(CASE WHEN KA_SYSTEM_CODE='H005' THEN 'W' WHEN KA_SYSTEM_CODE='H001' THEN 'W' WHEN KA_SYSTEM_CODE='H006' THEN 'W' WHEN KA_SYSTEM_CODE='H002' THEN 'W'
                            WHEN KA_SYSTEM_CODE='H013' THEN 'W' WHEN KA_SYSTEM_CODE='H017' THEN 'S' WHEN KA_SYSTEM_CODE='S050' THEN 'S' WHEN KA_SYSTEM_CODE='S052' THEN 'S'
                            WHEN KA_SYSTEM_CODE='H017' THEN 'S' WHEN KA_SYSTEM_CODE='H035' THEN 'S' WHEN KA_SYSTEM_CODE='S063' THEN 'S' WHEN KA_SYSTEM_CODE='H038' THEN 'S'
                            WHEN KA_SYSTEM_CODE='S052' THEN 'S' WHEN KA_SYSTEM_CODE='O466' THEN 'S' WHEN KA_SYSTEM_CODE='S007' THEN 'S' WHEN KA_SYSTEM_CODE='S170' THEN 'S'
                            WHEN KA_SYSTEM_CODE='S321' THEN 'S' WHEN KA_SYSTEM_CODE='S324' THEN 'S' WHEN KA_SYSTEM_CODE='S103' THEN 'S' WHEN KA_SYSTEM_CODE='S101' THEN 'S'
                            WHEN KA_SYSTEM_CODE='S302' THEN 'S' WHEN KA_SYSTEM_CODE='S099' THEN 'S' WHEN KA_SYSTEM_CODE='S097' THEN 'S' WHEN KA_SYSTEM_CODE='S106' THEN 'S'
                            WHEN KA_SYSTEM_CODE='S102' THEN 'S' WHEN KA_SYSTEM_CODE='C001' THEN 'C' WHEN KA_SYSTEM_CODE='C003' THEN 'C' WHEN KA_SYSTEM_CODE='C005' THEN 'C'
                            WHEN KA_SYSTEM_CODE='C007' THEN 'C' WHEN KA_SYSTEM_CODE='C010' THEN 'C' WHEN KA_SYSTEM_CODE='C014' THEN 'C' WHEN KA_SYSTEM_CODE='C016' THEN 'C'
                            WHEN KA_SYSTEM_CODE='C021' THEN 'C' WHEN KA_SYSTEM_CODE='O989' THEN 'Z' WHEN KA_SYSTEM_CODE='H076' THEN 'S' WHEN KA_SYSTEM_CODE='O992' THEN 'S'
                            WHEN KA_SYSTEM_CODE='S010' THEN 'S' WHEN KA_SYSTEM_CODE='S009' THEN 'C' WHEN KA_SYSTEM_CODE='S011' THEN 'S' WHEN KA_SYSTEM_CODE='S018' THEN 'S'
                            WHEN KA_SYSTEM_CODE='H076' THEN 'S' WHEN KA_SYSTEM_CODE='C122' THEN 'S' WHEN KA_SYSTEM_CODE='H010' THEN 'W' WHEN KA_SYSTEM_CODE='H007' THEN 'S'
                            WHEN KA_SYSTEM_CODE='C106' THEN 'C' WHEN KA_SYSTEM_CODE='S001' THEN 'S' WHEN KA_SYSTEM_CODE='H009' THEN 'S' WHEN KA_SYSTEM_CODE='S004' THEN 'S'
                            WHEN KA_SYSTEM_CODE='S042' THEN 'S' WHEN KA_SYSTEM_CODE='H011' THEN 'S' WHEN KA_SYSTEM_CODE='S016' THEN 'S' WHEN KA_SYSTEM_CODE='S025' THEN 'S'
                            WHEN KA_SYSTEM_CODE='S036' THEN 'S' WHEN KA_SYSTEM_CODE='S044' THEN 'S' WHEN KA_SYSTEM_CODE='H035' THEN 'S' WHEN KA_SYSTEM_CODE='S030' THEN 'C'
                            WHEN KA_SYSTEM_CODE='S052' THEN 'S' WHEN KA_SYSTEM_CODE='S289' THEN 'C' WHEN KA_SYSTEM_CODE='H019' THEN 'S' WHEN KA_SYSTEM_CODE='H025' THEN 'S'
                            WHEN KA_SYSTEM_CODE='C010' THEN 'C' WHEN KA_SYSTEM_CODE='C022' THEN 'C' WHEN KA_SYSTEM_CODE='C104' THEN 'C' WHEN KA_SYSTEM_CODE='C035' THEN 'C'
                            WHEN KA_SYSTEM_CODE='H076' THEN 'S' WHEN KA_SYSTEM_CODE='C116' THEN 'C' WHEN KA_SYSTEM_CODE='S013' THEN 'S' WHEN KA_SYSTEM_CODE='C038' THEN 'C'
                            WHEN KA_SYSTEM_CODE='S076' THEN 'S' WHEN KA_SYSTEM_CODE='S075' THEN 'C' WHEN KA_SYSTEM_CODE='S311' THEN 'S' WHEN KA_SYSTEM_CODE='H011' THEN 'S'
                            WHEN KA_SYSTEM_CODE='H029' THEN 'C' WHEN KA_SYSTEM_CODE='S093' THEN 'S' WHEN KA_SYSTEM_CODE='S110' THEN 'S' WHEN KA_SYSTEM_CODE='O992' THEN 'Z'
                            WHEN KA_SYSTEM_CODE='H019' THEN 'S' WHEN KA_SYSTEM_CODE='C095' THEN 'C' WHEN KA_SYSTEM_CODE='S275' THEN 'S' WHEN KA_SYSTEM_CODE='S327' THEN 'S'
                            WHEN KA_SYSTEM_CODE='H042' THEN 'S' WHEN KA_SYSTEM_CODE='H025' THEN 'S' WHEN KA_SYSTEM_CODE='H043' THEN 'S' WHEN KA_SYSTEM_CODE='H017' THEN 'S'
                            WHEN KA_SYSTEM_CODE='S302' THEN 'S' WHEN KA_SYSTEM_CODE='H011' THEN 'S' WHEN KA_SYSTEM_CODE='S013' THEN 'S' WHEN KA_SYSTEM_CODE='H016' THEN 'S'
                            WHEN KA_SYSTEM_CODE='S008' THEN 'S' WHEN KA_SYSTEM_CODE='S017' THEN 'C' WHEN KA_SYSTEM_CODE='H074' THEN 'S' WHEN KA_SYSTEM_CODE='O981' THEN 'S'
                            WHEN KA_SYSTEM_CODE='O982' THEN 'S' WHEN KA_SYSTEM_CODE='S026' THEN 'S' WHEN KA_SYSTEM_CODE='S052' THEN 'S' WHEN KA_SYSTEM_CODE='S284' THEN 'S'
                            WHEN KA_SYSTEM_CODE='H018' THEN 'S' WHEN KA_SYSTEM_CODE='S014' THEN 'S' WHEN KA_SYSTEM_CODE='H004' THEN 'S' WHEN KA_SYSTEM_CODE='S006' THEN 'S'
                            WHEN KA_SYSTEM_CODE='S063' THEN 'S' WHEN KA_SYSTEM_CODE='S015' THEN 'S' WHEN KA_SYSTEM_CODE='S151' THEN 'S' WHEN KA_SYSTEM_CODE='C064' THEN 'C'
                            WHEN KA_SYSTEM_CODE='S031' THEN 'S' WHEN KA_SYSTEM_CODE='C123' THEN 'C' WHEN KA_SYSTEM_CODE='S020' THEN 'S' WHEN KA_SYSTEM_CODE='S027' THEN 'S'
                            WHEN KA_SYSTEM_CODE='S028' THEN 'S' WHEN KA_SYSTEM_CODE='S184' THEN 'S' WHEN KA_SYSTEM_CODE='S192' THEN 'S' WHEN KA_SYSTEM_CODE='H076' THEN 'S'
                            WHEN KA_SYSTEM_CODE='S013' THEN 'S' WHEN KA_SYSTEM_CODE='H060' THEN 'S' WHEN KA_SYSTEM_CODE='S202' THEN 'C' WHEN KA_SYSTEM_CODE='H062' THEN 'S'
                            WHEN KA_SYSTEM_CODE='S031' THEN 'S' WHEN KA_SYSTEM_CODE='S309' THEN 'S' WHEN KA_SYSTEM_CODE='C107' THEN 'C' WHEN KA_SYSTEM_CODE='S313' THEN 'S'
                            WHEN KA_SYSTEM_CODE='C109' THEN 'C' WHEN KA_SYSTEM_CODE='S013' THEN 'S' WHEN KA_SYSTEM_CODE='H021' THEN 'S' WHEN KA_SYSTEM_CODE='C008' THEN 'C'
                            WHEN KA_SYSTEM_CODE='C018' THEN 'C' WHEN KA_SYSTEM_CODE='H037' THEN 'S' WHEN KA_SYSTEM_CODE='H040' THEN 'S' WHEN KA_SYSTEM_CODE='H059' THEN 'S'
                            WHEN KA_SYSTEM_CODE='S219' THEN 'S' WHEN KA_SYSTEM_CODE='C118' THEN 'C' WHEN KA_SYSTEM_CODE='H035' THEN 'S' WHEN KA_SYSTEM_CODE='S249' THEN 'S'
                            WHEN KA_SYSTEM_CODE='S251' THEN 'S' WHEN KA_SYSTEM_CODE='S252' THEN 'S' WHEN KA_SYSTEM_CODE='O973' THEN 'S' WHEN KA_SYSTEM_CODE='S307' THEN 'S'
                            WHEN KA_SYSTEM_CODE='S317' THEN 'S'
                            ELSE NULL
                       END)
    ;

    INSERT INTO DWWANT.CM_EMP_POS_TYPE
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , (CASE WHEN E.POS_TYPE_ID=''   THEN 'NULL' ELSE E.POS_TYPE_ID   END) AS EMP_POS_TYPE
         , (CASE WHEN E.POS_TYPE_NAME='' THEN  NULL  ELSE E.POS_TYPE_NAME END) AS EMP_POS_TYPE_NM
    FROM (SELECT MAX(EDI_NO) AS EDI_NO
               , POS_TYPE_ID, MAX(POS_TYPE_NAME) AS POS_TYPE_NAME
          FROM RAWWANT.IWANT_SALES_EMP_POSITION_ORG_VIEW
          WHERE POS_TYPE_ID<>''
          GROUP BY POS_TYPE_ID
          UNION
          SELECT MAX(EDI_NO) AS EDI_NO
               , DIRECTOR_POS_TYPE_ID AS POS_TYPE_ID, MAX(DIRECTOR_POS_TYPE_NAME) AS POS_TYPE_NAME
          FROM RAWWANT.IWANT_SALES_EMP_POSITION_ORG_VIEW
          WHERE DIRECTOR_POS_TYPE_ID<>''
            AND DIRECTOR_POS_TYPE_ID NOT IN (SELECT POS_TYPE_ID FROM RAWWANT.IWANT_SALES_EMP_POSITION_ORG_VIEW)
          GROUP BY DIRECTOR_POS_TYPE_ID) E
    ORDER BY E.POS_TYPE_ID
    ;

    INSERT INTO DWWANT.CM_EMP_POS_TYPE
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , '000' AS EMP_POS_TYPE, '无' AS EMP_POS_TYPE_NM
    ;

    SET VAR_SP_RESULT='Y';
    COMMIT;
END
;