DROP PROCEDURE IF EXISTS DWWANT.SP_KA_30201_KA_D;

CREATE PROCEDURE DWWANT.SP_KA_30201_KA_D (
    VAR_EDI_NO CHAR(12), VAR_DATA_DATE CHAR(8), OUT VAR_SP_RESULT CHAR(1)
)
BEGIN
    DECLARE VAR_POS_DATE_MIN CHAR(8);
    DECLARE VAR_POS_DATE_MAX CHAR(8);
    DECLARE VAR_INV_DATE_MIN CHAR(8);
    DECLARE VAR_INV_DATE_MAX CHAR(8);

    SELECT POS_DATE_MIN, POS_DATE_MAX, INV_DATE_MIN, INV_DATE_MAX 
      INTO VAR_POS_DATE_MIN, VAR_POS_DATE_MAX, VAR_INV_DATE_MIN, VAR_INV_DATE_MAX
    FROM DWWANT.EDI_FLOW_DWWANT_KA
    WHERE EDI_NO=VAR_EDI_NO;

    INSERT INTO DWWANT.TRAS_KA_POS_MATL_D
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , KA_SYSTEM_CODE
         , KA_STORE_CODE, MAX(KA_STORE_NM) AS KA_STORE_NM
         , MIN(SALES_COM_ID_SA) AS SALES_COM_ID_SA
         , MIN(SALES_COM_ID_WH) AS SALES_COM_ID_WH
         , MIN(SALES_COM_ID_DE) AS SALES_COM_ID_DE
         , PROD_MATL_ID
         , POS_DATE
         , SUM(IFNULL(POS_QTY_PCS,0)) AS POS_QTY_PCS
         , SUM(IFNULL(POS_QTY_PKG,0)) AS POS_QTY_PKG
         , SUM(IFNULL(POS_AMT,0)) AS POS_AMT
    FROM DWWANT.TRAS_KA_POS
    WHERE POS_DATE>=VAR_POS_DATE_MIN AND POS_DATE<=VAR_POS_DATE_MAX
      AND POS_STATUS='0' AND POS_TYPE='S' AND POS_SETTLE_TYPE='D'
      AND (IFNULL(POS_QTY_PCS,0)<>0 OR IFNULL(POS_AMT,0)<>0)
    GROUP BY KA_SYSTEM_CODE, KA_STORE_CODE, PROD_MATL_ID, POS_DATE
    ;

    INSERT INTO DWWANT.TRAS_KA_INV_STORE_D
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , KA_SYSTEM_CODE
         , KA_STORE_CODE, MAX(KA_STORE_NM) AS KA_STORE_NM
         , MIN(SALES_COM_ID_SA) AS SALES_COM_ID_SA
         , MIN(SALES_COM_ID_WH) AS SALES_COM_ID_WH
         , MIN(SALES_COM_ID_DE) AS SALES_COM_ID_DE
         , PROD_MATL_ID
         , INV_DATE
         , SUM(IFNULL(INV_QTY_PCS,0)) AS INV_QTY_PCS
         , SUM(IFNULL(INV_QTY_PKG,0)) AS INV_QTY_PKG
    FROM DWWANT.TRAS_KA_INV
    WHERE INV_DATE>=VAR_INV_DATE_MIN AND INV_DATE<=VAR_INV_DATE_MAX
      AND INV_STATUS='0' AND INV_TYPE='D'
      AND IFNULL(INV_QTY_PCS,0)<>0
    GROUP BY KA_SYSTEM_CODE, KA_STORE_CODE, PROD_MATL_ID, INV_DATE
    ;

    INSERT INTO DWWANT.TRAS_KA_INV_WH_D
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , KA_SYSTEM_CODE
         , KA_STORE_CODE AS KA_WH_CODE, MAX(KA_STORE_NM) AS KA_WH_NM
         , MIN(SALES_COM_ID_WH) AS SALES_COM_ID_WH
         , MIN(SALES_COM_ID_DE) AS SALES_COM_ID_DE
         , PROD_MATL_ID
         , INV_DATE
         , SUM(IFNULL(INV_QTY_PCS,0)) AS INV_QTY_PCS
         , SUM(IFNULL(INV_QTY_PKG,0)) AS INV_QTY_PKG
    FROM DWWANT.TRAS_KA_INV
    WHERE INV_DATE>=VAR_INV_DATE_MIN AND INV_DATE<=VAR_INV_DATE_MAX
      AND INV_STATUS='0' AND INV_TYPE='W'
      AND IFNULL(INV_QTY_PCS,0)<>0
    GROUP BY KA_SYSTEM_CODE, KA_STORE_CODE, PROD_MATL_ID, INV_DATE
    ;

    SET VAR_SP_RESULT='Y';
    COMMIT;
END
;