DROP PROCEDURE IF EXISTS DWWANT.SP_KA_ORDER_30105_TRAS_KA_ORDR_SHIP;

CREATE PROCEDURE DWWANT.SP_KA_ORDER_30105_TRAS_KA_ORDR_SHIP (
    VAR_EDI_NO CHAR(12), VAR_DATA_DATE CHAR(8), OUT VAR_SP_RESULT CHAR(1)
)
BEGIN
    DECLARE VAR_DATE_MIN CHAR(8);

    SET VAR_DATE_MIN = CONCAT(DATE_FORMAT(DATE_ADD(STR_TO_DATE(VAR_DATA_DATE, '%Y%m%d'), INTERVAL -3 MONTH), '%Y%m'), '01');

    INSERT INTO DWWANT.TRAS_KA_ORDR_SHIP_D
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , K.ID AS SHIP_SEQ
         , (CASE WHEN K.SAP_ORDER_NO='' THEN NULL ELSE K.SAP_ORDER_NO END) AS SAP_ORDR_NO
         , (CASE WHEN K.SAP_POSNR=-99999 THEN NULL ELSE K.SAP_POSNR END) AS SAP_LINE_NUM
         , (CASE WHEN K.ACTUAL_DELIVER_BOX_NUM=-99999 THEN NULL ELSE K.ACTUAL_DELIVER_BOX_NUM END) AS SHIP_QTY_PKG_DEV
         , (CASE WHEN K.DIFFERENCE_BOX_NUM=-99999 THEN NULL ELSE K.DIFFERENCE_BOX_NUM END) AS SHIP_QTY_PKG_DIF
         , (CASE WHEN K.CUSTOMER_RECEIVED_BOX_NUM=-99999 THEN NULL ELSE K.CUSTOMER_RECEIVED_BOX_NUM END) AS SHIP_QTY_PKG_ACT
         , (CASE WHEN K.SAP_HARVEST_DATE='' THEN NULL ELSE K.SAP_HARVEST_DATE END) AS SHIP_ACT_DATE
         , (CASE WHEN K.SAP_RETURN_RECEIPT_DATE='' THEN NULL ELSE K.SAP_RETURN_RECEIPT_DATE END) AS SHIP_REC_DATE
         , (CASE WHEN K.SAP_SHIPMENT_NUM='' THEN NULL ELSE K.SAP_SHIPMENT_NUM END) AS SHIP_USER
         , (CASE WHEN K.RETURN_TIME='' THEN NULL ELSE K.RETURN_TIME END) AS RETURN_TIME
         , (CASE WHEN K.TEXT_DESC='' THEN NULL ELSE K.TEXT_DESC END) AS RETURN_LINE_RMK
    FROM RAWWANT.KA_WANTWANT_KA_SAP_SHIPPING_RETURN K
    ;

    INSERT INTO DWWANT.TRAS_KA_ORDR_SHIP
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , X.SAP_ORDR_NO, X.SAP_LINE_NUM
         , X.SHIP_QTY_PKG_DEV_SUM, X.SHIP_QTY_PKG_DIF_SUM, X.SHIP_QTY_PKG_ACT_SUM
         , D.SHIP_ACT_DATE, D.SHIP_REC_DATE
         , D.SHIP_USER, D.RETURN_LINE_TIME, D.RETURN_LINE_RMK
    FROM (SELECT SAP_ORDR_NO, SAP_LINE_NUM
               , SUM(SHIP_QTY_PKG_DEV) AS SHIP_QTY_PKG_DEV_SUM
               , SUM(SHIP_QTY_PKG_DIF) AS SHIP_QTY_PKG_DIF_SUM
               , SUM(SHIP_QTY_PKG_ACT) AS SHIP_QTY_PKG_ACT_SUM
               , MAX(SHIP_D_SEQ) AS SHIP_D_SEQ_MAX
          FROM DWWANT.TRAS_KA_ORDR_SHIP_D
          GROUP BY SAP_ORDR_NO, SAP_LINE_NUM) X
    JOIN DWWANT.TRAS_KA_ORDR_SHIP_D D
    ON X.SAP_ORDR_NO=D.SAP_ORDR_NO AND X.SAP_LINE_NUM=D.SAP_LINE_NUM AND X.SHIP_D_SEQ_MAX=D.SHIP_D_SEQ
    WHERE D.SHIP_REC_DATE>=VAR_DATE_MIN AND D.SHIP_REC_DATE<=VAR_DATA_DATE
    ;

    SET VAR_SP_RESULT='Y';
    COMMIT;
END
;
