DROP PROCEDURE IF EXISTS DWWANT.SP_DC0024_00001_DELETE_DATA;

CREATE PROCEDURE DWWANT.SP_DC0024_00001_DELETE_DATA (
    VAR_EDI_NO CHAR(12), VAR_DATA_DATE CHAR(8), OUT VAR_SP_RESULT CHAR(1)
)
BEGIN
    DECLARE VAR_AUTO_EDI_NO CHAR(12);
    DECLARE VAR_POS_DATE_MIN CHAR(8);
    DECLARE VAR_POS_DATE_MAX CHAR(8);
    DECLARE VAR_POS_WEEK_NUM_MIN CHAR(6);
    DECLARE VAR_POS_WEEK_NUM_MAX CHAR(6);

    SELECT AUTO_EDI_NO INTO VAR_AUTO_EDI_NO
    FROM DWWANT.EDI_FLOW
    WHERE EDI_NO=VAR_EDI_NO;

    SELECT POS_DATE_MIN, POS_DATE_MAX INTO VAR_POS_DATE_MIN, VAR_POS_DATE_MAX
    FROM DWWANT.EDI_FLOW_DWWANT_KA
    WHERE EDI_NO=VAR_AUTO_EDI_NO;

    SET VAR_POS_WEEK_NUM_MIN = DWWANT.FN_GET_WEEK_NUM(VAR_POS_DATE_MIN);
    SET VAR_POS_WEEK_NUM_MAX = DWWANT.FN_GET_WEEK_NUM(VAR_POS_DATE_MAX);

    DELETE FROM DMMDL.DC0024_WEEK_NUM WHERE WEEK_NUM>=VAR_POS_WEEK_NUM_MIN AND WEEK_NUM<=VAR_POS_WEEK_NUM_MAX;
    DELETE FROM DMMDL.DC0024_POS_RPT01 WHERE DATA_DATE=VAR_DATA_DATE;
    DELETE FROM DMMDL.DC0024_POS_RPT01_SYSTEM WHERE POS_WEEK_NUM>=VAR_POS_WEEK_NUM_MIN AND POS_WEEK_NUM<=VAR_POS_WEEK_NUM_MAX;
    DELETE FROM DMMDL.DC0024_POS_RPT01_COM WHERE POS_WEEK_NUM>=VAR_POS_WEEK_NUM_MIN AND POS_WEEK_NUM<=VAR_POS_WEEK_NUM_MAX;
    DELETE FROM DMMDL.DC0024_POS_RPT01_STORE WHERE POS_WEEK_NUM>=VAR_POS_WEEK_NUM_MIN AND POS_WEEK_NUM<=VAR_POS_WEEK_NUM_MAX;
    DELETE FROM DMMDL.DC0024_POS_RPT01_PRODH1 WHERE POS_WEEK_NUM>=VAR_POS_WEEK_NUM_MIN AND POS_WEEK_NUM<=VAR_POS_WEEK_NUM_MAX;

    DELETE FROM DMMDL.DC0024_INVALID_RPT01 WHERE EDI_NO=VAR_EDI_NO;
    TRUNCATE TABLE DMMDL.DC0024_INVALID_RPT01_PROD_POS;
    TRUNCATE TABLE DMMDL.DC0024_INVALID_RPT01_PROD_INV;
    TRUNCATE TABLE DMMDL.DC0024_INVALID_RPT01_STORE_POS;
    TRUNCATE TABLE DMMDL.DC0024_INVALID_RPT01_STORE_INV;
    TRUNCATE TABLE DMMDL.DC0024_INVALID_RPT01_STORE_COM_POS;
    TRUNCATE TABLE DMMDL.DC0024_INVALID_RPT01_STORE_COM_INV;

    TRUNCATE TABLE DMMDL.DC0024_STORE_MATL_D;

    TRUNCATE TABLE DMMDL.DC0024_STORE_MATL_M;
    TRUNCATE TABLE DMMDL.DC0024_STORE_M;

    SET VAR_SP_RESULT='Y';
    COMMIT;
END
;