DROP PROCEDURE IF EXISTS DWWANT.SP_MAIN_30108_TRAS;

CREATE PROCEDURE DWWANT.SP_MAIN_30108_TRAS (
    VAR_EDI_NO CHAR(12), VAR_DATA_DATE CHAR(8), OUT VAR_SP_RESULT CHAR(1)
)
BEGIN
    DECLARE VAR_YM_BEGIN CHAR(6);
    DECLARE VAR_YMD_BEGIN CHAR(8);

    SET VAR_YM_BEGIN = SUBSTR(DWWANT.FN_GET_DATE(DATE_ADD(VAR_DATA_DATE, INTERVAL -2 YEAR)), 1, 6);
    SET VAR_YMD_BEGIN = DWWANT.FN_GET_DATE(DATE_ADD(VAR_DATA_DATE, INTERVAL -31 DAY));

    INSERT INTO DWWANT.TRAS_CUST_POSTED
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , (CASE WHEN T.ITEM_CATEG=''    THEN  NULL  ELSE T.ITEM_CATEG    END) AS SALES_DOC_ITEM_CATEG
         , (CASE WHEN T.CALMONTH=''      THEN  NULL  ELSE T.CALMONTH      END) AS POSTED_YM
         , (CASE WHEN T.CALDAY=''        THEN  NULL  ELSE T.CALDAY        END) AS POSTED_YMD
         , (CASE WHEN T.FISCYEAR=''      THEN 'NULL' ELSE T.FISCYEAR      END) AS FISC_YEAR
         , (CASE WHEN T.FISCVARNT=''     THEN 'NULL' ELSE T.FISCVARNT     END) AS FISC_VARNT
         , (CASE WHEN T.BILL_NUM=''      THEN 'NULL' ELSE T.BILL_NUM      END) AS BILL_NUM
         , (CASE WHEN T.BILL_ITEM=''     THEN 'NULL' ELSE T.BILL_ITEM     END) AS BILL_ITEM
         , (CASE WHEN T.DIVISION=''      THEN  NULL  ELSE T.DIVISION      END) AS PROD_DIV_ID
         , (CASE WHEN T.MATERIAL=''      THEN  NULL  ELSE T.MATERIAL      END) AS PROD_MATL_ID
         , (CASE WHEN T.DISTR_CHAN=''    THEN  NULL  ELSE T.DISTR_CHAN    END) AS SALES_CHAN_ID
         , (CASE WHEN T.SALESORG=''      THEN  NULL  ELSE T.SALESORG      END) AS SALES_COM_ID
         , (CASE WHEN T.COMP_CODE=''     THEN  NULL  ELSE T.COMP_CODE     END) AS SALES_COM_CODE
         , (CASE WHEN T.BIC_ZCUS_WWID='' THEN  NULL  ELSE T.BIC_ZCUS_WWID END) AS CUST_ID
         , T.SUBTOTAL_1 AS POSTED_AMT
    FROM RAWWANT.BW_SAPBHP_BIC_AZSD_O2100 T
    ;

    INSERT INTO DWWANT.TRAS_CUST_POSTING
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , (CASE WHEN T.DOC_NUMBER=''    THEN 'NULL' ELSE T.DOC_NUMBER    END) AS SALES_DOC_NUM
         , (CASE WHEN T.S_ORD_ITEM=''    THEN 'NULL' ELSE T.S_ORD_ITEM    END) AS SALES_DOC_ITEM
         , (CASE WHEN T.ITEM_CATEG=''    THEN  NULL  ELSE T.ITEM_CATEG    END) AS SALES_DOC_ITEM_CATEG
         , (CASE WHEN T.DOC_DATE=''      THEN  NULL  ELSE T.DOC_DATE      END) AS SALES_DOC_YMD
         , (CASE WHEN T.DELIV_NUMB=''    THEN 'NULL' ELSE T.DELIV_NUMB    END) AS DELIV_NUM
         , (CASE WHEN T.BIC_ZDN_ITEM=''  THEN 'NULL' ELSE T.BIC_ZDN_ITEM  END) AS DELIV_ITEM
         , (CASE WHEN T.DIVISION=''      THEN  NULL  ELSE T.DIVISION      END) AS PROD_DIV_ID
         , (CASE WHEN T.MATERIAL=''      THEN  NULL  ELSE T.MATERIAL      END) AS PROD_MATL_ID
         , (CASE WHEN T.DISTR_CHAN=''    THEN  NULL  ELSE T.DISTR_CHAN    END) AS SALES_CHAN_ID
         , (CASE WHEN T.SALESORG=''      THEN  NULL  ELSE T.SALESORG      END) AS SALES_COM_ID
         , (CASE WHEN T.COMP_CODE=''     THEN  NULL  ELSE T.COMP_CODE     END) AS SALES_COM_CODE
         , (CASE WHEN T.BIC_ZCUS_WWID='' THEN  NULL  ELSE T.BIC_ZCUS_WWID END) AS CUST_ID
         , T.BIC_ZWGZ_KDM AS POSTING_BILL_AMT
         , T.BIC_ZWGZ_QRM AS POSTING_CONF_AMT
    FROM RAWWANT.BW_SAPBHP_BIC_AZWGZ_O0100 T
    ;

    INSERT INTO DWWANT.TRAS_CUST_POSTED_SALES_D
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , A.POSTED_YMD
         , IFNULL(W.WANT_CHAN_ID, 'NULL') AS WANT_CHAN_ID, IFNULL(S.WANT_COM_ID, 'NULL') AS WANT_COM_ID
         , IFNULL(A.PROD_MATL_ID, 'NULL') AS PROD_MATL_ID, A.CUST_ID
         , SUM(A.POSTED_AMT) AS POSTED_AMT
    FROM DWWANT.TRAS_CUST_POSTED A
    JOIN DWWANT.CUST_SD D ON A.CUST_ID=D.CUST_ID
    JOIN DWWANT.CUST_SD_SALES_COM S ON A.PROD_DIV_ID=S.PROD_DIV_ID AND A.SALES_CHAN_ID=S.SALES_CHAN_ID AND A.SALES_COM_ID=S.SALES_COM_ID AND A.CUST_ID=S.CUST_ID
    JOIN DWWANT.PROD_MATL M ON A.PROD_MATL_ID=M.PROD_MATL_ID
    JOIN DWWANT.CUST_SD_SALES_COM_PROD W ON A.SALES_CHAN_ID=W.SALES_CHAN_ID AND A.PROD_MATL_ID=W.PROD_MATL_ID AND A.PROD_DIV_ID=W.PROD_DIV_ID AND
                                            A.SALES_COM_ID=W.SALES_COM_ID AND A.SALES_DOC_ITEM_CATEG=W.SALES_DOC_ITEM_CATEG AND A.CUST_ID=W.CUST_ID
    WHERE A.POSTED_YM>=VAR_YMD_BEGIN AND A.POSTED_YMD<=VAR_DATA_DATE
      AND (A.SALES_CHAN_ID<>'C6' OR A.SALES_CHAN_ID IS NULL)
      AND (D.CUST_CLASS<>'OB' OR D.CUST_CLASS IS NULL) AND D.CUST_ACCT_GRP IN ('Z002','Z003')
      AND S.WANT_COM_ID IS NOT NULL
      AND (M.PROD_H1_ID<>'999' OR M.PROD_H1_ID IS NULL) AND M.PROD_MATL_TYPE='FERT'
    GROUP BY A.POSTED_YMD
           , IFNULL(W.WANT_CHAN_ID, 'NULL'), IFNULL(S.WANT_COM_ID, 'NULL')
           , IFNULL(A.PROD_MATL_ID, 'NULL'), A.CUST_ID
    ;

    INSERT INTO DWWANT.TRAS_CUST_POSTED_SALES
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , A.POSTED_YM
         , IFNULL(W.WANT_CHAN_ID, 'NULL') AS WANT_CHAN_ID, IFNULL(S.WANT_COM_ID, 'NULL') AS WANT_COM_ID
         , IFNULL(A.PROD_MATL_ID, 'NULL') AS PROD_MATL_ID, A.CUST_ID
         , SUM(A.POSTED_AMT) AS POSTED_AMT
    FROM DWWANT.TRAS_CUST_POSTED A
    JOIN DWWANT.CUST_SD D ON A.CUST_ID=D.CUST_ID
    JOIN DWWANT.CUST_SD_SALES_COM S ON A.PROD_DIV_ID=S.PROD_DIV_ID AND A.SALES_CHAN_ID=S.SALES_CHAN_ID AND A.SALES_COM_ID=S.SALES_COM_ID AND A.CUST_ID=S.CUST_ID
    JOIN DWWANT.PROD_MATL M ON A.PROD_MATL_ID=M.PROD_MATL_ID
    JOIN DWWANT.CUST_SD_SALES_COM_PROD W ON A.SALES_CHAN_ID=W.SALES_CHAN_ID AND A.PROD_MATL_ID=W.PROD_MATL_ID AND A.PROD_DIV_ID=W.PROD_DIV_ID AND
                                            A.SALES_COM_ID=W.SALES_COM_ID AND A.SALES_DOC_ITEM_CATEG=W.SALES_DOC_ITEM_CATEG AND A.CUST_ID=W.CUST_ID
    WHERE A.POSTED_YM>=VAR_YM_BEGIN AND A.POSTED_YMD<=VAR_DATA_DATE
      AND (A.SALES_CHAN_ID<>'C6' OR A.SALES_CHAN_ID IS NULL)
      AND (D.CUST_CLASS<>'OB' OR D.CUST_CLASS IS NULL) AND D.CUST_ACCT_GRP IN ('Z002','Z003')
      AND S.WANT_COM_ID IS NOT NULL
      AND (M.PROD_H1_ID<>'999' OR M.PROD_H1_ID IS NULL) AND M.PROD_MATL_TYPE='FERT'
    GROUP BY A.POSTED_YM
           , IFNULL(W.WANT_CHAN_ID, 'NULL'), IFNULL(S.WANT_COM_ID, 'NULL')
           , IFNULL(A.PROD_MATL_ID, 'NULL'), A.CUST_ID
    ;

    INSERT INTO DWWANT.TRAS_CUST_POSTING_SALES
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , IFNULL(W.WANT_CHAN_ID, 'NULL') AS WANT_CHAN_ID, IFNULL(S.WANT_COM_ID, 'NULL') AS WANT_COM_ID
         , A.PROD_MATL_ID, A.CUST_ID
         , SUM((CASE WHEN A.SALES_DOC_ITEM_CATEG IN ('ZTAD','ZDZY') THEN A.POSTING_BILL_AMT ELSE A.POSTING_CONF_AMT END)*
               (CASE WHEN A.SALES_DOC_ITEM_CATEG IN ('ZCR','ZCT','ZFDR','ZFRT','ZREF','ZREG','ZREI','ZREJ','ZREK','ZREM','ZRZY','ZG2N','ZKRN','ZSZY') THEN -1 ELSE 1 END)) AS POSTING_AMT
    FROM DWWANT.TRAS_CUST_POSTING A
    JOIN DWWANT.CUST_SD D ON A.CUST_ID=D.CUST_ID
    JOIN DWWANT.CUST_SD_SALES_COM S ON A.PROD_DIV_ID=S.PROD_DIV_ID AND A.SALES_CHAN_ID=S.SALES_CHAN_ID AND A.SALES_COM_ID=S.SALES_COM_ID AND A.CUST_ID=S.CUST_ID
    JOIN DWWANT.PROD_MATL M ON A.PROD_MATL_ID=M.PROD_MATL_ID
    JOIN DWWANT.CUST_SD_SALES_COM_PROD W ON A.SALES_CHAN_ID=W.SALES_CHAN_ID AND A.PROD_MATL_ID=W.PROD_MATL_ID AND A.PROD_DIV_ID=W.PROD_DIV_ID AND
                                            A.SALES_COM_ID=W.SALES_COM_ID AND A.SALES_DOC_ITEM_CATEG=W.SALES_DOC_ITEM_CATEG AND A.CUST_ID=W.CUST_ID
    WHERE A.SALES_DOC_YMD>'20090000' AND A.SALES_DOC_YMD<=VAR_DATA_DATE
      AND (A.SALES_CHAN_ID<>'C6' OR A.SALES_CHAN_ID IS NULL)
      AND (D.CUST_CLASS<>'OB' OR D.CUST_CLASS IS NULL) AND D.CUST_ACCT_GRP IN ('Z002','Z003')
      AND S.WANT_COM_ID IS NOT NULL
      AND (M.PROD_H1_ID<>'999' OR M.PROD_H1_ID IS NULL) AND M.PROD_MATL_TYPE='FERT'
    GROUP BY IFNULL(W.WANT_CHAN_ID, 'NULL'), IFNULL(S.WANT_COM_ID, 'NULL')
           , A.PROD_MATL_ID, A.CUST_ID
    ;

    INSERT INTO DWWANT.TRAS_CUST_SALES
    SELECT DISTINCT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , POSTED_YM, WANT_CHAN_ID, WANT_COM_ID, PROD_MATL_ID, CUST_ID
         , POSTED_AMT, POSTING_AMT
    FROM (SELECT POSTED_YM, WANT_CHAN_ID, WANT_COM_ID, PROD_MATL_ID, CUST_ID
               , 0 AS POSTED_AMT, 0 AS POSTING_AMT
          FROM DWWANT.TRAS_CUST_POSTED_SALES
          WHERE POSTED_YM>=VAR_YM_BEGIN
          UNION ALL
          SELECT SUBSTR(VAR_DATA_DATE, 1, 6) AS POSTED_YM, WANT_CHAN_ID, WANT_COM_ID, PROD_MATL_ID, CUST_ID
               , 0 AS POSTED_AMT, 0 AS POSTING_AMT
          FROM DWWANT.TRAS_CUST_POSTING_SALES) S
    ;

    UPDATE DWWANT.TRAS_CUST_SALES S
    JOIN DWWANT.TRAS_CUST_POSTED_SALES P
    ON S.POSTED_YM=P.POSTED_YM AND 
       S.WANT_CHAN_ID=P.WANT_CHAN_ID AND S.WANT_COM_ID=P.WANT_COM_ID AND 
       S.PROD_MATL_ID=P.PROD_MATL_ID AND S.CUST_ID=P.CUST_ID
    SET S.POSTED_AMT=P.POSTED_AMT
    WHERE S.POSTED_YM>=VAR_YM_BEGIN
    ;

    UPDATE DWWANT.TRAS_CUST_SALES S
    JOIN DWWANT.TRAS_CUST_POSTING_SALES P
    ON S.WANT_CHAN_ID=P.WANT_CHAN_ID AND S.WANT_COM_ID=P.WANT_COM_ID AND 
       S.PROD_MATL_ID=P.PROD_MATL_ID AND S.CUST_ID=P.CUST_ID
    SET S.POSTING_AMT=P.POSTING_AMT
    WHERE S.POSTED_YM=SUBSTR(VAR_DATA_DATE, 1, 6)
    ;

    SET VAR_SP_RESULT='Y';
    COMMIT;
END
;