DROP PROCEDURE IF EXISTS DWWANT.SP_DC0021_30201_SALES_RPT01;

CREATE PROCEDURE DWWANT.SP_DC0021_30201_SALES_RPT01 (
    VAR_EDI_NO CHAR(12), VAR_DATA_DATE CHAR(8), OUT VAR_SP_RESULT CHAR(1)
)
BEGIN
    DECLARE VAR_RPT_YM CHAR(6);
    DECLARE VAR_DATA_DATE_D1 CHAR(8);
    DECLARE VAR_DATA_DATE_D2 CHAR(8);
    DECLARE VAR_DATA_DATE_D3 CHAR(8);
    DECLARE VAR_WORKDAYS INT;
    DECLARE VAR_WORKDAY_TOTAL INT;
    DECLARE VAR_WORKDAY_PC DECIMAL(21,8);
    DECLARE VAR_REQ_DATE CHAR(8);

    SET VAR_RPT_YM = SUBSTR(VAR_DATA_DATE, 1, 6);

    SET VAR_DATA_DATE_D1 = DWWANT.FN_GET_DATE(DATE_ADD(CONVERT(VAR_DATA_DATE, DATE), INTERVAL -1 DAY));
    SET VAR_DATA_DATE_D2 = DWWANT.FN_GET_DATE(DATE_ADD(CONVERT(VAR_DATA_DATE, DATE), INTERVAL -2 DAY));
    SET VAR_DATA_DATE_D3 = DWWANT.FN_GET_DATE(DATE_ADD(CONVERT(VAR_DATA_DATE, DATE), INTERVAL -3 DAY));

    SET VAR_WORKDAYS = 0;
    SET VAR_WORKDAY_TOTAL = 1;

    SELECT WORKDAYS, WORKDAY_TOTAL INTO VAR_WORKDAYS, VAR_WORKDAY_TOTAL
    FROM DWWANT.CM_WORKDAY
    WHERE WORKDAY_YMD=VAR_DATA_DATE
    ;

    SET VAR_WORKDAY_PC = VAR_WORKDAYS/VAR_WORKDAY_TOTAL;

    SET VAR_REQ_DATE = (CASE WHEN VAR_RPT_YM='201908' THEN '20190718'
                             WHEN VAR_RPT_YM='201909' THEN '20190818'
                             ELSE CONCAT(SUBSTR(DWWANT.FN_GET_DATE(DATE_ADD(CONVERT(VAR_DATA_DATE, DATE), INTERVAL -1 MONTH)), 1, 6), '17')
                        END);

    INSERT INTO DMMDL.DC0021_SALES_RPT01
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , Z.BU01_ID, Z.BU01_NM
         , (CASE WHEN VAR_DATA_DATE>='20190810' THEN (Z.BU_AMT_D2-Z.BU_AMT_D3) ELSE 0 END) AS BU_AMT_SD2
         , (CASE WHEN VAR_DATA_DATE>='20190809' THEN (Z.BU_AMT_D1-Z.BU_AMT_D2) ELSE 0 END) AS BU_AMT_SD1
         , (CASE WHEN VAR_DATA_DATE>='20190808' THEN (Z.BU_AMT_D-Z.BU_AMT_D1) ELSE 0 END) AS BU_AMT_SD
         , Z.BU_AMT_D
         , Z.BU_AMT_LAST_ALL
         , (CASE WHEN Z.BU_AMT_LAST_ALL=0 THEN 0 ELSE Z.BU_AMT_D/Z.BU_AMT_LAST_ALL END) AS BU_AMT_PC
         , (Z.BU_AMT_D-Z.BU_AMT_LAST_ALL) AS BU_AMT_DIF_ALL
         , Z.BU_AMT_LAST
         , (CASE WHEN Z.BU_AMT_LAST=0 THEN 0 ELSE (Z.BU_AMT_D-Z.BU_AMT_LAST)/Z.BU_AMT_LAST END) AS BU_AMT_GR
         , (Z.BU_AMT_D-Z.BU_AMT_LAST) AS BU_AMT_DIF
         , Z.BU_AMT_POSTING
         , NULL AS BU_AMT_STMT, NULL AS BU_AMT_STMT_DIF
         , NULL AS BU_REQ, NULL AS BU_REQ_PC, NULL AS BU_REQ_DIF
    FROM (SELECT BU01_ID, BU01_NM
               , SUM(CASE WHEN DATA_DATE=VAR_DATA_DATE THEN (POSTED_AMT_THIS+POSTING_AMT) ELSE 0 END) AS BU_AMT_D
               , SUM(CASE WHEN DATA_DATE=VAR_DATA_DATE_D1 THEN (POSTED_AMT_THIS+POSTING_AMT) ELSE 0 END) AS BU_AMT_D1
               , SUM(CASE WHEN DATA_DATE=VAR_DATA_DATE_D2 THEN (POSTED_AMT_THIS+POSTING_AMT) ELSE 0 END) AS BU_AMT_D2
               , SUM(CASE WHEN DATA_DATE=VAR_DATA_DATE_D3 THEN (POSTED_AMT_THIS+POSTING_AMT) ELSE 0 END) AS BU_AMT_D3
               , SUM(CASE WHEN DATA_DATE=VAR_DATA_DATE THEN POSTED_AMT_LAST_ALL ELSE 0 END) AS BU_AMT_LAST_ALL
               , SUM(CASE WHEN DATA_DATE=VAR_DATA_DATE THEN POSTED_AMT_LAST ELSE 0 END) AS BU_AMT_LAST
               , SUM(CASE WHEN DATA_DATE=VAR_DATA_DATE THEN POSTING_AMT ELSE 0 END) AS BU_AMT_POSTING
          FROM DMMDL.DC0021_CUST_SALES
          WHERE DATA_DATE IN (VAR_DATA_DATE, VAR_DATA_DATE_D1, VAR_DATA_DATE_D2, VAR_DATA_DATE_D3) AND RPT_YM=VAR_RPT_YM
            AND BU01_ID<>'NULL'
          GROUP BY BU01_ID, BU01_NM) Z
    ;

    UPDATE DMMDL.DC0021_SALES_RPT01 R
    JOIN (SELECT BU01_ID, SUM(BAL_BEGIN+CUM_AMT) AS BU_AMT_STMT
          FROM DMMDL.DC0021_CUST_STMT
          WHERE DATA_DATE=VAR_DATA_DATE AND RPT_YM=VAR_RPT_YM
          GROUP BY BU01_ID) S
    ON R.BU01_ID=S.BU01_ID
    SET R.BU_AMT_STMT=(CASE WHEN S.BU_AMT_STMT IS NULL THEN NULL 
                            ELSE IFNULL(S.BU_AMT_STMT, 0)-R.BU_AMT_D
                       END)
    WHERE R.DATA_DATE=VAR_DATA_DATE
    ;

    UPDATE DMMDL.DC0021_SALES_RPT01 R
    JOIN (SELECT BU01_ID, SUM(REQ_AMT) AS REQ_AMT
          FROM DMMDL.DC0021_REQ
          WHERE DATA_DATE=VAR_REQ_DATE AND REQ_YM=VAR_RPT_YM
          GROUP BY BU01_ID) S
    ON R.BU01_ID=S.BU01_ID
    SET R.BU_REQ=S.REQ_AMT
    WHERE R.DATA_DATE=VAR_DATA_DATE
    ;

    UPDATE DMMDL.DC0021_SALES_RPT01 SET
        BU_AMT_STMT_DIF=(BU_AMT_D+BU_AMT_STMT-BU_REQ)
      , BU_REQ_PC=(CASE WHEN BU_REQ IS NULL THEN NULL ELSE (CASE WHEN BU_REQ=0 THEN 0 ELSE (BU_AMT_D/BU_REQ) END) END)
      , BU_REQ_DIF=(CASE WHEN BU_REQ IS NULL THEN BU_AMT_D ELSE (BU_AMT_D-BU_REQ*VAR_WORKDAY_PC) END)
    WHERE DATA_DATE=VAR_DATA_DATE
    ;

    INSERT INTO DMMDL.DC0021_SALES_RPT01_HEAD
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , VAR_DATA_DATE_D1 AS DATA_DATE1
         , VAR_DATA_DATE_D2 AS DATA_DATE2
         , VAR_WORKDAYS AS WORKDAYS
         , VAR_WORKDAY_TOTAL AS WORKDAY_TOTAL
         , VAR_WORKDAY_PC AS WORKDAY_PC
         , VAR_REQ_DATE AS REQ_DATE
         , SUM(BU_AMT_SD) AS BU_AMT_SD
         , SUM(BU_AMT_D) AS BU_AMT_D
         , SUM(BU_AMT_POSTING) AS BU_AMT_POSTING
         , SUM(BU_AMT_LAST_ALL) AS BU_AMT_LAST_ALL
         , (CASE WHEN SUM(BU_AMT_LAST_ALL)=0 THEN 0 ELSE SUM(BU_AMT_D)/SUM(BU_AMT_LAST_ALL) END) BU_AMT_PC
         , SUM(BU_REQ) AS BU_REQ
    FROM DMMDL.DC0021_SALES_RPT01
    WHERE DATA_DATE=VAR_DATA_DATE
    ;

    SET VAR_SP_RESULT='Y';
    COMMIT;
END
;