DROP PROCEDURE IF EXISTS DWWANT.SP_KA_00001_DELETE_DATA;

CREATE PROCEDURE DWWANT.SP_KA_00001_DELETE_DATA (
    VAR_EDI_NO CHAR(12), VAR_DATA_DATE CHAR(8), OUT VAR_SP_RESULT CHAR(1)
)
BEGIN
    DECLARE VAR_POS_DATE_MIN CHAR(8);
    DECLARE VAR_POS_DATE_MAX CHAR(8);
    DECLARE VAR_INV_DATE_MIN CHAR(8);
    DECLARE VAR_INV_DATE_MAX CHAR(8);
    DECLARE VAR_POS_WEEK_NUM_MIN CHAR(6);
    DECLARE VAR_POS_WEEK_NUM_MAX CHAR(6);

    SELECT MIN(SALE_DATE), MAX(SALE_DATE) INTO VAR_POS_DATE_MIN, VAR_POS_DATE_MAX
    FROM RAWWANT.KA_WANTWANT_SYS_SALE_DATA
    WHERE END_MONTH_FLAG=0;

    SELECT MIN(INV_DATE), MAX(INV_DATE) INTO VAR_INV_DATE_MIN, VAR_INV_DATE_MAX
    FROM RAWWANT.KA_WANTWANT_SYS_INV_DATA;

    SET VAR_POS_WEEK_NUM_MIN = DWWANT.FN_GET_WEEK_NUM(VAR_POS_DATE_MIN);
    SET VAR_POS_WEEK_NUM_MAX = DWWANT.FN_GET_WEEK_NUM(VAR_POS_DATE_MAX);

    INSERT INTO DWWANT.EDI_FLOW_DWWANT_KA VALUES (
        VAR_EDI_NO, VAR_POS_DATE_MIN, VAR_POS_DATE_MAX, VAR_INV_DATE_MIN, VAR_INV_DATE_MAX
    );

    DELETE FROM DWWANT.TRAS_KA_POS WHERE POS_SETTLE_TYPE='D' AND POS_DATE>=VAR_POS_DATE_MIN AND POS_DATE<=VAR_POS_DATE_MAX;
    DELETE FROM DWWANT.TRAS_KA_POS WHERE POS_SETTLE_TYPE='M' AND LEFT(POS_DATE, 6)=LEFT(VAR_POS_DATE_MIN, 6);
    DELETE FROM DWWANT.TRAS_KA_INV WHERE INV_DATE>=VAR_INV_DATE_MIN AND INV_DATE<=VAR_INV_DATE_MAX;

    DELETE FROM DWWANT.TRAS_KA_POS_MATL_D WHERE POS_DATE>=VAR_POS_DATE_MIN AND POS_DATE<=VAR_POS_DATE_MAX;
    DELETE FROM DWWANT.TRAS_KA_INV_STORE_D WHERE INV_DATE>=VAR_INV_DATE_MIN AND INV_DATE<=VAR_INV_DATE_MAX;
    DELETE FROM DWWANT.TRAS_KA_INV_WH_D WHERE INV_DATE>=VAR_INV_DATE_MIN AND INV_DATE<=VAR_INV_DATE_MAX;

    DELETE FROM DWWANT.TRAS_KA_POS_MATL_W WHERE POS_WEEK_NUM>=VAR_POS_WEEK_NUM_MIN AND POS_WEEK_NUM<=VAR_POS_WEEK_NUM_MAX;

    DELETE FROM DWWANT.TRAS_KA_POS_MATL_M WHERE POS_YM=LEFT(VAR_POS_DATE_MIN, 6);
    DELETE FROM DWWANT.TRAS_KA_POS_STORE_M WHERE POS_YM=LEFT(VAR_POS_DATE_MIN, 6);

    SET VAR_SP_RESULT='Y';
    COMMIT;
END
;