DROP PROCEDURE IF EXISTS DWWANT.SP_MAIN_30102_ORG;

CREATE PROCEDURE DWWANT.SP_MAIN_30102_ORG (
    VAR_EDI_NO CHAR(12), VAR_DATA_DATE CHAR(8), OUT VAR_SP_RESULT CHAR(1)
)
BEGIN

    INSERT INTO DWWANT.ORG_SALES_CHAN
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , (CASE WHEN C.DISTR_CHAN='' THEN 'NULL' ELSE C.DISTR_CHAN END) AS SALES_CHAN_ID
         , (CASE WHEN C.TXTSH=''      THEN  NULL  ELSE C.TXTSH      END) AS SALES_CHAN_NM
    FROM RAWWANT.BW_SAPBHP_BI0_TDISTR_CHAN C
    ;

    INSERT INTO DWWANT.ORG_SALES_COM
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , (CASE WHEN C.SALESORG='' THEN 'NULL' ELSE C.SALESORG END) AS SALES_COM_ID
         , (CASE WHEN C.TXTLG=''    THEN  NULL  ELSE C.TXTLG    END) AS SALES_COM_NM
         , NULL AS SALES_COM_ABR
    FROM RAWWANT.BW_SAPBHP_BI0_TSALESORG C
    ;

    UPDATE DWWANT.ORG_SALES_COM SET
        SALES_COM_ABR=(CASE WHEN SALES_COM_ID='C101' THEN '杭州分' WHEN SALES_COM_ID='C111' THEN '上海分' WHEN SALES_COM_ID='C121' THEN '温州分' WHEN SALES_COM_ID='C131' THEN '苏州分'
                            WHEN SALES_COM_ID='C141' THEN '南京分' WHEN SALES_COM_ID='C181' THEN '青岛分' WHEN SALES_COM_ID='C191' THEN '哈尔滨分' WHEN SALES_COM_ID='C201' THEN '北京分' 
                            WHEN SALES_COM_ID='C211' THEN '天津分' WHEN SALES_COM_ID='C221' THEN '长春分' WHEN SALES_COM_ID='C231' THEN '沈阳分' WHEN SALES_COM_ID='C241' THEN '石家庄分'
                            WHEN SALES_COM_ID='C251' THEN '太原分' WHEN SALES_COM_ID='C271' THEN '广州分' WHEN SALES_COM_ID='C281' THEN '深圳分' WHEN SALES_COM_ID='C291' THEN '海南分'
                            WHEN SALES_COM_ID='C311' THEN '南昌分' WHEN SALES_COM_ID='C321' THEN '福州分' WHEN SALES_COM_ID='C341' THEN '长沙分' WHEN SALES_COM_ID='C351' THEN '贵阳分'
                            WHEN SALES_COM_ID='C361' THEN '成都分' WHEN SALES_COM_ID='C371' THEN '重庆分' WHEN SALES_COM_ID='C381' THEN '昆明分' WHEN SALES_COM_ID='C391' THEN '兰州分'
                            WHEN SALES_COM_ID='C401' THEN '乌鲁木齐分' WHEN SALES_COM_ID='C411' THEN '宁波分'  WHEN SALES_COM_ID='C441' THEN '包头分' WHEN SALES_COM_ID='C461' THEN '合肥分'
                            WHEN SALES_COM_ID='C491' THEN '郑州分' WHEN SALES_COM_ID='C501' THEN '济南分' WHEN SALES_COM_ID='C551' THEN '武汉分' WHEN SALES_COM_ID='C751' THEN '漯河分' 
                            WHEN SALES_COM_ID='C761' THEN '营口分' WHEN SALES_COM_ID='C771' THEN '南宁分' WHEN SALES_COM_ID='C781' THEN '西安分'
                            ELSE NULL
                       END)
     ;

    INSERT INTO DWWANT.ORG_SALES_OFF
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , (CASE WHEN O.SALES_OFF='' THEN 'NULL' ELSE O.SALES_OFF END) AS SALES_OFF_ID
         , (CASE WHEN O.TXTSH=''     THEN  NULL  ELSE O.TXTSH     END) AS SALES_OFF_NM
         , NULL AS SALES_OFF_TYPE
    FROM RAWWANT.BW_SAPBHP_BI0_TSALES_OFF O
    ;

    UPDATE DWWANT.ORG_SALES_OFF SET
        SALES_OFF_TYPE=(CASE WHEN SALES_OFF_NM LIKE '%营办销售办公室' THEN 'K'
                             WHEN SALES_OFF_NM LIKE '%销售办公室' THEN 'S'
                             WHEN SALES_OFF_NM LIKE '旺仔俱乐部%' OR SALES_OFF_NM LIKE '%门店' THEN 'H'
                             WHEN SALES_OFF_NM LIKE '%营业所%' THEN 'O'
                             WHEN SALES_OFF_NM LIKE '%分公司%' THEN 'C'
                             ELSE NULL
                        END)
     ;

    INSERT INTO DWWANT.ORG_WANT_CHAN
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , (CASE WHEN C.BIC_ZWWCHAN='' THEN 'NULL' ELSE C.BIC_ZWWCHAN END) AS WANT_CHAN_ID
         , (CASE WHEN C.TXTSH=''       THEN  NULL  ELSE C.TXTSH       END) AS WANT_CHAN_NM
    FROM RAWWANT.BW_SAPBHP_BIC_TZWWCHAN C
    ;

    INSERT INTO DWWANT.ORG_WANT_COM
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , (CASE WHEN C.BIC_ZWW_COMPY='' THEN 'NULL' ELSE C.BIC_ZWW_COMPY END) AS WANT_COM_ID
         , (CASE WHEN C.TXTSH=''         THEN  NULL  ELSE C.TXTSH         END) AS WANT_COM_NM
    FROM RAWWANT.BW_SAPBHP_BIC_TZWW_COMPY C
    ;

    INSERT INTO DWWANT.ORG_IWANT_BU
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , (CASE WHEN B.DIVISION_ID=''   THEN 'NULL' ELSE B.DIVISION_ID   END) AS IWANT_BU_ID
         , (CASE WHEN B.DIVISION_NAME='' THEN  NULL  ELSE B.DIVISION_NAME END) AS IWANT_BU_NM
    FROM (SELECT DISTINCT EDI_NO
               , DIVISION_ID, DIVISION_NAME
          FROM RAWWANT.IWANT_SALES_CHANNEL
          WHERE DIVISION_ID<>'') B
    ;

    INSERT INTO DWWANT.ORG_IWANT_CHAN
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , (CASE WHEN C.CHANNEL_ID=''        THEN 'NULL' ELSE C.CHANNEL_ID        END) AS IWANT_CHAN_ID
         , (CASE WHEN C.CHANNEL_NAME=''      THEN  NULL  ELSE C.CHANNEL_NAME      END) AS IWANT_CHAN_NM
         , (CASE WHEN C.DIVISION_ID=''       THEN  NULL  ELSE C.DIVISION_ID       END) AS IWANT_BU_ID
         , (CASE WHEN C.ERP_CHANNEL_ID=''    THEN  NULL  ELSE C.ERP_CHANNEL_ID    END) AS SALES_CHAN_ID
         , (CASE WHEN C.ERP_PROD_GROUP_ID='' THEN  NULL  ELSE C.ERP_PROD_GROUP_ID END) AS PROD_DIV_ID
    FROM RAWWANT.IWANT_SALES_CHANNEL C
    ;

    INSERT INTO DWWANT.ORG_IWANT_REGN
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , (CASE WHEN W.ID=''           THEN 'NULL' ELSE W.ID           END) AS IWANT_REGN_ID
         , (CASE WHEN W.NAME=''         THEN  NULL  ELSE W.NAME         END) AS IWANT_REGN_NM
         , (CASE WHEN W.COMPANY_ID=''   THEN  NULL  ELSE W.COMPANY_ID   END) AS IWANT_COM_ID
         , (CASE WHEN W.STATUS=''       THEN  NULL  ELSE W.STATUS       END) AS IWANT_REGN_TYP
    FROM RAWWANT.IWANT_SALES_AREA W
    ;

    INSERT INTO DWWANT.ORG_IWANT_COM
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , (CASE WHEN C.ID=''          THEN 'NULL' ELSE C.ID          END) AS IWANT_COM_ID
         , (CASE WHEN C.NAME=''        THEN  NULL  ELSE C.NAME        END) AS IWANT_COM_NM
         , (CASE WHEN C.DISTRICT_ID='' THEN  NULL  ELSE C.DISTRICT_ID END) AS IWANT_DIST_ID
    FROM RAWWANT.IWANT_SALES_COMPANY C
    ;

    INSERT INTO DWWANT.ORG_IWANT_OFF
    SELECT DISTINCT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , (CASE WHEN O.BRANCH_ID=''   THEN 'NULL' ELSE O.BRANCH_ID   END) AS IWANT_OFF_ID
         , (CASE WHEN O.BRANCH_NAME='' THEN  NULL  ELSE O.BRANCH_NAME END) AS IWANT_OFF_NM
         , (CASE WHEN O.COMPANY_ID=''  THEN  NULL  ELSE O.COMPANY_ID  END) AS IWANT_COM_ID
    FROM RAWWANT.IWANT_SALES_MARKET_FULL_VIEW O
    ;

    INSERT INTO DWWANT.ORG_IWANT_DIST
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , (CASE WHEN D.ID=''   THEN 'NULL' ELSE D.ID   END) AS IWANT_DIST_ID
         , (CASE WHEN D.NAME='' THEN  NULL  ELSE D.NAME END) AS IWANT_DIST_NM
    FROM RAWWANT.IWANT_SALES_DISTRICT D
    ;

    INSERT INTO DWWANT.ORG_IWANT_MARKET
    SELECT DISTINCT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , (CASE WHEN M.MARKET_ID=''   THEN 'NULL' ELSE M.MARKET_ID   END) AS IWANT_MARKET_ID
         , (CASE WHEN M.MARKET_NAME='' THEN  NULL  ELSE M.MARKET_NAME END) AS IWANT_MARKET_NM
         , (CASE WHEN O.BRANCH_ID=''   THEN  NULL  ELSE O.BRANCH_ID   END) AS IWANT_OFF_ID
    FROM (SELECT DISTINCT EDI_NO
               , MARKET_ID, MARKET_NAME
          FROM RAWWANT.IWANT_SALES_SMALL_MARKET
          WHERE MARKET_ID<>'') M
    LEFT JOIN (SELECT DISTINCT BRANCH_ID, MARKET_ID
               FROM RAWWANT.IWANT_SALES_MARKET_FULL_VIEW) O
    ON M.MARKET_ID=O.MARKET_ID
    ;

    INSERT INTO DWWANT.ORG_IWANT_MARKET_SMALL
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , (CASE WHEN M.SMALL_MARKET_ID=''   THEN 'NULL' ELSE M.SMALL_MARKET_ID   END) AS IWANT_MARKET_SMALL_ID
         , (CASE WHEN M.SMALL_MARKET_NAME='' THEN  NULL  ELSE M.SMALL_MARKET_NAME END) AS IWANT_MARKET_SMALL_NM
         , (CASE WHEN M.MARKET_ID=''         THEN  NULL  ELSE M.MARKET_ID         END) AS IWANT_MARKET_ID
    FROM RAWWANT.IWANT_SALES_SMALL_MARKET M
    ;

    INSERT INTO DWWANT.ORG_EMP_SALES_IWANT
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , (CASE WHEN E.EMP_ID=''            THEN 'NULL' ELSE E.EMP_ID            END) AS EMP_ID
         , (CASE WHEN E.COMPANY_ID=''        THEN 'NULL' ELSE E.COMPANY_ID        END) AS IWANT_COM_ID
         , (CASE WHEN E.BRANCH_ID=''         THEN  NULL  ELSE E.BRANCH_ID         END) AS IWANT_OFF_ID
         , (CASE WHEN E.MASTER_POS=''        THEN  NULL  ELSE E.MASTER_POS        END) AS EMP_POS_PRIORITY
         , (CASE WHEN E.POS_ID=''            THEN 'NULL' ELSE E.POS_ID            END) AS EMP_POS_ID
         , (CASE WHEN E.POS_TYPE_ID=''       THEN  NULL  ELSE E.POS_TYPE_ID       END) AS EMP_POS_TYPE
         , (CASE WHEN E.EMP_ONBOARD_DATE1='' THEN  NULL  ELSE E.EMP_ONBOARD_DATE1 END) AS ONBOARD_DATE1
    FROM RAWWANT.IWANT_SALES_EMP_POSITION_ORG_VIEW E
    ;

    SET VAR_SP_RESULT='Y';
    COMMIT;
END
;