DROP PROCEDURE IF EXISTS DWWANT.SP_DC0021_30102_CUST_STMT;

CREATE PROCEDURE DWWANT.SP_DC0021_30102_CUST_STMT (
    VAR_EDI_NO CHAR(12), VAR_DATA_DATE CHAR(8), OUT VAR_SP_RESULT CHAR(1)
)
BEGIN
    DECLARE VAR_RPT_YM CHAR(6);

    SET VAR_RPT_YM = SUBSTR(VAR_DATA_DATE, 1, 6);

    INSERT INTO DMMDL.DC0021_CUST_STMT
    SELECT VAR_EDI_NO AS EDI_NO, VAR_DATA_DATE AS DATA_DATE
         , VAR_RPT_YM AS RPT_YM
         , A.SALES_CREDIT_ID, E.SALES_CREDIT_DESC
         , A.WANT_COM_ID, C.WANT_COM_NM
         , A.SALES_OFF_ID, O.SALES_OFF_NM
         , A.TODAY_AMT, A.BAL_BEGIN, A.CUM_AMT, A.SALES_AMT, A.BAL_END
         , NULL AS BU01_ID, NULL AS BU01_NM
    FROM (SELECT S.SALES_CREDIT_ID
               , S.WANT_COM_ID
               , S.SALES_OFF_ID
               , SUM(S.TODAY_AMT) AS TODAY_AMT
               , SUM(S.BAL_BEGIN) AS BAL_BEGIN
               , SUM(S.CUM_AMT) AS CUM_AMT
               , SUM(S.SALES_AMT) AS SALES_AMT
               , SUM(S.BAL_END) AS BAL_END
          FROM DWWANT.FI_CUST_STMT S
          WHERE S.TODAY_AMT<>0 OR S.BAL_BEGIN<>0 OR S.CUM_AMT<>0 OR S.SALES_AMT<>0 OR S.BAL_END<>0
          GROUP BY S.SALES_CREDIT_ID, S.WANT_COM_ID, S.SALES_OFF_ID) A
    LEFT JOIN DWWANT.CM_SALES_CREDIT E ON A.SALES_CREDIT_ID=E.SALES_CREDIT_ID
    LEFT JOIN DWWANT.ORG_WANT_COM C ON A.WANT_COM_ID=C.WANT_COM_ID
    LEFT JOIN DWWANT.ORG_SALES_OFF O ON A.SALES_OFF_ID=O.SALES_OFF_ID
    WHERE A.SALES_CREDIT_ID IN ('CDY','CC5','CCL','CCK','CHER','CHEQ','CHF1','CHF2','CHF3') AND O.SALES_OFF_TYPE='O'
    ;    

    UPDATE DMMDL.DC0021_CUST_STMT SET
        BU01_ID=(CASE WHEN SALES_CREDIT_ID IN ('CHEQ','CHF1','CHF2') AND WANT_COM_ID IN ('W10','W12','W31','W32','WX5','WX6','WXI') THEN 'BU01'
                      WHEN SALES_CREDIT_ID IN ('CHEQ','CHF1','CHF2') AND WANT_COM_ID IN ('W11','W13','W14','W46','WX1','WXC') THEN 'BU02'
                      WHEN SALES_CREDIT_ID IN ('CHEQ','CHF1','CHF2') AND WANT_COM_ID IN ('W27','W28','W29','W77','WXD','WXE','WXG') THEN 'BU03'
                      WHEN SALES_CREDIT_ID IN ('CHEQ','CHF1','CHF2') AND WANT_COM_ID IN ('W34','W55','WX2','WXF') THEN 'BU04'
                      WHEN SALES_CREDIT_ID IN ('CHEQ','CHF1','CHF2') AND WANT_COM_ID IN ('W18','W49','W50','W75','WX8','WX9','WXA','WXB') THEN 'BU05'
                      WHEN SALES_CREDIT_ID IN ('CHEQ','CHF1','CHF2') AND WANT_COM_ID IN ('W19','W20','W21','W22','W23','W24','W76','WX3') THEN 'BU06'
                      WHEN SALES_CREDIT_ID IN ('CHEQ','CHF1','CHF2') AND WANT_COM_ID IN ('W35','W36','W37','W38','WX4','WXH') THEN 'BU07'
                      WHEN SALES_CREDIT_ID IN ('CHEQ','CHF1','CHF2') AND WANT_COM_ID IN ('W25','W39','W40','W44','W78','WX7') THEN 'BU08'
                      WHEN SALES_CREDIT_ID='CHER' THEN 'BU09'
                      WHEN SALES_CREDIT_ID='CC5' THEN 'BU10'
                      WHEN SALES_CREDIT_ID='CDY' THEN 'BU11'
                      WHEN SALES_CREDIT_ID='CCK' THEN 'BU12'
                      WHEN SALES_CREDIT_ID='CCL' THEN 'BU13'
                      WHEN SALES_CREDIT_ID='CHF3' THEN 'BU17'
                      ELSE 'NULL'
                 END)
    WHERE DATA_DATE=VAR_DATA_DATE
    ;
    
    UPDATE DMMDL.DC0021_CUST_STMT SET
        BU01_NM=DMMDL.FN_GET_CM_CODE_NM('0001', BU01_ID)
    WHERE DATA_DATE=VAR_DATA_DATE
    ;

    SET VAR_SP_RESULT='Y';
    COMMIT;
END
;