--批發客戶帳餘查詢
SELECT SUM(CASE WHEN A.FISCPER ='2019002' AND A.FISCVARNT='K4' AND A.AC_DOC_TYP<>'RV' AND SUBSTRING(A.BIC_ZTCODE,1,2)<>'VF' AND A.PSTNG_DATE='20190211' THEN A.DEB_CRE_LC ELSE 0 END) AS TODAY_AMT
     , SUM(CASE WHEN A.FISCPER< '2019002' AND A.FISCVARNT='K4'                                                                                          THEN A.DEB_CRE_LC ELSE 0 END) AS PERIOD_BEGIN
     , SUM(CASE WHEN A.FISCPER ='2019002' AND A.FISCVARNT='K4' AND A.AC_DOC_TYP<>'RV' AND SUBSTRING(A.BIC_ZTCODE,1,2)<>'VF'                             THEN A.DEB_CRE_LC ELSE 0 END) AS CUM_AMT
     , SUM(CASE WHEN A.FISCPER ='2019002' AND A.FISCVARNT='K4' AND A.AC_DOC_TYP= 'RV'                                                                   THEN A.DEB_CRE_LC ELSE 0 END) AS SALES_WO
     , SUM(CASE WHEN A.FISCPER<='2019002' AND A.FISCVARNT='K4'                                                                                          THEN A.DEB_CRE_LC ELSE 0 END) AS PERIOD_END
FROM RAWWANT.BW_SAPBHP_BI0_AFIAR_O0300 A
JOIN RAWWANT.BW_SAPBHP_BI0_PCUSTOMER D ON A.DEBITOR=D.CUSTOMER AND D.OBJVERS='A'
WHERE D.CUST_CLASS NOT IN ('O1','O2','O3','O4','O5','O6','O7','O8')
  AND SUBSTRING(A.COMP_CODE,1,1)='C'
  AND A.C_CTR_AREA NOT IN ('CDZ','FDZ','CDD','CD8','CDQ')
  AND D.ACCNT_GRP IN ('Z002','Z003')
;

SELECT SUM(CASE WHEN A.FISC_PER ='2019002' AND A.FISC_VARNT='K4' AND A.AC_DOC_TYPE<>'RV' AND (SUBSTRING(A.SALES_TRAS_CODE,1,2)<>'VF' OR A.SALES_TRAS_CODE IS NULL) AND A.AC_DOC_POST_YMD='20190211' THEN A.BAL_AMT ELSE 0 END) AS TODAY_AMT
     , SUM(CASE WHEN A.FISC_PER< '2019002' AND A.FISC_VARNT='K4'                                                                                                                                    THEN A.BAL_AMT ELSE 0 END) AS PERIOD_BEGIN
     , SUM(CASE WHEN A.FISC_PER ='2019002' AND A.FISC_VARNT='K4' AND A.AC_DOC_TYPE<>'RV' AND (SUBSTRING(A.SALES_TRAS_CODE,1,2)<>'VF' OR A.SALES_TRAS_CODE IS NULL)                                  THEN A.BAL_AMT ELSE 0 END) AS CUM_AMT
     , SUM(CASE WHEN A.FISC_PER ='2019002' AND A.FISC_VARNT='K4' AND A.AC_DOC_TYPE= 'RV'                                                                                                            THEN A.BAL_AMT ELSE 0 END) AS SALES_WO
     , SUM(CASE WHEN A.FISC_PER<='2019002' AND A.FISC_VARNT='K4'                                                                                                                                    THEN A.BAL_AMT ELSE 0 END) AS PERIOD_END
FROM DWWANT.FI_CUST_BAL A
JOIN DWWANT.CUST_SD D ON A.CUST_ID=D.CUST_ID
WHERE (D.CUST_CLASS NOT IN ('O1','O2','O3','O4','O5','O6','O7','O8') OR D.CUST_CLASS IS NULL)
  AND SUBSTRING(A.SALES_COM_CODE,1,1)='C'
  AND (A.SALES_CREDIT_ID NOT IN ('CDZ','FDZ','CDD','CD8','CDQ') OR A.SALES_CREDIT_ID IS NULL)
  AND D.CUST_ACCT_GRP IN ('Z002','Z003')
;
