--專款分析表
SELECT A.MATL_GRP_1, B.SALES_OFF, SUM(A.BIC_ZKAMOUNT) AS ZKAMOUNT
FROM RAWWANT.BW_SAPBHP_BIC_AZKZY_O0100 A
JOIN RAWWANT.BW_SAPBHP_BI0_PCUSTOMER B ON A.CUSTOMER=B.CUSTOMER AND B.OBJVERS='A'
WHERE A.MATL_GRP_1 IN ('Z77','Z78','Z79','Z81') AND A.BIC_ZZKZYS=''
GROUP BY A.MATL_GRP_1, B.SALES_OFF
;

SELECT A.PROD_MATL_GRP1_ID, B.SALES_OFF_ID, SUM(A.SPEC_AMT) AS SPEC_AMT
FROM DWWANT.FI_CUST_SPEC A
JOIN DWWANT.CUST_MAIN B ON A.CUST_ID=B.CUST_ID
WHERE A.PROD_MATL_GRP1_ID IN ('Z77','Z78','Z79','Z81') AND A.SPEC_STATUS IS NULL
GROUP BY A.PROD_MATL_GRP1_ID, B.SALES_OFF_ID
;
