SELECT CONCAT('W',SUBSTRING(R.IWANT_COM_ID,2)) AS WANT_COM_ID, SUM(R.REQ_AMT) AS REQ_AMT
FROM (SELECT IWANT_COM_ID, PROD_MATL_ID, REQ_AMT
      FROM DWWANT.ORDR_REQ_COM
      WHERE REQ_YM='201908') R
JOIN DWWANT.PROD_MATL P ON R.PROD_MATL_ID=P.PROD_MATL_ID
GROUP BY CONCAT('W',SUBSTRING(R.IWANT_COM_ID,2))
;
