SELECT C.WANT_COM_ID, SUM(R.REQ_AMT) AS REQ_AMT
FROM (SELECT (CASE WHEN CUST_ID IS NOT NULL THEN CUST_ID ELSE CUST_ID_WH END) AS CUST_ID
           , PROD_MATL_ID, REQ_AMT
      FROM DWWANT.ORDR_REQ_CUST_KA
      WHERE REQ_YM='201908') R
JOIN DWWANT.CUST_SD C ON R.CUST_ID=C.CUST_ID
JOIN DWWANT.PROD_MATL P ON R.PROD_MATL_ID=P.PROD_MATL_ID
GROUP BY C.WANT_COM_ID
;
