--業績類通用報表含未過帳含財年
--十年內憑證
SELECT SUM((CASE WHEN A.ITEM_CATEG IN ('ZTAD','ZDZY') THEN A.BIC_ZWGZ_KDM ELSE A.BIC_ZWGZ_QRM END)*
           (CASE WHEN A.ITEM_CATEG IN ('ZCR','ZCT','ZFDR','ZFRT','ZREF','ZREG','ZREI','ZREJ','ZREK','ZREM','ZRZY','ZG2N','ZKRN','ZSZY') THEN -1 ELSE 1 END)) AS ZWGZ_QRM
FROM RAWWANT.BW_SAPBHP_BIC_AZWGZ_O0100 A
JOIN RAWWANT.BW_SAPBHP_BI0_PCUSTOMER D ON A.CUSTOMER=D.CUSTOMER AND D.OBJVERS='A'
JOIN RAWWANT.BW_SAPBHP_BI0_PCUST_SALES S ON A.DIVISION=S.DIVISION AND A.DISTR_CHAN=S.DISTR_CHAN AND A.SALESORG=S.SALESORG AND A.CUST_SALES=S.CUST_SALES AND S.OBJVERS='A'
JOIN RAWWANT.BW_SAPBHP_BI0_PMATERIAL M ON A.MATERIAL=M.MATERIAL AND M.OBJVERS='A'
JOIN RAWWANT.BW_SAPBHP_BIC_PZCUS_WWID W ON A.DISTR_CHAN=W.DISTR_CHAN AND A.MATERIAL=W.MATERIAL AND A.DIVISION=W.DIVISION AND A.SALESORG=W.SALESORG AND A.ITEM_CATEG=W.ITEM_CATEG AND A.BIC_ZCUS_WWID=W.BIC_ZCUS_WWID AND W.OBJVERS='A'
WHERE D.CUST_CLASS<>'OB' AND A.DISTR_CHAN<>'C6' AND S.BIC_ZWW_COMPY<>'' AND M.PRODH1<>'999' AND A.BIC_ZCUS_WWID<>'' AND M.MATL_TYPE='FERT' AND D.ACCNT_GRP IN ('Z002','Z003') AND A.DOC_DATE>'20090000'
;

SELECT SUM((CASE WHEN A.SALES_DOC_ITEM_CATEG IN ('ZTAD','ZDZY') THEN A.POSTING_BILL_AMT ELSE A.POSTING_CONF_AMT END)*
           (CASE WHEN A.SALES_DOC_ITEM_CATEG IN ('ZCR','ZCT','ZFDR','ZFRT','ZREF','ZREG','ZREI','ZREJ','ZREK','ZREM','ZRZY','ZG2N','ZKRN','ZSZY') THEN -1 ELSE 1 END)) AS ZWGZ_QRM
FROM DWWANT.TRAS_CUST_POSTING A
JOIN DWWANT.CUST_SD D ON A.CUST_ID=D.CUST_ID
JOIN DWWANT.CUST_SD_SALES_COM S ON A.PROD_DIV_ID=S.PROD_DIV_ID AND A.SALES_CHAN_ID=S.SALES_CHAN_ID AND A.SALES_COM_ID=S.SALES_COM_ID AND A.CUST_ID=S.CUST_ID
JOIN DWWANT.PROD_MATL M ON A.PROD_MATL_ID=M.PROD_MATL_ID
JOIN DWWANT.CUST_SD_SALES_COM_PROD W ON A.SALES_CHAN_ID=W.SALES_CHAN_ID AND A.PROD_MATL_ID=W.PROD_MATL_ID AND A.PROD_DIV_ID=W.PROD_DIV_ID AND A.SALES_COM_ID=W.SALES_COM_ID AND A.SALES_DOC_ITEM_CATEG=W.SALES_DOC_ITEM_CATEG AND A.CUST_ID=W.CUST_ID
WHERE (D.CUST_CLASS<>'OB' OR D.CUST_CLASS IS NULL) AND (A.SALES_CHAN_ID<>'C6' OR A.SALES_CHAN_ID IS NULL) 
  AND S.WANT_COM_ID IS NOT NULL AND (M.PROD_H1_ID<>'999' OR M.PROD_H1_ID IS NULL) AND M.PROD_MATL_TYPE='FERT' AND D.CUST_ACCT_GRP IN ('Z002','Z003') AND A.SALES_DOC_YMD>'20090000'
;

--渠道為空的明細數據
SELECT A.WANT_COM_ID, (SELECT WANT_COM_NM FROM DWWANT.ORG_WANT_COM WHERE WANT_COM_ID=A.WANT_COM_ID) AS WANT_COM_NM
     , A.PROD_MATL_ID, (SELECT PROD_MATL_NM FROM DWWANT.PROD_MATL WHERE PROD_MATL_ID=A.PROD_MATL_ID) AS PROD_MATL_NM
     , A.CUST_ID, (SELECT CUST_NM FROM DWWANT.CUST_MAIN WHERE CUST_ID=A.CUST_ID) AS CUST_NM
     , A.POSTING_AMT
FROM DWWANT.TRAS_CUST_POSTING_SALES A
WHERE A.POSTING_AMT<>0 AND A.WANT_CHAN_ID='NULL'
;
