--業績類通用報表含未過帳含財年
SELECT SUM(CASE WHEN A.CALMONTH='201802' THEN A.SUBTOTAL_1 ELSE 0 END) AS LAST_YEAR_MONTH_ALL
     , SUM(CASE WHEN A.CALMONTH='201802' THEN A.SUBTOTAL_1 ELSE 0 END)*8/20 AS LAST_YEAR_MONTH_NOW
     , SUM(CASE WHEN A.CALMONTH='201902' THEN A.SUBTOTAL_1 ELSE 0 END) AS THIS_MONTH_NOW
FROM RAWWANT.BW_SAPBHP_BIC_AZSD_O2100 A
JOIN RAWWANT.BW_SAPBHP_BI0_PCUSTOMER D ON A.CUSTOMER=D.CUSTOMER AND D.OBJVERS='A'
JOIN RAWWANT.BW_SAPBHP_BI0_PCUST_SALES S ON A.DIVISION=S.DIVISION AND A.DISTR_CHAN=S.DISTR_CHAN AND A.SALESORG=S.SALESORG AND A.CUST_SALES=S.CUST_SALES AND S.OBJVERS='A'
JOIN RAWWANT.BW_SAPBHP_BI0_PMATERIAL M ON A.MATERIAL=M.MATERIAL AND M.OBJVERS='A'
JOIN RAWWANT.BW_SAPBHP_BIC_PZCUS_WWID W ON A.DISTR_CHAN=W.DISTR_CHAN AND A.MATERIAL=W.MATERIAL AND A.DIVISION=W.DIVISION AND A.SALESORG=W.SALESORG AND A.ITEM_CATEG=W.ITEM_CATEG AND A.BIC_ZCUS_WWID=W.BIC_ZCUS_WWID AND W.OBJVERS='A'
WHERE D.CUST_CLASS<>'OB' AND A.DISTR_CHAN<>'C6' AND S.BIC_ZWW_COMPY<>'' AND M.PRODH1<>'999' AND A.BIC_ZCUS_WWID<>'' AND M.MATL_TYPE='FERT' AND D.ACCNT_GRP IN ('Z002','Z003')
  AND A.CALMONTH IN ('201802','201902')
;

SELECT WORKDAYS, WORKDAY_TOTAL
FROM DWWANT.CM_WORKDAY
WHERE WORKDAY_YMD='20190213'
;

SELECT SUM(CASE WHEN A.POSTED_YM='201802' THEN A.POSTED_AMT ELSE 0 END) AS LAST_YEAR_MONTH_ALL
     , SUM(CASE WHEN A.POSTED_YM='201802' THEN A.POSTED_AMT ELSE 0 END)*8/20 AS LAST_YEAR_MONTH_NOW
     , SUM(CASE WHEN A.POSTED_YM='201902' THEN A.POSTED_AMT ELSE 0 END) AS THIS_MONTH_NOW
FROM DWWANT.TRAS_CUST_POSTED A
JOIN DWWANT.CUST_SD D ON A.CUST_ID=D.CUST_ID
JOIN DWWANT.CUST_SD_SALES_COM S ON A.PROD_DIV_ID=S.PROD_DIV_ID AND A.SALES_CHAN_ID=S.SALES_CHAN_ID AND A.SALES_COM_ID=S.SALES_COM_ID AND A.CUST_ID=S.CUST_ID
JOIN DWWANT.PROD_MATL M ON A.PROD_MATL_ID=M.PROD_MATL_ID
JOIN DWWANT.CUST_SD_SALES_COM_PROD W ON A.SALES_CHAN_ID=W.SALES_CHAN_ID AND A.PROD_MATL_ID=W.PROD_MATL_ID AND A.PROD_DIV_ID=W.PROD_DIV_ID AND A.SALES_COM_ID=W.SALES_COM_ID AND A.SALES_DOC_ITEM_CATEG=W.SALES_DOC_ITEM_CATEG AND A.CUST_ID=W.CUST_ID
WHERE (D.CUST_CLASS<>'OB' OR D.CUST_CLASS IS NULL) AND (A.SALES_CHAN_ID<>'C6' OR A.SALES_CHAN_ID IS NULL) AND S.WANT_COM_ID IS NOT NULL AND (M.PROD_H1_ID<>'999' OR M.PROD_H1_ID IS NULL) AND M.PROD_MATL_TYPE='FERT' AND D.CUST_ACCT_GRP IN ('Z002','Z003')
  AND A.POSTED_YM IN ('201802','201902')
;
